write_buffer/src/kafka.rs
I have 2 changes that I think will help with #2007 (I'm hesitant to say "fixed" until we've tried this out). 
The first uses a different Rust method that will retry rather than return a `QueueFull` error, and I've told it to never time out.
The second change is to bump up the max size of the librdkafka producer queue so that we'll be retrying less, hopefully-- because we bumped up the max message size by a factor of 10, it makes sense to me to also bump up the max queue size by a factor of 10.
If you want to try these out separately, I'm happy to split into 2 PRs that we can merge at different times!
=> fix: Kafka queueing

read_buffer/src/row_group.rs, read_buffer/src/table.rs, server/src/db.rs
I tried to do what I thought was a refactoring (I want to make it so that `MetaData` is never empty, it always starts with a row group), but tests started failing. I've isolated the problem, but I'm not sure what the right fix is.
I've isolated the problem in a new failing test in this PR-- I thought that this:
```
let meta_new = MetaData::new(&rg);
```
and this:
```
let meta_default = MetaData::default();
let meta_default = MetaData::update_with(meta_default, &rg);
```
would be equivalent, but they result in different values in the `size` field. This assertion fails:
```
assert_eq!(meta_new.size, meta_default.size);
```
I've added some comments pointing to where the problem is: `MetaData::new` sets the `size` field to the result of `rg.size()`. `MetaData::default` sets size to 0, then …
=> fix: use correct row group size when updating table meta data

write_buffer/src/kafka.rs
We're currently running with the default `acks=1`, which causes the replicas to fall out of sync at the minor bump on the road and never catch up again. acks=1 is not for the faint of heart
=> fix: Set acks=all for kafka writes

src/main.rs
`Config::from_args` from derive flag, and my IDE (CLion + IntelliJ Rust) doesn't recognize its type.
With explicity specify the type, developer can enjoy code highlight and other features from IDE.
=> refactor: explicitly specify the type, more friendly to IDE

Cargo.lock, data_types/Cargo.toml, data_types/src/database_rules.rs, generated_types/Cargo.toml, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, generated_types/src/database_rules/lifecycle.rs, lifecycle/src/policy.rs, src/commands/database.rs, tests/end_to_end_cases/management_api.rs
Hopefully closes out https://github.com/influxdata/influxdb_iox/issues/1983.
Currently IOx does not place any limits on the number of in-memory compactions that can run concurrently. Given compactions happen on a per-partition basis, and given the large numbers of partitions driven by many IOx tables/measurements, it is common to see this sort of thing:
```
⇒  ./target/debug/influxdb_iox --host http://Alameda.local:1234 database query mydb "select count(*), storage, lifecycle_action from system.chunks group by storage,lifecycle_action"
+-----------------+---------------------+------------------+
| COUNT(UInt8(1)) | storage             | lifecycle_action |
+-----------------+---------------------+------------------+
| 649             | OpenMutableBuffer   |                  |
| 168 …
```
=> feat: add per-db in-memory compaction limiter

server/src/db.rs, server/src/init.rs, server/src/lib.rs, tests/end_to_end_cases/write_buffer.rs, write_buffer/Cargo.toml, write_buffer/src/config.rs, write_buffer/src/core.rs, write_buffer/src/kafka.rs, write_buffer/src/mock.rs
Advantages are:
- for large DBs w/ many partitions we can ingest data in-parallel
- on top of this change we can implement per-sequencer seeking, which is
required for replay
=> refactor: use one stream per sequencer/partition

src/commands/run.rs, src/influxdb_ioxd.rs, src/influxdb_ioxd/http.rs
In prod we see some requests which decompress into 22MB. Let's allow users to configure the maximum request size.
=> feat(iox): Make max http request size configurable

lifecycle/src/policy.rs
@carols10cents noticed that https://github.com/influxdata/influxdb_iox/pull/2048 introduced a failing test when running on her machine. I forgot to update tests to ensure that the ones that test compactions have a high enough compaction limiter set.
The previous change passed my laptop and CI because they had enough CPU cores for the tests.
=> test: ensure high enough limit

data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, generated_types/src/database_rules/lifecycle.rs, src/commands/database.rs
This is the first part of adding the ability to use the locally attached disk as a cache for Parquet files. Follow on work will include:
=> feat: add parquet cache size setting to database rules

generated_types/protos/influxdata/iox/catalog/v1/parquet_metadata.proto, parquet_file/src/catalog.rs, parquet_file/src/metadata.rs, parquet_file/src/test_utils.rs, persistence_windows/src/checkpoint.rs, server/src/db/lifecycle/write.rs
1. There are two partitions A and B w/ a single write each (from the same
sequencer).
2. We persist A:
- The partition checkpoint for A will be empty because after persistence
there will be nothing to replay (the single write is persisted and
we're ready).
- The database checkpoint that contains the global minimum of all ranges
recognizes that for the sequencer there is indeed something left (the
minimum sequence number from B).
3. DB restart happens, replay starts
4. We scan all persisted files, figure out that we have a DB checkpoint
with a sequence minimum but (w/o the change in this commit) there is no
maximum. Only partition checkpoints contain maxima, and the only partition
checkpoint that was persisted was the one for partition A and that one was
empty (see above).
5. So now how do …
=> fix: checkpoint collection (replay preparation)

generated_types/protos/influxdata/iox/catalog/v1/parquet_metadata.proto, parquet_file/src/catalog.rs, parquet_file/src/metadata.rs, parquet_file/src/test_utils.rs, persistence_windows/src/checkpoint.rs, persistence_windows/src/min_max_sequence.rs, persistence_windows/src/persistence_windows.rs
Now we can handle all these cases:
There are two partitions w/ a single write each:
1. A reads sequence number 1
2. B reads sequence number 2
3. we persist A which only knows the sequences up until 1
=> the DB checkpoint needs the global max, otherwise we forget sequences
during replay (2 in this case, so B would be gone)
----
1. B reads sequence number 1
2. A reads sequence number 2
3. we persist A which (w/o this commit) would not track the sequencer at
all in this checkpoint (since there is nothing to replay)
=> we MUST also remember that we already read up until 2, otherwise we'll
re-read 2 after replay
=> the partition checkpoint needs the local seen max (no matter if there's
something to to persist)
=> refactor: correctly track "seen" ranges in persistence checkpoints

data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, generated_types/protos/influxdata/iox/management/v1/shard.proto, generated_types/src/database_rules.rs, generated_types/src/database_rules/shard.rs, generated_types/src/database_rules/sink.rs, server/src/lib.rs, src/influxdb_ioxd/rpc/management.rs, tests/end_to_end_cases/write_api.rs
__Context and rationale__
We can currently mirror the full ingest traffic of a large internal bucket. However, we don't want to process the full bucket because it contains a lot of irrelevant tables.
The current "sharding config" mechanism allows to achieve that. The sharding config can split an input batch into output batches according to matching rules which can match on table names. All matching tables can go into one shard while everything else can be dropped by mapping it to a shard connected to a "devnull" destination (currently there is no such devnull destination and we return an error, but the mirroring mechanism ignores the error and doesn't retry).
It's also possible to ignore some tables while routing everything else to a given destination. We're already doing both things in …
=> refactor: Generailize routing sinks

tests/end_to_end_cases/management_cli.rs, tests/end_to_end_cases/scenario.rs
Do not rely on the fact that the chunk ID is 1, because compaction and
other mechanisms might create chunks using different IDs.
Closes #2109.
=> fix: fix flaky `test_unload_partition_chunk`

.circleci/config.yml
Typo in introduced in #2114
See https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/8576/workflows/987faa6c-c6ce-41c0-981c-8667c61018b5/jobs/45429
=> fix: Fix typo in print_cpu command name

.circleci/config.yml
Closes https://github.com/influxdata/influxdb_iox/issues/2094
I think that the current setting for `ROARING_ARCH` of `x86-64` may not be specific enough to ensure that things are built with the avx2 instructions. ~Ivy Bridge~ Haswell has those so I think that this should work better. 🤞
=> chore: target architecture with avx2

generated_types/protos/influxdata/iox/management/v1/database_rules.proto, generated_types/src/database_rules.rs, tests/end_to_end_cases/write_api.rs
Removes backward compatibility layer introduced in the config API refactoring in #2100
=> refactor: Remove deprecated target field in RoutingConfig

data_types/src/chunk_metadata.rs, generated_types/src/chunk.rs, lifecycle/src/lib.rs, lifecycle/src/policy.rs, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/chunk.rs, server/src/db/lifecycle.rs, server/src/db/lifecycle/compact.rs, server/src/db/lifecycle/persist.rs, server/src/db/system_tables.rs, server/src/db/system_tables/chunks.rs, server/src/db/system_tables/columns.rs
This is the actual goal of https://github.com/influxdata/influxdb_iox/issues/1927, aside from some refactoring to see if we can make CatalogChunk the *only* place first/last write times are managed.
=> feat: Make CatalogChunk first/last write times required

Cargo.lock
This release includes https://github.com/saulius/croaring-rs/pull/73 which
includes https://github.com/RoaringBitmap/CRoaring/commit/6403d44cbea549b31c16266d57cf9a42aac320b6
which should hopefully fix some of the dynamic CPUID issues we're
seeing.
Connects to https://github.com/influxdata/influxdb_iox/issues/2094, I still think there's something not going right with the `ROARING_ARCH` env var, so I want to see if we can figure that out so that we get 0 dynamic checks, but this fix should hopefully get us to only 1 cached dynamic check 🤷🏻‍♀️
=> fix: Upgrade croaring to get a performance fix

data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, generated_types/src/database_rules/lifecycle.rs, lifecycle/src/policy.rs, src/commands/database.rs, tests/end_to_end_cases/management_api.rs
__Rationale__
We noticed that using all the CPUs for compaction starves the other components of the ingestion.
Instead of hardcoding a fraction, this PR introduces a `max_active_compactions_cpu_fraction` config parameter
which can be used instead (mutually exclusive to)`max_active_compactions`. For example, by setting `max_active_compactions_cpu_fraction: 0.5` the maximum number of compactions will be half of the cpus available on the server.
=> feat(iox): Implement max_active_compactions_cpu_fraction

write_buffer/src/kafka.rs
Setting the "compression.type" in the topic config causes the compression to happen in the broker.
Setting it here will send less data to the broker.
=> feat(iox): Enable snappy compression in the producer

data_types/src/partition_metadata.rs, data_types/src/write_summary.rs, mutable_buffer/src/chunk.rs, mutable_buffer/src/chunk/snapshot.rs, parquet_file/src/chunk.rs, parquet_file/src/test_utils.rs, read_buffer/benches/database.rs, read_buffer/src/chunk.rs, server/src/db.rs, server/src/db/catalog.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/partition.rs, server/src/db/chunk.rs, server/src/db/lifecycle.rs, server/src/db/lifecycle/compact.rs, server/src/db/lifecycle/move_chunk.rs, server/src/db/lifecycle/persist.rs, server/src/db/lifecycle/write.rs, server/src/db/load.rs, server_benchmarks/benches/snapshot.rs, server_benchmarks/benches/write.rs
In addition to `CatalogChunk` having `time_of_first_write`/`time_of_last_write` fields, they also still need to be stored:
- In the Parquet [`IoxMetadata`](https://github.com/influxdata/influxdb_iox/blob/23a331b1334714473cc77f2f0967bfeb8a20519c/parquet_file/src/metadata.rs#L255-L256) so that they can round trip through object storage
- In [`WriteSummary`](https://github.com/influxdata/influxdb_iox/blob/23a331b1334714473cc77f2f0967bfeb8a20519c/data_types/src/write_summary.rs#L8-L11)
- In [`ChunkSummary`](https://github.com/influxdata/influxdb_iox/blob/23a331b1334714473cc77f2f0967bfeb8a20519c/data_types/src/chunk_metadata.rs#L143-L148)
- In the `DbChunk` snapshots taken from `CatalogChunk` (added in this PR) 
But most noticeably, the `TableSummaryAndTimes` type goes away in this PR, with …
=> refactor: make CatalogChunk (almost) only place that cares about first/last write times

src/influxdb_ioxd/rpc/error.rs, tests/end_to_end_cases/write_api.rs
Fixes #2127.
I went with "failed precondition" because the fix for no matching sharding rule might be to fix the sharding rules or fix the line protocol. Let me know if you'd rather have this send a different tonic status!
=> fix: Return a more helpful error message for no matching sharding rule

persistence_windows/src/checkpoint.rs, persistence_windows/src/persistence_windows.rs, server/src/db.rs, server/src/db/replay.rs
Someone might wonder why a regression test takes sooo much code:
- we need to mock partially persisted partitions
- for that we need to tightly control the clock
- that requires some wiring in `Db`
- some asserts were a bit messy
- the test framework was flaky for persist operations
- there was some edge case regarding checkpoints that wasn't checked before (and now fails w/ a regression test)
The actual fix will be in a follow-up PR, I want to avoid overlarge PRs.
=> test: regression test for #2185 

Cargo.lock, persistence_windows/Cargo.toml, persistence_windows/src/checkpoint.rs, persistence_windows/src/min_max_sequence.rs, server/src/db/replay.rs
There are currently a few bugs and semi-understood edge cases that can
lead to this case. So instead of bailing out, just issue a warning.
Closes #2185.
=> fix: only warn when partition ckpt and DB ckpt mins are out-of-sync

server/src/database.rs, server/src/db.rs, server/src/db/load.rs, server/src/db/replay.rs, server/src/lib.rs, server/src/utils.rs
Up until now we only skipped the execution of the replay plan, not its
construction. The replay plan construction has some bugs left, so let's
move this part behind the toggle as well.
=> refactor: do not construct replay plan when skipping replay

persistence_windows/src/persistence_windows.rs, server/src/db/catalog/partition.rs, server/src/db/replay.rs
This fixes an edge case where the speculated sequence ranges that can be
obtained from flush handles do not account for overlapping windows. The
symptom being that the resulting partition checkpoint marked sequence
numbers as unpersisted that where already persisted.
Fixes #2206.
=> fix: incorrect speculation of post-persist sequence ranges

persistence_windows/src/persistence_windows.rs, server/src/db/replay.rs, server/src/utils.rs
Do not forget max seen sequence numbers for partition-sequencer
combinations that can be skipped during replay.
Fixes #2215.
=> fix: always remember max seen sequ. numbers during replay

read_buffer/src/chunk.rs, read_buffer/src/column/string.rs, read_buffer/src/row_group.rs
Tidies up some logging we were using for debugging compaction issues.
=> refactor: remove logging

server/src/database.rs, server/src/lib.rs
Now all the code that is required to create a new database lives under
`server::database`, so it can easily be used for tests that don't
involve a server.
=> refactor: move database creation code around

data_types/src/instant.rs, persistence_windows/src/persistence_windows.rs
Unfortunately the tests in this PR are failing locally (consistently) on Apple M1 machines. Perhaps related to the following Rust issue: https://github.com/rust-lang/rust/issues/87906.
Ignoring them for now to 🍏 up the suite locally.
=> test: ignore failing tests on aarch64

src/commands/run.rs, src/influxdb_ioxd.rs, src/main.rs, src/object_store.rs
The object store handling is a large part of our CLI and kinda inlined
into the rest of the setup routines. This commit moves the object store
related code into its own module. As a bonus it can now be reused by
other CLI commands (e.g. low-level debug tools).
There are no functional changes here except for slight changes in the
error structure.
=> refactor: isolate CLI handling for object store

src/influxdb_ioxd/http.rs
Also let's not use the name "heappy" in the url as it is a codename of a project.
What matters is that it produces a standard allocation profile.
=> fix: Use same allocation profile url path as Go

Cargo.lock, Cargo.toml, iox_object_store/Cargo.toml, iox_object_store/src/lib.rs, object_store/src/path/parsed.rs, parquet_file/Cargo.toml, parquet_file/src/catalog.rs, parquet_file/src/chunk.rs, parquet_file/src/cleanup.rs, parquet_file/src/metadata.rs, parquet_file/src/rebuild.rs, parquet_file/src/storage.rs, parquet_file/src/storage_testing.rs, parquet_file/src/test_utils.rs, server/Cargo.toml, server/src/database.rs, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/lifecycle/write.rs, server/src/db/load.rs, server/src/lib.rs, server/src/utils.rs
Connects to #2193.
This is a step towards making parquet files relative to the database directory so that we can easily change the database directory.
The weirdest part of this is the `tokio::spawn` with the channel for listing from the object store... this is because in the next step, I'm going to change the iox_object_store's API to only use and return `IoxPath`s that are created within this crate. The current object_store trait API has lifetime restrictions that the output stream's lifetime is tied to the input.... which I don't think is actually needed, but is proving tricky to resolve (I think the cloud_storage crate has some overly restrictive lifetimes, and Rust might need generators to understand what I'm trying to tell it...)
=> feat: Crate that wraps object store for a particular database

data_types/src/partition_metadata.rs
Closes #
git revert -n db5fd935dd37ca8dec34a86e525dcd5e5823c9c5
that revert [this PR](https://github.com/influxdata/influxdb_iox/pull/2250/commits/03da4dee6fbb19b4530fabcd8f8ff026820b2387) that cause panic in Query-3000
=> chore: revert panic commit

src/main.rs
The commands `convert`, `meta` and `stats` have been removed by #1639. 
This PR removes the description in the command line.
=> docs: Remove the description of unused commands in cli

server/src/lib.rs, write_buffer/src/config.rs, write_buffer/src/mock.rs
This was removed in #2203 due to insufficient mocking capabilities.
=> test: restore `write_buffer_errors_propagate`

iox_object_store/src/lib.rs, object_store/src/memory.rs, object_store/src/path.rs, object_store/src/path/cloud.rs, object_store/src/path/file.rs, object_store/src/path/parsed.rs, parquet_file/src/catalog.rs, parquet_file/src/cleanup.rs, server/src/database.rs, server/src/db.rs
This is follow up of #2223  that removes obsolete `display` methods and use `fmt::Display` instead.
=> refactor: remove display methods, use fmt::Display instead.

Cargo.lock, Cargo.toml
In https://github.com/mkmik/heappy/commit/aed37ab50a70c3f0a7a8bd1c51d28d3d8050461f I fixed the main
problem that rendered free tracking useless: the allocator was actually allocating more bytes than requested; we were tracking the amount of memory requested by the user and not the size of the block that was returned to the user. However, when we were tracking a call to free we used the size of the memory block which was bigger than the amount that was tracked; this led to negative numbers of "in use memory".
=> feat: Enable freed memory tracking in heappy

read_buffer/src/chunk.rs, server/src/db.rs
Towards #2317
IOx is now utilising a feature of the Read Buffer that allows a chunk to contain multiple row groups. This needs to be observable via metrics. Whilst tracking the distribution of row groups in chunks would be ideal (outlined in #2317) I am starting with just a gauge to track overall number of row groups in the Read Buffer.
=> feat: add metric to track total row groups

src/influxdb_ioxd/http.rs, src/influxdb_ioxd/http/heappy.rs
Rename `frequency` to `interval` and set the default to `1`, which means that
every allocation will be counted.
Before this PR, we were incorrectly reusing the same "frequency" parameter (and related default of 99)
which meant that we were skipping small allocations that.
The sampling interval is a number of bytes that have to cumulatively allocated for a sample to be taken.
For example if the sampling interval is 99, and you're doing a million of 40 bytes allocations, the allocations profile will account for 16MB instead of 40MB. Heappy will adjust the estimate for sampled recordings, but now that feature is not yet implemented.
=> fix: Make allocs profile record all allocations

Cargo.lock, Cargo.toml
Currently heappy is reporting "bytes allocated" and "inuse_bytes" ("bytes allocated - freed bytes").
Since the allocation site and free site can be wildly different, it's very hard to correlate these events
and have a meaningful "inuse_bytes" graph.
I have a plan for how to fix this for good, but in the meantime I'd like to report raw "freed bytes".
=> feat(iox): Upgrade heappy to present free memory events

write_buffer/src/kafka.rs
By default the queue will be filled to up to 1GB which makes finding
memory leaks quite hard.
=> fix: limit kafka consumer queue to 100MB

write_buffer/src/kafka.rs
I think that while this value limits the maximum memory consumption, it
is too optimistic.
=> fix: limit kafka consumer queue to 10MB

iox_data_generator/benches/point_generation.rs, iox_data_generator/src/agent.rs, iox_data_generator/src/lib.rs, iox_data_generator/src/main.rs, iox_data_generator/src/write.rs
Adds batch_size to the data genrator to optionally gather multiple calls to generate for each agent. For example, if you have a sampling interval of 10 seconds and start at some point back in time with a batch size of 3, it gather 3 samplings before writing to the points writer. For runs against a server API, this will batch them together in a single API call.
=> feat: Add batching to the data generator

Cargo.lock, Cargo.toml, src/influxdb_ioxd/http.rs, src/influxdb_ioxd/http/heappy.rs
Upgrades heappy to include https://github.com/mkmik/heappy/pull/2
and adapts to the API change.
=> fix(heappy): Prevent re-entering a running heap profile

read_buffer/src/column/encoding/string/dictionary.rs, read_buffer/src/column/encoding/string/rle.rs
Following on from https://github.com/influxdata/influxdb_iox/pull/2379
This is a belt and braces type of PR.
This PR updates the capacity-based size metrics to include any excess capacity in allocated strings stored in dictionary encodings. It also ensures strings are minimally sized when using some APIs.
=> refactor: improve string storage and sizing metrics for Read Buffer columns

influxdb_iox_client/src/client/management.rs, influxdb_iox_client/src/lib.rs
Previously a consumer of the API client would have to import both `influxdb_iox_client` and `generated_types` in order to access some types used in the API client - this change makes everything accessible from the `influxdb_iox_client` crate 👍 
---
* refactor: re-export google proto types (87beefa9)
The TemplatePart::Table() variant contains a google::protobuf::Empty type
which is defined in the generated_types crate.
Rather than force consumers to import two crates which have to be kept in
sync, this commit re-exports the google types within the influxdb_iox_client
crate as it's already a dependency, and makes using types like protobuf's
Duration or long-running-operation API easier for the consumer.
=> refactor: re-export google proto types

server/src/db.rs, server/src/db/replay.rs, tests/end_to_end_cases/management_api.rs, tests/end_to_end_cases/management_cli.rs
- add longer wait times to tests
- exclude chunks that have active lifecycle actions early (instead of
failing the whole set)
- properly catch the "no chunks" case
Fixes #2434.
=> fix: make "persist partition" a bit more stable

generated_types/protos/influxdata/iox/management/v1/service.proto, influxdb_iox_client/src/client/management.rs, iox_object_store/src/lib.rs, iox_object_store/src/paths.rs, iox_object_store/src/paths/parquet_file.rs, iox_object_store/src/paths/transaction_file.rs, server/src/database.rs, server/src/lib.rs, src/influxdb_ioxd/rpc/error.rs, src/influxdb_ioxd/rpc/management.rs, tests/end_to_end_cases/management_api.rs
This PR adds a management gRPC API to delete a database, which creates a tombstone file. The code that looks for active generations now checks to see if the tombstone file exists in a generation directory, and if it does exist, that generation is marked as deleted.
I feel like I'm probably doing some snafu things wrong; I'd like to have @shepmaster take a look at it.
Closes #1871.
=> feat: Add an iox_object_store API for writing the tombstone file

query/src/provider/overlap.rs
Closes #2408 
The fix: If the column is "time", do not need to check if it is sorted in the key because it is always last
=> fix: time column is alwyas last even if the column is sorted lexicographically

server/src/lib.rs, src/commands/database.rs, src/influxdb_ioxd/rpc/error.rs, tests/end_to_end_cases/management_api.rs, tests/end_to_end_cases/management_cli.rs
Fixes #2432 and #2197.
Turns out with the changes in 2f49e47a2362f6b30774f278a88b09eabe24aaab to filter out databases that don't returned provided rules, listing databases without listing deleted databases Just Works because deleted databases don't return provided rules!
Not sure if this feels too coincidental?
=> feat: Wire database deletion through the CLI, add tests for not including deleted databases in database list

server/src/lib.rs
Fixes #2196.
Most of the server startup work was done in https://github.com/influxdata/influxdb_iox/commit/6d0959fbc3c0bfb7420caa9e92b0ba7e250f7d6b but this adds a test for the expected error state of a database when there's more than one generation directory that doesn't have a tombstone file.
=> test: Database startup error when there are multiple active generations

data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, generated_types/src/database_rules.rs, iox_data_generator/src/bin/create_database.rs, server/src/database.rs, server/src/lib.rs, tests/end_to_end_cases/scenario.rs, tests/end_to_end_cases/write_buffer.rs, write_buffer/src/config.rs
This allows:
- different types (instead of guessing through the connection URL)
- sequencer counts (not used yet but will be by #2455)
- extensible configs (e.g. to configure Kafka in a more granular way,
not wired up yet)
- future extensions (since we use a message now instead of a single
string)
**BREAKING: This requires changes for deployed systems / existing DBs!**
=> refactor: more flexible writer buffer config

influxdb_iox_client/Cargo.toml
This was forcing Conductor to pull in and compile all of the `arrow` crate, adding 22 compilation units - we spent more time compiling arrow than `libconductor`!
Looks like an oversight added in #2098  @alamb ?
---
* build: feature-gate arrow dep for mgmt client (dd88b5ed)
Avoid pulling in & compiling arrow for consumers of the managemnt client.
PR #2098 added arrow_util as a dependency of this crate which in turn pulls in
all of arrow, however it is only used in the flight client.
This commit feature-gates arrow_util behind "flight" with the rest of the
arrow deps.
=> build: feature-gate arrow dep for mgmt client

iox_data_generator/src/bin/create_database.rs, iox_data_generator/src/bin/iox_data_generator.rs, iox_data_generator/src/lib.rs, iox_data_generator/src/substitution.rs, iox_data_generator/src/write.rs
- Move main binary to `src/bin`. It's easier to reason about when all
binaries are in a single directory and the other files in `src` just
belong to the lib. Note that `cargo run [-p iox_data_generator]` still
works.
- Enable lints that we use elsewhere. Fix the few issues that were found
by this (e.g. broken intradoc links).
=> chore: `iox_data_generator` QA

Cargo.lock, iox_data_generator/Cargo.toml, iox_data_generator/benches/point_generation.rs, iox_data_generator/schemas/storage_cardinality_example.toml, iox_data_generator/src/bin/iox_data_generator.rs, iox_data_generator/src/lib.rs, iox_data_generator/src/specification.rs, iox_data_generator/src/substitution.rs, iox_data_generator/src/tag.rs, iox_data_generator/src/tag_set.rs, iox_data_generator/src/write.rs
This adds the ability to pre-generate values and tag sets in the data generator. This makes it easy to have tags that depend on other tag values (like buckets in an org) and have tag values that have one associated tag (like if something is in production or staging environment). Follow on work will add the actual generation to the agent spec. An added bonus of these pre-generated values is that generating samples won't require any sort of template evaluation for all of the tags in the tag sets. Only unique values (like trace_id or span_id) would need to be generated during sampling generation.
At this point I think I have a specification that is nice and tag data that looks like how I want it to look (see the tests in `tag_set.rs`. Next up I need to update `MeasurementSpec` to be able to …
=> feat: Add pre-generated values and tag sets to data generator

parquet_file/src/catalog/dump.rs, src/commands/debug.rs
=> feat: show number of stripped bytes in catalog dump

Cargo.lock, Cargo.toml, data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, generated_types/src/database_rules/lifecycle.rs, parquet_file/src/catalog/mod.rs, parquet_file/src/catalog/prune.rs, server/src/db.rs, src/commands/database.rs, tests/end_to_end_cases/management_api.rs
Through checkpoints, the preserved catalog is currently growing quadratic since each new checkpoint lists all files of the previous one plus the new files since then. Since we probably only wanna "go back in time" for a limited time span, let's just delete old transactions.
In the future, we could extend the pruning to be more sophisticated, e.g. keep checkpoints in different granularity depending on the age (e.g. hourly for checkpoints aged >1d, daily for checkpoints aged >1W, ...). I deem this simple approach here good enough for now though.
=> feat: prune old transactions from preserved catalog

Cargo.lock, query/Cargo.toml, query/src/predicate.rs
As a a nice side effect, the parser no longer depends on the line
protocol parser.
=> refactor: stricter delete predicate TS parsing

server/src/db.rs, server/src/db/replay.rs, server/src/lib.rs, server/src/write_buffer.rs
Instead of depending on the `chrono` clock implicitly via `Utc::now()`
we should make it an explicit parameter. This is essential for testing:
1. We have many tests guessing around this value by taking `Utc::now()`
directly before or after the write (this commit doesn't fix that, but
allows us to fix it in a follow-up).
2. We have some tests that ignore the `time_of_write` values in some
comparisons because they cannot control that value (fix not included
here but left as a follow-up).
3. The upcoming compression (#2528) needs to control timestamps within
the compressed payload (and `time_of_write` is embedded in the
parquet metadata) because the compressed size depends on it (even if
the uncompressed size is stable).
In general I argue that a "clock" is always data and should be passed …
=> refactor: make `time_of_write` a parameter

parquet_file/src/catalog/cleanup.rs, parquet_file/src/catalog/core.rs, parquet_file/src/catalog/dump.rs, parquet_file/src/catalog/interface.rs, parquet_file/src/catalog/mod.rs, parquet_file/src/catalog/prune.rs, parquet_file/src/catalog/rebuild.rs, parquet_file/src/catalog/test_helpers.rs, parquet_file/src/metadata.rs, server/src/database.rs, server/src/db.rs, server/src/db/lifecycle/error.rs, server/src/db/lifecycle/write.rs, server/src/db/load.rs, server/src/lib.rs
This makes it clearer which traits and functions users of the preserved
catalog must implement. This also splits the error types into smaller
enums that are easier to understand.
This change should make it easier to implement new functionality (like
capturing delete predicates).
=> refactor: split preserved catalog `api` into `core` and `interface`

read_buffer/src/column.rs, read_buffer/src/column/encoding/scalar/fixed.rs, read_buffer/src/column/encoding/scalar/fixed_null.rs, read_buffer/src/column/encoding/scalar/rle.rs, read_buffer/src/column/encoding/scalar/transcoders.rs, read_buffer/src/column/float.rs
This PR addresses a defect I identified when working on a new timestamp compression feature.
As far as I'm aware we have not hit upon this defect during internal testing yet, likely because we primarily test via the gRPC API, and with that API you generally do not filter on field columns.
The defect applies to `f64` columns in the Read Buffer that have been encoded using the Byte Trimming encoder. Recall that this encoding can store a column of `f64` values as integers with a smaller physical footprint, subject to the input values all being natural numbers.
For example: `[1.0, 20.0, 30.0] -> [1_u8, 2, 30]`.
The defect is as follows: prior to this change, if you provided a predicate along these lines to the read buffer `WHERE my_col >= 20.4` the column encoding would first convert the …
=> fix: Ensure byte trimmed floats can handle arbitrary float literals

server/src/db.rs, server/src/db/chunk.rs, server/src/db/lifecycle/compact.rs
Lift a few `Utc::now()` calls further and narrow down checks in tests.
Also avoid a few `<` comparisons which might not always hold.
=> test: even more time-related lifting

predicate/src/predicate.rs, query/src/lib.rs, query/src/test.rs, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/partition.rs, server/src/db/chunk.rs, server/src/db/lifecycle/compact.rs, server/src/db/lifecycle/persist.rs, server/src/db/load.rs, src/influxdb_ioxd/rpc/management.rs
The motivations are:
1. The API uses a SINGLE predicate and adds that to many chunks. With
`Arc<Vec<...>>` you gain nothing, with `Vec<Arc<...>>` the predicate
is only stored once (in many vectors)
2. While we currently add predicates blindly to all chunks, we can be way
smarter in the future and prune out tables, partitions or even single
chunks (based on statistics). With that, it will be rare that many
chunks share the exact same set of predicates.
3. It would be nice if we could de-duplicate predicates when writing them
to the preserved catalog without needing to repeat the pruning
discussed in point 2. This is way easier to implement whan chunks
exists in `Arc`s.
4. As a side-note: the `Arc<Vec<...>>` wasn't really cloned around but
instead was created many time. So the new version …
=> refactor: `Arc<Vec<...>>` => `Vec<Arc<...>>` for del predicates

generated_types/protos/influxdata/iox/catalog/v1/catalog.proto, parquet_file/src/catalog/core.rs, parquet_file/src/catalog/dump.rs, parquet_file/src/catalog/test_helpers.rs
~Based on #2572 because this PR here uses the fact that predicates are not carrying table names any longer.~
For #2518. There will be one last PR on top of this that adds the `Db` => `PreservedCatalog` wiring + testing.
=> feat: teach preserved catalog to handle delete predicates

.cargo/audit.toml, .circleci/config.yml
For now we ignore warnings (e.g. "crate is yanked" or "crate is
unmaintained") because:
- internal crates w/ names of crates.io crates (e.g. `query`) are
treated like crates.io-crates even though they shouldn't, see
https://github.com/rustsec/rustsec/issues/232
- many crates are currently unmaintained and require a bit of upstream
work (e.g. `chrono` is currently not very active but uses an old
version of `time` which uses the unmaintained `stdweb`)
Closes #2575.
=> ci: add cargo audit

Cargo.lock, generated_types/Cargo.toml, internal_types/Cargo.toml, mutable_buffer/Cargo.toml, object_store/Cargo.toml, parquet_file/Cargo.toml, write_buffer/Cargo.toml
This doesn't remove any crates from our dependency set but should make compilation a bit faster because more work can be done sooner.
=> chore: clean up dependencies a bit

query_tests/src/influxrpc/field_columns.rs, query_tests/src/influxrpc/read_filter.rs, query_tests/src/influxrpc/read_group.rs, query_tests/src/influxrpc/read_window_aggregate.rs, query_tests/src/influxrpc/table_names.rs, query_tests/src/influxrpc/tag_keys.rs, query_tests/src/influxrpc/tag_values.rs, query_tests/src/sql.rs, query_tests/src/table_schema.rs
The compile times of `query_tests` are currently rather long. Since macros are expended rather early in the compilation process they are rather costly. Also they are "not nice" for IDEs since type-checking is done on the expansion side (rather than in the macro body). Luckily the macros here can easily be replaced by ordinary functions.
**Before:**
```text
+--------------------------------------------------+-----------+-----------------+----------+------------+---------------------------------+
| Item                                             | Self time | % of total time | Time     | Item count | Incremental result hashing time |
+--------------------------------------------------+-----------+-----------------+----------+------------+---------------------------------+
| …
```
=> refactor: convert macros in `query_tests` to functions

CONTRIBUTING.md, perf/perf.py, src/influxdb_ioxd.rs, src/influxdb_ioxd/http.rs, tests/end_to_end_cases/tracing.rs, trace_exporters/src/lib.rs, trace_http/src/ctx.rs, trace_http/src/tower.rs
Closes https://github.com/influxdata/influxdb_iox/issues/2367, related to https://github.com/influxdata/influxdb_iox/issues/2549
When making requests to IOx, it would be nice  if we could request tracing without having to make up unique trace ids / spans such as `4459495:30434:0:1` for each request, as described in https://github.com/influxdata/influxdb_iox/blob/main/CONTRIBUTING.md#step-3-send-a-request-with-trace-context
1. Add `JAEGER_DEBUG_HEADER` consistent with https://pkg.go.dev/k8s.io/ingress-nginx/internal/ingress/controller/config
2. Remove redundant default values in trace_http (use the defaults from command line)
3. Update the docs
4. Update perf.py
1. If the `jaeger_trace_context_header_name` (defaults to `uber-trace-id`) is specified, then the trace/span from that is used
2. …
=> feat: Add support to create new traces in IOx via JAEGER_DEBUG_HEADER

server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/load.rs
This is prep work for improving the error handling around predicate preservation.
=> refactor: `CatalogChunk::add_delete_predicate` cannot fail

server/src/db/catalog/partition.rs, server/src/db/lifecycle/compact.rs, server/src/db/lifecycle/persist.rs
- Bubbles up "not found" error, the caller should reason about it
- Returns deleted chunk
This will be useful if we wanna handle predicates correctly during the lifecycle (at the moment we might loose a few new predicates on the way).
=> refactor: make `Partition::force_drop_chunk` similar to `Partition::drop_chunk`

read_buffer/benches/read_filter.rs, read_buffer/src/chunk.rs, read_buffer/src/table.rs, server/src/db/chunk.rs
Related to #1603.
This PR adds some validation checks on the expressions within predicates supplied to the Read Buffer. This ensures that invalid predicates cannot cause the Read Buffer to panic, but instead result in an error that is propogated back to the query engine.
Currently, invalid predicates are those where making a comparison between the values and the column and the provided literal are not obvious, e.g., trying to apply the expression `region > 33` to a `region` column that has a string datatype.
This PR does not resolve https://github.com/influxdata/influxdb_iox/issues/1603 - in fact a predicate `temp = 22.2` for a `temp` column with a physical type `u64` is considered valid within the logic of this PR.
A follow on PR will teach the Read Buffer to coalesce compatible types …
=> feat: validate Read Buffer predicates

src/commands/debug.rs
I noticed running `influxdb_iox --help`:
```
SUBCOMMANDS:
database     All possible subcommands for database
debug        Manage long-running IOx operations
help         Prints this message or the help of the given subcommand(s)
operation    Manage long-running IOx operations
run          CLI config for server ID
server       IOx server commands
sql          Start IOx interactive SQL REPL loop
```
This PR updates the description for the `debug` sub-command.
So now:
```
SUBCOMMANDS:
database     All possible subcommands for database
debug        Interrogate internal database data
help         Prints this message or the help of the given subcommand(s)
operation    Manage long-running IOx operations
run          CLI config for server ID
server       IOx server commands
sql          Start IOx …
```
=> refactor: tidy up debug CLI help

Cargo.lock, iox_object_store/src/lib.rs, object_store/Cargo.toml, object_store/src/aws.rs, object_store/src/azure.rs, object_store/src/disk.rs, object_store/src/dummy.rs, object_store/src/gcp.rs, object_store/src/lib.rs, object_store/src/memory.rs, object_store/src/throttle.rs, parquet_file/src/catalog/core.rs, parquet_file/src/catalog/internals/proto_io.rs, parquet_file/src/storage.rs, server/src/db.rs, server/src/lib.rs, server_benchmarks/benches/catalog_persistence.rs, src/object_store.rs
Closes #2483 
The future is here! And they're evenly distributed, all over!
This borrows heavily from [the s3-algo crate's retry of rusoto requests](https://github.com/openanalytics/s3-algo/blob/464f7481b644ea8b5f21ea2d943002a8ee90db06/src/lib.rs#L133) and wraps all S3 requests in the `s3_request` function, that uses the [futures-retry crate](https://crates.io/crates/futures_retry) to clone the future and run it again if it fails and certain conditions are met.
There's a lot of minor rearranging of the API to make futures and closures that make futures and closures... I hope it'll make sense if you look commit-by-commit, but please ask if anything is confusing. 
The `ObjectStore` trait needed to change, so there's a tiny bit of changes in all the object store implementations, but this …
=> fix: Retry S3 requests that fail with 5xx and remove streaming put API that wasn't used

query_tests/src/sql.rs, read_buffer/src/chunk.rs, read_buffer/src/row_group.rs, read_buffer/src/table.rs, server/src/db/chunk.rs, server/src/db/pred.rs
Closes #1603 
This PR restricts the validation of predicates against the Read Buffer to only those that contain the same literal type as the column specified in the chunk schema.
For cases where the expression's literal differs in type (e.g., it's a float) from the column (e.g., it's an integer column) the new `validate_predicate` API will return an error. This API is used to validate predicates againts read buffer chunks before execution begins, which gives us the opportunity to fall-back to using the `Filter` step in the DF plan.
*Note* - I have a follow-on PR planned that will allow us to push expressions like `col_int > 3.2` down to the RUB, but I wanted to split it out of the "fix" step.
This PR fixes the issue of wrong query results, the follow on will allow us to push more types of …
=> fix: fallback to DataFusion predicates if unable to execute on RUB

Cargo.lock
Update `nix` dependency which includes a fix for RUSTSEC-2021-0119
=> fix: Fix RUSTSEC-2021-0119

Cargo.lock, generated_types/protos/influxdata/iox/catalog/v1/predicate.proto, predicate/Cargo.toml, predicate/src/delete_expr.rs, predicate/src/expr.rs, predicate/src/lib.rs, predicate/src/serialize.rs
Place a dedicated `Expr` type between datafusion and protobuf. While
this type is currently only used during serialization, it will be used
within `Predicate` in a follow-up change to enable de-duplication of
predicates and avoid the double parsing of datafusion expressions (we
are already somewhat parsing them when we check for valid delete
predicates).
This change looks larger than it is. In practice it just separates the
conversion "datafusion => protobuf" into "datafusion => IOx => protobuf"
and "protobuf => datafusion" into "protobuf => IOx => datafusion". So
(apart from the error types) this is functionally the same.
=> refactor: use dedicated in-memory `Expr` type during IO

data_types/src/chunk_metadata.rs, generated_types/src/chunk.rs, lifecycle/src/policy.rs, parquet_file/src/catalog/core.rs, parquet_file/src/catalog/dump.rs, parquet_file/src/catalog/rebuild.rs, parquet_file/src/metadata.rs, parquet_file/src/storage.rs, parquet_file/src/test_utils.rs, query/src/test.rs, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/partition.rs, server/src/db/system_tables/chunks.rs, server/src/db/system_tables/columns.rs, tests/end_to_end_cases/management_api.rs, tests/end_to_end_cases/management_cli.rs
This will make it easier to handle missing values.
Helps with #2633.
=> refactor: make `ChunkOrder` non-zero

generated_types/protos/influxdata/iox/catalog/v1/predicate.proto, parquet_file/src/catalog/core.rs, parquet_file/src/catalog/test_helpers.rs, predicate/src/delete_predicate.rs, predicate/src/serialize.rs, query_tests/src/scenarios/delete.rs, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/lifecycle/compact.rs, server/src/db/lifecycle/persist.rs, src/influxdb_ioxd/http.rs, src/influxdb_ioxd/rpc/management.rs
This "just" deletes code or makes code private, no functional change.
=> refactor: remove unused fields from `DeletePredicate` and remove intermediate `ParseDeletePredicate`

generated_types/build.rs, generated_types/protos/influxdata/iox/catalog/v1/catalog.proto, parquet_file/src/catalog/core.rs, parquet_file/src/catalog/dump.rs, parquet_file/src/catalog/internals/proto_parse.rs
It's slightly more efficient and I plan to use the same format for UUID-based chunk IDs.
=> refactor: use protobuf bytes for transaction UUIDs

client_util/src/connection.rs
Unblocks https://github.com/influxdata/conductor/issues/577
---
* refactor: derive Clone for IOx client builder (53e49156)
Allows an IOx client builder (with its associated configuration) to be cloned.
=> refactor: derive Clone for IOx client builder

generated_types/protos/influxdata/iox/management/v1/service.proto, influxdb_iox_client/src/client/management.rs, predicate/src/delete_predicate.rs, src/influxdb_ioxd/http.rs, src/influxdb_ioxd/rpc/error.rs, src/influxdb_ioxd/rpc/management.rs, tests/end_to_end_cases/management_api.rs
Closes #2703 
Now the delete process is clear, this PR handles the responses that were  unclear before
=> feat: handle delete responses

.github/dependabot.yml, influxdb_line_protocol/Cargo.toml
Ideally we would eliminate the dependency on the line protocol parser for consumers of the IOx API client as it does not functionally depend upon it (and more!) but it fairly intertwined through `data_types` / `generated_types` - this unblocks Conductor work.
Fixes https://github.com/influxdata/influxdb_iox/issues/2735.
---
* build: pin smallvec (5abc5540)
Pin the smallvec version until the rest of the ecosystem catches up.
Fixes https://github.com/influxdata/influxdb_iox/issues/2735.
=> build: pin smallvec

data_types/src/chunk_metadata.rs, parquet_file/src/catalog/dump.rs
The full UUIDs are a bit annoying for test ChunkIds, esp. since they are hex-based.
=> feat: improve `Debug`/`Display` for test `ChunkId`s

Cargo.lock, query/Cargo.toml, query/src/exec/task.rs
Our executor is not meant as a fire-and-forget system. Instead the
submitter should always poll the result. Dropping the receiver side (aka
the job handle) should cancel the job.
Note that this is NOT sufficient to fix #2027 since datafusion also has a few places involving `spawn` where dropping the receiver doesn't cancel the spawned task.
=> refactor: cancel executor jobs on drop

write_buffer/src/core.rs, write_buffer/src/kafka.rs, write_buffer/src/mock.rs
Pulled out of #2497. I would like to do a bit of write buffer work (e.g. adding a format header for a potential transition to protobuf-based messages), and would like to merge this change beforehand. No matter how we implement message distribution, this feature here is going to be required anyways (since the producer side needs to detect the number of partitions).
=> feat: allow write buffer producers to read sequencer IDs

generated_types/build.rs, generated_types/protos/influxdata/iox/management/v1/server_config.proto, generated_types/src/database_rules.rs, generated_types/src/lib.rs, generated_types/src/server_config.rs, iox_object_store/src/lib.rs, iox_object_store/src/paths.rs, server/src/database.rs, server/src/lib.rs, server/src/rules.rs
Connects to #2676.
In the course of working on #2675, it became clear that not knowing the database name until reading the db rules wasn't quite the desired API. Instead of reading the db rules to find database names, and instead of storing multiple `link` files, each server will have one `config.pb` file in its `s3://<bucket..>/nodes/<server-id>/` directory that will contain the list of databases it owns with their names and object store locations.
This PR *writes* out the file after starting up the server and after databases are created to transition to using this file. The next PR will switch server startup to reading the file if it exists and falling back to scanning object storage until we've transition to the server config file always existing.
=> feat: Write a server config that lists database names and object storage locations

server/src/database.rs, server/src/db.rs, server/src/lib.rs, src/influxdb_ioxd/http.rs, src/influxdb_ioxd/rpc/write.rs, src/influxdb_ioxd/rpc/write_pb.rs
This doesn't do anything really useful yet because the consumer side cannot really use it (yet) due to missing wiring. Hence the end2end test is missing.
=> feat: wire span context frontent=>WriteBuffer

scripts/logfmts
Local timezones and sharing logs with geographically distributed colleagues don't mix together.
=> fix(logfmts): Use UTC for ./scripts/logfmts

generated_types/build.rs, generated_types/protos/influxdata/iox/preserved_catalog/v1/catalog.proto, generated_types/protos/influxdata/iox/preserved_catalog/v1/parquet_metadata.proto, generated_types/protos/influxdata/iox/preserved_catalog/v1/predicate.proto, generated_types/src/lib.rs, parquet_catalog/src/core.rs, parquet_catalog/src/dump.rs, parquet_catalog/src/internals/proto_io.rs, parquet_catalog/src/internals/proto_parse.rs, parquet_catalog/src/internals/types.rs, parquet_file/src/metadata.rs, predicate/src/delete_expr.rs, predicate/src/serialize.rs
This makes it clearer what's going since the contained messages are
only for the preserved part, not the in-mem catalog and its management.
=> refactor: move `catalog` protobuf to `preserved_catalog`

influxdb_iox/src/commands/debug/dump_catalog.rs, influxdb_iox/tests/end_to_end_cases/scenario.rs, iox_object_store/src/lib.rs, iox_object_store/src/paths.rs, iox_object_store/src/paths/parquet_file.rs, iox_object_store/src/paths/transaction_file.rs, parquet_file/src/test_utils.rs, server/src/database.rs, server/src/db/load.rs, server/src/lib.rs, server/src/utils.rs
Closes #2677.
I wrote tests simulating updating to this code with an existing database under the server ID in object storage that pass; so I **don't** think it will be necessary to wipe object storage when deploying this. Let me know if you'd like anything added to the test!
=> fix: Change database paths to be under /dbs/ instead of under /[server id]/

Cargo.lock, data_types/src/write_buffer.rs, generated_types/src/write_buffer.rs, router/Cargo.toml, router/src/connection_pool.rs, router/src/grpc_client.rs, router/src/lib.rs, write_buffer/src/kafka.rs
Implements connection pooling and mocking features. This is slightly similar to what the old `ConnectionManager` does but relies (like the write buffer) on dynamic dispatch so we don't have to use generics all over the place.
The `data_types` changes are required so we can hash write buffer configs.
=> feat: add connection management for router

data_types/src/router.rs, influxdb_iox/src/commands/run/router.rs, router/src/lib.rs, router/src/router.rs, router/src/server.rs, router/src/write_sink.rs
~Draft, on top of #3040.~
This implements the full core logic required for **write** routing. With #3035 I can then wire up the gRPC and HTTP APIs rather easily.
=> feat: router core logic

.circleci/config.yml
`--all-tags` as introduced for version 20.10 but appearently we're
running an older version.
=> ci: fix usage of old docker version

influxdb_iox_client/src/client/router.rs
This is required to construct a write-buffer-based router config.
This will make the conductor code a bit cleaner.
=> fix: also export `write_buffer` gRPC types from router client

docker/Dockerfile.iox.dockerignore
I have no idea why this didn't occur locally :shrug:
=> fix: `perf_image` docker ignore

influxdb_iox/src/commands/run/router.rs, influxdb_iox/tests/common/server_fixture.rs, influxdb_iox/tests/end_to_end_cases/deployment_api.rs, influxdb_iox/tests/end_to_end_cases/metrics.rs, influxdb_iox/tests/end_to_end_cases/scenario.rs, influxdb_iox/tests/end_to_end_cases/tracing.rs, influxdb_iox/tests/end_to_end_cases/write_buffer.rs, influxdb_iox_client/Cargo.toml, influxdb_iox_client/src/client/deployment.rs
See commits (it's mostly prep work for the actual fix).
=> fix: server IDs for routers on startup + improve client error handling

Cargo.lock, data_types/Cargo.toml, data_types/src/consistent_hasher.rs
The std `DefaultHasher` is NOT guaranteed to stay the same, so let's
directly use the `SipHasher13` which at the moment (2021-11-15) is used
by the standard lib.
Fixes #3063.
=> fix: ensure `ConsistenHasher` is consistent

Cargo.lock, router/src/connection_pool.rs, router/src/server.rs, router/src/write_sink.rs, server/src/application.rs, write_buffer/Cargo.toml, write_buffer/src/config.rs, write_buffer/src/kafka.rs
This maps a subset of Kafka stats as metrics. The set can -- of course
-- be changed in the future depending on our needs.
Fixes #3100.
=> feat: emit Kafka stats as metrics instead of logs

.circleci/config.yml, Dockerfile, docker/Dockerfile.ci, docker/Dockerfile.iox
This will break `perf_image` until the new CI image is built due to the
newly required `--all-tags` parameter to `docker push` that isn't
available for the docker version we run on buster.
=> ci: update CI images from docker buster to bullseye

data_types/src/chunk_metadata.rs, data_types/src/job.rs, generated_types/build.rs, generated_types/protos/influxdata/iox/management/v1/chunk.proto, generated_types/protos/influxdata/iox/management/v1/jobs.proto, generated_types/src/chunk.rs, generated_types/src/job.rs, lifecycle/src/lib.rs, lifecycle/src/policy.rs, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/partition.rs, server/src/db/lifecycle.rs, server/src/db/lifecycle/compact_object_store.rs, server/src/db/lifecycle/error.rs
This is the first part of  #3089. The function is available but only step 1 is implemented and tested. Step 2-4 will be in the following PRs
=> feat: compact_object_store_chunks : initial implementation that also lists steps to complete

iox_data_generator/src/field.rs
This generates 4 samples of a incrementing metric with a range of 3..10.
If the value for the first 3 "intervals" is 3, and the last is 9, the assertion can fail.
i.e. val1 = 3, val2 = 6, val3 = 9, val4 = 9
The simple fix is to make the range 3..8
=> fix: flaky incrementing_i64_that_resets (#3197)

influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/data.rs, influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/service.rs, query/src/exec/seriesset/series.rs
Closes https://github.com/influxdata/influxdb_iox/issues/3165
This PR adds support to optionally emit the tag keys `_measurement` and `_field` as the special representation of `\x00` and `\xff` respectively.
This feature is needed because as part of the Storage Read API there is an enum on `ReadFilterRequest` that the caller can set to request that tag sets include `\x00` and `\xff` instead of the aforementioned names.
https://github.com/influxdata/influxdb_iox/blob/67c24ccd7e5dbb98ce8dbdf3c2fd6955838c6d09/generated_types/protos/influxdata/platform/storage/storage_common.proto#L35-L58
As well as new unit test confirming this behaviour I have ran the internal Flux test suite: *no regressions*. Further, I have ran the internal InfluxQL test suite and reduced the number of failures from …
=> feat: support emitting measurement/field tag keys in binary format

generated_types/protos/influxdata/iox/management/v1/service.proto, influxdb_iox/src/commands/server.rs, influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs, influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/mod.rs, influxdb_iox/tests/end_to_end_cases/management_api.rs, influxdb_iox/tests/end_to_end_cases/management_cli.rs, influxdb_iox/tests/end_to_end_cases/metrics.rs, influxdb_iox/tests/end_to_end_cases/persistence.rs, influxdb_iox/tests/end_to_end_cases/scenario.rs, influxdb_iox/tests/end_to_end_cases/tracing.rs, influxdb_iox/tests/end_to_end_cases/write_api.rs, influxdb_iox/tests/end_to_end_cases/write_buffer.rs, influxdb_iox_client/src/client/management.rs
Tests are covered by `deployment_api.rs`.
Ref #2980.
=> refactor: remove methods from `ManagementService` that were moved to `DeploymentService`

generated_types/protos/influxdata/iox/delete/v1/service.proto, influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/delete.rs, influxdb_iox/src/influxdb_ioxd/server_type/router/rpc/delete.rs, influxdb_iox/tests/end_to_end_cases/delete_api.rs, influxdb_iox_client/src/client/delete.rs, router/src/grpc_client.rs
IOx is the only consumer of this API so we might just use the serialized
form. Cloud2 uses the HTTP API which supports SQL-like predicates.
Fixes #3192.
=> refactor: use serialized predicates instead of strings for gRPC deletes

generated_types/protos/influxdata/iox/management/v1/service.proto, influxdb_iox/src/commands/server_remote.rs, influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs, influxdb_iox/tests/end_to_end_cases/management_api.rs, influxdb_iox/tests/end_to_end_cases/write_api.rs, influxdb_iox_client/src/client/management.rs
Tests are covered by `remote_api.rs`.
Ref #2980.
=> refactor: remove methods from `ManagementService` that were moved to `RemoteService`

influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/service.rs
Adds some trace output to see the contents of meta query responses before they're sent over the wire.
=> refactor: add debug logging for meta queries

Cargo.lock, write_buffer/Cargo.toml, write_buffer/src/core.rs, write_buffer/src/file.rs
The existing channel construction could lead to cases where streams
would consume messages, put them into the channel but then when the
stream gets dropped the message would be gone forever. So lets move from
a channel-based implementation to directly invoke the generator future,
so this buffering doesn't occur.
Fixes #3179.
=> fix: do not forget outputs of file-based write buffer

query/src/frontend/influxrpc.rs, query_tests/src/influxrpc/tag_keys.rs, query_tests/src/scenarios.rs
Closes #3202
This PR fixes a defect in the `tag_keys` implementation on the InfluxRPC frontend. The semantics of a Tag Keys meta query are to return to the caller the distinct set of tag keys (column names for InfluxDB tags). 
If a table did not contain any tag columns (i.e., only contained field columns and a time column) *and* if a full general purpose plan was required to determine which columns contained rows passing some predicate, then the implementation would build a logical plan containing a projection of all tag columns. Since this projection would be empty (no tag columns in table) then the logical plan would effectively not have any specific projections and would select _all_ columns, including the `"time"` column. 
This results in `"time"` being sent back to the InfluxQL query …
=> fix: ensure time column not returned

influxdb_iox/tests/common/server_fixture.rs, influxdb_iox/tests/end_to_end_cases/scenario.rs, influxdb_iox/tests/end_to_end_cases/write_buffer.rs
Remove the ones that are covered by `write_pb.rs` or that are obsolete
(i.e. rely on behavior that only exist in the legacy router code).
Migrate the remaining ones to use an actual router.
=> refactor: clean up write buffer end2end tests

influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs, influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/error.rs, influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/write_pb.rs, influxdb_iox/tests/end_to_end_cases/write_buffer.rs, server/src/db.rs, server/src/lib.rs, server/src/resolver.rs
~On top of #3206 and requires #3210.~
API users should use `Database` instead, there's no need any longer to mirror
this API in `Server`. Note that `Database` is better than `Db` in this
case, because the former can also check if we're writing from a write
buffer and can easily reject unsequenced writes. The `pub` modifiers
were adjusted to make it impossible to write through `Db` directly.
=> refactor: remove write routing logic from `Server`

influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs, influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/delete.rs, influxdb_iox/tests/end_to_end_cases/write_buffer.rs, server/src/db.rs
Similar to how writes to a databases that reads from a write buffer are
forbidden deletes should be rejected as well.
=> feat: disallow unsequenced deletes when reading from write buffer

influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs, influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/delete.rs, influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/write_pb.rs, query_tests/src/cancellation.rs, query_tests/src/influxrpc/read_window_aggregate.rs, query_tests/src/pruning.rs, query_tests/src/scenarios.rs, query_tests/src/scenarios/util.rs, server/src/database.rs, server/src/db.rs, server/src/db/chunk.rs, server/src/db/lifecycle/compact.rs, server/src/db/lifecycle/compact_object_store.rs, server/src/db/lifecycle/persist.rs, server/src/utils.rs, server/tests/delete.rs, server_benchmarks/benches/catalog_persistence.rs
As a side effect, writing to database no longer requires `async`.
Closes #2243.
=> refactor: remove write buffer producer logic from `Db`

data_types/src/write_buffer.rs, generated_types/protos/influxdata/iox/write_buffer/v1/write_buffer.proto, generated_types/src/write_buffer.rs, influxdb_iox/tests/end_to_end_cases/management_api.rs, influxdb_iox/tests/end_to_end_cases/scenario.rs, influxdb_iox/tests/end_to_end_cases/write_buffer.rs, iox_data_generator/README.md, iox_data_generator/src/bin/create_database.rs, perf/perf.py, router/src/write_sink.rs, server/src/database.rs, server/src/lib.rs, server/tests/write_buffer_compaction.rs, server/tests/write_buffer_delete.rs, test_bench/k8s/overlays/demo/database-1.json, test_bench/k8s/overlays/demo/router-1.json, write_buffer/src/config.rs
The direction was required when a database could read or write from/to a
write buffer. Now it is clear from the usage context of a write buffer
context which of the two applications is meant (databases read, routers
write) so the direction flag is no longer required.
=> refactor: remove write buffer direction

docker/Dockerfile.ci
This prepares a PR to run these two tools as linters.
=> ci: add `yamllint` and `shellcheck` to CI image

data_types/src/partition_metadata.rs, influxdb_iox/src/commands/debug/mod.rs, influxdb_iox/src/influxdb_ioxd/http/mod.rs, influxdb_iox/tests/common/udp_listener.rs, influxdb_iox/tests/end_to_end_cases/storage_api.rs, iox_data_generator/src/measurement.rs, iox_data_generator/src/tag_set.rs, metric/src/lib.rs, mutable_batch_tests/src/lib.rs, mutable_buffer/src/lib.rs, mutable_buffer/src/snapshot.rs, object_store/src/azure.rs, parquet_file/src/chunk.rs, persistence_windows/src/persistence_windows.rs, query/src/provider/overlap.rs, query_tests/src/scenarios.rs, read_buffer/src/column/encoding/scalar/transcoders.rs, read_buffer/src/row_group.rs, rust-toolchain.toml, server/src/db.rs, server/src/lib.rs, test_helpers/src/tracing.rs, write_buffer/src/file.rs, write_buffer/src/kafka.rs
The biggest change is probably that Rust is now able to detect that fields are unread. I marked all those with `#[allow(dead_code)]` because I'm not sure if they're valid or if they're signs of work to come or if they're old code that can be cleaned up.
=> chore: Update Rust and fix or allow new Rust+clippy warnings

data_types/src/chunk_metadata.rs, influxdb_iox/src/commands/database/chunk.rs, influxdb_iox/tests/end_to_end_cases/management_cli.rs, influxdb_iox_client/src/client/management.rs, parquet_catalog/src/core.rs, parquet_file/src/metadata.rs
Closes #3267
This PR follows on the work that @tustvold has been doing to teach IOx to load chunks from object storage back into the Read Buffer.
```
$ influxdb_iox database chunk load NAME_OF_DATABASE CHUNK_ID_IN_BASE_16
```
I have tested this locally. Start IOx with some persisted chunks and note:
```
influxdb_iox database query query_log "select * from system.chunks"
+--------------------------------------+---------------------+------------+-----------------+------------------+--------------+--------------------+-----------+---------------------+-----------------------------+-----------------------------+-------+
| id                                   | partition_key       | table_name | storage         | lifecycle_action | memory_bytes | object_store_bytes | row_count | …
```
=> feat: add CLI command for loading chunks to Read Buffer

.circleci/config.yml
This avoids that we have to pull rustc and friends twice (once via
image, once when actually executing it).
=> ci: improve perf image build time by pre-fetching correct rust version

iox_data_generator/benches/point_generation.rs, iox_data_generator/schemas/cap-write.toml, iox_data_generator/schemas/full_example.toml, iox_data_generator/schemas/storage_cardinality_example.toml, iox_data_generator/schemas/tracing-spec.toml, iox_data_generator/src/agent.rs, iox_data_generator/src/bin/iox_data_generator.rs, iox_data_generator/src/lib.rs, iox_data_generator/src/measurement.rs, iox_data_generator/src/specification.rs, iox_data_generator/src/tag_set.rs, iox_data_generator/src/write.rs, perf/battery-0/datagen.toml
This adds the ability for the data generator to write to many databases. A new command line argument, `bucket_list`, is added which should be a file name. The file should contain a list of databsaes, one per line, with the structure of `<org>_<bucket>`. This is a little odd given the data generator expects org and bucket separately, but I expect the file that we'll be using will be database names, which have this format.
The configuration can specify what percentage of the list should get written to by which agents at what sampling interval. This should allow configurations where databases get different levels of ingest and different types (as specified via different agent specs). The structure is a little wonky, but I think it'll get the job done. The next step is to run some perf tests …
=> feat: add ability for data generator to write to many buckets

Cargo.toml, Dockerfile
Closes #3316
A "full build" was me deleting `/target` and then running the command. A "rebuild" was me changing a particular `unreachable!` to a `panic!` in the `read_buffer` crate.
| Command | Full build | Rebuild |
|-----------|-----------|---------|
| `cargo build --release` |  7m 24s | 5m 13s |
| `cargo build --profile quick-release` | 4m 11s | 2m 06s |
Bikeshed time:
- Should the profile optimizing for compile time be `--release` or should the profile optimizing for binary size be `--release`?
- What should the name of the non-`--release` profile be?
- Any other comparison stats you want to see?
- Any other settings that should be changed?
=> feat: Create a build-time-optimized release build profile

influxdb_iox/tests/end_to_end_cases/deployment_api.rs, server/src/lib.rs
This is important for idempotence and simplifies clients and helper
scripts a lot.
=> fix: allow setting the same server ID twice

Cargo.lock, influxdb_iox/src/structopt_blocks/object_store.rs, object_store/Cargo.toml, object_store/src/aws.rs, object_store/src/dummy.rs, object_store/src/lib.rs
Otherwise the whole thing blows up when starting a server that has many
DBs registered, because we potentially create 1 connection per DB (e.g.
to read out the preserved catalog).
Fixes #3336.
Work for other backends is tracked under #3341.
=> fix: limit number of S3 connections

.circleci/config.yml, Dockerfile, influxdb_iox/Cargo.toml, influxdb_iox/tests/end_to_end_cases/kafka.rs, influxdb_iox/tests/end_to_end_cases/management_api.rs, influxdb_iox/tests/end_to_end_cases/mod.rs, perf/perf.py, router/Cargo.toml, server/Cargo.toml, write_buffer/Cargo.toml, write_buffer/src/codec.rs, write_buffer/src/config.rs, write_buffer/src/core.rs, write_buffer/src/kafka.rs, write_buffer/src/lib.rs
Closes #3315.
This saves me ~15 seconds on a release build. According to the Cargo timings analysis, on this branch:
```
$ cargo build --release 
```
builds 441 total units (crates?) in 7m 59.2s.
```
$ cargo build --release --features kafka
```
builds 455 total units in 8m 13.6s.
=> feat: Optionally build Kafka

server/src/database.rs
As [noted](https://github.com/influxdata/influxdb_iox/pull/3292#pullrequestreview-826159666
) by @crepererum , the diagram (well textual description really) has drifted from the reality
Update the docstring of `DatabaseState` enum
=> docs: Update database startup machine diagram

Cargo.lock, iox_data_generator/Cargo.toml, iox_data_generator/benches/point_generation.rs, iox_data_generator/schemas/cap-write.toml, iox_data_generator/schemas/full_example.toml, iox_data_generator/schemas/storage_cardinality_example.toml, iox_data_generator/schemas/tracing-spec.toml, iox_data_generator/src/bin/iox_data_generator.rs, iox_data_generator/src/lib.rs, iox_data_generator/src/measurement.rs, iox_data_generator/src/specification.rs, iox_data_generator/src/tag_set.rs, iox_data_generator/src/write.rs, perf/battery-0/datagen.toml
This adds the ability to specify a regex to match against database names when specifying what agents should write to which buckets in the data generator.
A default has also been added for ratio so that it doesn't need to be specified if only a single database writer is defined.
Closes #3344
=> feat: add regex to bucket writers assignment in data generator

iox_data_generator/schemas/many_dbs.toml, iox_data_generator/schemas/many_measurements.toml
One schema is a test for many small databases like a bunch of free tier users. The other is for a database with 2k measurements getting moderate ingest load (4.1 MB/sec).
=> chore: add two test schemas in data generator examples

.circleci/config.yml, Dockerfile, docker/entrypoint.sh
Also includes a patch to speed up linking a bit by using `lld`. We tried to do this for a long time already (introduced in #1022):
https://github.com/influxdata/influxdb_iox/blob/95f907efd8f7de900eb2cca8c3165e19abb9554f/.cargo/config#L1-L4
The issue was that since #2118 we are setting the `RUSTFLAGS` environment variable which overrides the cargo config. The patch combines both flags into single env var and also installs `lld` (otherwise linking obviously fails).
Closes #3322.
Triggered via CircleCI REST API.
- **Job:** <https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/13696/workflows/02cdd6a2-3d8b-458e-8503-95ce4abc38cd/jobs/102100>
- **IOx Image:** <https://quay.io/repository/influxdb/iox?tab=tags> (`crepererum_issue3322`/`2f2ef97f`)
- **Data Generator Image:** …
=> ci: LLD linking +docker image for data generator

generated_types/protos/influxdata/platform/storage/service.proto, influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/input.rs, influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/service.rs, influxdb_storage_client/src/lib.rs
Towards #3372.
This PR adds some initial server and storage client plumbing to handle a `TagValuesGroupedByMeasurementAndTagKeyRequest` message.
If this message is sent over the gRPC API the server used to respond with:
```
actual  : "{\"results\":[{\"statement_id\":0,\"error\":\"rpc error: code = Unimplemented desc = \"}]}"
```
and now will respond with:
```
actual  : "{\"results\":[{\"statement_id\":0,\"error\":\"rpc error: code = Internal desc = Operation not yet implemented:  tag_values_grouped_by_measurement_and_tag_key. Measurement patterns:......
```
=> refactor: add support for handling `TagValuesGroupedByMeasurementAndTagKeyRequest`

influxdb_iox/src/commands/run/mod.rs, influxdb_iox/src/commands/run/test.rs, influxdb_iox/src/influxdb_ioxd.rs, influxdb_iox/src/influxdb_ioxd/rpc.rs, influxdb_iox/src/influxdb_ioxd/server_type/database/mod.rs, influxdb_iox/src/influxdb_ioxd/server_type/mod.rs, influxdb_iox/src/influxdb_ioxd/server_type/test.rs, influxdb_iox/tests/end_to_end_cases/run_cli.rs
Instead of just logging the issue, also make sure the error gets
propagated all the way up to the exit code.
Fixes #3375.
=> fix: treat early server worker exit as proper error

.circleci/config.yml, influxdb_iox/src/structopt_blocks/object_store.rs, object_store/src/aws.rs
This removes 3 "nonexisting region" tests that where testing very
specific error behavior that no local emulator (minio and localstack)
replicate and that don't add much value. It's better to test our AWS
code at all than being to picky.
#3389 demonstrates that we're indeed testing something.
=> test: `object_store` aws test using localstack

object_store/src/aws.rs, object_store/src/azure.rs, object_store/src/disk.rs, object_store/src/gcp.rs, object_store/src/lib.rs, object_store/src/memory.rs, object_store/src/path/cloud.rs, object_store/src/path/parsed.rs, object_store/src/throttle.rs
Don't use string prefixes, e.g. `foo/bar/` is a prefix of `foo/bar/x`
but NOT of `foo/bar_baz/y`.
This also removes some heuristics during the cloud storage parsing that
assumed that file names always contain a dot but directories don't.
Technically we should now always be able to know whether a path points
to a file or a directory:
- Rust (manually constructed): we use `DirsAndFileName` which knows the
difference (i.e. if `file_name` is set)
- in-mem store: we also use `DirsAndFileName`
- file system: this was fixed by #1523
(ccd094dfcfca6e27fec97835f233a86dadd54272 and 464667d8b8d571718392c0e1f970e8f9c4d44376)
- cloud: cloud doesn't know about directories. So all paths that these
APIs return and that end with a `/` are directories (can only occur in
`list_with_delimiter`); everyting …
=> refactor: make object store prefixes segment based

influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/service.rs
Towards #3372
This PR implements the functionality in IOx to support many instantiations of a `TagValuesGroupedByMeasurementAndTagKey` RPC call.
Specifically, this PR adds support for 
* specifying measurements as literals or regex matches;
* providing arbitrary predicates that at least one returned tag value must satisfy;
* specifying a tag key as a literal match.
The following types of InfluxQL meta-queries are covered:
```
SHOW TAG VALUES FROM measurement WITH KEY = 'column'
SHOW TAG VALUES FROM measurement WITH KEY = 'column' WHERE 'other_column' = 'foo'
SHOW TAG VALUES FROM measurement WITH KEY = 'column' WHERE 'other_column' ~= /^.*a$/'
SHOW TAG VALUES FROM measurement1,measurement2 WITH KEY = 'column' WHERE 'other_column' ~= /^.*a$/'
SHOW TAG VALUES FROM /^Foo.+/ WITH KEY = …
```
=> feat: increase support for TagValuesGroupedByMeasurementAndTagKey

influxdb_iox/Cargo.toml, influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/service.rs
Closes #3372
**Need to merge this first** https://github.com/influxdata/influxdb_iox/pull/3406 
This PR closes out the known outstanding `SHOW TAG VALUES` InfluxQL support using the newer `TagValuesGroupedByMeasurementAndTagKeyRequest` RPC request.
This PR adds support for applying predicates to the `WITH key ` clause in `SHOW TAG VALUES WITH KEY` statements.
The following operators are supported:
- literal equality `WITH KEY = "some_column"`
- literal inequality `WITH KEY != "some_column"`
- regex match `WITH KEY =~ /foo.+/`
- regex not match `WITH KEY !~ /foo.+/`
- list match `WITH KEY IN ("col1", "col2", "col3")
I implemented several of the above by materialising the column names for a table and then applying the appropriate logic to filter away columns (tag keys) that don't match. …
=> feat: add support for predicates on SHOW TAG VALUES WITH KEY = pred

.circleci/config.yml
Workaround for <https://github.com/rust-lang/cargo/issues/10280>.
=> ci: use CLI-driven SSH for cargo

Cargo.lock, Cargo.toml, influxdb_iox/Cargo.toml, influxdb_iox/src/commands/run/mod.rs, influxdb_iox/src/commands/run/router2.rs, influxdb_iox/src/influxdb_ioxd/http/dml.rs, influxdb_iox/src/influxdb_ioxd/http/error.rs, influxdb_iox/src/influxdb_ioxd/server_type/mod.rs, influxdb_iox/src/influxdb_ioxd/server_type/router2.rs, router2/Cargo.toml, router2/src/lib.rs, router2/src/server.rs, router2/src/server/grpc.rs, router2/src/server/http.rs
Adds `router2` skeleton.
A follow-up PR will start fleshing it out by populating the HTTP/gRPC handlers and pushing requests into a common DML processor.
---
* feat: new router2 crate (a8cb8755)
This commit adds an almost-empty router2 crate containing enough of a skeleton
to plumb into the IOx CLI/server runner.
* refactor: add router2 server mode (7fc17203)
Plumbs the router2 crate into IOx's CLI & server-runner framework.
=> feat: router2 skeleton

influxdb_iox/src/influxdb_ioxd/http/utils.rs
If all the stars aligned in just the right way, it was possible to silently drop line protocol fields / timestamp due to truncation of the HTTP body when reading a gzipped request.
---
* fix: undected gzip HTTP body truncation (3d329018)
When reading the gzip-encoded body of a HTTP request, the stream is read up
until the configured maximum number of allowable bytes, at which point the
body was silently trucated. This could allow fields in submitted line protocol
to be silently lost (amongst other bad things).
This change ensures that truncation results in a RequestSizeExceeded error.
=> fix: undetected gzip HTTP body truncation

arrow_util/src/display.rs, db/src/access.rs, db/src/lib.rs, db/src/query_log.rs, db/src/system_tables/queries.rs, influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs, influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/flight.rs, influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/service.rs, query/src/lib.rs, query/src/test.rs
Closes #3457 
This PR adds a new `completed_duration` column to the `queries` system table, which populates rows with the wall-clock time the query took to execute.
It looks like this :-)
```
edd@m1:~|⇒  influxdb_iox database query query_log "select * from system.queries"
+-----------------------------+------------+-------------------------------------+--------------------+
| issue_time                  | query_type | query_text                          | completed_duration |
+-----------------------------+------------+-------------------------------------+--------------------+
| 2022-01-13T19:32:01.281203Z | sql        | show tables                         | 25.382ms           |
| 2022-01-13T19:32:10.657779Z | sql        | select count(1) from query_log      | 60.239ms           |
| …
```
=> feat: add query completion duration to queries system table

Cargo.lock, iox_catalog/README.md, iox_catalog/migrations/20211229171744_initial_schema.sql, iox_catalog/src/postgres.rs
Support for the `sequencer` table + misc doc improvements.
---
* refactor: ensure sequencers are unique (093251fb)
Adds a unique constraint to ensure only one sequencer record exists for each
Kafka (topic, partition).
* test: use DSN from env for integration tests (c628d326)
Removes the hard-coded DSN, instead sourcing it from the DATABASE_URL 
environment variable.
* docs: integration testing for iox_catalog (5cf93f8b)
Documents the required steps in order to run the Postgres integration tests
for the iox_catalog crate.
* feat(iox_catalog): create & list sequencers (c87796de)
Adds support for interacting with the "sequencer" table.
* chore: update lockfile (595f7d33)
Running cargo in iox_catalog generates a lockfile diff.
=> feat: iox_catalog sequencers

Cargo.lock, router2/Cargo.toml, router2/src/dml_handler/mock.rs, router2/src/dml_handler/nop.rs, router2/src/dml_handler/trait.rs, router2/src/server/http.rs
Follows on from #3468 adding a HTTP handler for the `/api/v2/delete` endpoint.
---
* feat(router2): implement delete API handler (6f2e10ca)
Adds support for the HTTP v2 delete API endpoint.
=> feat(router2): implement delete API handler

iox_catalog/src/interface.rs, iox_catalog/src/lib.rs, iox_catalog/src/mem.rs, iox_catalog/src/postgres.rs
* Adds a memory based catalog, useful for testing purposes.
* Separates getting the namespace schema from the namespace and moves the schema code out interface out of postgres.
* Make postgres and mem catalog implementations public
* Make iox_catalog tests generic for any backend implementation
=> feat: implement memory backed iox_catalog

trace/src/span.rs
Linking of span contexts was introduced in #2803 but the high-level
interface was never used. This adds the missing bits to allow links to
be used with `Span` and `SpanRecorder`.
=> feat: simplify linking of spans

ingester/src/data.rs, ingester/src/server.rs, iox_catalog/src/interface.rs, iox_catalog/src/lib.rs, iox_catalog/src/mem.rs, iox_catalog/src/postgres.rs
This updates the catalog API to make it easier to work with for consumers. I also found a bug in the MemCatalog implementation while refactoring the tests to work with the new API definition. Consumers will now be able to Arc wrap the catalog and use it across awaits.
=> refactor: Clean up the Catalog API

.kodiak.toml
The team decided to switch to "squash all the commits"
=> chore: Set default to squash

router2/src/dml_handlers/mock.rs, router2/src/dml_handlers/nop.rs, router2/src/dml_handlers/sharded_write_buffer.rs, router2/src/dml_handlers/trait.rs
This commit was supposed to be part of https://github.com/influxdata/influxdb_iox/issues/3549 but was lost during a rebase and is part of the same end goal - refactoring the `DmlHandler` to be an easily-composable trait.
---
* refactor: decouple error types for DmlHandler (b38deaa7)
Allows the DmlHandler to return different types for each method.
This enables a DmlHandler implementation decorating an inner handler to return
the inner handler's error directly, avoiding any "wrapper" errors.
=> refactor: decouple error types for DmlHandler

rust-toolchain.toml
Update to the latest rust.
:wave: @jdstrand 
---
* build: use rust 1.58.1 (5438a4af)
Security bugfix release, see:
https://groups.google.com/g/rustlang-security-announcements/c/R1fZFDhnJVQ?pli=1
=> build: use rust 1.58.1

Cargo.lock, predicate/Cargo.toml, predicate/src/lib.rs, predicate/src/sql.rs
This PR adds support for converting a string expression into an InfluxRPC Predicate node.
IOx implements support for the InfluxDB TSM based gRPC read API. Therefore it can support being a backend for Flux and InfluxQL queries. However, IOx itself does not contain a Flux or InfluxQL query engine. As a product developer and an operator this makes it hard to issue arbitrary gRPC requests to IOx.
Whilst we do now have some ability to replay entire gRPC requests that have been logged in the `queries` system table, it would be of considerable use if we could issue stand-alone requests from the CLI. It would also open the door up to having more data-driven gRPC tests in IOx, much like we do for SQL.
This PR introduces an API that lets one specify an expression as a string, which very closely …
=> feat: add support for parsing sql expressions into RPCNode

read_buffer/src/chunk.rs, read_buffer/src/column.rs, read_buffer/src/column/encoding/string.rs, read_buffer/src/column/encoding/string/dictionary.rs, read_buffer/src/column/encoding/string/rle.rs, read_buffer/src/column/float.rs, read_buffer/src/column/string.rs, read_buffer/src/lib.rs, read_buffer/src/row_group.rs, read_buffer/src/table.rs, read_buffer/src/value.rs
Following on a little bit from the discussion in https://github.com/influxdata/influxdb_iox/issues/553 I added the following lints to the `read_buffer` crate as a little experiment:
* [str_to_string](https://rust-lang.github.io/rust-clippy/master/#str_to_string)
* [string_string](https://rust-lang.github.io/rust-clippy/master/)
These lints encourage the use of `to_owned` rather than `to_string` for `&str` and `String` types. And I'm all about the consistency...
Unfortunately `clippy --fix` did not pick these up as being automatically fixable, which would make handling the whole code-base a bit arduous. I also tried the imaginatively called ` __CARGO_FIX_YOLO=1  cargo clippy --fix` incantation but that didn't help either.
I'm tempted to just try a massive rename on the code base and deal …
=> refactor: introduce to_string clippy lints in read buffer

predicate/src/lib.rs, predicate/src/rewrite.rs
This is part of https://github.com/influxdata/influxdb_iox/pull/3557
Closes https://github.com/influxdata/influxdb_iox/issues/3585
Rationale:
1. This is a rewrite that we need in IOx to avoid overhead of treating rpc predicates specally, but I think it is a bit too specialized to put in DataFusion (yet)
Changes:
Add a rewrite for BinaryExpr and case statements that converts a `CASE` statement that is not binary to one that is (so they will then be subject to https://github.com/apache/arrow-datafusion/issues/1693)
```sql
CASE
WHEN tag_col IS NULL THEN ''
ELSE tag_col
END = 'cpu'
```
```sql
CASE
WHEN tag_col IS NULL THEN '' = 'cpu'
ELSE tag_col = 'cpu'
END
```
After this PR is completed, I will connect it into https://github.com/influxdata/influxdb_iox/pull/3588 and then hook it all …
=> feat: Fold past CASE blocks / translate to boolean CASE

Cargo.lock, influxdb_iox/Cargo.toml, influxdb_iox/src/commands/storage.rs, influxdb_iox/src/main.rs
Towards: #3598
This PR adds a new `influxdb_iox` sub-command: `storage`. This sub-command will be responsible for interpreting provided arguments, crafting InfluxRPC read request messages, executing read requests against IOx, and displaying the results to the user of the CLI.
The contribution in this PR is a skeleton CLI sub-command that can deal with necessary arguments for a `ReadFilter` RPC request. It does not issue an RPC request (future PRs).
Here are some examples of how the CLI can be used. All storage sub-commands will accepts:
* `start`: an optional starting timestamp. The CLI can parse either integer values representing nanoseconds since (or before) the epoch, or alternatively timestamps in `RFC3339` format.
* `stop`: see `start` above. Note `stop` is exclusive.
* `predicate`: …
=> feat: add skeleton `storage` CLI command

influxdb_iox/src/commands/catalog.rs, influxdb_iox/src/commands/catalog/topic.rs, influxdb_iox/src/main.rs
This PR adds the `catalog` command which has an `unimplemented` `setup` command, and a `topic` subcommand which is implemented in this PR.
Part of #3509. The `setup` command will be implemented in a separate PR, which will close that issue.
=> feat: catalog CLI command with update subcommand

influxdb_iox/src/commands/run/router2.rs, iox_catalog/src/lib.rs, router2/src/dml_handlers/mod.rs, router2/src/dml_handlers/ns_autocreation.rs, router2/src/dml_handlers/trait.rs, router2/src/server/http.rs
This PR adds a new handler into the write path which automatically populates the catalog with the requested namespace (if it does not already exist).
To avoid putting catalog I/O in the request path of every write, this PR utilises the namespace cache split out in #3626 to avoid sending a "create namespace" request for namespaces the router already knows exist. In the case of a cache miss, a create request is pessimistically sent to the catalog and response handled appropriately. We can expect this behaviour to cause a just-booted router to exhibit higher latency at the start of a test run until the namespace cache has warmed.
This is a bit of a shim to enable testing the new architecture and will most likely not be in the final prod build - nonetheless it's tested, etc like any other …
=> feat(router2): namespace auto-creation

influxdb_iox/src/commands/storage.rs, influxdb_iox/src/commands/storage/request.rs, influxdb_iox/src/commands/storage/response.rs
Towards #3598.
This PR adds support for `tag_values` to the storage CLI. The tag values RPC requires that a column (tag key) is specified. Thus, the command us used as follows:
```
⇒  influxdb_iox storage db_name tag-values host
tag values: 3
+-----------------------+
| values                |
+-----------------------+
| -                     |
| foo                   |
| bar                   |
+-----------------------+
```
If you specify `_measurement` or `_field` the value will be correctly transformed into the byte-specific format used by the storage read API (`\x00` or `\xff` respectively).
```
⇒  influxdb_iox storage db_name tag-values _measurement
tag values: 3
+-----------------------+
| values                |
+-----------------------+
| m1                    |
| m2 …
```
=> feat: add tag_values to storage cli

trace/src/ctx.rs, trace/src/span.rs, write_buffer/src/core.rs, write_buffer/src/kafka/aggregator.rs
Fix a few edge cases in our traces that came up when using this functionality in our test bench. Jaeger is now a bit more happy. Sadly it doesn't really like our links due to https://github.com/jaegertracing/jaeger-ui/issues/662 and it's a bit cumbersome to navigate them.
=> fix: write buffer traces

influxdb_iox/src/commands/storage.rs, influxdb_iox/src/commands/storage/response.rs
This PR adds a new flag to the storage CLI command: `--format`. This flag accepts two options right now: `pretty` (emit pretty printed tables) and `quiet` (don't emit anything).
Naturally, a future format might be "raw frames" or some other formats that could help with debugging.
In all cases, the execution time to get the results from the query engine are timed and emitted.
```
⇒  influxdb_iox storage 0000000000000123_0000000000000123 read-filter 
_measurement: air_temperature
rows: 12
+--------------+-------+-------------------+------------------------+-------------------------------+
| location     | state | sea_level_degrees | tenk_feet_feet_degrees | time                          |
+--------------+-------+-------------------+------------------------+-------------------------------+
| …
```
=> feat: add timed/quiet output for storage CLI

influxdb_iox/src/commands/storage.rs, influxdb_iox/src/commands/storage/request.rs
Towards #3598
This PR adds support for `read_window_aggregate` to the `storage` CLI tool. Since the responses from this RPC call don't include any group frames they can be emitted via the `pretty` output format that `read_filter` uses.
* One thing note here is that the operator can provide human readable durations for the windowing and offset properties, e.g., `--window-every 23m` or `--offset 46ms`.
* Another thing of note is that I'm not sure if we need to set one of the `window` (enum) properties of the RPC message if we are already setting the `every` and `offset` fields anyway. I think one overrides the other. I added the ability to easily hook up the other one though if needed in the future.
```
⇒  influxdb_iox storage 0000000000000123_0000000000000123 read-window-aggregate …
```
=> feat: add read_window_aggregate storage sub-command

.circleci/get-deploy-tags.sh
Closes #
Removes k8s-iox promotion/image introduction.
=> chore: The k8s-iox promotion is no longer used and can be removed

influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/service.rs
A quick tidy I noticed as I was reviewing logs:
- log `measurement` name for `measurement_fields`
- use the same log message for `tag_values`
=> refactor: influxRPC operation logging

influxdb_iox/src/main.rs, trace_exporters/src/lib.rs
This PR basically lets you easily trace commands issued from the IOx gRPC client. To do this you need to:
- Have IOx running with an appropriate tracing configuration set (e.g., jaeger running locally).
- Have not changed the `--traces-exporter-jaeger-trace-context-header-name` argument from the default of `uber-trace-id`.
Assuming that, then when you want to trace your query (or other operation) you can now do:
```
$ influxdb_iox database query mydb "select * from cpu" --gen-trace-id
Trace ID set to fcde5072a178bf81:1112223334445:0:1
...
...
```
The trace ID will be automatically generated (based on a hash of the current time) and then emitted to you. IOx will then trace the command and ship that trace to jaeger.
You can then take the first part of the emitted ID, in this case …
=> feat: generate a trace ID when using gRPC client

influxdb_iox/src/commands/run/router2.rs, router2/src/dml_handlers/instrumentation.rs, router2/src/dml_handlers/mod.rs, router2/src/dml_handlers/schema_validation.rs, router2/src/namespace_cache.rs, router2/src/namespace_cache/metrics.rs
This PR adds instrumentation to each stage of the request handling pipeline to allow us to observe the latencies of the various operations within the router. It adds latency histograms the following stages:
* Submitting ops to the write buffer (inc. waiting for internal buffer flush)
* Schema validation (inc. catalog interactions)
* Write partitioning
* Overall e2e request handling latency
Each metric is broken down by success/error response and operation type (write/delete).
Because the request pipeline is constructed as a chain of nested handlers, the timing for each stage is inclusive of the child handlers it calls:
```
┌ ─                                          
│     ┌───────────────┐                      
│  NS Creation  │                      
│     └───────────────┘ …
```
=> feat: router2 metrics

Cargo.lock, iox_catalog/Cargo.toml, iox_catalog/migrations/20210217134322_create_schema.sql, iox_catalog/migrations/20211229171744_initial_schema.sql, iox_catalog/src/postgres.rs
This PR enables catalog tests to run in parallel without interfering with each other.
While working on the catalog I added a couple tests and (eventually) discovered they were trashing each other's global catalog state as it was shared across tests. This is currently avoided by running all the test code runs in one test (`test_catalog`).
The test code paths now generate a random schema name for each catalog test (or more specifically, for each call to [`setup_db`](https://github.com/influxdata/influxdb_iox/blob/44e9eaf92b0740af5e2087fc03cf0220cea7323c/iox_catalog/src/postgres.rs#L928-L968)). The prod code paths [continue to use `iox_catalog`](https://github.com/influxdata/influxdb_iox/blob/44e9eaf92b0740af5e2087fc03cf0220cea7323c/influxdb_iox/src/clap_blocks/catalog_dsn.rs#L47) as the …
=> test: isolated catalog tests

iox_catalog/src/postgres.rs
Adds a couple invariant asserts to ensure we're not accidentally proceeding under the assumption a write has succeeded, when in fact the data in the catalog does not match.
---
* test(iox_catalog): assert no spurious writes (4b72b40d)
This commit introduces test cases that ensure that for each of the tombstone &
partition repos:
* create_or_get() is idempotent
* create_or_get() does not silently drop conflicting writes
The former covers the expected use case: callers issuing potentially multiple
calls to create_or_get() with the same args, causing the catalog impl to
transparently turn the subsequent calls into NOPs.
The latter illustrates an issue where multiple calls to create_or_get() with
differing arguments is silently accepted by the catalog, causing both callers
to believe they …
=> fix: catalog spurious writes

.circleci/config.yml, iox_catalog/src/postgres.rs
Fix the explicit `catalog setup` command broken as part of #3776.
This command wasn't run as part of the CI process so the breakage wasn't noticed, and all the tests worked fine as they bootstrapped their own schema before running the migrations.
Adds `catalog setup` as part of the CI checks.
---
* fix: add public to schema search path (f49c9c46)
The _sql_migrations table cannot be created by the `catalog setup` bootstrap
command because it is created before the migrations run, one of which creates
the iox_catalog namespace the catalog operates in.
This change allows the _sql_migrations table to be created in the public 
schema to start the migration process, with everything else living in the
iox_catalog schema.
* build: run "catalog setup" in CI (22ac2e3b)
Ensures the "catalog setup" …
=> fix: "catalog setup" migrations in non-public schema

influxdb_iox/src/commands/run/router2.rs, router2/benches/e2e.rs, router2/src/dml_handlers/chain.rs, router2/src/dml_handlers/fan_out.rs, router2/src/dml_handlers/instrumentation.rs, router2/src/dml_handlers/mock.rs, router2/src/dml_handlers/mod.rs, router2/src/dml_handlers/nop.rs, router2/src/dml_handlers/ns_autocreation.rs, router2/src/dml_handlers/partitioner.rs, router2/src/dml_handlers/schema_validation.rs, router2/src/dml_handlers/sharded_write_buffer.rs, router2/src/dml_handlers/trait.rs, router2/src/server/http.rs, router2/tests/http.rs
This refactor changes the way DML handlers are chained together in the router in order to produce more useful metrics (see #3764).
While this change caused a fair bit of code churn, the changes are pretty trivial compiler-driven fixups - the result is much nicer to test / work with though! An example of the benefit of this is it moved responsibility for parallelising certain operations (like writes across shards) out from the request handler and into an external type, separating responsiblities and making the parallisation pluggable / configurable / optional.
---
* refactor: chain DML handlers (bb132b61)
The router is composed of several DML handlers called in sequence in order to
construct the full request handling pipeline. Prior to this commit, each
handler nested the next handler it …
=> refactor(router2): non-intrusive handler chain

influxdb_iox/src/commands/run/router2.rs, router2/benches/e2e.rs, router2/src/dml_handlers/schema_validation.rs, router2/tests/http.rs
A quick and easy reduction in cache overwrites and unnecessary PG load due to concurrent schema validation across partitions.
---
* refactor: early schema validation (d7eda885)
Changes the configuration of the router request pipeline to move schema 
validation before partitioning.
This reduces the concurrency of callsm into the schema validator when a single
write is split into one or more partitions, reducing contention and cash
thrashing. It also ensures we don't bother partitioning the writes if the
request will fail.
=> refactor: early schema validation

ingester/src/data.rs, ingester/src/handler.rs, iox_catalog/src/lib.rs, iox_catalog/src/postgres.rs, router2/src/dml_handlers/schema_validation.rs
Make things faster the easy way - by hiding latency with parallelism!
While adding tests to this I noticed the in-mem catalog behaves differently than the postgres impl, and deadlocks when attempting to get two handles to the `RepoCollection` (https://github.com/influxdata/influxdb_iox/issues/3859).
---
* refactor: parallel column resolution (b07f15be)
A quick change to perform the ColumnRepo::create_or_get() calls in parallel
(up to a maximum of 3 in-flight at any one time) in order to mitigate the
latency of the call and reduce the overall schema validation call duration.
The in-flight limit is enforced to avoid starving the DB connection pool of
connections.
=> refactor: parallel column resolution

influxdb_iox/src/clap_blocks/catalog_dsn.rs, iox_catalog/src/postgres.rs
Quick addition to the shared catalog config block.
---
* refactor: configurable max catalog connections (35792526)
Allow the maximum number of catalog (postgres) connections to be specified as
part of the catalog configuration.
=> refactor: configurable max catalog connections

influxdb_iox/src/commands/run/router2.rs, router2/benches/e2e.rs, router2/src/server/http.rs, router2/tests/http.rs
Quick one to plumb in some handy ingest metrics for the HTTP write endpoint.
---
* feat: http ingest metrics (6d9709be)
Records LP line count, field count & request body size (decompressed, byte
size) for writes, and request body byte size for deletes.
=> feat: http ingest metrics

Cargo.lock, ingester/src/data.rs, ingester/src/handler.rs, iox_catalog/Cargo.toml, iox_catalog/src/interface.rs, iox_catalog/src/lib.rs, iox_catalog/src/mem.rs, iox_catalog/src/metrics.rs, iox_catalog/src/postgres.rs, router2/src/dml_handlers/schema_validation.rs
Adds a new batch upsert method to the column repo in order to upsert N columns to the catalog in one round trip.
As part of 210f6b40 the scope of the catalog trait taken by the schema validation was reduced, causing some minor code churn. The only functional change is within the body of `validate_mutable_batch()` where the new bulk method is called.
---
* docs: metric decorate macro (89dba1b7)
Some helpful tips for using the metric decorator's decorate! macro when 
modifying the catalog traits.
* feat: batch upsert of columns to catalog (da145ffb)
Adds ColumnRepo::create_or_get_many() to upsert multiple columns in one round
trip to Postgres.
* feat: batch column upsert for schema validation (8de453ed)
Uses the new ColumnRepo::create_or_get_many() catalog method to perform a bulk
upsert of …
=> feat: batch column upsert

.guppy/hakari.toml, Cargo.lock, README.md, data_types2/Cargo.toml, influxdb2_client/Cargo.toml, influxdb_iox/Cargo.toml, iox_catalog/Cargo.toml, iox_gitops_adapter/Cargo.toml, object_store/Cargo.toml, object_store/src/aws.rs, object_store/src/azure.rs, sqlx-hotswap-pool/Cargo.toml, workspace-hack/Cargo.toml
This PR removes our dependency on OpenSSL, instead using [rustls](https://github.com/rustls/rustls) as the TLS implementation. 
Some benefits of this include:
* OpenSSL is a pain as a dependency on various platforms/envs/cross-compiling
* rustls was reported as being [faster](https://jbp.io/2019/07/01/rustls-vs-openssl-performance.html) (in 2019, requires a little 🧂)
* May well improve compile times - OpenSSL is a beast!
* Perhaps most importantly, is designed ground up to be a lower-risk TLS implementation, helped by the memory safety of rust and by implementing only features/protocol versions/ciphers that are commonly used in modern deployments
However a notable behavioural difference is the lack of IP SAN support - certificates that specify an IP address as the subject name will not …
=> feat: rustls as TLS backend

influxdb_iox/src/commands/run/router2.rs, router2/Cargo.toml, router2/benches/e2e.rs, router2/benches/schema_validator.rs, router2/src/dml_handlers/sharded_write_buffer.rs, router2/src/namespace_cache/metrics.rs, router2/src/sequencer.rs, router2/src/server/http.rs, router2/tests/http.rs
These metrics will help us answer a few questions that have popped up over the last couple days.
More metrics == more insights 👀 
---
* refactor: write table count metric (e00986c56)
Record the number of tables in each write - this will let us observe the total
number of tables a router instance has observed, which when combined with the
existing metrics helps us understand the shape
(distribution of tables/lines/fields) of the workload hitting the routers.
* refactor: sequencer metrics (bb9b140f4)
Records per-sequencer (kafka partition) enqueue latency / counts broken down
by operation success/error.
* refactor: NamespaceCache latency histograms (6b5283bf3)
Switches the get/put counters to latency histograms to record the duration of
each call - this might be interesting!
* feat: schema …
=> feat: more router metrics

.circleci/config.yml
Fixes #3680.
When someone (either dependabot or a person) opens a PR that needs changes to the workspace hack crate to update the features listed, or if other crates need to be changed to make them depend on the workspace hack crate, instead of CI, this will add a commit to the PR.
Take a look at the previous PR for this: https://github.com/influxdata/influxdb_iox/pull/3713
It's this branch plus a commit where I deleted part of the workspace-hack's Cargo.toml, and the hakari CircleCI job was able to push a new commit to the PR that fixed it 🎉
=> feat: Auto commit cargo hakari generate changes

Cargo.lock, influxdb_iox/src/commands/run/router2.rs, router2/Cargo.toml, router2/benches/e2e.rs, router2/src/dml_handlers/mock.rs, router2/src/dml_handlers/trait.rs, router2/src/server.rs, router2/src/server/grpc.rs, router2/src/server/http.rs, router2/tests/http.rs
Implements the gRPC write service (which previously existed, but returned an error).
This isn't strictly needed at the moment, but can't hurt, and will help the e2e effort (https://github.com/influxdata/influxdb_iox/pull/3905#discussion_r819467597).
---
* feat: grpc write handler (26c43f0a2)
Implements the gRPC write handler endpoint.
* refactor: enable gRPC handler (7c5ba34d4)
Plumbs the gRPC write handler into the existing router2 server.
=> feat: router grpc write handler

Cargo.lock, influxdb_ioxd/Cargo.toml, workspace-hack/Cargo.toml
Looks like #3908 accidentally reintroduced OpenSSL as a dependency.
We should blacklist openssl with something like [`cargo-deny`](https://github.com/EmbarkStudios/cargo-deny) to avoid this dance.
---
* build: remove openssl dependency (baae6910f)
Switches a stray reqwest dependency to use rustls.
=> build: remove openssl dependency

iox_catalog/migrations/20220308120917_ingester-missing-indexes.sql
Adds a couple of indexes to the catalog to support the [`TabelRepo::get_table_persist_info()`](https://github.com/influxdata/influxdb_iox/blob/aaec1c7828139e47296665c84aeea4c974026118/iox_catalog/src/postgres.rs#L717-L734) calls.
Plan before indexes:
```
Hash Left Join  (cost=80844.84..80913.72 rows=2500 width=24)
Hash Cond: (tid.id = parquet_file.table_id)
CTE tid
->  Seq Scan on table_name  (cost=0.00..195.75 rows=2500 width=4)
Filter: (namespace_id = 1)
->  Hash Left Join  (cost=58.19..117.69 rows=2500 width=12)
Hash Cond: (tid.id = tombstone.table_id)
->  CTE Scan on tid  (cost=0.00..50.00 rows=2500 width=4)
->  Hash  (cost=58.18..58.18 rows=1 width=12)
->  Subquery Scan on tombstone  (cost=50.15..58.18 rows=1 width=12)
->  Limit  (cost=50.15..58.17 rows=1 width=12)
InitPlan 2 …
```
=> perf: get_table_persist_info indexes for joins

data_types2/src/lib.rs, ingester/src/data.rs, iox_catalog/src/interface.rs, iox_catalog/src/lib.rs, iox_catalog/src/mem.rs, iox_catalog/src/metrics.rs, iox_catalog/src/postgres.rs, iox_tests/src/util.rs, parquet_file/src/metadata.rs
This has the advantages of:
- Not needing to create fake parquet file IDs or fake deleted_at values that aren't used by create before insertion
- Not needing too many arguments for create
- Naming the arguments so it's easier to see what value is what argument, especially in tests
- Easier to reuse arguments or parts of arguments by using copies of params, which makes it easier to see differences, especially in tests
- Encapsulates within the catalog the `compaction_level` value that should always get the `INITIAL_COMPACTION_LEVEL` on create
=> refactor: Extract a ParquetFileParams catalog type for use in ParquetFileRepo create

compactor/src/compact.rs, compactor/src/utils.rs, data_types2/src/lib.rs, iox_catalog/src/interface.rs, iox_catalog/src/mem.rs, iox_catalog/src/metrics.rs, iox_catalog/src/postgres.rs
I chose to fix #3950 and #3946 together because it was hard to test each without the other :)
This will conflict with https://github.com/influxdata/influxdb_iox/pull/4001 because I see that moved `TablePartition` too; I'm happy to take care of the merge conflicts.
You'll see a reference to a sqlx bug in here near some icky code; I'm working on submitting an upstream fix.
=> feat: Add catalog/compactor functions for getting level 0 and level 1 files; marking files as level 1

influxdb_ioxd/src/server_type/querier/mod.rs
I noticed this while playing with @alamb 's all-in-one mode 🎉 
---
* fix: propagate shutdown into QuerierHandlerImpl (22eab934c)
Prior to this commit, calling shutdown() on the QuerierServer (the server
layer run by the iox binary) would cancel it's own CancellationToken, while
the QuerierHandlerImpl (the actual querier workload entrypoint) would be
watching it's own, different token.
This commit removes the redundant CancellationToken in the QuerierServer,
instead using the inner QueryHandlerImpl for cancellation notification &
completion.
=> fix: propagate shutdown into QuerierHandlerImpl

influxdb_ioxd/src/server_type/compactor.rs
Same as #4043 - looks like a copy/paste rather than intentional.
---
* fix: propagate shutdown into CompactorHandler (5c16f28a1)
Prior to this commit, calling shutdown() on the CompactorServerType (the 
server layer run by the iox binary) would cancel it's own CancellationToken,
while the CompactorHandler (the actual compaction workload entrypoint) would
be watching it's own, different token.
This commit removes the redundant CancellationToken in the 
CompactorServerType, instead using the inner CompactorHandler for cancellation
notification & completion.
=> fix: propagate shutdown into CompactorHandler

influxdb2_client/tests/common/server_fixture.rs
It seems I'm the only one who doesn't have an iox binary on my laptop for the test fixtures to use, so it uses Docker, and that code path either never worked or got stale.
The addition of the `container` term is because `docker run` has long been deprecated but will probably never be removed. The real fix is the removal of the superfluous `database` term.
=> fix: docker server fixture had mistake in run command

iox_catalog/src/postgres.rs
Can't hurt! 60s is still quite a lot but will definitely reduce connection hogging.
---
* refactor: lower pg idle connection timeout (0d4949cd1)
Configure the postgres catalog to close unused connections after 1 minute,
rather than 500s to introduce a bit of fluidity to pool of connection
acquires.
=> refactor: lower pg idle connection timeout

Cargo.lock, ingester/Cargo.toml, ingester/src/data.rs, ingester/src/handler.rs, ingester/src/test_util.rs
Adds 3 metrics that'll give some insight into ingester performance / state.
---
* feat: ingester pause metrics (c0d5c6a55)
Emit a counter metric "ingest_paused_duration_ms_total" that records the 
duration of time an ingester stream is paused with millisecond granularity.
This metric will allow us to measure the frequency and severity of, and alert
on, an ingester stopping ingest due to memory limits enforced by the
LifecycleManager. This will help us tune these config params.
* refactor: ingester table & namespace count metrics (d9900f661)
Record the number of tables / namespaces an ingester process has observed.
=> feat: more ingester metrics

db/src/catalog/partition.rs, db/src/lifecycle/compact.rs, tracker/src/task/history.rs
We're killing our logging infrastructure :fire:
---
* refactor: reduce INFO verbosity (1b26bf1d7)
We're currently emitting ~5GB of logs every 30 minutes, and a quick scan 
through the logs shows the lines this PR changes to be the most frequent
(multiple times per second).
I don't believe any of these are important enough to be INFO, but if needed,
an appropriate log filter will bring them back.
=> refactor: reduce INFO verbosity

compactor/src/query.rs, db/src/chunk.rs, influxdb_ioxd/src/rpc/storage/service.rs, ingester/src/query.rs, query/src/frontend/influxrpc.rs, query/src/lib.rs, query/src/test.rs, query_tests/src/db.rs
This makes it way easier to dyn-type database implementations. The only
real change is that we make `QueryChunk::Error` opaque. Nobody is going
to inspect that anyways, it's just printed to the user.
This is a follow-up of #4053.
Ref #3934.
=> refactor: make `QueryChunk` object-safe

db/src/access.rs, db/src/lib.rs, querier/src/namespace/query_access.rs, query/src/exec.rs, query/src/lib.rs, query/src/test.rs, query_tests/src/db.rs
It should be possible to use some form of `Arc<dyn AbstractDb>` like DataFusion  already does it. There are only a few methods that are currently not object-safe and I'm about to fix that.
After this PR the last big TODO is `QueryDatabase::Chunk` (associated type) but that's a bit of a bigger change, so I'll create a separate PR for that.
Ref #3934.
=> refactor: steps towards dynamic database type dispatch

compactor/src/handler.rs, influxdb_ioxd/src/server_type/compactor.rs, influxdb_ioxd/src/server_type/querier/mod.rs
This PR restores #4044 & #4043 which were reverted by #4090 & #4091 and fixes an issue in the compactor that was incorrectly exiting immediately when `join()`-ed - I've left this as a TODO as the compactor worker loop does not yet exist.
Closes #4089.
---
* fix: propagate shutdown into QuerierHandlerImpl (011d3fbf2)
Prior to this commit, calling shutdown() on the QuerierServer (the server
layer run by the iox binary) would cancel it's own CancellationToken, while
the QuerierHandlerImpl (the actual querier workload entrypoint) would be
watching it's own, different token.
This commit removes the redundant CancellationToken in the QuerierServer,
instead using the inner QueryHandlerImpl for cancellation notification &
completion.
* fix: propagate shutdown into CompactorHandler (a4aedcf2a) …
=> fix: propagate shutdown requests & compactor join() fix

iox_catalog/src/interface.rs, router2/src/dml_handlers/schema_validation.rs, router2/src/server/http.rs, router2/tests/http.rs
The service limits added in #3807 should return a "HTTP 429 Too Many Requests" error when they're reached.
Closes #4066.
---
* refactor: emit HTTP 429 for service limits (1edc4ca56)
When a user hits the service limit, emit a "HTTP 429 Too Many Requests" error
with no "Retry-After" header. Reference:
https://docs.influxdata.com/influxdb/cloud/account-management/limits/#api-error-responses
* refactor: explicit schema validation errors (c6af2f593)
This commit adds new service limit & schema conflict error variants to the
SchemaError enum, allowing less error-prone matching higher up the stack and
more explicit log messages for both.
HTTP status codes are now correctly reported as 500 for internal catalog 
errors during schema validation.
* refactor: lowercase error messages (8e85846db) …
=> fix: service limit http code

compactor/src/compact.rs, compactor/src/garbage_collector.rs, compactor/src/lib.rs, data_types2/src/lib.rs, ingester/src/data.rs, ingester/src/persist.rs, iox_catalog/migrations/20220324152729_add_namespace_id_to_parquet_file.sql, iox_catalog/migrations/20220328150925_add_index_to_to_delete.sql, iox_catalog/src/interface.rs, iox_catalog/src/mem.rs, iox_catalog/src/metrics.rs, iox_catalog/src/postgres.rs, iox_tests/src/util.rs, object_store/src/lib.rs, parquet_file/src/metadata.rs
Fixes #3954.
I'm happy to change names if "garbage collector" is too overloaded ;)
This does not actually call the function to clean up old files, nor does it set what "old" means.
=> feat: Clean up old parquet files in the catalog and object storage

ingester/src/compact.rs, ingester/src/data.rs, ingester/src/lib.rs, ingester/src/sort_key.rs, query/src/lib.rs
Fixes #4194.
I have now SPLIT #3968 into 3 parts, so this PR now only contains the *computation* of the sort key. It does *not* cover storing the sort key in the catalog (now #4195) or checking and potentially updating the sort key (now #4196).
=> feat: Compute a sort key in the ingester

iox_catalog/migrations/20220404120116_column_name-table_id-index.sql
Adds a missing index to the `column_name` table.
---
* refactor: add table_id index on column_name (61bc9c83a)
After checking the postgres workload for the catalog in prod, this missing
index was noted as the cause of unexpectedly expensive plans for simple
queries.
=> refactor: add table_id index on column_name

Cargo.lock, ingester/Cargo.toml, ingester/src/lib.rs, ingester/src/stream_handler/handler.rs, ingester/src/stream_handler/mock_sink.rs, ingester/src/stream_handler/mod.rs, ingester/src/stream_handler/sink.rs, test_helpers/Cargo.toml, test_helpers/src/lib.rs, test_helpers/src/timeout.rs
This PR is aims to refactor the [`stream_in_sequenced_entries()`](https://github.com/influxdata/influxdb_iox/blob/d393ec6c257800508e33a6486c27d78b85b400fa/ingester/src/handler.rs#L273) fn that currently handles reading from kafka and applying the operation down through to the table buffer (and other things) with the intent being primarily to refine error handling and observability, and secondarily decouple various responsibilities within the ingest process to improve encapsulation / make testing easier.
This PR does NOT add the code within it to the ingest pipeline, instead the old handler remains in place - I've a little more to add to this refactor (specifically instrumentation, kafka watermark fetching, and a sink to connect the handler to the existing op processing impl) but felt this …
=> refactor: handle errors in ingester stream handler

ingester/src/stream_handler/mod.rs, ingester/src/stream_handler/periodic_watermark_fetcher.rs, write_buffer/src/mock.rs
Implements [fetching the maximum write buffer offset](https://github.com/influxdata/influxdb_iox/blob/b08540064cd2f9f614d23e532587ba61da8295cb/ingester/src/handler.rs#L356-L379) as a singly responsible type that can be mocked out for testing.
This is work towards replacing the existing stream handler in the ingester with `SequencedStreamHandler`:
---
* feat: periodic kafka max watermark offset fetcher (891d2e136)
Adds the PeriodicWatermarkFetcher type responsible for querying write buffer /
Kafka for the maximum sequence number / offset, surfacing any errors via both
logs & metrics.
This high watermark / max offset value is used within the ingest 
instrumentation metrics. This use case is tolerant of caching / stale values,
and as such the value is periodically updated to minimise load on …
=> feat: periodic high watermark fetcher

compactor/src/compact.rs, compactor/src/handler.rs, compactor/src/utils.rs, iox_object_store/src/paths/parquet_file.rs, parquet_file/src/chunk.rs, parquet_file/src/storage.rs
This PR simply adds more debug logging - can't fix what you can't see 👀 
---
* refactor: print parquet path in Debug impl (2607151ec)
Print the actual path being used when debug-printing a ParquetFilePath.
* refactor: add debug in compaction path (3706ac042)
Adds debug!() and friends through the compaction path.
=> refactor: compactor debug logging

ingester/src/stream_handler/mock_watermark_fetcher.rs, ingester/src/stream_handler/mod.rs, ingester/src/stream_handler/periodic_watermark_fetcher.rs, ingester/src/stream_handler/sink_instrumentation.rs
This PR adds a `DmlSink` implementation that decorates other implementations to emit metrics & traces during the `DmlSink::apply()` call.
This type currently emits both the write buffer metrics and op call metrics - these responsibilities will likely need splitting if we wind up composing together `DmlSink` implementations in the future and would like to record latencies for each.
There are some differences in the metrics this PR adds compared to what we [currently have](https://github.com/influxdata/influxdb_iox/blob/b6f9c9bfd4b138d71d5440b372dc5652223ac53f/db/src/write_buffer/metrics.rs#L29-L60):
* All metrics were [labelled with `db_name`](https://github.com/influxdata/influxdb_iox/blob/b6f9c9bfd4b138d71d5440b372dc5652223ac53f/db/src/write_buffer/metrics.rs#L77) - this is now …
=> feat: ingester op instrumentation

Cargo.lock, ingester/Cargo.toml, ingester/src/handler.rs, ingester/src/stream_handler/handler.rs, ingester/src/stream_handler/mod.rs, ingester/src/stream_handler/sink_adaptor.rs, ioxd_ingester/src/lib.rs
This PR switches out the old `stream_in_sequenced_entries()` kafka consumer for the `SequencedStreamHandler` introduced in #4203.
If this swap causes problems, reverting dce939c58 (or this whole PR) should switch back to the old code paths - if anything goes wrong, I'll be doing this to unblock prod once I've grabbed enough problem context. As such, depending on what time this PR is reviewed, I may **hold off merging** until Monday to ensure I am around when it is deployed.
Once merged the ingesters will emit slightly different metrics, and I will ensure the dashboards are updated.
---
* feat: impl DmlSink for IngesterData (c2236fa3f)
This commit adds an adaptor (IngestSinkAdaptor) that provides a DmlSink 
implementation for the existing write path (IngesterData). With this, the
existing …
=> feat(ingester): use SequencedStreamHandler

rust-toolchain.toml
[Much improvement, many toy](https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html).
---
* build: use rust 1.60 (3624d635)
=> build: use rust 1.60

.circleci/config.yml
🧹 cleanup 🧹 
---
* ci: remove duplicate RUSTFLAGS definition (6aac162e)
This commit unifies RUSTFLAGS config in the CircleCI config.
Previously in the CircleCI config file for the "build_release" job, we specify
an env var (RUSTFLAGS) in the env config section, but then override / use a
different value when passing flags to the docker build steps.
=> ci: remove duplicate RUSTFLAGS definition

compactor/src/compact.rs, compactor/src/query.rs, compactor/src/utils.rs, data_types2/src/lib.rs, iox_catalog/src/interface.rs, iox_catalog/src/mem.rs, iox_catalog/src/metrics.rs, iox_catalog/src/postgres.rs, iox_tests/src/util.rs, parquet_file/src/chunk.rs, querier/src/chunk/mod.rs, querier/src/table/mod.rs
Connects to #4124.
This is an incremental step to stop fetching the parquet_metadata column from the parquet_files table for most parquet_files queries, which should help with performance.
The places that do use the metadata are still fetching it and decoding it for now. For one place, I made a special `_with_metadata` catalog method. For the other place, I'm doing more queries to get each parquet file's metadata column. It was slightly easier to do each place this way, but not impossible to change either place to use the other technique, so let me know if you'd like me to make these consistent.
However, the next steps should be trying to move to using other catalog data instead of the parquet_metadata, so that change may be moot. These next steps are not trivial 😅 
If we end up removing …
=> feat: Store parquet_metadata in catalog, but don't fetch it by default

Cargo.lock, iox_gitops_adapter/Cargo.toml
Closes #4292.
Closes #4294.
Closes #4295.
=> chore: bump kube to version 0.71.0

datafusion_util/src/lib.rs, query/src/exec/split.rs
This PR fixes the compaction deadlock we have observed during testing.
The deadlock is caused by the `StreamSplitExec` background worker that pushes results into two channels - one for each partition. The channels have a [buffer size of 2], and the worker [gets stuck] trying to push results into the second partition while the compactor is reading the first partition.
Because the worker is stuck, it cannot push the rest of the records into the channel for the first partition, nor close the channel (indicating completion, and signalling to the compactor that it can move on). Because the channel is never closed, the compaction loop [blocks waiting for the first partition](https://github.com/influxdata/influxdb_iox/blob/31fdeaaabc21d2e7d24b801b8503d77aee7853f8/compactor/src/compact.rs#L671) …
=> fix: compactor deadlock

Cargo.lock, querier/Cargo.toml, querier/src/ingester/flight_client.rs, querier/src/ingester/mod.rs
Add infrastructure to test how the querier processes ingester gRPC
responses w/o performing a full query or end2end test.
On top of #4307.
=> test: mock gRPC ingester response for querier 

Cargo.lock, influxdb_iox/src/commands/run/all_in_one.rs, influxdb_iox/src/commands/run/compactor.rs, influxdb_iox/src/commands/run/database.rs, influxdb_iox/src/commands/run/ingester.rs, influxdb_iox/src/commands/run/main.rs, influxdb_iox/src/commands/run/querier.rs, influxdb_iox/src/commands/run/router.rs, influxdb_iox/src/commands/run/router2.rs, influxdb_iox/src/commands/run/test.rs, panic_logging/Cargo.toml, panic_logging/src/lib.rs
This PR adds a `thread_panic_count_total` metric to the various server types so we can measure the frequency of, and alert on panics.
I was going to keep the logging-to-tracing and metric recorder concerns separate and compose the impls as needed, but the drop ordering becomes important when setting multiple panic handlers and it was overly brittle / easy to cock up, so it's an optional behaviour of the existing custom panic handler instead 👍 
---
* feat: emit thread panic count metric (49c38c297)
Allows the panic handler to be optionally configured to emit a thread panic
metric, increasing by 1 each time a panic is observed.
* refactor: emit panic metrics for server types (c36324290)
Configures the long-running / server modes to emit panic metrics.
=> feat: panic metrics

Dockerfile
Draft as I test this
As pointed out by @domodwyer , https://github.com/influxdata/influxdb_iox/pull/4357 broke the `build_release` job (which builds the docker images that are deployed to production)
https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/18258/workflows/0a91a876-b32c-4855-af19-61929d6088eb/jobs/151724
```
#17 152.3   CMAKE_PREFIX_PATH = None
#17 152.3   CMAKE_x86_64-unknown-linux-gnu = None
#17 152.3   CMAKE_x86_64_unknown_linux_gnu = None
#17 152.3   HOST_CMAKE = None
#17 152.3   CMAKE = None
#17 152.3   running: "cmake" "/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.1/third-party/protobuf/cmake" "-DCMAKE_INSTALL_PREFIX=/influxdb_iox/target/release/build/prost-build-86ce3b21d9074480/out" "-DCMAKE_C_FLAGS= -ffunction-sections …
```
=> fix: Add protobuf compiler to docker build image

Cargo.lock, influxdb_iox/tests/end_to_end_ng_cases/mod.rs, influxdb_iox/tests/end_to_end_ng_cases/tracing.rs, test_helpers_end_to_end_ng/Cargo.toml, test_helpers_end_to_end_ng/src/config.rs, test_helpers_end_to_end_ng/src/lib.rs, test_helpers_end_to_end_ng/src/mini_cluster.rs, test_helpers_end_to_end_ng/src/udp_listener.rs
Connects to #4102.
Adds some infrastructure to the test helper crate; there is some more that could maybe be shared with the NG querier RPC tests, but I wasn't sure if that was worth it or not.
The port is done in 2 commits: one where I just ran `cp influxdb_iox/tests/end_to_end_cases/tracing.rs influxdb_iox/tests/end_to_end_ng_cases` and committed even though it doesn't compile at all, and then another commit that actually does the port, so that if you review this PR commit-by-commit it should hopefully be easier to see what actually changed in the port.
=> feat: Port end-to-end tracing tests to NG end-to-end tests

data_types2/src/lib.rs, querier/src/ingester/mod.rs
This is required to pass the query tests with ingester data. (the actual query tests will follow in a separate PR)
=> feat: Provide basic summaries for `IngesterPartition`

Cargo.lock, influxdb_line_protocol/src/lib.rs, mutable_batch_lp/Cargo.toml, mutable_batch_lp/src/lib.rs, router2/src/server/http.rs
This PR changes how IOx handles line-protocol lines that reference the same column name more than once, as described in #4326.
Previously a write such as `table A=1,A=1` would cause IOx to panic in the `MutableBuffer`. After this PR is merged, IOx will accept writes with duplicate fields according to the following semantics:
* duplicate fields, same value - do nothing/coalesce
* duplicate fields, different value - last write wins
* duplicate fields, different types - reject the request
* duplicate tags, same value - reject the request
* duplicate tags, different value - reject the request
* duplicate tags, different type - reject the request
* same name for tag and field - reject the request
* same name for tag and field, different type  - reject the request
This retains parity with TSM, …
=> fix: handle LP lines with duplicated fields/tags

Cargo.lock, mutable_batch_lp/Cargo.toml, mutable_batch_lp/benches/parse_lp.rs
A quick benchmark to check the overhead of #4398 - see https://github.com/influxdata/influxdb_iox/pull/4398#discussion_r857476339 
---
* feat: benchmark LP -> MutableBuffer conversion (4174c88bc)
Adds a benchmark that measures the time taken to parse the 
test_fixtures/metrics.lp dataset, and convert it into a MutableBuffer 
instance.
=> feat: benchmark LP -> MutableBuffer conversion

influxdb_iox/tests/end_to_end_ng_cases/metrics.rs
Fixes an e2e failure first noticed in #3577.
I'm not sure if this was intentional - I can't think of a reason why we'd want to assert this one metric appears an exact number of times, though I am happy to change it back to an == if needed 👍 
Relates to https://github.com/influxdata/influxdb_iox/issues/4457
---
* test: remove hard-coded metric count (246af0c3c)
Prior to this commit, adding any metric to the catalog (and only the catalog)
would cause the end_to_end_ng_cases::metrics::test_metrics test to fail due to
asserting an exact number of metrics observed.
This commit changes the check condition to a more permisive >= rather than ==.
=> test: remove hard-coded metric count

README.md
Solve the link jumping problem.
=> docs: fix the wrong link jumping in README

Cargo.lock, influxdb_iox/Cargo.toml
pprof updated a new version, see https://github.com/influxdata/influxdb_iox/pull/4562 and I noticed that the old version of pprof was still used by heappy.
1. update heappy to https://github.com/mkmik/heappy/commit/5d47dff152b8430e1dc1aea5a54c91c0c3099219
=> chore: Update heappy

ingester/src/data.rs, ingester/src/querier_handler.rs, querier/src/ingester/flight_client.rs, querier/src/ingester/mod.rs, querier/src/table/mod.rs, querier/src/table/state_reconciler.rs, write_summary/src/lib.rs
I still don't know what's causing #4395. 
The debug logs didn't include all the information I was wondering about, like what the ingesters think they have, what they're sending to the querier, when they're persisting what, what the querier gets from the ingesters, what the querier sees in the catalog, what happens when the querier puts together data from the ingester and from the catalog.
=> feat: Add more logging in particular situations to debug flaky test

arrow_util/src/bitset.rs
See https://github.com/influxdata/influxdb_iox/pull/4620#discussion_r875010222
---
* fix: bounds check BitSet access (43bc47346)
Prior to this commit, it was possible to read/write to the allocated, but
unused storage bits outside of the "length" of the BitSet.
Bit access is now bounds checked.
=> fix: bounds check BitSet access

Cargo.lock, arrow_util/src/bitset.rs, mutable_batch_pb/Cargo.toml, mutable_batch_pb/src/encode.rs, mutable_batch_pb/tests/encode.rs
As mentioned in slack, this is a "quick fix" for #4272.
The commit message explains the problem and implemented fix, but there are a few notable points:
1. The proto wire format allows a column to contain values of many types at the same time, as it is [expressed as a record/struct][proto] of all available types, rather than an enumeration which would constrain the wire format to match the semantics of the system internals - a record batch column can have only one type, but our wire protocol column can have many types.
2. Because we do not differentiate between NULL and "empty"/"zero value" in the proto messages, the current message is ambiguous - I don't think conflating zero values with NULL is the right strategy, and explicit NULLs would have prevented this bug. Fundamentally 0 != NULL …
=> fix: partition null column serialisation

querier/src/table/mod.rs, querier/src/table/query_access.rs, querier/src/table/state_reconciler.rs, querier/src/table/state_reconciler/interface.rs
Re: https://github.com/influxdata/influxdb_iox/issues/4634
This is a the first of a few PRs to add parquet file caching to the querier
I want the reconcilation code to be easier to test as I add in a cache to it
Extract the code into its own module. No functional changes intended
=> refactor: Encapsulate reconciliation logic more

.circleci/config.yml
Fixes the release build & unblocks deployments.
---
* build: remove iox_gitops_adapter from build (6b6dbb028)
Broken release builds since:
https://github.com/influxdata/influxdb_iox/pull/4675
=> build: remove iox_gitops_adapter from build

Cargo.lock, cache_system/src/driver.rs, compactor/src/compact.rs, querier/Cargo.toml, querier/src/cache/mod.rs, querier/src/cache/read_buffer.rs, querier/src/chunk/mod.rs, querier/src/chunk/query_access.rs, querier/src/table/state_reconciler.rs
Connects to #4681.
This is a new querier cache that eventually will cache Read Buffer chunks created from Parquet files as they're requested.
The new querier cache isn't called anywhere yet, and it doesn't work completely: I have a bunch of functions sketched out that show the steps I'm planning on taking, but all except the last one in the sequence are `unimplemented!` in this PR.
However, because this isn't called anywhere yet, this can be safely merged in and iterated on!
=> feat: Start of a read buffer chunk cache

compactor/src/compact.rs, data_types/src/lib.rs, parquet_file/src/chunk.rs, querier/src/cache/mod.rs, querier/src/cache/read_buffer.rs, querier/src/chunk/mod.rs, querier/src/chunk/query_access.rs, querier/src/database.rs, querier/src/namespace/mod.rs, querier/src/table/mod.rs, querier/src/table/state_reconciler.rs, querier/src/table/test_util.rs
Connects to #4681.
This brings back [a bunch of code from the OG `DbChunk`](https://github.com/influxdata/influxdb_iox/blob/37c7ce793cc12a7f5dc29b3bc3d575c6c500f2bf/db/src/chunk.rs) when the chunk's storage was in the read buffer.
I also added a method for the read buffer cache in the catalog cache, but it's deliberately unimplemented so that it won't get used in production yet. That's so I could call it in `ChunkAdapter::new_chunk` and start to get an idea of what data I'll have when, but I'm not calling `new_chunk` anywhere yet either. 
Is everything in the place you'd expect it to be?
=> feat: Make a QuerierRBChunk wrapper that implement QueryChunk and QueryChunkMeta

compactor/src/compact.rs, compactor/src/utils.rs
A small clean-up - pub fields trigger me to an unreasonable degree.
---
* refactor: constructor for ParquetFileWithTombstone (9ae58c89b)
Use a constructor to initialise a ParquetFileWithTombstone struct, rather than
making the fields pub.
This allows IDEs to "go to" places where this is constructed when browsing the
code, but also keeps the type closed for modification of internals (SOLID).
=> refactor: constructor for ParquetFileWithTombstone

influxdb_iox/src/commands/remote/partition.rs, influxdb_iox/tests/end_to_end_cases/cli.rs
I'll let you guess why I am proposing this change.
---
* refactor: warn for silly object store configs (0e5c86fd8)
Warn when downloading files to an in-memory object store.
The "remote partition pull" command downloads parquet files from an object
store via a router, and saves them locally. It's pretty unlikely the user
intends to download those files to memory of the CLI process which then exits
when the pull is complete, throwing away the downloaded files, but this is the
default.
* test(e2e): ensure "partition pull" writes files (1fc95ba72)
Adds a test case covering the "remote partition pull" command configured with
file-based object storage.
=> refactor: warn for silly object store configs

parquet_file/src/chunk.rs, parquet_file/src/storage.rs, querier/src/cache/read_buffer.rs, querier/src/chunk/mod.rs
Connects to #4681. 
This adds a new type parameter to the cache loader so that, if we need to load the chunk from the parquet file, we can use the other information we already have about that parquet file rather than needing to look it up in the catalog again.
The cache still stores the chunk by parquet file ID.
This still isn't actually hooked up yet as there's only the most rudimentary tests. ~~Namely, I haven't verified the LRU behavior at all.~~
=> feat: Cache read buffer chunks

compactor/src/compact.rs, compactor/src/garbage_collector.rs, data_types/src/lib.rs, influxdb_iox/src/commands/remote/partition.rs, ingester/src/compact.rs, ingester/src/data.rs, ingester/src/handler.rs, ingester/src/partioning.rs, ingester/src/test_util.rs, iox_catalog/src/interface.rs, iox_catalog/src/mem.rs, iox_catalog/src/metrics.rs, iox_catalog/src/postgres.rs, iox_tests/src/util.rs, parquet_file/src/metadata.rs, querier/src/cache/parquet_file.rs, query_tests/src/scenarios/util.rs, service_grpc_catalog/src/lib.rs, service_grpc_object_store/src/lib.rs
This PR adds a new `PartitionKey` type so we can accept a typed input in fn calls, instead of a bare `String`, taking advantage of type checking to eliminate errors. It also ref-counts the underlying string to reduce memory usage, but this wasn't the primary motivation.
The actual functional code change is small, but quite a few tests needed updating.
---
* refactor: PartitionKey type (b41ea1d71)
This commit changes the code base to use a new reference-counted PartitionKey
type wrapper, instead of passing a bare String around.
This allows the compiler to type check & verify usage of the partition key,
instead of passing a bare string around. By reference counting the underlying
string, we reduce memory usage for some use cases.
=> refactor: PartitionKey type

data_types/src/lib.rs, dml/src/lib.rs, influxdb_iox_client/src/client/write.rs, ingester/src/data.rs, ingester/src/handler.rs, ingester/src/stream_handler/handler.rs, ingester/src/stream_handler/sink_instrumentation.rs, ioxd_common/src/http/dml.rs, mutable_batch/src/payload.rs, mutable_batch/src/payload/partition.rs, mutable_batch_pb/tests/encode.rs, mutable_batch_tests/benches/write_pb.rs, query_tests/src/scenarios/util.rs, router/src/dml_handlers/partitioner.rs, router/src/dml_handlers/sharded_write_buffer.rs, write_buffer/src/codec.rs, write_buffer/src/core.rs, write_buffer/src/file.rs, write_buffer/src/kafka/aggregator.rs, write_buffer/src/kafka/mod.rs, write_buffer/src/mock.rs
This change allows us to propagate the derived partition key through the system, but stops short of passing it over the kafka boundary - I'll follow up with another PR to add this shortly (tracked in #3603).
Prerequisite for fixing https://github.com/influxdata/influxdb_iox/issues/4787.
---
* refactor: emit PartitionKey from partitioner (61182f506)
Changes the partitioning code to emit a PartitionKey, instead of a bare 
String.
* refactor: always generate a partition key (0da8ec87d)
Changes the partitioner to always generate a partition key, even if the column
being used to partition doesn't exist. This doesn't functionally change the
batch partitioning output, but ensures we always have a non-empty string for
the partition key.
* refactor: store PartitionKey in DmlWrite (4df296456)
Carry …
=> refactor: add partition key to DmlWrite

write_buffer/src/core.rs, write_buffer/src/file.rs, write_buffer/src/kafka/aggregator.rs, write_buffer/src/kafka/mod.rs
This PR fixes #4787.
The router is hard-coded to [partition writes by YMD][scheme] (meaning a partition per day, today's being `2022-06-16`), breaking the writes into a single [DML write request per partition][router-partition]. The router then dispatches each of these partitioned DML writes into kafka via the write buffer abstraction.
On the other side of kafka, the ingester reads these messages and uses the same hard-coded partitioning scheme to [infer the partition key][ingest] of the batch. This inference solution was a temporary workaround until OG was deprecated and removed, which made changing the kafka message format feasible (#3603). 
Correctness of this scheme relies on the atomicity of the DML batches being preserved through the system - a batch is split up by the router …
=> fix: respect partition key when batching dml ops

router/src/dml_handlers/partitioner.rs
I wrote these while I was debugging #4787 to ensure partitioning backfill writes wasn't broken.
More tests == more good.
---
* test: assert backfill partitioning in router (2cc2ad688)
Assert writes in the router that cover multiple partitions are correctly split
up.
=> test: assert backfill partitioning in router

ingester/src/data.rs, ingester/src/stream_handler/sink_instrumentation.rs
These don't get identified by the unused lint, I assume because of the macro generated magic code.
---
* refactor: remove unused errors (87af3848d)
These errors are not referenced, but are hidden from the "unused" lint because
of the macro magic code generation.
=> refactor: remove unused errors

ingester/src/lifecycle.rs
Fixes #4936.
---
* fix: account for partition memory until persisted (9a79d1658)
The ingester maintains a rough "total memory in use" counter it uses to try
and limit the amount of memory the ingester is using overall.
When a partition is persisted, this total memory usage value is adjusted to
account for releasing the partition memory. Prior to this commit, the ordering
was:
* Writes increase the memory counter
* maybe_persist() is called to trigger persistence
* A partition is identified for persistence
* Partition memory usage is released back to the total memory counter
* Persistence starts
This meant that the partitions in the process of being persisted were not
accounted for in the ingester's total memory counter, and therefore we could
significantly overrun the configured memory …
=> fix: account for partition memory until persist is completed

iox_query/src/frontend/influxrpc.rs, predicate/src/rpc_predicate.rs, query_tests/src/influxrpc/tag_keys.rs, query_tests/src/scenarios/library.rs, service_grpc_influxrpc/src/expr.rs, service_grpc_influxrpc/src/service.rs
Helps #4827 
When the predicate is empty (note `_measurement = "foo"` and `time range all time` predicates are simplified away), satisfy tag_keys queries from the metadata store instead of reading all the parquet data.
This means deletes are not honoured for this query.
=> fix: optimize tag_keys to go only to schema when predicate is empty

clap_blocks/src/catalog_dsn.rs, influxdb_iox/tests/end_to_end_cases/all_in_one.rs, influxdb_iox/tests/end_to_end_cases/metrics.rs, influxdb_iox/tests/end_to_end_cases/tracing.rs, iox_catalog/src/lib.rs, test_helpers_end_to_end/src/config.rs, test_helpers_end_to_end/src/server_fixture.rs
Fixes #5022.
Since https://github.com/influxdata/influxdb_iox/pull/4887, the all-in-one ephemeral mode, used by some integration tests, has been intermittently failing.
The problem was that the all-in-one mode was assuming 1 Kafka partition/sequencer in most places, but if an ephemeral in-memory catalog was being used, `create_or_get_default_records` was making 2 sequencer records in the catalog. That meant the router was sharding using 1 shard, and the querier was sharding using the 2 shards in the catalog (but only had 1 sequencer -> ingester mapping configured). If the querier happened to shard the query to the same shard the router used, everything worked fine, but if the querier sharded to the other shard, the query would error.
The `create_or_get_default_records` method was also …
=> fix: Correctly set up querier-to-ingester config, sequencers, and catalog for all-in-one ephemeral mode

.guppy/hakari.toml, Cargo.lock, Cargo.toml, workspace-hack/Cargo.toml
Closes #5109
@tustvold said he'll cut a new release. I made this PR anyway when I realised that hackari was complaining when I patched  with:
```
[patch.crates-io]
object_store = { path = "../object_store_rs" }
```
so I figured I would have to fiddle with hackari config also if we bump the `object_store` dep to `0.4.0`
=> fix: Bump object_store crate for EKS support

generated_types/protos/influxdata/platform/storage/storage_common.proto, influxdb_iox/src/commands/storage/request.rs, service_grpc_influxrpc/src/service.rs, test_helpers_end_to_end/src/grpc.rs
The storage API has been updated in https://github.com/influxdata/idpe/pull/12868
in January, but since we forked the `.proto` files we never noticed.
Closes https://github.com/influxdata/conductor/issues/1054
=> fix: Sync ReadWindowAggregate API: TagKeyMetaNames

compactor/src/compact.rs, compactor/src/lib.rs, compactor/src/parquet_file_combining.rs, compactor/src/query.rs, compactor/src/utils.rs
Connects to #5121.
This does not include any metrics yet, and it isn't correctly hooked up yet (the `compact_partition` function in compactor/src/lib.rs needs to log and ignore some of the errors).
But while I'm working on those two parts, I wanted to get some feedback on the code and the tests.
=> feat: Compact filtered parquet files

data_types/src/lib.rs, predicate/src/lib.rs, query_tests/src/influxrpc/field_columns.rs, service_grpc_influxrpc/src/service.rs
(For optimized metadata queries only)
InfluxQL queries can send (technically incorrect) ranges like this, meaning all time
but excluding the max nanosecond time.
Since this is an important case, we should handle it specially and use the optimized
'all time' handling for meta queries even though this is technically wrong in that
it does not filter out column names / measurement names at MAX_NANO_TIME exactly.
Closes: https://github.com/influxdata/conductor/issues/1072
=> fix: interpret [MIN_NANO_TIME, MAX_NANO_TIME) range as all time

influxdb_line_protocol/src/lib.rs
Fixes "Scientific notation without + or -" (closes #5263)
Fixes "Negative scientific notation without decimal parts" (closes #5264)
Closes #5261 
(Ideally we should test against https://github.com/influxdata/line-protocol-corpus/blob/main/corpus.json)
---
Helps with https://github.com/influxdata/conductor/issues/1021
Helps with https://github.com/influxdata/conductor/issues/1053
=> fix: Fix bug and incompatibility in floating point parsing of scientific notation

clap_blocks/src/compactor.rs, compactor/src/compact.rs, compactor/src/handler.rs, compactor/src/lib.rs, compactor/src/parquet_file_filtering.rs, influxdb_iox/src/commands/run/all_in_one.rs, iox_catalog/src/interface.rs, iox_catalog/src/mem.rs, iox_catalog/src/metrics.rs, iox_catalog/src/postgres.rs, ioxd_compactor/src/lib.rs
Fixes [#1078](https://github.com/influxdata/conductor/issues/1078).
This PR does somewhat more than the issue describes, but Nga and Paul and I have discussed it and this is ok.
This PR moves the current compaction procedure to `compact_hot_partitions`, and adds a new, slightly different procedure in `compact_cold_partitions` which also runs in the compaction handler loop.
There's a new CLI flag/env var, `--compaction-hot-multiple` (thoughts on a better name?), that controls how many times a compactor loop iteration will run compaction of hot partitions for every 1 time the loop runs compaction of cold partitions, to control how much we bias the compactor towards spending time on hot partitions. I've set the default to 4, so every compaction loop iteration will compact hot partitions 4 …
=> feat: Compact cold partitions; upgrade a single non-overlapping level 0 file to level 1 without running compaction

Cargo.lock, clap_blocks/src/compactor.rs, compactor/src/handler.rs, influxdb_iox/Cargo.toml, influxdb_iox/src/commands/compactor.rs, influxdb_iox/src/main.rs, influxdb_iox/tests/end_to_end_cases/cli.rs, influxdb_iox/tests/end_to_end_cases/error.rs, ioxd_compactor/Cargo.toml, ioxd_compactor/src/lib.rs, test_helpers_end_to_end/src/lib.rs, test_helpers_end_to_end/src/mini_cluster.rs, test_helpers_end_to_end/src/server_fixture.rs, test_helpers_end_to_end/src/steps.rs
So before this PR, some of the tests were running a compactor, doing its own thing willy-nilly as we want it to do in production. That's pretty inconvenient in the tests, like [in this PR](https://github.com/influxdata/influxdb_iox/pull/5194), as we want to be able to say "ok run compaction now, and once it's done, then assert some things".
So, in the tests, rather than running the compactor as a server, we've created a command `influxdb_iox compactor run-once` that will run the compactor loop one time and then exit. It sets a default of `--compaction-hot-multiple` to 1 so that `run-once` will run one hot and one cold compaction operation. We can change other defaults of other settings if that sounds useful.
I could see this command being useful in development, if you want to run a …
=> feat: Compactor e2e tests and a "run once" compactor command

Cargo.lock, write_buffer/Cargo.toml
Lets deploy https://github.com/influxdata/rskafka/pull/164 and see how much difference (if any) it makes.
Of the two (or three) planned changes, this is likely the least impactful - it's still good to see it in isolation though!
---
* build: bump rskafka (7174f38f3)
Bumps rskafka to HEAD to pick up:
https://github.com/influxdata/rskafka/pull/164
=> build: bump rskafka

router/src/lib.rs
No one is merging anything and I need deployment-driven data!
---
* docs: router writes to partitions (d3dfc4221)
Though it can write to different topics, it currently writes to different
partitions.
=> docs: router writes to partitions

Cargo.lock, iox_catalog/Cargo.toml, iox_catalog/src/lib.rs, router/src/dml_handlers/schema_validation.rs, router/tests/http.rs
Changes errors like this:
```
dml handler error: schema conflict: column foo is type tag but write has type iox::column_type::field::float
```
Into:
```
dml handler error: schema conflict: table bar, column foo is type tag but write has type iox::column_type::field::float
```
Closes #5408, closes #5410.
---
* feat: table name in schema validation errors (76c0c3373)
Scopes all schema validation errors to include the table name in the error
output.
=> feat: table name in schema validation errors

generated_types/protos/influxdata/iox/sharder/v1/sharder.proto
A proposed API definition to expose sharding logic outside of the router.
Ideally the sharding logic lives in one place, rather than multiple components having their own  compiled-in implementation to minimise bugs / simplify keeping everything in sync / support customised sharding keys in the future. This PR exposes the sharding logic in the router to any caller in a future-proof way.
Relates to https://github.com/influxdata/influxdb_iox/pull/5447#pullrequestreview-1080574538
---
* feat: sharder API definition (57bbe6b21)
This commit adds a gRPC endpoint for callers to map (table, namespace) tuples
to Sequencer IDs, using the logic internal to the router.
Reference:
https://github.com/influxdata/influxdb_iox/pull/5447#pullrequestreview-1080574538
=> feat: sharder API definition

ioxd_router/src/lib.rs, router/benches/e2e.rs, router/src/dml_handlers/sharded_write_buffer.rs, router/src/sequencer.rs, router/tests/http.rs
A quick tidy-up PR that uses the `KafkaPartition` type wrapper instead of bare `usize`, adds asserts when we cast between types.
I'm not sure why, but the [`KafkaPartition` is an `i32`](https://github.com/influxdata/influxdb_iox/blob/9b920f1cbbfee5b996b5757cd3f855b4a7a72b95/data_types/src/lib.rs#L184), but the [`WriteBuffer` uses a `u32`](https://github.com/influxdata/influxdb_iox/blob/9b920f1cbbfee5b996b5757cd3f855b4a7a72b95/write_buffer/src/core.rs#L167) even though Kafka (and it's clients) [use `i32`](https://github.com/influxdata/influxdb_iox/blob/9b920f1cbbfee5b996b5757cd3f855b4a7a72b95/write_buffer/src/kafka/mod.rs#L452) to identify partitions - this causes us to cast a whole lotta times.
Relates to https://github.com/influxdata/influxdb_iox/pull/5435
---
* refactor(router): use …
=> refactor(router): use KafkaPartition in sequencer

generated_types/build.rs, generated_types/protos/influxdata/iox/sharder/v1/sharder.proto, generated_types/src/lib.rs
An update to the inital proto definition (#5451) for https://github.com/influxdata/influxdb_iox/pull/5447.
---
* refactor(proto): simplify RPC messages & types (f11af90c4)
Removes the input oneof - a shard caller MUST always provide a 
table/namespace, and MAY provide an optional payload (which in the future will
enable sharding using column valuess/etc). As there is currently no
payload-based sharding, this simplifies the RPC message.
Changes the returned types to better reflect the types we use internally
- this should avoid type juggling for both server & client.
* build: generate gRPC bindings for ShardService (c6d4109e0)
Builds the ShardService proto file in the generated_types package.
=> refactor(proto): update ShardService gRPC defintion

Cargo.lock, ioxd_router/src/lib.rs, querier/src/database.rs, querier/src/namespace/test_util.rs, querier/src/table/test_util.rs, query_tests/src/scenarios/util.rs, router/benches/e2e.rs, router/benches/schema_validator.rs, router/src/namespace_cache/sharded_cache.rs, router/tests/http.rs, sharder/Cargo.toml, sharder/benches/sharder.rs, sharder/src/jumphash.rs
Bit of a tidy-up whilst working on the gRPC ShardService.
---
* refactor: infallible JumpHash initialisation (13e7b93c1)
This doesn't really need to be fallible but forces propagation of a ton of
error handling - no shards is always a sign of something being very wrong, and
can be caught in the caller if it's for some reason an acceptable state / can
be recovered from.
=> refactor: infallible JumpHash initialisation

ioxd_router/src/lib.rs, router/src/server.rs, router/src/server/grpc.rs, router/src/server/grpc/sharder.rs, sharder/src/jumphash.rs, sharder/src/trait.rs
This PR completes the implementation of a gRPC shard service for external clients to look up the mapping of `(table, namespace)` to a Kafka shard/partition/whatevs.
I used "shard" (instead of "partition"/etc) because of the impending [changes](https://github.com/influxdata/influxdb_iox/pull/5435).
---
* feat: impl Sharder<()> for JumpHash (baacc015d)
Implement a payload-less Sharder for the JumpHash concrete type. This models
the input the gRPC ShardService will provide.
* feat: ShardService gRPC endpoint handler (da31f3140)
Implements the ShardService to expose the shard mapping produced by routers to
external clients.
This impl uses an internal cache to eliminate unnecessary Catalog queries, as
the Kafka partition/Sequencer/Shard mapping is static once a router has
initialised.
* …
=> feat(router): sharding lookup gRPC service 

.guppy/hakari.toml, Cargo.lock, Cargo.toml, deny.toml, workspace-hack/Cargo.toml
Supersedes https://github.com/influxdata/influxdb_iox/pull/5486
---
* build: remove Azure SDK / bump object_store (c2f8efa03)
Bumps the object_store pin to master to pick up:
https://github.com/apache/arrow-rs/pull/2509
This removes the Azure SDK.
* ci: remove audit ignore for RUSTSEC-2022-0048 (227149e5b)
Now the Azure SDK is no longer a transitive dependency, we can remove this
audit override for xml-rs.
=> build: bump object_store

Cargo.lock
Bump dotenvy to the latest version - I fixed the cause of https://github.com/influxdata/influxdb_iox/issues/5454 which was a dependabot bump here https://github.com/influxdata/influxdb_iox/pull/5468.
@mkmik  added a regression test that remains in the code base and now passes: https://github.com/influxdata/influxdb_iox/pull/5461 (I added my own regression test to dotenvy itself in the fix PR: https://github.com/allan2/dotenvy/pull/16)
---
* build: bump dotenvy (dcc0f9d34)
I fixed this while waiting for my build to deploy. I think that says more
about our build than anything else!
=> build: bump dotenvy

.guppy/hakari.toml, Cargo.lock, Cargo.toml, deny.toml, workspace-hack/Cargo.toml
Revert https://github.com/influxdata/influxdb_iox/pull/5488 to try eliminate it as the cause.
---
* revert: remove audit ignore for RUSTSEC-2022-0048 (e752a707f)
This reverts commit 227149e5b6ba43e98d4271ad81aaaf37a1a3e6fb.
* revert: remove Azure SDK / bump object_store (66f0b59db)
This reverts commit c2f8efa03ae035316778552d7839690df2042e33.
=> revert: object store bump

compactor/src/parquet_file_combining.rs, parquet_file/src/serialize.rs, parquet_file/src/storage.rs, parquet_file/tests/metadata.rs
Fixes https://github.com/influxdata/conductor/issues/1121.
While this will stop the code from emitting the panic, it also means we won't notice opportunities to improve our compaction planning - there are a couple cases where we're using `SplitExec` knowing up front that it'll produce no output. We should try to improve our planning logic to eliminate those cases.
Lacking data to prove it, my conjecture is that the situation where this panic was unavoidable is exceedingly rare, and instead was caused by the (far more plausible) cases where we can avoid adding useless split points.
---
* refactor: raise error for no rows in parquet file (769826476)
Previously when attempting to serialise a stream of one or more RecordBatch
containing no rows (resulting in an empty file), the parquet …
=> fix: remove empty parquet panic

clap_blocks/src/ingester.rs, influxdb_iox/src/commands/run/all_in_one.rs, ingester/src/data.rs, ingester/src/handler.rs, ingester/src/lifecycle.rs, ingester/src/stream_handler/handler.rs, ioxd_ingester/src/lib.rs, query_tests/src/scenarios/util.rs
Restrict the number of rows in each partition before marking for persistence - defaulting to 500,000.
---
* feat(ingester): restrict partition row count (2a1960645)
This limit restricts a single partition to containing at most N rows before it
is marked for persistence (note: being marked for persistence does not
currently prevent further ingest for that partition.)
=> feat(ingester): restrict partition row count

clap_blocks/src/write_buffer.rs, ioxd_ingester/src/lib.rs, ioxd_router/src/lib.rs, write_buffer/src/config.rs, write_buffer/src/kafka/mod.rs
Not initialising producers for Kafka partitions we will never use will speed up ingester startup time, and reduce the request/connection load on the brokers.
---
* fix(ingester): connect to assigned Kafka partition (d1ca29c02)
During initialisation, the ingester connects to the Kafka brokers - this 
involves per-partition leadership discovery & connection establishment. These
connections are then retained for the lifetime of the process.
Prior to this commit, the ingester would establish a connection to all 
partition leaders for a given topic. After this commit, the ingester connects
to only the partition leaders it is going to consume from
(for those shards that it is assigned.)
=> fix(ingester): connect to assigned Kafka partitions

Cargo.lock, write_buffer/Cargo.toml, write_buffer/src/kafka/instrumentation.rs, write_buffer/src/kafka/mod.rs, write_buffer/src/kafka/record_aggregator.rs
This PR bumps rskakfa to HEAD, primarily to pick up:
* Perf changes in https://github.com/influxdata/rskafka/pull/173
* Switching to chrono for timestamps in https://github.com/influxdata/rskafka/pull/176
The former should change the latency profile of the routers, and the latter saves a lot of error-prone timestamp juggling :tada:
---
* build: bump rskafka (33b78eb5d)
Update rskafka to HEAD, picking up:
d7e14a8 test: increase timeouts, CircleCI is slow
4e92ed2 refactor: replace `time` w/ `chono`
c0ba668 fix: never leak flusher background tasks
786d6e1 refactor: move batch into producer mod
82862df perf: use RwLock for BroadcastOnce
e12c812 perf: async batch flushing & lock contention
ad126c5 test: increase timeouts
6565321 test: improve testing config
3379959 refactor: also invalidate …
=> perf: use rskafka producer optimisations

compactor/src/parquet_file_combining.rs, compactor/src/utils.rs
Closes https://github.com/influxdata/influxdb_iox/issues/5511
When computing split times for compaction output, it is assumed that data is dispersed evenly across the time range.  If large gaps exist between chunks, there may be time splits that have no chunks covering them.  This produces empty parquet files.  This PR checks the computed split times against the time ranges of the chunks to be included in the compaction.  If no chunks exist within the time range of split, the split is omitted.
It is still possible to have empty parquet files when chunks have large gaps within them, rather than between them.
=> fix: avoid splitting compaction output for time ranges with no chunks

README.md
Closes #
Since 0.11, Prost no longer bundles `protoc` (https://github.com/tokio-rs/prost/tree/v0.11.0#protoc)
=> docs: Update instructions for protoc install

influxdb2_client/examples/query.rs, influxdb2_client/src/api/query.rs, influxdb2_client/src/lib.rs
It's just plain text afaict.
Closes #5484.
So after actually getting a local influxdb 2.4 running and trying out queries that return data and queries that don't, I think the real problem is that we're trying to parse the response as JSON at all... 😳 
Looking at some of the other influxdb2 clients, it looks like the APIs that return the text without interpreting it at all are called `query_raw` rather than `query`, so I have another commit proposing to rename the function here... not sure if it'll break anything, but I doubt it as I don't think this ever worked 🤣 
@rkudryashov could you try out this branch and see if it works as you'd expect? Thanks!
=> fix: Don't try to parse /api/v2/query response as JSON

compactor/src/cold.rs, compactor/src/hot.rs, compactor/src/parquet_file_filtering.rs, data_types/src/lib.rs, iox_catalog/src/interface.rs, iox_catalog/src/lib.rs, iox_catalog/src/mem.rs, iox_catalog/src/postgres.rs, router/tests/http.rs
I swear I'm going somewhere with this, this is just the first step to some refactoring to improve code reuse, encapsulation, and testing of the compactor code.
`estimate_arrow_bytes_for_file` had the possibility of failing if the column type `i16` couldn't be converted to a `ColumnType` value. This really shouldn't be the case, as we're controlling what goes into and out of the database. And even if there is a failure, it should be at the database interaction level, not computing estimated memory usage.
sqlx can take care of the transformations between int and enum for us if we add `#[repr(i16)]` to `ColumnType` (the `column_type` column in postgres is `SMALLINT`, [which corresponds to Rust `i16`](https://docs.rs/sqlx/latest/sqlx/postgres/types/index.html)).
There's only one spot where …
=> fix: Use `ColumnType` as an enum in more places; make `estimate_arrow_bytes_for_file` infallible

ingester/src/data.rs, ingester/src/data/namespace.rs, ingester/src/data/partition.rs, ingester/src/data/partition/buffer.rs, ingester/src/data/table.rs, ingester/src/test_util.rs
A quick PR that moves the per-partition "max sequence number" onto the per-partition data structure, instead of being in the data/RecordBatch buffer within it 🧹 
---
* refactor: hoist persistence watermark from buffer (fc17f2ec2)
The maximum persisted sequence number is tracked to answer "up to where has
this partition been persisted", used for querying and skipping writes that
have already been applied (though I suspect this is redundant).
This is a property of the partition, not the actual data buffer, so this 
commit hoists it up out of the data buffer and onto the per-partition data
structure, internalising the field in the process (not pub).
=> refactor: hoist per-partition persistence watermark from buffer

data_types/src/lib.rs, import/src/aggregate_tsm_schema/update_catalog.rs, ingester/src/compact.rs, ingester/src/data.rs, iox_catalog/migrations/20220915085930_per-partition-persist-offset.sql, iox_catalog/src/interface.rs, iox_catalog/src/mem.rs, iox_catalog/src/metrics.rs, iox_catalog/src/postgres.rs
This PR adds a new field `persisted_sequence_number` to the `partitions` table in the catalog, and adds the necessary code for the ingesters to WRITE to it only.
The field in the DB is marked `NOT NULL` with a default of  `0`. Upon loading this offset, an ingester will replay writes in partitions that have already been persisted. This is tolerable by the system overall as it only creates (slightly) more work for the compactors, as this extra replay is **bounded by the shard minimum persist marker**, which means relatively little data would be duplicated.
Obviously new catalog instances / "the future" clusters will always have the value populated, and this minor replay is just for the currently live clusters.
However despite the above probably being absolutely fine, I intend to deploy this …
=> feat: store per partition persist markers

data_types/src/lib.rs, import/src/aggregate_tsm_schema/update_catalog.rs, ingester/src/compact.rs, ingester/src/data.rs, iox_catalog/migrations/20220915155941_nullable-partition-persist-offset.sql, iox_catalog/src/interface.rs, iox_catalog/src/mem.rs
0 is a valid sequence number (the first write) and it's therefore a valid persist marker: a parquet file could contain only the first write for a shard.
---
* refactor(db): NULLable persisted_sequence_number (8eebd1fb0)
Makes the partition.persisted_sequence_number column in the catalog DB 
NULLable. 0 is a valid persisted sequence number.
=> refactor(db): NULLable persisted_sequence_number

compactor/src/cold.rs, compactor/src/compact.rs, compactor/src/hot.rs, compactor/src/lib.rs, compactor/src/parquet_file.rs, compactor/src/parquet_file_combining.rs, compactor/src/parquet_file_filtering.rs, compactor/src/parquet_file_lookup.rs, iox_tests/src/util.rs
This is some more refactoring that I think clears up and separates some responsibilities:
- Estimating bytes is now done by the `PartitionCompactionCandidateWithInfo` because it keeps track of the column type counts.
- When `CompactorParquetFile`s are created, they give their number of rows to the partition and ask for their estimated bytes, then that gets carried with them.
- This makes it easier and clearer to test filtering based on the memory budget.
- The `FilteredFiles`' `FilterResult` now combines its data and its states, so that, for example, `NothingToCompact` doesn't need any data.
- There's a new type `ReadyToCompact` that gets created from a `FilterResult::Proceed` because the compaction after that point doesn't need to know about the memory budget at all.
I'm hoping to …
=> refactor: Clear up responsibilities of different parts of the compactor

ingester/src/data.rs, ingester/src/data/table.rs
This is the read-side change to use the per-partition persist markers added in https://github.com/influxdata/influxdb_iox/pull/5648 (described/tracked in https://github.com/influxdata/influxdb_iox/issues/5638).
This should significantly help https://github.com/influxdata/conductor/issues/971 for clusters that have been running more than a couple of weeks.
---
* perf: O(1) partition persist mark discovery (2b8985071)
Changes the ingest code path to eliminate scanning the parquet_files table to
discover the last persisted offset per partition, instead utilising the new
persisted_sequence_number field on the Partition itself to read the same
value.
This lookup blocks ingest for the shard, so removing the expensive query from
the ingest hot path should improve catch-up time after a …
=> perf: O(1) partition persist mark discovery

ingester/src/data.rs, ingester/src/data/namespace.rs, ingester/src/data/partition.rs, ingester/src/data/partition/buffer.rs, ingester/src/data/shard.rs, ingester/src/data/table.rs, ingester/src/handler.rs, ingester/src/querier_handler.rs, ingester/src/query.rs, ingester/src/test_util.rs, query_tests/src/scenarios/util.rs
All this PR does is change a function like this:
```rust
partition_data.snapshot_to_persisting_batch(
partition_info.partition.shard_id,
partition_info.partition.table_id,
partition_info.partition.id,
&partition_info.table_name,
)
```
which has a risk of being passed the wrong thing, instead removing the redundant args (a partition should know it's own ID):
```rust
partition_data.snapshot_to_persisting_batch()
```
It replicates the same pattern where necessary for the shard, namespace, table & partition.
There catalog could be pulled out of fn args in a similar way, but I have grander plans for it that will help simplify testing so it can live there for a bit longer.
---
* refactor: snapshot_to_persisting redundant ID (85d6efafe)
Partition::snapshot_to_persisting() passes the ID of the …
=> refactor(ingester): remove redundant fn args

compactor/src/cold.rs, compactor/src/hot.rs, compactor/src/lib.rs, compactor/src/parquet_file_combining.rs, compactor/src/parquet_file_filtering.rs, compactor/src/parquet_file_lookup.rs, compactor/src/query.rs, compactor/src/utils.rs, data_types/src/lib.rs
This PR re-enables full compaction by making `filter_parquet_files` more general to handle either level 0 -> level 1 compaction or level 1 -> level 2 compaction.
This implementation of full compaction is more similar to the other compaction procedures in that it will only limit groups based on the estimated arrow bytes memory budget code (it does not use `max_desired_file_size_bytes`). It differs from the other compaction procedures in that it doesn't split the output files based on `split_percentage`; it will always create one level 2 file per group.
I don't think we actually need to limit the group sizes using `max_desired_file_size_bytes` too, because:
- The estimated arrow bytes are a function of the columns and rows
- The file sizes are also a function of the column and rows
- The …
=> feat: Re-enable full compaction to level 2, limited by the memory budget

Cargo.lock, compactor/src/cold.rs, compactor/src/compact.rs, compactor/src/garbage_collector.rs, compactor/src/hot.rs, data_types/Cargo.toml, data_types/src/lib.rs, garbage_collector/src/parquetfile/deleter.rs, iox_catalog/src/interface.rs, iox_catalog/src/mem.rs, iox_catalog/src/postgres.rs, iox_tests/src/util.rs, iox_time/src/lib.rs, parquet_file/src/metadata.rs
There are a bunch of places this sort of math is done in the compactor and catalog, and rather than copy-pasting this everywhere, it can be a method on `TimeProvider`.
=> refactor: Add helper methods for computing times to TimeProvider

ingester/src/data/namespace.rs, ingester/src/data/partition.rs, ingester/src/data/partition/buffer.rs, ingester/src/data/shard.rs, ingester/src/data/table.rs, ingester/src/querier_handler.rs, ingester/src/test_util.rs
This is the change needed to unblock #5658, described [here](https://github.com/influxdata/influxdb_iox/pull/5658#issuecomment-1249464240) as:
> The failing tests construct every bit of ingester state from the bottom up - it populates each buffer, partition, table, namespace and shard and is therefore very tightly coupled with the current code - it makes a lot of assumptions about how the ingester works internally, rather than driving the ingester and asserting on the result.
> 
> I am untangling these tests - instead of setting the various bits of state to reflect what the test **believes** should be the state after buffering a write/delete, I am instead writing the test to simply buffer the writes/deletes through the ingester using the same code paths as actual writes/deletes and **test …
=> test: refactor ingester query tests

cache_system/src/backend/policy/lru.rs, cache_system/src/backend/policy/mod.rs, cache_system/src/backend/policy/refresh.rs, cache_system/src/backend/policy/ttl.rs
Policy subscribers basically never store `V` (the cached value), so we should not clone that one unconditionally. But even `K` (the cache key) is not stored in all cases. So let's pass a reference for both and let the policies decide if they wanna clone the data or not.
=> refactor: avoid clones for `policy::Subscriber::set`

ingester/src/compact.rs, ingester/src/data.rs, ingester/src/data/namespace.rs, ingester/src/data/partition.rs, ingester/src/data/partition/buffer.rs, ingester/src/data/query_dedup.rs, ingester/src/data/shard.rs, ingester/src/data/table.rs, ingester/src/handler.rs, ingester/src/lib.rs, ingester/src/lifecycle.rs, ingester/src/query.rs, ingester/src/stream_handler/handler.rs, ingester/src/stream_handler/mod.rs, ingester/src/stream_handler/periodic_watermark_fetcher.rs, ingester/src/stream_handler/sink_adaptor.rs, ingester/src/stream_handler/sink_instrumentation.rs, ingester/src/test_util.rs, query_tests/src/scenarios/util.rs
**This PR has no functional changes**.
The only real code change is in de0be877b, where the `ShardData` initialisation is DRYed and internalised - this allows the `ShardData` (an internal data structure) to be non-pub.
The following commit 72e02ee9e capitalises on this reduced scope which cascades through the lower tiers of the buffer tree, marking child/related structures as also non-pub, which in turn highlighted various bits of dead code. I also got some drive-by non-pub :tada:
---
* refactor: internalise ShardData init (72e02ee9e)
Move the initialisation of ShardData (an internal ingester data structure)
into the ingester itself.
Previously callers would initialise the ingester state, and pass it into the
IngesterData constructor.
* refactor(ingester): limit visibility (de0be877b) …
=> refactor(ingester): limit visibility of internals

iox_catalog/src/interface.rs, iox_catalog/src/mem.rs, iox_catalog/src/metrics.rs, iox_catalog/src/postgres.rs
Discovering the most recently created partitions can be used as a proxy for partitions that are currently hot for writes - those that were just created, are likely being wrote to. 
Using a proxy / this query is very cheap:
```
QUERY PLAN
----------------------------------------------------------------------------------------------------------
Limit  (cost=0.42..79.61 rows=10 width=116)
->  Index Scan Backward using partition_pkey on partition  (cost=0.42..302094.18 rows=38150 width=116)
Filter: (shard_id = ANY ('{0,1,2,3,4,5}'::bigint[]))
```
This can be used to identify which partitions to pre-load into an ingester at startup, ref #5638.
---
* feat(catalog): most recent N partitions (c3cd31a83)
Adds a Partition::most_recent_n() method to the catalog interface, returning
the N most recent …
=> feat(catalog): most recent N partitions

ingester/src/handler.rs, ingester/src/stream_handler/handler.rs, write_buffer/src/core.rs, write_buffer/src/file.rs, write_buffer/src/kafka/mod.rs, write_buffer/src/mock.rs
Fixes a panic:
```
thread 'tokio-runtime-workerthread 'tokio-runtime-worker' panicked at '' panicked at 'Shard Index ShardIndex(23) stream for topic iox-shared has a high watermark BEFORE the sequence number we want. This is either a bug (see https://github.com/influxdata/rskafka/issues/147 for example) or means that someone re-created the shard and data is lost. In both cases, it's better to panic than to try something clever.Shard Index ShardIndex(16) stream for topic iox-shared has a high watermark BEFORE the sequence number we want. This is either a bug (see https://github.com/influxdata/rskafka/issues/147 for example) or means that someone re-created the shard and data is lost. In both cases, it's better to panic than to try something clever.', ', …
```
=> fix(write_buffer): spurious watermark < read offset panic

data_types/src/lib.rs, ingester/src/data.rs, ingester/src/data/namespace.rs, ingester/src/data/partition.rs, ingester/src/data/partition/resolver/cache.rs, ingester/src/data/partition/resolver/catalog.rs, ingester/src/data/partition/resolver/mock.rs, ingester/src/data/partition/resolver/mod.rs, ingester/src/data/partition/resolver/trait.rs, ingester/src/data/shard.rs, ingester/src/handler.rs, ingester/src/test_util.rs, query_tests/src/scenarios/util.rs
This should deliver a decent improvement to ingester catchup time after a deployment (https://github.com/influxdata/conductor/issues/971) and eliminate a whole lotta catalog load :tada:
Closes https://github.com/influxdata/influxdb_iox/issues/5638.
---
* test: simplify partition provider mock (38ebd5fb2)
Removes redundant fields from the MockPartitionProvider.
* refactor(ingester): server-wide PartitionProvider (a3d6e7a45)
Lifts the PartitionProvider initialisation higher in the stack to a point
where a single instance can be used across all shards an ingester manages.
This is a pre-requisite for sharing a cache of Partitions across all shards.
* perf(ingester): cache Partition (2068ff394)
This commit implements a PartitionCache decorator over the PartitionProvider
abstraction.
When an …
=> perf(ingester): partition ID + persist marker cache

influxdb_iox/src/commands/compactor/generate.rs
Connects to https://github.com/influxdata/conductor/issues/1169.
Builds on https://github.com/influxdata/influxdb_iox/pull/5729.
- The `--num-rows` argument will now control how many rows end up in each line protocol file.
- When `--compaction-type hot` is specified (or if `--compaction-type` isn't specified, because hot is the default), the files will have data from about the last 30 minutes until now, and the data in each file will overlap its adjacent files' data by a minute on either side.
- When `--compaction-type cold` is specified, the files will have data from 24 hours ago to 8 hours ago, and the data in the files will NOT overlap their adjacent files' data.
These pieces will be coming in future PRs:
- Actually generating files for `--num-partitions` specified
- Writing parquet …
=> feat: Generate the requested num rows and compaction type

data_types/src/lib.rs, ingester/src/data/partition.rs, ingester/src/data/partition/resolver/cache.rs, ingester/src/data/partition/resolver/catalog.rs, ingester/src/data/partition/resolver/trait.rs
Change the `PartitionData` buffer structure so that it carries the `PartitionKey` derived for it to avoid having to resolve it later.
As an added bonus, these `PartitionKey` strings will be shared across many tables when read from the cache via ref counting rather than copying :tada:
Relates to #5767 - this is a stepping stone towards removing a bunch of queries.
---
* refactor: PartitionData carries PartitionKey (f5a7fbf8e)
Changes the PartitionData to carry the derived PartitionKey for which it is
buffering ops for. This is used at persist time.
=> refactor: PartitionData carries PartitionKey

Cargo.lock, influxdb_iox/src/commands/compactor/generate.rs, influxdb_iox/tests/end_to_end_cases/compactor.rs, iox_data_generator/Cargo.toml, iox_data_generator/benches/point_generation.rs, iox_data_generator/src/agent.rs, iox_data_generator/src/bin/iox_data_generator.rs, iox_data_generator/src/lib.rs, iox_data_generator/src/specification.rs, iox_data_generator/src/write.rs, iox_tests/src/util.rs, parquet_file/src/metadata.rs, parquet_to_line_protocol/src/lib.rs
Connects to https://github.com/influxdata/conductor/issues/1169.
I changed my mind about how `compactor generate` will work; rather than generating line protocol files then converting them to Parquet files, we gave the data generator the ability to output Parquet files.
This only generates the files and does *not* import them into a catalog yet. The `IoxMetadata` put into the file is just placeholders, with the expectation that the code that will import the Parquet files into the catalog will ignore the `IoxMetadata` in the file and will instead generate the appropriate values based on where those files will go in the catalog.
Now, when you run `cargo run -- compactor generate`, rather than a directory of line protocol files, there will be a directory of Parquet files.
These pieces will …
=> feat: Generate parquet files instead of line protocol

ingester/src/data/partition/resolver/cache.rs, ingester/src/data/partition/resolver/mock.rs, ingester/src/data/partition/resolver/trait.rs, ingester/src/lifecycle.rs, ingester/src/lifecycle/mock_handle.rs, ingester/src/test_util.rs, query_tests/src/scenarios/util.rs
Clean up a bit of ingester test helpers before the next series of PRs that make use of them.
---
* test: shared mock LifecycleHandle impl (f0885612e)
Moves the NoopLifecycleHandle to the Ingester's test_utils to share it across
multiple components.
* test: re-use test_utils::make_op (fc47f6ab8)
Share the make_op helper across all tests in the Ingester.
* test: share populate_catalog() across tests (c33499764)
Parametrises test_util::populate_catalog() and exports for re-use in ingester
tests.
* test: simplify PartitionProvider mock (7dd28f423)
The PartitionKey is now part of the PartitionData, so there is no need to
specify the redundant ID when configuring the mock.
=> test: refactor ingester helpers

ingester/src/data/table.rs, ingester/src/lifecycle/mock_handle.rs, query_tests/src/scenarios/util.rs
A quick fix for the op buffering / memory tracking where a write was recorded in the memory tracker before being applied. Because applying the op is fallible, this could lead to writes being recorded as applied, but not actually applied, and thus slowly draining the ingester of usable memory budget.
I don't think this has ever been hit, but it is in the area I'm working on today and was a quick fix 🚀 
---
* test: MockLifecycleHandle captures calls (20451921d)
Changes the NoopLifecycleHandle to MockLifecycleCall, and adds code causing it
to log all calls made to the log_write() method.
This will allow tests to assert calls and their values in DML buffering tests.
* fix: spurious memory accounting for failed write (b23ad3171)
Fixes a case where the ingester may incorrectly record a write as …
=> fix(ingester): incorrect memory tracking of failed writes

ingester/src/compact.rs, ingester/src/data.rs, ingester/src/data/namespace.rs, ingester/src/data/partition.rs, ingester/src/data/partition/resolver/cache.rs, ingester/src/data/partition/resolver/trait.rs, ingester/src/data/shard.rs, ingester/src/data/table.rs, ingester/src/lifecycle.rs, query_tests/src/scenarios/util.rs
This PR accomplishes two things:
* Makes all the ID lookup queries at `persist()` time redundant, with the exception of acquiring the `SortKey`. In a follow-up PR I will remove this requirement and significantly reduce the query load at persist time (part of #5767).
* Changes the buffer tree nodes (shards -> namespaces -> tables -> partitions) to support being addressed by ID, in addition to string names. This enables the above, but is also in preparation for #4880.
There will be a slight memory overhead for maintaining the additional ID indexes, but I've been careful to minimise the amount of memory these will use (through use of existing Arc's, storing ref-counted keys and making two lookups in the cold ID path, etc).
This also documents a TOCTOU bug tracking the memory usage of …
=> refactor: reference buffer tree nodes by ID

ingester/src/data.rs, ingester/src/data/namespace.rs, ingester/src/data/shard.rs, ingester/src/handler.rs, ingester/src/querier_handler.rs, ingester/src/test_util.rs
This PR embeds the name of the namespace in the `NamespaceData`, using a ref-counted type wrapper (`NamespaceName`) for type safety (aka getting the compiler to do the work for me).
---
* refactor: carry namespace name in NamespaceData (abb9122e2)
Changes the ingester's NamespaceData to carry a ref-counted string
identifier as well as the ID.
The backing storage for the name in NamespaceData is shared with the
index map in ShardData, so it is effectively free!
=> refactor: carry namespace name in NamespaceData

ingester/src/data.rs, ingester/src/data/namespace.rs, ingester/src/data/partition.rs, ingester/src/data/partition/buffer.rs, ingester/src/data/partition/resolver/cache.rs, ingester/src/data/partition/resolver/catalog.rs, ingester/src/data/partition/resolver/mock.rs, ingester/src/data/partition/resolver/trait.rs, ingester/src/data/table.rs, ingester/src/handler.rs, ingester/src/querier_handler.rs, ingester/src/query.rs, ingester/src/test_util.rs
A quick dev life change - use a typed table name, rather than passing around a string.
This reflects the `NamespaceName` equivalent.
---
* refactor: use TableName, not Arc<str> (97c6e0f8c)
Adds a type wrapper TableName, internally an Arc<str> to leverage the
type system instead of passing around untyped strings.
=> refactor: use TableName, not Arc<str>

ingester/src/data/namespace.rs, iox_catalog/src/interface.rs, iox_catalog/src/mem.rs, iox_catalog/src/metrics.rs, iox_catalog/src/postgres.rs
Resolving a table name -> table ID happens in the ingest hot path (once per table, when the first op for it is observed).
After the recent changes (#5807) this can now be a cheaper indexed query with no JOIN, which should improve the ingest rate immediately after startup ("recovery rate"). 
Ultimately I intend to remove this query entirely.
---
* perf(ingester): cheaper table discovery (15e153a74)
This commit changes the table ID lookup query from an expensive,
JOIN multi-query to a simple, single table, indexed lookup.
As this is on the hot path, this should help with the recovery rate of
the ingesters.
* refactor: remove Table::get_table_persist_info() (3e1e4c1f0)
Remove the now-redundant get_table_persist_info() implementations.
=> perf(ingester): cheapen table lookup

ingester/src/stream_handler/handler.rs
This should make correlating op outcomes easier.
---
* refactor: include sequence numbers in apply() logs (dbcbb5b82)
Include the op sequence number in the error/success apply() log
messages.
=> refactor: include sequence numbers in apply() logs

data_types/src/lib.rs, ingester/src/compact.rs, ingester/src/data.rs, ingester/src/data/namespace.rs, ingester/src/data/partition.rs, ingester/src/data/partition/resolver/cache.rs, ingester/src/data/partition/resolver/catalog.rs, ingester/src/data/partition/resolver/mock.rs, ingester/src/data/partition/resolver/trait.rs, ingester/src/data/table.rs, ingester/src/test_util.rs, iox_catalog/src/interface.rs, iox_catalog/src/mem.rs, iox_catalog/src/metrics.rs, iox_catalog/src/postgres.rs
This PR reduces the number of catalog queries needed at `persist()` time by a third.
Closes #5767.
---
* refactor: use deferred sort key loading (10d77b0ef)
Changes the persist() implementation in the ingester to load the sort
key using the deferred loading mechanism, instead of on-demand.
* perf(ingester): remove persist lookup queries (e55667719)
Removes the catalog queries previously used to look up various
information about the partition/table/namespace that was already in
memory.
As part of this change, the compaction helper function is changed to
accept the inputs it needs, rather than a struct of data from the
catalog - this significantly simplifies testing.
This commit also adds additional context to all log messages in the
persist() fn.
* refactor: defer querying for table schema …
=> perf(ingester): reduce catalog queries during persist()

compactor/src/cold.rs
Connects to https://github.com/influxdata/influxdb_iox/issues/5836.
@NGA-TRAN as far as I can tell, the code is already doing the two items listed in #5836: 
1. If there is only one L1 file in a group because by itself it takes up the memory budget, upgrade its level to L2 without running compaction
2. Limit the L1 files chosen as input to a compaction round if their memory budget is greater than the limit
I've added tests to verify these, am I missing something or misunderstanding the issue description?
=> test: Add verification that aspects of L1 -> L2 compaction are working as expected

iox_catalog/migrations/20221014122742_lower-default-per-table-column-limit.sql, iox_catalog/src/interface.rs, iox_catalog/src/lib.rs, iox_catalog/src/mem.rs, iox_catalog/src/postgres.rs, router/src/dml_handlers/ns_autocreation.rs
This PR changes the default value for the per-column service limit from 1,000 to 200.
**This change only affects new namespaces / org&buckets**.
It also beefs up some of the testing to make sure the code + database default stays in sync.
Closes #5858.
---
* refactor: reduce default column limit (46bbee542)
Reduces the default number of columns allowed per-table, from 1,000 to
200.
* test: assert default service limit values (e4179605d)
Adds tests that assert the default service limit values.
=> refactor(iox_catalog): reduce default column limit

router/src/server/http.rs, router/tests/http.rs
Does what it says on the tin.
Closes https://github.com/influxdata/influxdb_iox/issues/5861.
---
* refactor: return HTTP 400 for service limits (895ac97d7)
Changes the HTTP response code from 429 to 400 for requests that exceed
a service protection limit (table count, per-table column count).
=> refactor: return HTTP 400 for service limits

ingester/src/stream_handler/handler.rs
Closes #5878.
---
* refactor: use histogram to record TTBR (c63312ce1)
Changes the TTBR metric from a gauge to a histogram so that observations
maintain a time dimension.
=> refactor: use histogram to record TTBR

ingester/src/handler.rs, ingester/src/lifecycle.rs, ingester/src/querier_handler.rs, ingester/src/stream_handler/handler.rs, ingester/tests/common/mod.rs, ingester/tests/write.rs
This PR serves three purposes:
* Create a reusable, easy-to-use test harness for ingester integration tests that allows easy writing and querying of data, and asserting of alert-able metrics so that adding new tests is low-friction - the easier they are to write, the more that will be wrote!
* Add sufficient tests to guard against any breakage in upcoming PRs that significantly refactors the way data is buffered/snapshot'ed and bubbled up to queries by driving all external APIs.
* Replace some tests that are very tightly coupled to how data is currently stored in the ingester, which will change with the above referenced PRs anyway.
---
* refactor: impl converting IngesterQueryResponse (d0b546109)
An existing function to map the complex IngesterQueryResponse type to a
simple set of …
=> test: ingester integration tests

ingester/src/data/partition/buffer/always_some.rs, ingester/src/data/partition/buffer/mutable_buffer.rs, ingester/src/data/partition/buffer/state_machine.rs, ingester/src/data/partition/buffer/state_machine/buffering.rs, ingester/src/data/partition/buffer/state_machine/buffering_with_snapshot.rs, ingester/src/data/partition/buffer/state_machine/persisting.rs, ingester/src/data/partition/buffer/state_machine/snapshot.rs, ingester/src/data/partition/buffer/traits.rs, ingester/src/data/sequence_range.rs
**This PR adds code that isn't used yet.** A follow-up PR will stitch it in to minimise the PR size.
---
This PR aims to set the stage to replace the implicit state machine used to buffer writes in a partition, with the code in this PR.
The aim is to create an implementation that has a lower complexity burden for callers, and is easier/quicker to optimise & build additional functionality on top of.
When this is actually used (next PR) ~this will fix #5805 to decrease query latency~ (see comments below), and provides a clear path forwards for improved memory tracking in the ingester (to fix bugs such as #5872 and #5777).
---
* feat(ingester): partition buffer state machine (fbd262dd2)
This commit introduces code that is intended to replace the current
implicit state machine used by …
=> feat(ingester): partition buffer state machine

docs/compactor.md
Closes https://github.com/influxdata/influxdb_iox/issues/5894.
Plus some cleanups because my brain is broken and notices inconsequential things like double spaces and then can't un-see them 🙃
=> docs: Add skipped-compaction CLI to the compactor documentation

influxdb_iox/src/commands/debug/skipped_compactions.rs
@NGA-TRAN just sent me some production output from the new skipped-compactions command and... I forgot that `skipped_at` hasn't been put through line protocol/etc and therefore is [postgres epoch seconds](https://github.com/influxdata/influxdb_iox/blob/95853aed1a0955e580fc9b96debc940c7eaf3e56/iox_catalog/src/postgres.rs#L1257) rather than nanoseconds 🤦🏻‍♀️ This should bring all the dates displayed back to the present day 😜
=> fix: Compactor skipped_at is in seconds, not nanoseconds oops

generated_types/protos/influxdata/iox/catalog/v1/service.proto, influxdb_iox/src/commands/remote.rs, influxdb_iox/src/commands/remote/store.rs, influxdb_iox/tests/end_to_end_cases/cli.rs, influxdb_iox/tests/end_to_end_cases/mod.rs, influxdb_iox/tests/end_to_end_cases/remote.rs, influxdb_iox_client/src/client/catalog.rs, service_grpc_catalog/src/lib.rs
Connects to https://github.com/influxdata/influxdb_iox/issues/5967.
This PR adds the new command `influxdb_iox remote store get-table <DATABASE> <TABLE>` that will fetch all Parquet files for the specified database's table to the local filesystem.
I tested this out by running a local all-in-one server, which has http://localhost:8081 as the router gRPC port. I set `INFLUXDB_IOX_PERSIST_PARTITION_AGE_THRESHOLD_SECONDS=10` to get lots of Parquet files.  I wrote some data into the database `test_db`, table `disk`. Then I ran:
```
influxdb_iox -h http://localhost:8081 remote store get-table test_db disk
```
and I saw this output:
```
found 2 Parquet files, downloading...
downloading file 1 of 2 (a1fb45f9-d04f-4aa1-a058-0a75c846264c.parquet)...
downloading file 2 of 2 …
```
=> feat: MVP of remote store get-table command

generated_types/protos/influxdata/iox/catalog/v1/service.proto, influxdb_iox/src/commands/remote.rs, influxdb_iox/src/commands/remote/store.rs, influxdb_iox/tests/end_to_end_cases/remote.rs, influxdb_iox_client/src/client/catalog.rs, influxdb_iox_client/src/client/error.rs, service_grpc_catalog/src/lib.rs
Connects to https://github.com/influxdata/influxdb_iox/issues/5967
This PR implements 2 of the bonus points:
And [feedback from the previous PR](https://github.com/influxdata/influxdb_iox/pull/5984#discussion_r1006216160), at least for the code that I just added (the rest of the codebase I'll save for later): 
I also made what I think are improvements to some error message displays:
Before this change, if the namespace specified wasn't found, the error message would be:
```
Error in the store subcommand: Client error: Some requested entity was not found: Namespace nacho-namespace 
not found
```
Which is:
- Unhelpful, I know I ran the `store` subcommand
- Confusing, am I the client? (no) Does "Client error" mean I did something wrong? (also no)
- Repetitive, why tell me something wasn't …
=> feat: Some bonus features for `remote store get-table`

ioxd_router/src/lib.rs, router/benches/e2e.rs, router/benches/schema_validator.rs, router/src/dml_handlers/chain.rs, router/src/dml_handlers/fan_out.rs, router/src/dml_handlers/instrumentation.rs, router/src/dml_handlers/mock.rs, router/src/dml_handlers/mod.rs, router/src/dml_handlers/nop.rs, router/src/dml_handlers/ns_autocreation.rs, router/src/dml_handlers/partitioner.rs, router/src/dml_handlers/schema_validation.rs, router/src/dml_handlers/sharded_write_buffer.rs, router/src/dml_handlers/trait.rs, router/src/dml_handlers/write_summary.rs, router/src/lib.rs, router/src/namespace_cache.rs, router/src/namespace_cache/memory.rs, router/src/namespace_cache/metrics.rs, router/src/namespace_cache/sharded_cache.rs, router/src/namespace_resolver.rs, router/src/namespace_resolver/mock.rs, router/src/namespace_resolver/ns_autocreation.rs, router/src/server.rs, router/src/server/grpc.rs, router/src/server/grpc/sharder.rs, router/src/server/http.rs, router/src/shard.rs, router/tests/http.rs
The first in a series of PRs to push namespace + table IDs over Kafka (#4880).
This PR changes the router to propagate the `NamespaceId` through the request handlers, so it is available when serialising the DML operation into the Kafka wire format.
---
* style: format imports (0c5eb3f70)
Re-order and re-format the imports so that they follow a consistent
pattern.
This helps eliminate conflicts due to imports.
* refactor: resolve namespace before DML dispatch (d166de931)
This commit introduces a new (composable) trait; a NamespaceResolver is
an abstraction responsible for taking a string namespace from a user
request, and mapping to it's catalog ID.
This allows the NamespaceId to be injected through the DmlHandler chain
in addition to the namespace name.
As part of this change, the …
=> refactor(router): pass NamespaceId through handler stack

ioxd_router/src/lib.rs, router/src/dml_handlers/partitioner.rs, router/src/dml_handlers/schema_validation.rs, router/src/dml_handlers/sharded_write_buffer.rs, router/src/server/http.rs, router/tests/http.rs
One of a series of PRs to push namespace + table IDs over Kafka (#4880).
This PR changes the router to propagate the `TableId` through the request handlers, so it is available when serialising the DML operation into the Kafka wire format.
---
* refactor(router): pass TableId through DmlHandlers (80e88a77c)
Changes the DML handler transformers to pass through the TableId once it
has been resolved during schema validation.
This value is collated by shard, and then unused. This collated TableId
map will be used in a follow-up PR.
* perf(router): remove routing indirection (c27e3ff32)
Removes an unnecessary Arc pointer indirection for routing to the HTTP
handler delegate.
=> refactor(router): pass TableId through handler stack

Cargo.lock, dml/src/lib.rs, generated_types/protos/influxdata/pbdata/v1/influxdb_pb_data_protocol.proto, ingester/Cargo.toml, ingester/src/data.rs, ingester/src/handler.rs, ingester/src/stream_handler/handler.rs, ingester/src/stream_handler/sink_instrumentation.rs, ingester/src/test_util.rs, ingester/tests/common/mod.rs, mutable_batch_pb/src/decode.rs, mutable_batch_pb/src/encode.rs, mutable_batch_pb/tests/encode.rs, mutable_batch_tests/Cargo.toml, mutable_batch_tests/benches/write_pb.rs, query_tests/src/scenarios/util.rs, router/src/dml_handlers/sharded_write_buffer.rs, write_buffer/src/codec.rs, write_buffer/src/core.rs, write_buffer/src/kafka/mod.rs, write_buffer/src/kafka/record_aggregator.rs, write_buffer/src/mock.rs
This PR changes the router -> ingester write protocol message format to include the IDs of the table & namespaces for the write, as part of https://github.com/influxdata/influxdb_iox/issues/4880.
Note that this commit only **pushes the IDs on the sender-side** and the consumer **does not make use of them**. This will allow us a transition period where messages will contain both the names, and their IDs (see various large and shouty code comments).
In a follow-up PR I will remove the extra map added to the `DmlWrite` in this PR when switching the consumer to use IDs, so the size inflation is temporary.
---
* refactor(write_buffer): pass IDs in wire format (ddd6ab0ba)
This commit is part of a two-part change in order to add the table &
namespace IDs to the write buffer wire format. This …
=> refactor(write_buffer): pass IDs in wire format

predicate/src/delete_expr.rs
This lint upsets me (and my IDE).
---
* refactor: disable large variant lint (eb603bfb5)
The DataFusionToExprError::UnsupportedOperants variant contains twice as
many Expr to the second biggest variant. This is of a sufficient size
difference to cause a lint warning.
=> refactor: disable large variant lint

ingester/src/arcmap.rs, ingester/src/lib.rs
This is a helper type to DRY the frequent exactly-once initialisation of concurrency-safe map entries within the ingester, with an emphasis on minimising lock time.
It also contains some methods that are not currently used, because it's from "the future" (an ongoing branch for future PR-ing).
---
* feat: add ArcMap map type (17890a990)
Implements a map of K -> Arc<V> with exactly-once initialisation
semantics.
This map can be used to ensure a given key maps to singleton instances
of V; exactly what all the nodes in the ingester "buffer tree" of shard
-> namespace -> table -> partition require.
This impl contains unused funcs (silenced with an allow(dead_code)) due
to it being picked from a future branch.
=> feat: add ArcMap map type

write_buffer/src/config.rs, write_buffer/src/kafka/mod.rs
When Kafka type is selected in WriteBuffer, we expect to be able to configure multiple bootstrap_broker server.
=> feat: support multiple bootstrap_broker server config

dml/src/lib.rs, generated_types/protos/influxdata/iox/delete/v1/service.proto, influxdb_iox_client/src/client/delete.rs, ingester/src/data.rs, ingester/src/stream_handler/handler.rs, query_tests/src/scenarios/util.rs, router/src/dml_handlers/sharded_write_buffer.rs, router/tests/http.rs, write_buffer/src/codec.rs, write_buffer/src/kafka/mod.rs
This is the delete counterpart to #6036, part of https://github.com/influxdata/influxdb_iox/issues/4880.
---
* feat: NamespaceId in DmlDelete (6fa48731a)
Changes the DmlDelete to contain the NamespaceId for which it should be
applied, propagating this value over the wire.
Like the existing IDs within the DmlWrite, these values are marked
unsafe to use due to avoid the consumers utilising them accidentally
during deployment. Unlike DmlWrite, the DmlDelete is completely unused,
so this is less of an issue.
* test(router): assert DmlHandler ID propagation (906645c5b)
Adds an integration test asserting that the NamespaceId and Table IDs
are propagated through the router.
=> refactor(write_buffer): propagate NamespaceId across Kafka boundary for DML deletes

ingester/src/data.rs, ingester/src/data/namespace.rs, ingester/src/data/partition.rs, ingester/src/data/table.rs, ingester/src/querier_handler.rs
Prior to this PR there was a per-table mutex that serialised operations across all the partitions within it. 
This change pushes the mutex down into the partitions themselves, therefore increasing intra-table query parallelism in the presence of multiple partitions, and reduces the contention for the write path due to various persist-time operations on individual partitions.
Closes https://github.com/influxdata/influxdb_iox/issues/5725.
---
* refactor: push down per-partition op skipping (425fd46de)
This moves the logic that skips operations that do not need to be
applied to a partition during shard replay from the table level, to the
partition level.
* perf(ingester): granular per-partition locking (79d24fa35)
This commit pushes the existing table-level mutex down to the partition.
This …
=> perf(ingester): granular per-partition locking

ingester/src/data.rs, ingester/src/data/namespace.rs, ingester/src/data/partition.rs, ingester/src/data/table.rs, ingester/src/querier_handler.rs
There have been panics in the ingesters:
`Thread panic" panic_info="panicked at 'partition 13702863 in table 72 in namespace 75 not in shard 156 state'`
The timing suggests #6068 may be the culprit.
---
* revert: granular per-partition locking (7ac0857a2)
This reverts commit 79d24fa350a3d83ec7ee311e5de04858ad330a6d.
* revert: push down per-partition op skipping (fbd25a06d)
This reverts commit 425fd46def52b9e858b5a9f96b9d28559154ad1e.
=> revert: granular locking

ingester/src/arcmap.rs
This PR fixes an issue with the `ArcMap` that caused an `insert()` in one thread to not be visible in another thread because different thread-local hasher instances were being used.
Also included is a small refactor to DRY the key checking, and avoid cloning a key when calling `insert()` that I noticed while working on this.
---
* test: cross-thread hashmap entry visibility (e9bda70c7)
At the time of this commit, this test fails. Performing a get() on a key
previously inserted by another thread should not fail.
* fix: cross-thread map entry visibility (1fb9cfba8)
This commit changes the ArcMap HashBuilder to use the same instance as
the underlying HashMap hasher.
This prevents divergent hashing across threads that MAY initialise a
hasher with a different seed.
* refactor: extract key …
=> fix: cross-thread ArcMap::get()

ingester/src/data.rs, ingester/src/data/namespace.rs, ingester/src/data/partition.rs, ingester/src/data/table.rs, ingester/src/querier_handler.rs
This PR contains the exact same code changes as what was in #6068, which was subsequently reverted by #6083 due to a problem with the ArcMap which was resolved in #6086.
**TL;DR**: 
---
* refactor: push down per-partition op skipping (b8181119e)
This moves the logic that skips operations that do not need to be
applied to a partition during shard replay from the table level, to the
partition level.
* perf(ingester): granular per-partition locking (b73d07c22)
This commit pushes the existing table-level mutex down to the partition.
This allows the ingester to gather data from multiple partitions within
a single table in parallel, and reduces contention between ingest/query
workloads.
=> perf(ingester): mutex pushdown

dml/src/lib.rs, ingester/src/data.rs, ingester/src/data/namespace.rs, ingester/src/data/shard.rs, ingester/src/data/table.rs, ingester/src/querier_handler.rs, ingester/src/test_util.rs, mutable_batch_pb/src/decode.rs, mutable_batch_pb/src/encode.rs, router/tests/http.rs, write_buffer/src/codec.rs
This PR makes use of the namespace & table IDs that are sent over the wire by the router since #6036, allowing the ingester to eliminate the namespace & table queries in the hot path 🎉 
As an added bonus, this fixes potential data loss in the ingester due to lack of retries on these queries (https://github.com/influxdata/influxdb_iox/issues/5008), and also simplifies testing.
This should make a large difference in catalog load during deployments & cluster bootstrapping, as well as speed up the ingester recovery rate (https://github.com/influxdata/conductor/issues/971).
---
* feat: table/namespace IDs in write protocol (f46df5bb5)
Expose the Table and Namespace IDs encoded within the serialised DML
write (added in #6036).
This makes the IDs available for use in the consumers, ending the …
=> perf(ingester): eliminate table / namespace queries

ingester/src/handler.rs
This is completely redundant jiggery that adds confusion.
---
* refactor: remove redundant shard data init (d1cfa9d08)
Removes confusingly unused shard data initialisation.
=> refactor: remove redundant shard data init

ingester/src/data.rs, ingester/src/data/partition/resolver/catalog.rs, ingester/src/data/partition/resolver/mock.rs, ingester/src/data/partition/resolver/mod.rs, ingester/src/data/partition/resolver/sort_key.rs, ingester/src/data/partition/resolver/trait.rs, ingester/src/handler.rs, ingester/src/test_util.rs, query_tests/src/scenarios/util.rs
A little cleanup now, to prevent a mess later 👌 
---
* refactor: internalise PartitionProvider (75a7a287c)
Removes the need to leak the PartitionProvider outside of the ingester
crate.
This will allow the PartitionProvider to utilise a
DeferredLoad<TableName> without having to make the DeferredLoad and
TableName pub.
=> refactor: internalise PartitionProvider

ingester/src/data.rs, ingester/src/data/namespace.rs, ingester/src/data/partition.rs, ingester/src/data/partition/resolver/cache.rs, ingester/src/data/partition/resolver/catalog.rs, ingester/src/data/partition/resolver/mock.rs, ingester/src/data/partition/resolver/trait.rs, ingester/src/data/shard.rs, ingester/src/data/table.rs, ingester/src/data/table/name_resolver.rs, ingester/src/querier_handler.rs
This PR is a pre-requisite to removing string identifiers from the ingest write protocol (#4880).
This changes the ingester to no longer use the string table name in the write message, and instead perform a query at some random point in time between the first op for the table, and 1 minute later. This random jitter helps avoid smashing the catalog with lots of queries when an ingester first comes up, and removes the query latency from the ingest hot path, increasing throughput compared to the previous ID discovery mechanism.
This PR contains effectively identical changes as #6121, except for a table name, instead of namespace name.
---
* perf(ingester): address tables by ID only (8dae6d399)
Changes the buffer tree to address TableData by their ID only (removing
support for addressing …
=> perf(ingester): deferred table name discovery

dml/src/lib.rs, docs/ingester_querier_protocol.md, generated_types/protos/influxdata/iox/delete/v1/service.proto, generated_types/protos/influxdata/pbdata/v1/influxdb_pb_data_protocol.proto, influxdb_iox_client/src/client/delete.rs, ingester/src/data.rs, ingester/src/data/namespace.rs, ingester/src/data/shard.rs, ingester/src/handler.rs, ingester/src/stream_handler/handler.rs, ingester/src/stream_handler/sink_instrumentation.rs, ingester/src/test_util.rs, ingester/tests/common/mod.rs, mutable_batch_pb/src/encode.rs, mutable_batch_tests/benches/write_pb.rs, query_tests/src/scenarios/util.rs, router/src/dml_handlers/sharded_write_buffer.rs, router/tests/http.rs, write_buffer/src/codec.rs, write_buffer/src/core.rs, write_buffer/src/file.rs, write_buffer/src/kafka/mod.rs, write_buffer/src/kafka/record_aggregator.rs, write_buffer/src/mock.rs
I highly recommend reviewing this PR commit-by-commit.
This PR:
- Removes the namespace (database) name from `IoxHeaders`, which is metadata that goes into the write buffer but is never read as far as I can tell. CHECK ME ON THIS BEFORE MERGING!!!
- Deprecates the protobuf `DeletePayload` `db_name` field and the `DatabaseBatch` `database_name` field, which I believe are unused as far as I can tell. CHECK ME ON THIS BEFORE MERGING!!!
- Removes the namespace (database) name from `Dml` operations as part of https://github.com/influxdata/influxdb_iox/issues/4880
- Fixes https://github.com/influxdata/influxdb_iox/issues/6049 by updating the documentation in docs/ingester_querier_protocol.md; everything else looks done for that issue.
* fix: Update docs on the ingester-querier protocol.
I …
=> fix: Remove namespace string from router -> write buffer -> ingester communication

generated_types/build.rs, generated_types/protos/influxdata/iox/ingester/v1/write.proto, generated_types/protos/influxdata/pbdata/v1/influxdb_pb_data_protocol.proto, test_helpers_end_to_end/src/client.rs
This PR defines a simple request/response placeholder for a direct RPC write from a router, to an ingester.
---
* feat: define router -> ingester write protocol (dcc7b10bc)
Specify a gRPC service and request/response message formats to push
writes directly from a router to an ingester.
=> feat: define router -> ingester write protocol

arrow_util/Cargo.toml
:broom:
---
* build(arrow_util): datafusion is not a release dep (4435d7259)
Moves datafusion to dev-dependencies.
=> build(arrow_util): datafusion is not a release dep

router/src/dml_handlers/mod.rs, router/src/dml_handlers/partitioner.rs, router/src/dml_handlers/rpc_write.rs, router/src/dml_handlers/rpc_write/client.rs, router/src/dml_handlers/trait.rs, router/src/server/http.rs
This adds an [RPC write](#6145) client to the router, to push DML operations to ingesters instead of going through Kafka.
**Note**: this impl is currently unused.
---
* feat(router): handler for direct write to ingester (9da5b7963)
This commit adds the (unused) RpcWrite implementation of the DmlHandler
trait that implements pushing a write over gRPC to a single, arbitrary
ingester. Requests are round-robin'ed across all available ingesters.
This DmlHandler implementation can be swapped out with the
ShardedWriteBuffer to change how writes are propagated to the ingester.
=> feat(router): handler for direct write to ingester

ingester/src/dml_sink/mock_sink.rs, ingester/src/dml_sink/trait.rs, ingester/src/server/grpc/rpc_write.rs, ingester/src/stream_handler/handler.rs, ingester/src/stream_handler/sink_adaptor.rs, ingester/src/stream_handler/sink_instrumentation.rs
Allow the `DmlSink` implementation to specify what error type it returns, requiring that error type to be convertable into a `DmlError`.
This allows concise impl-specific error types, but still allow the API handlers that interact with one or more `DmlSink` to convert the impl error into a type they can enumerate and map to a suitable response. 
---
* refactor: decouple DmlSink error type (1938c18c5)
Allows different DmlSink implementations to return different error
types. This allows for small, concise errors that are local to the
DmlSink implementation and specific to it. This helps avoid bloated
"kitchen sink" error types.
=> refactor: decouple DmlSink error type

ingester2/src/query/exec.rs, ingester2/src/query/instrumentation.rs, ingester2/src/query/mock_query_exec.rs, ingester2/src/query/mod.rs, ingester2/src/query/partition_response.rs, ingester2/src/query/response.rs, ingester2/src/query/tracing.rs, ingester2/src/query/trait.rs, ingester2/src/server/grpc/query.rs
Adds a decorator over the `QueryExec` trait to add additional distributed tracing spans as the query data is sourced.
---
* refactor: rename Response -> QueryResponse (a54326d1a)
Both more descriptive, and less conflict-y! This seems like a more
sensible name for a system with many Response's.
* feat: query exec tracing spans (443ec49f2)
Implement a QueryExec decorator that emits named tracing spans covering
the inner delegate's query_exec() execution.
Captures the result, emitting the error string in the span on failure.
=> feat(ingester2): query tracing decorator

ingester2/src/query/instrumentation.rs, ingester2/src/query/partition_response.rs, ingester2/src/query/response.rs, ingester2/src/query/tracing.rs, ingester2/src/server/grpc/query.rs
This PR changes the query reponse code path in `ingester2`, diverging it from how queries are streamed in the current ingester code.
This started out as an attempt to make the code/types more readable, and then once I understood what was happening optimising it for a fully streaming response was easy :tada:
**NOTE:** This PR changes the way queries _will_ be run - currently the query path is not connected up in `ingester2` (soon!)
---
* refactor(ingester2): explicit PartitionStream type (2ed9780f6)
Simplify the streaming types by introducing explicitly named wrappers to
improve visibility.
* perf(ingester2): streaming query data sourcing (1a379f5f1)
Changes the query code (taken from the ingester crate) to stream data
for query execution, tidy up unnecessary Result types and removing …
=> perf(ingester2): streaming queries

ingester2/Cargo.toml, ingester2/src/buffer_tree/namespace.rs, ingester2/src/buffer_tree/root.rs, ingester2/src/buffer_tree/table.rs, ingester2/src/query/exec.rs, ingester2/src/query/instrumentation.rs, ingester2/src/query/mock_query_exec.rs, ingester2/src/query/tracing.rs, ingester2/src/query/trait.rs, ingester2/src/server/grpc.rs, ingester2/src/server/grpc/query.rs
This PR teaches the (previously write-only) `BufferTree` to return arrow `RecordBatch` instances for a given table (across any and all partitions within it).
It does this in a different way to the `ingester` crate query path by deferring the partition read until the client is ready to consume the partition data (pull-based streaming) - this reduces the memory usage of a query, and avoids doing unnecessary work if the client disconnects. This also lets us define the deterministic read consistency of the `BufferTree`, which was harder to specify/not so clear before.
---
* refactor: associated QueryExec return type (de6f0468d)
Allow the return type of the QueryExec trait's query_exec() method to be
parametrised by the implementer.
This allows the trait to be reused across different data …
=> perf(ingester2): streaming buffer tree queries

Cargo.lock, ingester2/Cargo.toml, ingester2/src/dml_sink/trait.rs, ingester2/src/lib.rs, ingester2/src/server/grpc/rpc_write.rs, ingester2/src/wal/mod.rs, ingester2/src/wal/traits.rs, ingester2/src/wal/wal_sink.rs, wal/src/lib.rs, wal/tests/end_to_end.rs
This commit adds the functionality to write incoming DML operations to a write-ahead log.
There is currently no functionality to rotate or replay this log (coming next).
---
* refactor(Wal): remove SequenceNumberNg (30e2dd7fb)
This actually starts getting more confusing than passing the bare u64
around.
* refactor(wal): rename next_ops -> next_op (628e0a713)
It only returns one op, so remove the plural.
* feat(ingester2): commit writes to write-ahead log (4f4687569)
Adds WalSink, an implementation of the DmlSink trait that commits DML
operations to the write-ahead log before passing the DML op into the
decorated inner DmlSink chain.
By structuring the WAL logic as a decorator, the chain of inner DmlSink
handlers within it are only ever invoked after the WAL commit has
successfully …
=> feat(ingester2): commit DML ops to WAL

ingester2/src/init.rs
A simple PR!
When the ingester starts up, it pre-loads the most recently created N partitions from the catalog - optimistically we assume that recently created partitions are "hot" for writes, whereas old partitions (from days ago) are not.
Without this cache, every request that hits a just-started-up ingester will cause the ingester to query the catalog to find out the partition information, and then place it into the `BufferTree`. Subsequent requests use the information in the `BufferTree`, avoiding the query.
By using this cache, we remove the latency (and correlated load) of a catalog query for every new partition that is a cache hit.
Recent PRs have reduced the amount of data we need to maintain in the cache (namely removing the persist marker sequence number, and the shard ID), so …
=> refactor(ingester2): cache more hot partitions

ingester2/src/init.rs, ingester2/src/init/wal_replay.rs, ingester2/src/test_util.rs
This PR adds write-ahead log replay functionality to the ingester2 startup sequence.
Startup will block while the WAL is replayed (the gRPC write service will not be available until it completes).
**Currently WAL files are never deleted** - that code is coming, but for testing purposes you'll need to periodically delete WAL files or every startup will take longer and longer.
I've done my best to make WAL replay _observable_ from the logs, including the progress of replay, as it is often a source of operational surprise / concern.
---
* feat(ingester2): WAL entry replay at startup (cb248c75d)
Replay the WAL log, if any, at startup.
Op replay is performed synchronously, during initialisation of the
ingester2 instance, and passes all ops through the "normal" write path
that the system uses …
=> feat(ingester2): WAL entry replay at startup

ingester2/src/init.rs, ingester2/src/init/wal_replay.rs, ingester2/src/wal/mod.rs, ingester2/src/wal/rotate_task.rs, wal/src/lib.rs, wal/tests/end_to_end.rs
Adds a background task to `ingester2` that periodically rotates the WAL file (configurable when initialising the ingester2 instance, I intend via CLI/env arg :+1:)
This background task is stopped when the `ingester2` guard instance is dropped, ensuring we don't leak resources.
---
* refactor(wal): remove needless async/await (f40885d4c)
Obtaining a rotation handle isn't async.
* feat(ingester2): rotate wal periodically (c7f88d779)
Spawn a background task to rotate the WAL file with the given internal.
* refactor(ingester2): clean-up rotation task (81619fd5b)
When an ingester2 instance goes out of scope, automatically stop the WAL
rotation task.
=> feat(ingester2): periodic WAL rotation

ingester2/src/buffer_tree/partition.rs, ingester2/src/buffer_tree/partition/persisting.rs
This PR changes the `PartitionData` to support an (unbounded) number of buffers in the "persisting" state - this lets us queue up partition work without having to wait for existing persist tasks to complete; see commit message.
I think this fixes https://github.com/influxdata/influxdb_iox/issues/4928 if I understand the ticket correctly.
I think @aierui might be interested in this too! :)
---
* perf(ingester2): partition persist queue (4f928fbd0)
This commit swaps the existing single "persisting batch" slot (field) in
a PartitionData for an ordered queue of outstanding partitions.
This decouples marking a partition buffer for persistence from the
actual persistence operation, allowing them to proceed at different
rates. This reduces the complexity of persistence management, but also …
=> perf(ingester2): partition persist queue

ingester2/src/wal/rotate_task.rs
Once persistence is complete, drop the old WAL segment.
**There is a race in this logic** described (at length) in the code. I also propose a plan to fix it, and have synced with @carols10cents to discuss implementing it.
It is low risk, low impact, and definitely not a blocker for MVP testing next week - I will put together a proper solution when I am back :+1:
---
* feat(ingester2): drop WAL segments after persist (26bf54d04)
Changes the WAL rotation task to drop the WAL segment after the
partition data has completely persisted.
This logic contains a race condition outlined (at length) in the code
comments, along with a plan to resolve it once I'm back from holiday.
For now, the extremely low likelihood and minor impact of the race
occurring is likely acceptable for testing purposes.
=> feat(ingester2): drop WAL segments after persist

ingester2/src/init.rs
It's done! 👌 
---
* chore: remove old comment (de52a2475)
The ingester will replay the ops, and then immediately trigger a
persist! This comment is done :)
Outstanding is actually deleting the replayed files, which will come
with the ref-counted WAL segment change later.
=> chore: remove old comment

wal/src/lib.rs
When sending an RPC write and disconnecting before it completes, the WAL would panic because there is nothing listening for the commit ACK.
---
* fix: do not panic when writer disconnects (7cb1636c6)
When the RPC write disconnects without waiting for completion, the WAL
panics as there is no longer a consumer of the "committed" ACK.
=> fix: do not panic when writer disconnects

.editorconfig
Makes the indenting sane for shell scripts. Should the default not be 4 anyway?
---
* chore: editor config spacing for shell scripts (65d45fbe9)
Set .bash and .sh script indent size to 4.
=> chore: editor config spacing for shell scripts

ingester2/src/persist/context.rs, ingester2/src/persist/handle.rs, ingester2/src/wal/rotate_task.rs
This adds a bit more logging to persist, and captures the time a persist job spent in the queue, and how long it actually took to persist once dequeued - this information is displayed in the existing "persisted partition" INFO log:
```
INFO persisted partition <snip> total_persist_duration=51.535291ms active_persist_duration=12.523375ms queued_persist_duration=39.011916ms
```
---
* feat(ingester2): persist active & queue timings (5fa4e4909)
Adds more debug logging to the persist code paths, as well as capturing
& logging (at INFO) timing information tracking the time a persist task
spends in the queue, the active time spent actually persisting the data,
and the total duration of time since the request was created (sum of
both durations).
=> feat(ingester2): log persist active & queue timings

.circleci/config.yml, Cargo.lock, clap_blocks/Cargo.toml, clap_blocks/src/lib.rs, clap_blocks/src/querier.rs, clap_blocks/src/router2.rs, influxdb_iox/Cargo.toml, influxdb_iox/src/commands/run/all_in_one.rs, influxdb_iox/src/commands/run/ingester.rs, influxdb_iox/src/commands/run/ingester2.rs, influxdb_iox/src/commands/run/mod.rs, influxdb_iox/src/commands/run/querier.rs, influxdb_iox/src/commands/run/router.rs, influxdb_iox/src/commands/run/router2.rs, influxdb_iox/src/commands/run/router_rpc_write.rs, influxdb_iox/tests/end_to_end_cases/ingester.rs, influxdb_iox/tests/end_to_end_cases/mod.rs, influxdb_iox/tests/end_to_end_cases/mode_switching.rs, ioxd_querier/src/lib.rs, ioxd_router/Cargo.toml, ioxd_router/src/lib.rs, test_helpers_end_to_end/Cargo.toml, test_helpers_end_to_end/src/config.rs, test_helpers_end_to_end/src/mini_cluster.rs, test_helpers_end_to_end/src/server_fixture.rs, test_helpers_end_to_end/src/server_type.rs
And standardize on ingester2 and router2 for consistency.
**The `test_rpc_write` CI job is now exactly the same as the `test` job but I can't remove it because it's required; @domodwyer could you un-require it please?** ❤️
Closes #6402.
You will now see `router2` and `ingester2` in `influxdb_iox run --help`.
BUT it shouldn't be possible to *only* typo the command by adding `2`; you also need to set `INFLUXDB_IOX_RPC_MODE` (to any value, I've been setting it to `2`, but it's only set/unset that's checked).
Querier is still different as it shares more code; there is no `querier2`. But the `INFLUXDB_IOX_RPC_MODE` and setting `--ingester-addresses` instead of shard to ingester mappings is how you switch the querier into the RPC write path.
So now you can run these commands to use the RPC …
=> fix: Remove the rpc_write feature flag and use INFLUXDB_IOX_MODE env var instead

Cargo.lock, clap_blocks/src/ingester2.rs, ingester2/Cargo.toml, ingester2/src/init.rs, ingester2/src/persist/backpressure.rs, ingester2/src/persist/context.rs, ingester2/src/persist/handle.rs, ingester2/src/server/grpc/rpc_write.rs, iox_query/src/exec.rs, ioxd_ingester2/src/lib.rs
This PR changes the ingester2 persist system with the aim to perform optimal parallelisation of persist tasks within the parallelism bound; persists that can be parallelised are parallelised (across all workers), serialising only those jobs that **must** be serialised for correctness.
Some persist operations require updating the partition's sort key - this is not a commutative operation; updates must be applied one after another. We can cheaply and easily determine if a persist job will need to update the sort key before starting the persist job, and this PR takes advantage of that fact:
* Persist jobs that need to update a sort key are enqueued to a partition's assigned worker - serialising within the partition, but parallelising across partitions.
* Persist jobs that will not modify the …
=> feat(ingester2): optimal persist parallelism

ingester2/README.md, ingester2/src/init.rs
Make ingester2 work with empty or existing catalogs. Also adds a quickstart documentation that shows how to run it the i/r/q triplet locally.
Closes https://github.com/influxdata/influxdb_iox/issues/6420
I see that the `TRANSITION_SHARD_ID` is also asserted by the test utils, it seems that that's the place this assert belongs to, thus removing from the main init code.
The documentation is based on the gourmet copy pasta first cooked by @carols10cents in #6406
=> fix(ingester2): Make ingester2 work with empty or existing catalogs 

write_buffer/src/core.rs
When running integration tests recently I got the error message telling me `KAFKA_CONNECT` wasn't set, which was correct, but the instructions it gives you are out of date. Compose file has moved, and the port was `9092` for me.
=> chore: update error message when running int tests w/out kafka

clap_blocks/src/ingester2.rs, ingester2/src/buffer_tree/mod.rs, ingester2/src/buffer_tree/namespace.rs, ingester2/src/buffer_tree/partition.rs, ingester2/src/buffer_tree/partition/buffer.rs, ingester2/src/buffer_tree/partition/buffer/always_some.rs, ingester2/src/buffer_tree/partition/buffer/mutable_buffer.rs, ingester2/src/buffer_tree/partition/buffer/state_machine/buffering.rs, ingester2/src/buffer_tree/post_write/mock.rs, ingester2/src/buffer_tree/post_write/mod.rs, ingester2/src/buffer_tree/post_write/trait.rs, ingester2/src/buffer_tree/root.rs, ingester2/src/buffer_tree/table.rs, ingester2/src/init.rs, ingester2/src/persist/handle.rs, ingester2/src/persist/hot_partitions.rs, ingester2/src/persist/mod.rs, ingester2/src/wal/rotate_task.rs, ioxd_ingester2/src/lib.rs
Implement hot partition persistence for ingester2 🚒 
This should ensure that a partition receiving a large volume of writes does not grow to such a degree it causes an OOM.
I'm sure we'll iterate on the selection algorithm, but it is decoupled & easily extended.
---
* feat(ingester2): hot partition persistence (c830a8310)
This PR uses the MutableBatch persist cost estimation added in #6425 to
selectively mark "hot" partitions for persistence.
This uses a (composable!) "post-write" observer that is invoked after
each buffer call - this allows the HotPartitionPersister in this commit
to inspect the cost of the partition after applying the write, and if it
exceeds the configurable cost threshold, enqueue it for persistence
(rotating the buffer within the partition in the process).
Unlike …
=> feat(ingester2): hot partition persistence

.circleci/config.yml, ingester2/src/buffer_tree/namespace.rs, ingester2/src/buffer_tree/partition.rs, ingester2/src/buffer_tree/partition/resolver/cache.rs, ingester2/src/buffer_tree/partition/resolver/catalog.rs, ingester2/src/buffer_tree/partition/resolver/mock.rs, ingester2/src/buffer_tree/partition/resolver/trait.rs, ingester2/src/buffer_tree/root.rs, ingester2/src/buffer_tree/table.rs, ingester2/src/init.rs, ingester2/src/lib.rs, ingester2/src/persist/context.rs, ingester2/src/persist/handle.rs, ingester2/src/query/partition_response.rs, ingester2/src/query/response.rs, ingester2/src/server/grpc/query.rs, ingester2/src/test_util.rs
Connects to #6421. Does not completely solve yet.
The first problem both Dom and I suspected was that the transition shard ID was not matching the hardcoded hack value. The first commit in this PR changes the code to still hardcode the transition shard *index* to 1, but to look up in the catalog what the transition shard *id* ends up being and use that value. This didn't seem to affect the problem in the issue at all as far as I could tell, but was incorrect, so good to change anyway. Ultimately, shards will completely go away when the transition is complete.
The next problem I noticed is in the test mkm was doing, the steps were:
- Enqueue data
- Query, data is returned
- Ingester persists
- Query, data is not returned
I noticed the querier was not getting any metadata about the ingester …
=> fix: Correct *some* problems mkm found with ingester2/querier

ingester2/src/persist/backpressure.rs
https://github.com/influxdata/influxdb_iox/pull/6403#discussion_r1049779382
---
* docs: fix incomplete comment (84e29791e)
Finishes the incomplete sentence that
=> docs: fix incomplete comment

compactor/src/compact.rs, import/src/aggregate_tsm_schema/update_catalog.rs, ingester/src/buffer_tree/partition.rs, ingester/src/buffer_tree/partition/resolver/sort_key.rs, ingester/src/data.rs, ingester2/src/buffer_tree/partition.rs, ingester2/src/buffer_tree/partition/resolver/sort_key.rs, ingester2/src/persist/context.rs, iox_catalog/src/interface.rs, iox_catalog/src/mem.rs, iox_catalog/src/metrics.rs, iox_catalog/src/postgres.rs, iox_tests/src/util.rs, querier/src/cache/partition.rs
Change the partition `update_sort_key` method in the catalog interface to a compare-and-swap primitive, allowing the caller to detect serialisation violations.
This is related to https://github.com/influxdata/influxdb_iox/issues/6439 in that it allows ingester2 to detect parallel updates.
* ingester1 will panic if it observes a prohibited parallel update (an invariant in the design)
* ingester2 will (incorrectly) overwrite the sort key as it did before this PR (for now, next PR fixes this)
---
* feat(catalog): linearise sort key updates (2a8454583)
Updating the sort key is not commutative and MUST be serialised. The
correctness of the current catalog interface relies on the caller
serialising updates globally, something it cannot reasonably assert in a
distributed system.
This change of …
=> feat(catalog): linearise sort key updates

ingester2/src/persist/context.rs, ingester2/src/persist/handle.rs, ingester2/src/persist/worker.rs
Handle concurrent, cross-node catalog sort key updates as described in https://github.com/influxdata/influxdb_iox/issues/6439.
Closes https://github.com/influxdata/influxdb_iox/issues/6439.
---
* fix(ingester2): handle concurrent sort key updates (f64ffbe03)
Allow an ingester2 instance to tolerate concurrent partition sort key
updates in the catalog.
A persist job is optimistically executed with the locally cached sort
key. If an ingester2 instance observes a concurrent update, it aborts
both the sort key update, and the overall persist operation (before
making the parquet file visible) and retries the operation with the
newly observed sort key. Concurrent sort key updates are theorised to be
relatively rare overall.
Any orphaned parquet files uploaded as part of a persist job that aborts …
=> fix(ingester2): handle concurrent sort key updates

ingester2/src/persist/context.rs, ingester2/src/persist/handle.rs, ingester2/src/persist/mod.rs, ingester2/src/persist/worker.rs
Moves things around, but changes nothing else.
---
* refactor(persist): explicit worker module (15cff11b0)
Separate out persist worker types & routines into a separate worker
module rather than commingling them with the persist handle, and rename
the unimaginative "inner" to reflect the actual usage.
=> refactor(persist): explicit worker module

querier/src/table/mod.rs
Connects to #6421, [namely this comment](https://github.com/influxdata/influxdb_iox/issues/6421#issuecomment-1361580387).
=> fix: Allow partitions from ingesters to overlap in RPC write mode

ingester2/src/init.rs, ingester2/src/persist/backpressure.rs, ingester2/src/persist/handle.rs, ingester2/src/server/grpc/rpc_write.rs
When this happens we stop accepting writes, so it's a good starting point!
---
* feat(ingester2): persist saturation metric (679c6a789)
Expose a metric ("ingester_persist_saturated_duration_ns") that records
the cumulative duration of time the persist system has spent in the
"saturated" state.
=> feat(ingester2): persist saturation metric

ingester2/src/init.rs, ingester2/src/persist/backpressure.rs, ingester2/src/persist/drain_buffer.rs, ingester2/src/persist/handle.rs, ingester2/src/persist/hot_partitions.rs, ingester2/src/persist/mod.rs, ingester2/src/persist/queue.rs, ingester2/src/wal/rotate_task.rs
Decoupling! 🚀 
Everything in ingester2 that enqueued partitions for persistence was **painfully** coupled to the `PersistHandle`. This made it difficult to test, and reuse. It's also just good engineering practice to depend on _behaviours_ rather than types.
There is no new code in this PR, only new abstractions & reusability.
Pre-requisite to the fix for #6461 which needs `PartitionIter`.
---
* refactor: extract BufferTree persist helper (e54896e5f)
Extract an existing function for re-use (from the WAL rotation task)
that marks & enqueues all non-empty partitions in a BufferTree for
persistence.
* refactor(persist): decoupled PartitionIter (dee9743e5)
The persist_buffer() fn iterates over all the partitions in a BufferTree
and persists them - however it only depends on one behaviour; …
=> refactor(ingester2): decouple persistence subsystem

ingester2/Cargo.toml, ingester2/benches/wal.rs, ingester2/src/buffer_tree/mod.rs, ingester2/src/buffer_tree/partition.rs, ingester2/src/buffer_tree/partition/persisting.rs, ingester2/src/dml_sink/trait.rs, ingester2/src/init.rs, ingester2/src/init/wal_replay.rs, ingester2/src/lib.rs, ingester2/src/persist/mod.rs, ingester2/src/persist/queue.rs, ingester2/src/query_adaptor.rs, ingester2/src/wal/mod.rs, ingester2/src/wal/rotate_task.rs
Fixes #6461, but may slow down startup as we now wait for persistence to complete for each file before being "ready". As a nice side-effect, crash loops that make some progress (a file or two each time) will eventually recover automatically.
This can be optimised to allow something like:
* Replay file 1
* Enqueue persist jobs but do not wait for completion
* Replay file
* Enqueue persist job
* (persists for job 1 complete) -> drop file 1
But this approach must respect the saturation of the persist system (otherwise we're just moving the OOM problem to persisting data, rather than buffered data). Given there should rarely be many files, this doesn't seem like a big deal.
Now we have a bit of time, we need to increase the test coverage before making WAL replay more complicated - I'd love to …
=> fix: drop WAL segments after replay

influxdb_iox/tests/end_to_end_cases/ingester.rs, influxdb_iox/tests/end_to_end_cases/querier.rs, test_helpers_end_to_end/src/client.rs, test_helpers_end_to_end/src/config.rs, test_helpers_end_to_end/src/mini_cluster.rs, test_helpers_end_to_end/src/server_fixture.rs, test_helpers_end_to_end/src/server_type.rs, test_helpers_end_to_end/src/steps.rs
Connects to #6317.
This PR does not actually port any of the `query_tests`. That will come in a future PR.
It does, however, port some more of the end-to-end tests and also adds some infrastructure to the test helpers that I plan to use in the port of the query tests, namely:
- Creating a MiniCluster that contains a querier using the RPC write path (router2 and ingester2 existed already)
- Creating an ingester2 configured to effectively never persist data (`INFLUXDB_IOX_WAL_ROTATION_PERIOD_SECONDS=86400`) so that the tests can exercise the state of data being in the ingester's buffers but not in Parquet files yet. The default configuration for ingester2 in tests is to persist as fast as possible (`INFLUXDB_IOX_WAL_ROTATION_PERIOD_SECONDS=1`)
- Creating a function that verifies a change in …
=> test: Lay the groundwork for porting query_tests to the RPC write path

data_types/src/lib.rs, iox_catalog/src/interface.rs, iox_catalog/src/mem.rs, iox_catalog/src/metrics.rs, iox_catalog/src/postgres.rs
Second PR for https://github.com/influxdata/idpe/issues/16836
This new catalog query `partitions_with_recent_created_files` is not yet invoked anywhere. My next step is to used it in hot/cold/warm compaction
=> feat: catalog query to select partitions with recently created files

ioxd_router/src/lib.rs, router/src/dml_handlers/rpc_write.rs, router/src/dml_handlers/rpc_write/client.rs
As per the commit message, this has (minor) downsides. I'll add a comment to #6173 that should include improving this logic.
Fixes #6503.
---
* fix(router2): lazily connect to ingesters (a5a26f5ef)
Allow the routers to start up without requiring full availability of all
downstream ingesters. Previously a single unavailable ingester prevented
the routers from starting up.
This has downsides:
* Lazily initialising a connection will cause the first writes to have
higher latency as the connection is established.
* The routers MAY come up in a state that will never work (i.e. bad
ingester addresses)
* Using the opaque gRPC load balancing mechanism restricts the
visibility into which nodes are up/down (hindering useful log
messages) and prevents us from implementing more advanced circuit …
=> fix(router2): lazily connect to ingesters

Cargo.lock, router/Cargo.toml, router/src/dml_handlers/rpc_write.rs
I'm not sure the upstream tonic/tower load-balancing implementation works as it should for a static list of endpoints. See https://github.com/hyperium/tonic/issues/1147.
Hopefully fixes https://github.com/influxdata/influxdb_iox/issues/6508.
---
* fix(router2): drive ingester node (re)-discovery (9ab86fa15)
The tonic / tower load-balance implementation discards failed nodes,
even when using a static list - this causes nodes that fail once to
never be retried.
This doesn't happen for the last node for some reason, and leads to all
the load from one router hitting a single ingester instead of load
balancing across all ingesters.
This commit adds a hack to constantly tell the load balancer to probe
all nodes, hopefully causing them to re-discover previously failed
nodes. I don't have the …
=> fix(router2): drive ingester node (re)-discovery

schema/src/lib.rs
Update docstrings on the `Schema` to clarify it is cheaply cloneable, inspired by @tustvold 's PR https://github.com/influxdata/influxdb_iox/pull/6511
=> docs: Update docstring on Schema

Cargo.lock, deny.toml, trogging/Cargo.toml, trogging/src/lib.rs, workspace-hack/Cargo.toml
This unblocks CI: https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/27576/workflows/1c554826-4058-4005-adeb-ad87167b3881/jobs/246465
bonus: is-terminal was already a dependency.
---
* refactor(trogging): remove atty dependency (fa6b07f3a)
Replace atty with IsTerminal due to:
https://rustsec.org/advisories/RUSTSEC-2021-0145
* ci: whitelist RUSTSEC-2021-0145 (6b090fae5)
atty is used by criterion and mockito, both dev-only dependencies.
* chore: bump tokio 1.22 -> 1.24 (7f7f0ca17)
Fixes a bug on windows:
https://github.com/tokio-rs/tokio/security/advisories/GHSA-7rrj-xr53-82p7
=> refactor: remove atty & bump tokio

rust-toolchain.toml
Use the newest rust release 🧹 
---
* chore: bump rust to 1.66.1 (e0dcfc883)
Picks up a fix to SSH host authentication in cargo when pulling the
crates index:
https://blog.rust-lang.org/2023/01/10/cve-2022-46176.html
=> chore: bump rust to 1.66.1

.circleci/config.yml
There's no rust 1.66.1 docker image: https://hub.docker.com/_/rust/tags
This lets us use the fixed cargo, and unblocks the failing CI / deployments on "main".
I will revert this when it's possible.
---
* ci: use rust 1.66.0 for CI (71f54528d)
Temporary fix as there's no official 1.66.1 docker image (yet?), so use
1.66 for now.
I kept the toolchain version pinned and switched only the CI version so
that we are all using the fixed cargo. I will revert this commit when
there's a 1.66.1 image.
=> ci: use rust 1.66.0 for CI

ingester2/src/persist/backpressure.rs, router/src/dml_handlers/rpc_write.rs
Fixes a panic (causing no ill effect) at shutdown, introduced in #6509.
---
* fix: gRPC balancer shutdown panic (6ef68513d)
The gRPC node discovery hack spawns a task that outlives the gRPC
balancer - once the balancer stops, the task should stop too (and not
panic sending on the closed channel).
* refactor: drop PersistState visibility (2fa12622c)
This is now an implementation detail internal to the persist subsystem.
=> fix: node discovery shutdown panic

generated_types/protos/influxdata/iox/catalog/v1/service.proto, influxdb_iox/tests/end_to_end_cases/querier.rs, influxdb_iox_client/src/client/catalog.rs, service_grpc_catalog/src/lib.rs, test_helpers_end_to_end/src/client.rs, test_helpers_end_to_end/src/steps.rs
Fixes #6506.
Also has the pleasant side effect of making this code simpler and less hacky-- it now checks the number of Parquet files for the whole namespace, which is useful in cases where the line protocol writes to several tables.
=> test: Record number of Parquet files before a write

.circleci/config.yml
There is now a [1.66.1 image](https://hub.docker.com/layers/library/rust/1.66.1-slim-buster/images/sha256-8c19cad1f738f87f56622d10f9aeaacf99a06d9fbed40f15ed37ea5b5660f505?context=explore).
---
* revert: "ci: use rust 1.66.0 for CI" (38eeffac0)
This reverts commit 71f54528d086aee10bf046acaa954ccc7c0ddc5e.
=> revert: "ci: use rust 1.66.0 for CI"

Cargo.lock, ingester2/Cargo.toml, ingester2/src/init.rs, ingester2/src/init/graceful_shutdown.rs, ioxd_common/src/lib.rs, ioxd_common/src/server_type.rs, ioxd_compactor/Cargo.toml, ioxd_compactor/src/lib.rs, ioxd_garbage_collector/Cargo.toml, ioxd_garbage_collector/src/lib.rs, ioxd_ingest_replica/Cargo.toml, ioxd_ingest_replica/src/lib.rs, ioxd_ingester/Cargo.toml, ioxd_ingester/src/lib.rs, ioxd_ingester2/Cargo.toml, ioxd_ingester2/src/lib.rs, ioxd_querier/Cargo.toml, ioxd_querier/src/lib.rs, ioxd_router/src/lib.rs, ioxd_test/Cargo.toml, ioxd_test/src/lib.rs
After this change, ingester2 can ensure the RPC server is stopped **after** the persist operations have completed:
```
INFO ingester2::init::graceful_shutdown: gracefully stopping ingester
INFO ingester2::init::graceful_shutdown: persisting all data before shutdown
INFO ingester2::init::graceful_shutdown: persisted all data - stopping ingester
INFO ioxd_common: frontend shutdown completed server_type=Ingester2
INFO ioxd_common: backend shutdown completed server_type=Ingester2
```
Fixes https://github.com/influxdata/influxdb_iox/issues/6578.
---
* refactor: delegate frontend shutdown to backend (0d111c467)
Prior to this commit, the (happy path) shutdown sequence of an IOx
process was hard coded to:
1. Stop gRPC & HTTP servers
2. Stop backend server (i.e. ingester2)
After this commit, the …
=> refactor: delegate frontend shutdown to backend

ingester2/src/buffer_tree/namespace.rs, ingester2/src/buffer_tree/table.rs
Remove an unused extra mapping, and the shared mutex protecting it (used in the hot path) 🧹 
---
* perf: remove double-ref Partition map (8dc18a983)
The ingester no longer needs to access a specific PartitionData by ID
(they are addressed either via an iterator over the BufferTree, or
shared by Arc reference).
This allows us to remove the extra map maintaining ID -> PartitionData
references, and the shared access lock protecting it.
=> perf: remove double-ref Partition map

ingester2/src/ingester_id.rs, ingester2/src/init.rs, ingester2/src/lib.rs, ingester2/src/server/grpc.rs, ingester2/src/server/grpc/query.rs
Changes where the ingester UUID is initialised so it can be re-used (also wraps it in a newtype :+1:)
---
* refactor: use system-wide ingester ID (6413362c7)
The query API exposes a unique-per-instance UUID to allow callers to
detect a crash of the ingester process - this was initialised directly
in the query RPC handler.
This commit turns the bare UUID into a type, and initialises it in the
top-level initialisation of the ingester, plumbing it down into the
query RPC handler.
This allows the UUID to be reused by other components/handlers.
=> refactor: use system-wide ingester ID

ingester2/src/persist/context.rs, ingester2/src/persist/mod.rs, ingester2/src/persist/worker.rs
There is **❕no new logic in this PR ❕** - only moving things around, and new tests.
---
Cleans up a mess I willingly made when nocking out `ingester2` before the deadline.
This moves the "logic" of how a persistence happens away from the data of the persist job itself (in the persist job's `Context`). This also adds two integration tests covering the entire persist subsystem:
* A normal persistence
* A persistence that observes a concurrent sort key update, retries, and completes (#6439)
---
* test: persistence system integration test (1f5294c09)
This test ensures the persistence system as a whole works in the happy
path.
* refactor(persist): decouple Context & worker logic (091b428d4)
The persist::Context struct carries the data to be persisted, a
reference to the partition from which it …
=> refactor(persist): decouple persist job Context & logic

ioxd_router/src/lib.rs, router/src/dml_handlers/rpc_write.rs, router/src/dml_handlers/rpc_write/balancer.rs, router/src/dml_handlers/rpc_write/circuit_breaker.rs, router/src/dml_handlers/rpc_write/circuit_breaking_client.rs, router/src/server/http.rs
Circuit-break ingester connections in the routers, so that we don't send requests to unavailable ingesters during deployments.
Removes the hack I added in https://github.com/influxdata/influxdb_iox/pull/6509, pulling the balancing logic "up" into the IOx codebase again. This should improve the latency & error rate during deployments.
Part of https://github.com/influxdata/influxdb_iox/issues/6173 (only metrics outstanding, coming next).
---
* perf(router): circuit break ingester connections (7596dc082)
Adds on-path health checking / recording using the CircuitBreaker
construct, stopping requests to unhealthy upstreams (minus the probe
requests) until they recover.
This removes the horrible gRPC balancer hack I added to get us deployed
ASAP, and should eliminate latency spikes and elevated …
=> perf(router): circuit break ingester connections

ingester2/src/dml_sink/instrumentation.rs, ingester2/src/dml_sink/mod.rs, ingester2/src/dml_sink/tracing.rs, ingester2/src/init.rs, ingester2/src/persist/context.rs, ingester2/src/persist/handle.rs, ingester2/src/persist/mod.rs, ingester2/src/persist/worker.rs, ingester2/src/query/instrumentation.rs
Here's a load of metrics:
* Persist jobs enqueued / completed + latency
* Query execution against the buffer (inc. locks acquisition, `RecordBatch` generation, etc)
* DML apply count/latency
* Tracing spans for write/query paths.
More to come, but this should give us decent viability into what is going on with the ingester (write path metrics + persist system metrics)
---
* feat(metrics): cumulative persist job count (0637540aa)
Tracks the cumulative number of persist jobs enqueued on a single
ingester (the total amount, so including now-completed jobs).
* feat(metrics): persist duration histograms (3541243fc)
Adds metrics to track the distribution duration spent actively
persisting a batch of partition data (compacting, generating parquet,
uploading, DB entries, etc) and another tracking …
=> feat(ingester2): metrics

ingester2/src/persist/handle.rs, ingester2/src/persist/mod.rs
Exports two metrics:
* ingester_persist_max_parallelism
* ingester_persist_max_queue_depth
This lets us compute saturation in lock-step with any changes to these values, without coupling the dashbaords/alerts to the configuration system.
---
* feat: export persist config metrics (7b69c84ce)
Export the configured maximum persist parallelism, and the maximum queue
depth, so they can be used to compute % saturation in alerts /
dashboards.
=> feat: export persist config metrics

.circleci/config.yml, Cargo.lock, generated_types/protos/influxdata/iox/ingester/v1/write.proto, influxdb_iox/Cargo.toml, influxdb_iox/tests/end_to_end.rs, influxdb_iox/tests/end_to_end_cases/querier.rs, influxdb_iox/tests/end_to_end_cases/querier/influxrpc.rs, influxdb_iox/tests/end_to_end_cases/querier/influxrpc/metadata.rs, influxdb_iox/tests/query.rs, influxdb_iox/tests/query_tests2/framework.rs, influxdb_iox/tests/query_tests2/mod.rs, influxdb_iox_client/src/client/ingester.rs, ingester/src/server/grpc/persist.rs, ingester2/src/server/grpc.rs, ingester2/src/server/grpc/persist.rs, test_helpers_end_to_end/src/mini_cluster.rs
Connects to #6617.
I've ported two tests from [`query_tests/influxrpc/field_columns`](https://github.com/influxdata/influxdb_iox/blob/6f39ae342e64848bd6555bddbc1d3fa30050f75e/query_tests/src/influxrpc/field_columns.rs#L51-L86) and made them more in the style of the tests already existing in [`influxdb_iox/tests/end_to_end_cases/querier/influxrpc/metadata.rs`](https://github.com/influxdata/influxdb_iox/blob/6f39ae342e64848bd6555bddbc1d3fa30050f75e/influxdb_iox/tests/end_to_end_cases/querier/influxrpc/metadata.rs).
I think I have an abstraction that should work for the other kinds of InfluxRpc tests, namely:
- A new trait, `InfluxRpcTest`, that types can implement to define how to run a test on a specific Storage gRPC API. `InfluxRpcTest` takes care of iterating through the two …
=> test: Start of porting InfluxRpc query_tests

influxdb_iox/tests/end_to_end_cases/querier.rs, influxdb_iox_client/src/client/flight/mod.rs, service_grpc_flight/src/lib.rs
Fixes https://github.com/influxdata/idpe/issues/17000
This is basically because the fix in #6668 was incomplete. The schema that is sent from IOx to its clients is currently expanded (so it contains no dictionaries) but that transformation was not applied to the special case of zero record batches.
=> fix: Do not send dictionary encoded data to clients

clap_blocks/src/router2.rs, ioxd_router/src/lib.rs
Allows the partition key to be configured at runtime. It only supports setting the strftime pattern for now (as opposed to say, the value of a column).
Only supported on kafkaless clusters. Please don't use this.
---
* feat(router): configurable partition key (6797eab5f)
Allows the partition key to be set at runtime, though it's probably best
no one does so for now.
Context: https://docs.google.com/document/d/1q2Z8_3cX-baK2YISJeoxau9aUFuJuB2xZ9RDzRK-mwI/edit#heading=h.rrplyx64cq2l
=> feat(router): configurable partition key

compactor2/src/test_util.rs, data_types/src/lib.rs, ingest_replica/src/lib.rs, ingester2/src/lib.rs, ioxd_compactor2/src/lib.rs
This is just a cleanup to avoid risking changing one constant in one component and forgetting to update it in another.
=> chore: Avoid defining transition shard numbers in multiple crates

ingester2/src/buffer_tree/namespace/name_resolver.rs, ingester2/src/buffer_tree/partition/resolver/sort_key.rs, ingester2/src/buffer_tree/table/name_resolver.rs
Log some IDs when it's all on fire.
---
* refactor: panic with unresolvable partition IDs (0d9b77369)
Include the partition ID in the panic message.
* refactor: panic with unresolvable namespace IDs (6e540bc8d)
Include the namespace ID in the panic message.
* refactor: panic with unresolvable table IDs (a029de95f)
Include the table ID in the panic message.
=> refactor: log IDs in panic messages

service_grpc_namespace/src/lib.rs
Disable namespace deletion.
Rationale is that deleting namespaces causes catalog corruption (see linked issue) so we want to disable the feature while we make sure namespace deletion works reasonably
Part of https://github.com/influxdata/idpe/issues/17043
---
* fix: disable namespace delete gRPC endpoint (c70ccee4a)
Do not allow this endpoint to be called - the logic is incorrect.
* refactor: log namespace RPC actions (363ce1629)
Adds info logs for namespace CRUD actions.
=> refactor: disable ns delete

Cargo.lock, router/tests/grpc.rs, service_grpc_namespace/Cargo.toml, service_grpc_namespace/src/lib.rs
This maps `0` to `NULL` (meaning "infinite") instead of allowing a retention period of `0` ("keep nothing").
I also added logic to reject negative retention periods in a separate commit, because while it has theoretical meaning, it's very unlikely to have been tested / supported properly in all components at this stage.
I also added router e2e tests that assert the correctness of the high-level interface and the changes it propagates to the catalog. It also highlights the (unresolved) impact of #6175 nicely.
Closes #6787.
---
* fix: map retention period 0 values to NULL (bf6ae3dc4)
Treat a retention period of 0 as "infinite", and not "none".
* fix: reject negative retention periods (ec5b35e3c)
Do not allow a negative retention period to be specified.
* test(router): e2e namespace …
=> fix(router): 0 value retention periods

generated_types/protos/influxdata/iox/namespace/v1/service.proto, influxdb_iox_client/src/client/namespace.rs
Document changes made in #6795.
---
* docs: namespace retention protobuf mappings (52ac1b97a)
Document that the caller can specify 0 or NULL for an infinite retention
period, and that IOx will respond with NULL.
Document that negative retention periods are rejected.
* docs: retention period values in Namespace client (77ff4dc4b)
Document the 0/null and negative value behaviours for retention periods
in the namespace RPC client.
=> docs: retention period value mappings

docker/Dockerfile.ci
This fixes the nightly CI image generation (probably).
We recently [rotated our security keys](https://www.influxdata.com/blog/linux-package-signing-key-rotation/) in response to a CircleCI security incident - this changes the build script to use the new key.
---
* ci: use new influx gpg signing key (8ca12d488)
We recently rotated our GPG keys:
https://www.influxdata.com/blog/linux-package-signing-key-rotation/
=> ci: use new influx gpg signing key

wal/src/blocking/reader.rs, wal/src/blocking/writer.rs, wal/src/lib.rs
The data is checksummed, but the actual checksum itself has no use outside of the WAL reader/writer.
---
* refactor: remove unused checksum field (6e6a439ef)
This unreachable checksum is meaningless outside of the WAL
reader/writer implementations.
* refactor: remove test-only checksum (b5ce0e4c4)
The correctness of data checksumming is validated by the tests as a
reader property (corrupt checksum -> error), the actual value of the
checksum is irrelevant.
=> refactor(wal): remove unused checksum

influxdb_iox/tests/end_to_end_cases/querier.rs
Part of https://github.com/influxdata/idpe/issues/17076
The first commit just ports the tests; the second commit un-nests the tests from the module and is probably easier to review without whitespace changes.
=> test: Port more query tests to kafkaless

Cargo.lock, influxdb_iox/Cargo.toml, influxdb_iox/tests/end_to_end_cases/mod.rs, influxdb_iox/tests/end_to_end_cases/router.rs, ioxd_common/src/http/error.rs
It turns out IOx has never returned a content-type header for errors! This change causes `content-type: application/json` to be returned alongside the JSON-encoded error payload.
As a bonus I've added an e2e that also ensures the `code` and `message` fields are always non-empty in the JSON error payload.
Fixes https://github.com/influxdata/idpe/issues/17083.
---
* fix: return content-type for HTTP errors (17d43ad4a)
No "Content-Type" header has ever been returned, even though the
response body has always been hard-coded to a JSON string.
This commit returns a content type of "application/json" for all
JSON-encoded HTTP errors.
* test(e2e): HTTP error response (0e1e5f01f)
Ensure a HTTP error response contains a well-formed JSON structure
containing "code" and "message" fields (for …
=> fix: correct http content-type header for error responses

clap_blocks/src/ingest_replica.rs, clap_blocks/src/ingester_address.rs, clap_blocks/src/lib.rs, clap_blocks/src/querier.rs, clap_blocks/src/router2.rs, influxdb_iox/src/commands/run/all_in_one.rs, ioxd_ingest_replica/src/lib.rs, ioxd_querier/src/lib.rs, ioxd_router/src/lib.rs
Fixes #6418.
Makes sure the querier, the router, and the ingest replica CLI all accept and validate ingester addresses the same, except whether or not at least one value is required.
I saw https://github.com/influxdata/influxdb_iox/pull/6740 that added enforcement that the address *must* contain a scheme, but sometimes I'm lazy and I don't want to type `http://` 😝
This doesn't _overwrite_ any existing scheme, but if there's _no_ scheme it'll assume `http://`.
This makes it so that `--ingester-addresses`/`INFLUXDB_IOX_INGESTER_ADDRESSES`  behaves exactly the same in:
- router2
- querier
- ingest replica (not used yet)
=> fix: Consolidate ingester address specification

compactor2/src/test_util.rs, data_types/src/lib.rs, iox_catalog/src/mem.rs, router/src/namespace_resolver/ns_autocreation.rs
I am blown away that there aren't more references to this struct to update 🤷 
Part of https://github.com/influxdata/influxdb_iox/issues/6492.
---
* refactor(catalog): expose deleted_at on Namespace (a85dcd745)
Add the new catalog column to the Namespace representation/model.
=> refactor(catalog): expose deleted_at on Namespace

router/tests/common/mod.rs, router/tests/grpc.rs
This change to the router's e2e testing harness allows us to simulate a router restart, and then uses that functionality to assert the current behaviour of retention period caching (https://github.com/influxdata/influxdb_iox/issues/6175).
This is a pre-requisite to having a similar test for namespace soft-deletion (https://github.com/influxdata/influxdb_iox/issues/6492).
---
* refactor(e2e): simulate router restart (ce12daa96)
Allow a router to be "restarted" within an e2e test.
* test(router): retention change after cache reset (4a0149a41)
Assert that the new retention period value is used once a router is
restarted and the cache converged.
=> test(router): router restarts + caching effects

data_types/src/sequence_number_set.rs
A pick of the first commit in https://github.com/influxdata/influxdb_iox/pull/6608 which I intend to close.
---
* refactor: SequenceNumberSet::as_bytes -> to_bytes (1805f7fbe)
The conversion is not (always) a cheap cast/conversion, and therefore
should be prefixed with "to_" and not "as_".
=> refactor: SequenceNumberSet::as_bytes -> to_bytes

compactor2/src/compactor.rs
This PR corrects a spelling mistake in an existing compactor done log message, and adds a log message as the compactor begins to shut down.  I'm not finding the existing `comapctor done`, or the `Compactor was not shut down properly` messages in the log.  A log message indicating we're beginning to shut down will make it easier to detect shut downs that time out, etc.
=> chore: add shutdown logging

clap_blocks/src/compactor2.rs, influxdb_iox/src/commands/run/all_in_one.rs, influxdb_iox/src/commands/run/compactor2.rs
This PR makes the default for compactor_config.query_exec_thread_count be one less than the CPU count, as discussed in the comments for https://github.com/influxdata/influxdb_iox/pull/7022, following the pattern used for https://github.com/influxdata/influxdb_iox/blob/b785f751b354c65d2e0548972f9e94b50e118612/clap_blocks/src/querier.rs#L50-L58
=> chore: change default for compactor_config.query_exec_thread_count 

wal/src/lib.rs, wal/src/writer_thread.rs
Moves the buffer serialisation, compression and blocking file syscalls / I/O from the async runtime threads.
This should help reduce the latency variance, which would be much more pronounced when running with fewer threads/cores.
---
* refactor: derive Debug on WAL types (d57b3319c)
Deriving debug is highly encouraged so that Result::unwrap() and friends
can print the state of an object if it is causing a panic (it's
impossible to call unwrap() otherwise!)
* perf(wal): use dedicated writer I/O thread (7c6d80c73)
Change the WAL buffer flusher to use a dedicated I/O thread instead of
performing serialisation & blocking file I/O on the async runtime
threads. This should reduce runtime blocking / latency variance on the
async threads.
The added overhead is 1 channel send, but this is per WAL …
=> perf(wal): dedicated file writer I/O thread

ingester2/src/query/result_instrumentation.rs
We already see 3 partitions in a low-volume cluster, so clearly we need more range in the histogram!
It's true ⬇️ 
---
* refactor(metric): increase partition bucket range (90f8166b4)
More buckets -> more better.
=> refactor(metric): increase partition bucket range

ingester/src/dml_sink/mod.rs, ingester2/src/buffer_tree/mod.rs, ingester2/src/buffer_tree/partition.rs, ingester2/src/buffer_tree/root.rs, ingester2/src/dml_sink/mod.rs, ingester2/src/ingest_state.rs, ingester2/src/ingester_id.rs, ingester2/src/init.rs, ingester2/src/lib.rs, ingester2/src/partition_iter.rs, ingester2/src/persist/handle.rs, ingester2/src/persist/hot_partitions.rs, ingester2/src/persist/mod.rs, ingester2/src/server/mod.rs
The ingester is composed of smaller, independent, decoupled components ("subsystems").
This documents what they are, and provides a high-level overview of the purpose & design of the ingester overall.
To view these rendered, run:
```shellsession
% cargo doc --open -p ingester2 --document-private-items
```
---
* docs: ingester overview documentation (3f2c03174)
Adds "overview" documentation for the ingester, including the high-level
purpose & design. Each subsystem is briefly documented, with links for
jumping-off points into more specific documentation.
* docs: module-level overviews (b0cf54098)
Adds one-liner documentation of what each module contains - this is
helpful to understand what is where, when looking at the rendered docs.
* docs(persist): fix-up handle usage (f0dd77cad) …
=> docs: ingester overview + subsystem docs

ingester2/src/cancellation_safe.rs, ingester2/src/dml_sink/instrumentation.rs, ingester2/src/dml_sink/tracing.rs, ingester2/src/lib.rs, ingester2/src/wal/wal_sink.rs
Fixes https://github.com/influxdata/influxdb_iox/issues/6281, a low risk/impact issue, but a pre-requisite for WAL reference counting (https://github.com/influxdata/influxdb_iox/issues/6566).
There's still a low risk / impact issue that remains, documented in https://github.com/influxdata/influxdb_iox/issues/7111.
---
* feat(ingester): cancellation-safe future helper (cf228fa38)
Allow a future to be wrapped such that it is always driven to completion
(obviously excluding deadlocks/process crashes).
* refactor: derive Clone on instrumentation wrappers (e442957ae)
If the inner types are Clone-able, the instrumentation wrappers become
clone-able too. Both wrappers are cheap to clone.
* fix: WAL/buffer commit cancellation safety (bde300c98)
Ensure that a write that is added to the WAL is …
=> fix(wal): write commit cancellation safety

ingester2/src/persist/drain_buffer.rs
🧹  
---
* style: remove unnecessary nesting (5c86f0570)
I'm not sure why rustfmt didn't do this, but it removes a level of
indenting.
=> style: remove unnecessary nesting

data_types/src/sequence_number_set.rs
Add the ability to compute the intersection between two `SequenceNumberSet` instances, pre-allocate and RLE optimise the underlying storage, and compare two sets for equality.
Necessary for #6566.
---
* feat(data_types): PartialEq for SequenceNumberSet (043f3421b)
Derive + test partial equality matching for SequenceNumberSet.
* feat: apply RLE optimisation for SequenceNumberSet (7801a6333)
Allow a SequenceNumberSet to be space-optimised by transforming it to
use run length encoding.
* perf: pre-allocation of SequenceNumberSet (146494f61)
Support pre-allocation of SequenceNumberSet for known-length sets.
* feat(data_types): SequenceNumberSet intersection (ac1b37c0f)
Support computing the intersection of two SequenceNumberSet.
=> feat: SequenceNumberSet intersection + helpers

.circleci/config.yml
This reverts commit d6265c988ff830f8980a9c5b645d06570103ee70.
It seems that Debian's skopeo is so horribly old or the packaging is so broken that you cannot run it out of the box as a normal non-root user. I need to fix the CI first before we can try again.
See https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/30392/workflows/a7b6ecf6-f56e-437b-82f6-430859ecb9bb/jobs/277181 .
=> revert: streamline CD (#7163)

compactor2/src/components/commit/metrics.rs, compactor2/src/components/partition_done_sink/metrics.rs, compactor2/src/components/partition_filter/metrics.rs, compactor2/src/components/partition_source/metrics.rs, compactor2/src/components/partitions_source/metrics.rs, compactor2/src/components/split_or_compact/metrics.rs, metric/src/counter.rs, metric/src/histogram.rs
Slight usability improvement :+1:
---
* refactor(metric): assert macro import scopes (45c8519a0)
The assert_counter! and assert_histogram! macros use items in the metric
crate, but the macros can be called from other crates/modules that may
not have those items in scope.
=> refactor(metric): assert macro import scopes

ingester2/src/server/grpc/query.rs
When ingester2 handles queries that target data that have previously been persisted and are no longer in the buffer tree, the handler logs a message at error. This is a bit noisy for an expected error state (the querier will have to go check object storage), so I've bumped it to `debug`.
---
* chore(ingester2): Log well-known query error at dbg ([`882d087`](https://github.com/influxdata/influxdb_iox/commit/882d087dd5636e6dd57561e42950436a55932178))
When the ingester handles a query for a table/namespace
that has been persisted and the data is not in the
buffer it logs at error level that the table/namespace
could not be found. This is a valid state and an
expected error (the data can be queried from object
storage), so we can make this less noisy.
=> chore(ingester2): Log well-known query errors at debug

influxdb_iox/tests/end_to_end_cases/cli.rs, test_helpers_end_to_end/src/config.rs, test_helpers_end_to_end/src/mini_cluster.rs
Putting back the test that I removed in
<https://github.com/influxdata/influxdb_iox/pull/6850>
now that they can use `run compactor2 --compaction-process-once --compaction-process-all-partitions`
thanks to <https://github.com/influxdata/influxdb_iox/pull/6886>!
=> test: Re-enable running compactor once in step tests

ingester2/tests/common/mod.rs, ingester2/tests/write.rs
Now we have ingester e2e tests, we can assert the behaviour of graceful shutdowns 🎉 
---
* test(ingester): graceful shutdown (eb72fbf3d)
Adds a ingester e2e test asserting the graceful shutdown behaviour;
specifically that:
* Buffered data is uploaded to object storage
* WAL files are cleaned up and empty (no replay on startup)
=> test(ingester): graceful shutdown

Cargo.lock, Cargo.toml, ioxd_common/Cargo.toml, ioxd_common/src/http/mod.rs, router/Cargo.toml, router/src/server/http.rs, server_util/Cargo.toml, server_util/src/authorization.rs, server_util/src/lib.rs
The router tried to access the "authorization" header of a request but that header gets stripped off by common code in the `ioxd_common` crate:
```rust
// we don't need the authorization header and we don't want to accidentally log it.
req.headers_mut().remove("authorization");
```
That code is there for a good reason (#1316): it's very easy to accidentally log an entire request including all the headers and thus leak tokens.
Luckily request extensions offer a nice way to attach custom data to a request without that being logged.
The extensions are "typed", which means that the crate that creates the extension and the crate that reads the extension must share a type.
Importing `ioxd_common` into the `router` is technically possible, but breaks the nice distinction between the `ioxd_<foo>` …
=> fix: Put authorization header in request extension

router/src/dml_handlers/rpc_write.rs, router/src/dml_handlers/rpc_write/balancer.rs, router/src/dml_handlers/rpc_write/upstream_snapshot.rs
Prevent an empty `UpstreamSnapshot` from being generated, moving the "there are no healthy upstream ingesters" error from write time, to before the first write is attempted.
---
* refactor: access upstream count in UpstreamSnapshot (2fefbc45c)
Adds a method to return the number of upstreams in an UpstreamSnapshot.
* refactor: disallow empty UpstreamSnapshot (8279ad161)
This simplifies the semantics of upstream RPC endpoint snapshots; an
empty snapshot will never be returned, and therefore if the caller has a
snapshot, it contains at least one endpoint to attempt an RPC call
against.
This moves the "no upstream" error handling from a write-time error, to
a pre-write error.
=> refactor: non-empty RPC endpoint sets

router/src/dml_handlers/rpc_write.rs, router/src/dml_handlers/rpc_write/client.rs
🧹 
---
* refactor(test): generic return iterator (874325d9c)
This change allows the MockWriteClient to accept more input types and
internalises the box dyn bits; I got tired of writing "Box::new()"
everywhere.
=> refactor(test): generic return iterator

compactor2/src/compactor.rs, compactor2/src/components/hardcoded.rs, compactor2/src/driver.rs, compactor2/src/error.rs, compactor2/src/partition_info.rs
Closes #7364.
When starting work on this, I thought saving the Parquet file state would happen earlier, such as when a partition was selected for compaction by the `partitions_source` (but after partition filtering, to save work). However, each `branch` loop of `try_compact_partition` potentially modifies the Parquet files in the catalog, so I think this is where the snapshotting has to happen: at the beginning of each `branch` loop, then checked in `update_catalog` before committing. Thus one compaction won't be seen as conflicting with itself :) Let me know if I'm missing a better way to do this.
I'm not sure a good way to test that this catches modifications to the catalog, other than calling `try_compact_partition` with a mock `partition_files_source`? There aren't currently any tests …
=> feat: Save Parquet file state and check it remains the same before committing compaction

clap_blocks/src/router.rs, clap_blocks/src/router2.rs, data_types/src/namespace_name.rs, influxdb_iox/src/commands/run/all_in_one.rs, ioxd_router/src/lib.rs, router/benches/e2e.rs, router/src/server/http.rs, router/src/server/http/write/mod.rs, router/src/server/http/write/multi_tenant.rs, router/src/server/http/write/params.rs, router/src/server/http/write/single_tenant.rs, router/src/server/http/write/v1.rs, router/src/server/http/write/v2.rs, router/tests/common/mod.rs
This PR builds on https://github.com/influxdata/influxdb_iox/pull/7331 - some minor logical changes, but mostly the same. This PR effectively moves some things around and tidies up some loose ends.
Note that the existing HTTP write test coverage has been preserved and runs in the default "run mode" (multi-tenant for cloud2) to assert no change to behaviour when this is deployed.
Additional per-mode tests have been added for multi-tenant and I will push a commit adding single-tenant tests tomorrow - opening this for early review - I don't anticipate any logic changes :+1:
Part of https://github.com/influxdata/idpe/issues/17265.
---
* test(router): constify test namespace (857a5afa5)
Define the namespace as a const to make the purpose/magic clear.
* feat(router): single tenancy operational …
=> feat(router): CST mode

ingester2/src/buffer_tree/partition/resolver/cache.rs, ingester2/src/buffer_tree/partition/resolver/catalog.rs, ingester2/src/buffer_tree/partition/resolver/coalesce.rs, ingester2/src/buffer_tree/partition/resolver/mock.rs, ingester2/src/buffer_tree/partition/resolver/mod.rs, ingester2/src/buffer_tree/partition/resolver/trait.rs, ingester2/src/buffer_tree/table.rs, ingester2/src/init.rs
This PR reduces the load on the catalog (and the ingester's catalog connection pool) in the presence of multiple concurrent writes for the same, non existing partition, when the catalog is down or otherwise slow enough to allow the requests to pile up.
This is a reliability / resource usage improvement that should have minimal overhead on the happy path.
---
* refactor: resolve Arc-wrapped PartitionData (435499e9d)
Changes the PartitionResolver trait to return a ref-counted
PartitionData instance, instead of a plain PartitionData (which is then
wrapped in an Arc anyway).
This allows resolver implementations to return multiple references to
the same physical instance.
* refactor: request coalescing partition resolver (b32a21d09)
Implement a new PartitionResolver decorator that coalesces …
=> feat: coalesce partition catalog fetches

Cargo.lock, data_types/src/namespace_name.rs, service_grpc_namespace/Cargo.toml, service_grpc_namespace/src/lib.rs
As found by @wiedld: namespaces created via the `NamespaceService` (the expected case in prod) did not apply validation. This hasn't been a problem, as in prod namespaces are always mapped to the opaque `orgid_bucketid` regardless of the input name.
This fix ensures the same validation happens with this API as the implicit/autocreation path.
Relates to https://github.com/influxdata/idpe/issues/17434 and https://github.com/influxdata/influxdb_iox/pull/7549.
---
* refactor: error message should not end in . (92b1055e4)
Change the "bad character" namespace name error to not include a
trailing "."
* test: invalid namespace name creation (54d4ca872)
Adds tests that attempt to create namespaces via the gRPC
NamespaceService with a variety of invalid names.
NOTE: this test currently fails!
* …
=> fix: consistent NamespaceName validation

ingester2/src/buffer_tree/partition/resolver/coalesce.rs
Patches up a hypothetical problem (though unreachable in practice) I introduced as part of #7559.
---
* test(ingester): use constants in coalesce test (23a6dfeda)
Clean up the CoalescePartitionResolver tests by using constants across
tests - I should have done this before but was rushing around!
* perf(ingester): avoid optimistic RMW operation (5e42c5be6)
Changes the CoalescePartitionResolver state cleanup path to avoid an
optimistic RMW operation against the atomic "has been cleaned up" flag.
This gives callers who are going to fail the opportunity to do so
quickly and cheaply, where all but one caller will fail.
* fix(ingester): always complete partition fetches (b0cc2bda0)
In #7559 I introduced code to coalesce N queries for a given partition
down to a single query, with the other …
=> fix(ingester): always drive partition resolve futures to completion

data_types/src/lib.rs, dml/src/lib.rs, ingester2/benches/write.rs, ingester2/src/buffer_tree/namespace.rs, ingester2/src/dml_sink/tracing.rs, ingester2/src/init/wal_replay.rs, ingester2/src/server/grpc/rpc_write.rs, ingester2/src/test_util.rs, ingester2/src/wal/wal_sink.rs, ingester2_test_ctx/src/lib.rs
Extracted from https://github.com/influxdata/influxdb_iox/pull/7049.
This takes care of a few TODO comments in the ingester.
=> fix: In DmlMeta, only use SequenceNumber rather than Sequence (shard index plus seq num)

Cargo.lock, router/Cargo.toml, router/src/namespace_cache/memory.rs
The new `NamespaceCache` API is a good candidate for a proptest - this PR is a nice example of composing together data generation methods to produce a randomised property test!
---
* test: property test namespace schema merging (9cc58eb4e)
This commit adds a randomised property test, that compares the results
of the new namespace cache schema merging (#7555) with a known-good
stdlib HashSet union (the cache implementation is effectively a more
specialised set union operation).
This property test also validates the "last writer wins" semantics for
other, non-schema data within the namespace.
Additionally the ChangeSet values returned over a pair of updates are
asserted to reflect the actual values added to the cache (but not each
call individually) to ensure accurate metrics are reported.
=> test: property test namespace schema merging

.config/hakari.toml, Cargo.lock, Cargo.toml, deny.toml, garbage_collector/Cargo.toml, iox_data_generator/Cargo.toml, iox_data_generator/src/bin/iox_data_generator.rs
Fixes https://github.com/influxdata/influxdb_iox/issues/5065.
Related to https://github.com/influxdata/influxdb_iox/pull/7568.
Ugh I thought the git source was causing `cargo-deny` to fail in https://github.com/influxdata/influxdb_iox/pull/7704, but now I see that was just a warning and that PR is failing for a different reason. But the work's done now sooo 🤷🏻‍♀️
=> fix: Use only humantime; get rid of chrono-english

influxdb_influxql_parser/src/select.rs, iox_query_influxql/src/plan/ir.rs, iox_query_influxql/src/plan/planner.rs, iox_query_influxql/src/plan/rewriter.rs, iox_query_influxql/src/plan/util.rs
Helps #7739
This PR addresses [@crepererum's primary concern](https://github.com/influxdata/influxdb_iox/pull/7727#discussion_r1183718466) by no longer relying on the `is_tag_field` API, which was fragile. With this change, we are now able to determine schema accurately and this sets the foundation for implementing subqueries.
> **Note**
>
> There is still planned work to the intermediate representation following this PR.
=> refactor: Remove fragile `is_tag_field` API

ingester2/src/buffer_tree/namespace.rs, ingester2/src/buffer_tree/partition/resolver/cache.rs, ingester2/src/buffer_tree/partition/resolver/coalesce.rs, ingester2/src/buffer_tree/partition/resolver/trait.rs, ingester2/src/buffer_tree/root.rs, ingester2/src/buffer_tree/table.rs, ingester2/src/dml_sink/instrumentation.rs, ingester2/src/dml_sink/tracing.rs, ingester2/src/persist/handle.rs, ingester2/src/persist/mod.rs, ingester2/src/test_util.rs
https://github.com/influxdata/influxdb_iox/pull/7651 refactored a bunch of test code to re-use stuff - some of that stuff causes problems, and @carols10cents fixed it in this PR: https://github.com/influxdata/influxdb_iox/pull/7673
I've picked the commits into a new PR while we work on #7673 to get the fixes merged ASAP :+1:
---
* fix: don't share Executor instances between tests (edf5b310e)
And remove some executor instances where they're not even being used
* fix: don't share DeferredLoad instances between tests (537874042)
=> test(ingester): fix flappy tests

data_types/src/columns.rs, mutable_batch/src/lib.rs, parquet_file/tests/metadata.rs, schema/src/builder.rs
Closes #7764 
Changes `schema` methods to accept `impl Into<String>` instead of `&str` so that caller can decide whether to own it or now. I am not sure if the added flexibility is worth the monomorphization hit the compile time would end up with. Considering it is only couple of methods this shouldn't matter, I wonder if it would affect if this type of changes introduced to everywhere.
=> refactor: accept `impl Into<String>` instead of `&str` for schema methods

garbage_collector/src/objectstore/checker.rs, import/src/aggregate_tsm_schema/update_catalog.rs, ingester/src/buffer_tree/partition/resolver/catalog.rs, ingester/src/test_util.rs, ingester_test_ctx/src/lib.rs, iox_catalog/src/interface.rs, iox_catalog/src/lib.rs, iox_catalog/src/postgres.rs, iox_catalog/src/sqlite.rs, iox_tests/src/catalog.rs, ioxd_router/src/lib.rs, router/tests/http.rs, service_grpc_catalog/src/lib.rs, service_grpc_object_store/src/lib.rs, service_grpc_schema/src/lib.rs
In the custom partitioning work, I've been changing the function interface of creating namespaces and tables in the catalog. We've been trying different exact implementations in different PRs like #7713 and #7790, and I wouldn't be surprised if I end up changing the interfaces again when all is said and done.
There are a bunch of places in various tests that create _a_ namespace or _a_ table but these places aren't testing namespaces or tables, they just need those records to put other stuff into the catalog. All of these places create namespaces and tables in exactly the same way, and whenever I change the interface, I have to update all these places. And I'm tired 😴 
Additionally, this PR also changed the interface for creating namespaces in a different way than I am, so that PR also …
=> refactor: Extract some catalog test helper methods to reduce places that need to change

ingester/src/init.rs, ingester/src/persist/completion_observer.rs, ingester/src/persist/context.rs, ingester/src/persist/file_metrics.rs, ingester/src/persist/mod.rs, ingester/src/persist/worker.rs, ingester/src/wal/reference_tracker/handle.rs, ingester/tests/write.rs, ingester_test_ctx/src/lib.rs
This PR adds a metric observer to the Ingester's persist subsystem that captures various statistics about the generated files.
These statistics will help us quantify the effects of tuning the system for less frequent file generation.
---
* refactor: parquet metadata in persist notification (507ccc2eb)
Changes the CompletedPersist notification data structure to embed the
generated parquet file's metadata for completion observers.
* feat: persisted Parquet file attribute metrics (3114c67cf)
Implements a PersistCompletionObserver that records various attributes
of the generated and persisted Parquet file as histogram metrics to
capture the distribution of values:
* File size
* Row count
* Column count
* Time range of data (max - min timestamp)
These metrics will give us insight into the …
=> feat(metrics): Parquet file attribute statistics

ingester/src/persist/file_metrics.rs
Who knew?
---
* fix: correct time range buckets (0a31afd00)
Turns out there are 60 seconds in a minute, not 3,600.
=> fix: correct time range buckets

wal_inspect/src/lib.rs
Some small additions to `wal_inspect` I've been making during my implementation of the CLI command. 
This makes 2 changes. First, batch writing behaviour is now a trait so that generic code can operate on writers with different `Fn(NamespaceId) -> Result<W: Write, Error>` write sink closures. Second is to make the Table ID -> Table Name index optional for instances where table names are not needed/catalog lookup is not available. When no index is provided IDs are used as measurement names.
---
* refactor(wal_inspect): Make namespaced table batch writing a trait (e7a0ed4b2)
This change allows callers to treat LineProtoWriter instances with
different write sink generators the same using generic parameters.
* feat(wal_inspect): Make table_name_index optional for line proto writing …
=> feat(wal_inspect): Make table batch writing a trait, support table ID based line protocol

influxdb_iox/tests/end_to_end_cases/cli.rs, influxdb_iox/tests/end_to_end_cases/compactor.rs, influxdb_iox/tests/end_to_end_cases/ingester.rs, influxdb_iox/tests/end_to_end_cases/querier.rs, influxdb_iox/tests/end_to_end_cases/querier/multi_ingester.rs, influxdb_iox/tests/end_to_end_cases/remote.rs, influxdb_iox/tests/query_tests/cases.rs, influxdb_iox/tests/query_tests/framework.rs, influxdb_iox/tests/query_tests/setups.rs, test_helpers_end_to_end/src/steps.rs
If the test setup calls `Step::Persist` to persist on-demand, that means it shouldn't be used with `ChunkStage::Parquet`, which tries to persist as fast as possible. This will fail the test with a hopefully helpful message to prevent this.
Also a bonus removal of straggling "2"s!
=> test: Add an invalid test configuration checker and fix potentially flaky test setups it detects

clap_blocks/src/router.rs, influxdb_iox/src/commands/run/all_in_one.rs, router/src/dml_handlers/rpc_write.rs, router/tests/common/mod.rs
This change only effects the help text, not the behaviour.
---
* refactor(cli): update replication help text (82500720e)
The replication flag defines the total number of copies of each write -
slightly less confusing than the additional copies it was previously,
and matches with the actual code.
=> refactor(cli): update replication help text

iox_catalog/migrations/20230524095337_remove_unused_parquet_file_indices.sql
Remove unused Postgres indices. This lower database load but also gives us room to install actually useful indices (see #7842).
To detect which indices are used, I've used the following query (on the actual write/master replicate in eu-central-1):
```sql
SELECT
n.nspname                                      AS namespace_name,
t.relname                                      AS table_name,
pg_size_pretty(pg_relation_size(t.oid))        AS table_size,
t.reltuples::bigint                            AS num_rows,
psai.indexrelname                              AS index_name,
pg_size_pretty(pg_relation_size(i.indexrelid)) AS index_size,
CASE WHEN i.indisunique THEN 'Y' ELSE 'N' END  AS "unique",
psai.idx_scan                                  AS number_of_scans,
psai.idx_tup_read …
```
=> refactor: remove ununused `parquet_file` indices

iox_catalog/src/interface.rs, iox_catalog/src/mem.rs, iox_catalog/src/postgres.rs, iox_catalog/src/sqlite.rs
It's not possible to remove this because our testing setup is a bit circular.... but at least this removes it from the prod code, which should make it less likely to be used incorrectly.
---
* refactor(catalog): mark metrics() as test only (2094b45c1)
This method is used to enable tests - it's never intended to be used in
production code to access the underlying metric registry. The Catalog
trait is responsible for Catalog things, not acting as a dependency
injection for metrics.
The only current use of this is in test code, so no changes needed.
=> refactor(catalog): mark metrics() as test only

Cargo.lock, Cargo.toml, data_types/src/partition_template.rs, generated_types/build.rs, generated_types/protos/influxdata/iox/table/v1/service.proto, generated_types/src/lib.rs, influxdb_iox/tests/end_to_end_cases/namespace.rs, ioxd_router/src/lib.rs, router/Cargo.toml, router/src/server/grpc.rs, router/tests/grpc.rs, service_grpc_namespace/src/lib.rs, service_grpc_table/Cargo.toml, service_grpc_table/src/lib.rs
This adds a table creation gRPC API to the router that enables setting a custom partition template for the table.
=> feat: table creation gRPC API with optional custom table template

iox_query_influxql/src/plan/planner.rs, iox_query_influxql/src/plan/rewriter.rs
This PR is some minor housekeeping I extracted from another branch so it can be used sooner.
I separated out the `scope` from the `Context` in the planner, as this concern does not belong in the `Context` structure. In particular, it results in unnecessary copying for each transformation of a column in the projection:
https://github.com/influxdata/influxdb_iox/blob/928731767e98ed5d108e45d8594ee328ae907366/iox_query_influxql/src/plan/planner.rs#L926
and when transforming the `WHERE` condition:
https://github.com/influxdata/influxdb_iox/blob/928731767e98ed5d108e45d8594ee328ae907366/iox_query_influxql/src/plan/planner.rs#L1258-L1262
=> chore: Minor cleanup

Cargo.toml, clap_blocks/Cargo.toml, compactor/Cargo.toml, compactor_test_utils/Cargo.toml, datafusion_util/Cargo.toml, garbage_collector/Cargo.toml, influxdb_iox/Cargo.toml, ingester/Cargo.toml, ingester_test_ctx/Cargo.toml, iox_query/Cargo.toml, iox_tests/Cargo.toml, ioxd_querier/Cargo.toml, ioxd_router/Cargo.toml, object_store_metrics/Cargo.toml, parquet_file/Cargo.toml, parquet_to_line_protocol/Cargo.toml, querier/Cargo.toml, router/Cargo.toml, service_grpc_object_store/Cargo.toml
I really wanted a single place to change the `object_store` dependency specification the other and it was annoying to have to find it in a bunch of crates
Make `object_store` a workspace dependency
=> chore: use workspace dependencies for `object_store`

data_types/src/lib.rs, ingester_test_ctx/src/lib.rs, iox_catalog/src/interface.rs, iox_catalog/src/lib.rs, iox_catalog/src/mem.rs, iox_catalog/src/metrics.rs, iox_catalog/src/postgres.rs, iox_catalog/src/sqlite.rs, mutable_batch/src/payload.rs, mutable_batch/src/payload/partition.rs, mutable_batch/tests/writer_fuzz.rs, router/src/dml_handlers/partitioner.rs, router/src/dml_handlers/schema_validation.rs, service_grpc_namespace/src/lib.rs, service_grpc_table/src/lib.rs
I'll be linking to the module directly later, so it needs to be visible outside the crate.
---
* refactor: explicit submod for partition_template (9e0570f2b)
Move the import into the submodule itself, rather than re-exporting it
at the crate level.
This will make it possible to link to the specific module/logic.
=> refactor: explicit submod for partition_template

router/Cargo.toml, router/benches/partitioner.rs, router/benches/schema_validator.rs
You can't improve what you can't measure! At least not intentionally.
---
* test(bench): router partitioner (a873e119c)
Adds a benchmark that exercises the router's partitioning DmlHandler
implementation against a set of three files (very small, small, medium)
with 4 different partitioning schemes:
* Single tag, which occurs in all rows
* Single tag, which does not occur in any row
* Default strftime formatter (YYYY-MM-DD)
* Long and complicated strftime formatter
This covers the entire partitioning overhead - building the formatters,
evaluating each row, grouping the values into per-partition buckets, and
returning to the caller, where it normally would be passed to the next
handler in the pipeline.
Note that only one template part is evaluated in each case - this
measures the overhead …
=> test(bench): router partitioner

mutable_batch/src/payload/partition.rs, router/tests/grpc.rs
This is a very simple optimisation that nets up to ~18% partitioner throughput increase by reducing the number of times the partition key buffer string must be grown, therefore eliminating preventable allocations.
In the common case (using a default partitioning template of YYYY-MM-DD) every partition key is of identical length, so this reduces the number of allocations needed for the string buffer to 1 per row.
More optimisations to come!
---
* refactor: remove InvalidStrftime value (8e61dc5ae)
It's big, it's annoying, it's already available to the user.
* perf: preallocate partition key strings (ea3dcba30)
Partition keys tend to be approximately the same size each time (and in
the default case, always exactly the same size).
This simple change reduces allocations by pre-sizing the next …
=> perf: pre-allocate partition key string buffer

Cargo.lock, data_types/Cargo.toml, data_types/src/partition_template.rs, ingester_test_ctx/src/lib.rs, iox_catalog/src/interface.rs, iox_catalog/src/lib.rs, iox_catalog/src/postgres.rs, iox_catalog/src/sqlite.rs, mutable_batch/src/payload/partition.rs, router/benches/partitioner.rs, router/tests/grpc.rs, service_grpc_namespace/src/lib.rs, service_grpc_table/src/lib.rs
Fixes #7895.
On creation of custom partition templates, they are checked that they have:
- At least one part
- No more than 8 parts
- Only nonempty, valid strftime formats
=> feat: Validate custom partition templates on their creation

Cargo.lock, data_types/src/partition_template.rs, mutable_batch/Cargo.toml, mutable_batch/src/payload/partition.rs, mutable_batch/src/payload/partition/strftime.rs
This PR bounds both the individual parts within a partition key, and the number of parts allowed in a key - this effectively bounds the overall size of the key to 1,607 bytes (1.57 KiB).
The reversal function that reconstructs the tag column values from the partition key now emits a tuple of `(column_name, column_value_enum)` which encodes the valid operations (equality/prefix-match) into the type system.
Closes #7900.
---
* feat: truncate partition key parts at 200 bytes (050093df1)
This commit ensures all partition key parts are less than or equal to
200 bytes long.
If a string exceeds the 200 byte limit, it is truncated (avoiding
splitting unicode code-points or graphemes) and then a single "#"
sentinel value is appended. When reversed from the string, these column
values are indicated …
=> feat: bound partition key size

influxdb_iox/src/commands/sql.rs
The `influxdb_iox sql` command, unlike the `influxdb_iox query` command or generally other flighsql clients, fails if the endpoint doesn't implement flight healthcheck API. 
Somtimes we serve IOx behind a reverse proxy that doesn't pass throught the flight helthcheck gRPC requests and thus we cannot use the `influxdb_iox sql` REPL because of that, which is annoying.
We _could_ fix the reverse proxy configs, but we can also decide to make `influxdb_iox sql` less skittish.
=> fix: influxdb_iox sql command warns on flight healthcheck failure

influxdb_iox/tests/end_to_end_cases/querier.rs, test_helpers_end_to_end/src/config.rs, test_helpers_end_to_end/src/mini_cluster.rs, test_helpers_end_to_end/src/server_fixture.rs, test_helpers_end_to_end/src/steps.rs
This was a quick test to confirm file discovery was working as expected after graceful shutdown of the ingesters.
---
* refactor(e2e): const server graceful stop timeout (a2f2f9ef6)
Allow the timeout to be referenced in docs, and increase it a bit - it's
it a bit close to being too low for ingester shutdown persistence to
complete.
* feat(e2e): step to gracefully stop ingesters (c933c1532)
Adds a step that gracefully stops all ingesters (stop - not restart -
they don't come back!)
* feat(e2e): assert absolute parquet count (de9392c01)
An existing pair of e2e steps allows the caller to assert an increase in
the number of persisted parquet files, but there was no primitive to
assert the current count.
* feat(e2e): configurable querier circuit breakers (fd15b2e71)
Allow the querier's circuit …
=> test(e2e): ingester shutdown persist file discovery

compactor_scheduler/src/local_scheduler/partitions_source/catalog_to_compact.rs
This PR Is a followon and complementary change to https://github.com/influxdata/influxdb_iox/pull/8112 from yesterday changing the same area of code, but for a different issue.
We've seen the compactor spam the catalog with queries when its idle.  But it doesn't do this in every idle circumstance.  If it is completely idle (no partitions seeing any activity) it doesn't hit the catalog very hard.
When its mostly idle, like many partitions all receiving data trickle in, that's when the catalog may get spammed with many requests.
I believe the cause of spamming the catalog in a semi-idle state results from the hard coded 10m lookback for "hot" partitions that may need compacted.  If the compactor is idle enough that it can get through the batch of hot partitions quickly (e.g. 2m), the next …
=> fix: don't redundantly evaluate the same partitions for compaction

iox_catalog/migrations/20230707195110_add_created_at_index.sql
Closes # https://github.com/influxdata/idpe/issues/17850
This PR adds an index for `created_at` to the partition table.  The compactor frequently queries based on `created_at` to find partitions with recent activity.
=> chore: create index on created_at in partition table

ingester/src/buffer_tree/root.rs, ingester/src/buffer_tree/table.rs
https://github.com/influxdata/influxdb_iox/issues/8221
Will improve https://github.com/influxdata/idpe/issues/17884
---
* perf: only send metadata for relevant partitions (7bd6e9083)
When partition pruning is possible, it skips sending the data for
partitions that have no affect on the query outcome.
This commit does the same for the partition metadata - these frames can
form a significant portion of the query response when the row count is
low, and for pruned partitions have no bearing on the query result.
=> perf: only send metadata for relevant partitions

Cargo.lock, influxdb_iox/src/commands/run/all_in_one.rs, influxdb_iox/src/commands/run/router.rs, ingester/benches/query.rs, ingester/benches/write.rs, ingester/src/server/grpc/rpc_write.rs, ingester/tests/query.rs, ingester/tests/write.rs, ingester_test_ctx/Cargo.toml, ingester_test_ctx/src/lib.rs, ioxd_router/src/lib.rs, querier/src/ingester/mod.rs, router/Cargo.toml, router/src/dml_handlers/rpc_write.rs, router/src/dml_handlers/rpc_write/balancer.rs, router/src/dml_handlers/rpc_write/circuit_breaking_client.rs, router/src/dml_handlers/rpc_write/client.rs, router/src/dml_handlers/rpc_write/lazy_connector.rs, router/src/server/http.rs
This resolves #6177, by encoding the Jaeger format trace context into the RPC write request and inheriting from it at the Ingester's RPC handler.
Here's a screenshot from running the following against an all-in-one mode instance:
```
influxdb_iox write company_sensors test_fixtures/lineproto/metrics.lp --host http://localhost:8080 --gen-trace-id
```
The details on spans and their hierarchy could be looked at in a follow up PR if needed - this PR doesn't make any new opinions on how the trace should look.
Maybe this should be `chore`? I'm not very consistent with that semcommit 😅 
---
* feat(router): Send tracing SpanContext header to ingester during RPC write (5a37c92c2)
* feat(ingester): Extract SpanContext from RPC write request (458b1bf1a)
Ensure that if a `SpanContext` type is present …
=> feat(router): Propagate tracing spans for RPC write to Ingester

iox_catalog/migrations/20230714154828_make-kafka-columns-nullable.sql
First small step for towards https://github.com/influxdata/influxdb_iox/issues/6217.
This just allows the columns to be nullable and drops related foreign key constraints. I've tested this in a scenario with two routers, and ingester and a querier all on the old db schema having processed some writes and queries, before performing the migration and rolling one of the routers to the new version. All the old services seem happy to serve requests after the change has been made.
=> refactor(catalog): Allow kafka columns to be nullable

iox_catalog/migrations/20230720132400_modify_parquet_file_triggers.sql, iox_catalog/sqlite/migrations/20230720132400_parquet_file_triggers.sql, iox_catalog/src/interface.rs, iox_catalog/src/mem.rs
This PR updates `new_file_at` for all new files. Previously, it only updated `new_file_at` for new L0s and L1s. I've observed on backed up partitions, if they have a lot of L1s to compact to L2s, they may time out during that.  In that case, since all they were doing is creating new L2s, `new_file_at` wasn't updated, allowing the partition to become cold.  So it never finishes compacting.
Helps: https://github.com/influxdata/idpe/issues/17902
=> fix: update new_file_at following all compactions

compactor/src/components/round_info_source/mod.rs, compactor/tests/layouts/stuck.rs
If there is a single start level file (e.g. L0), and `max_num_files_per_plan` target level files (e.g. L1), then it would try to do target level to target level (L0->L0) compactions.  But we can't compact it to less than a single L0 file, so it loops forever.
helps: https://github.com/influxdata/idpe/issues/17902
=> fix: avoid compacting 1 L0 to 1 L0 file (stuck looping)

data_types/src/partition_template.rs, router/tests/grpc.rs
By rejecting `time` for TagValue parts and preventing it during template construction code-paths this should be enough to close #8320.
---
* fix: Reject `time` as a tag value for custom partition templates (aac4166bf)
Time has a special meaning and can be partitioned on by the strftime
formatter. It should not be used as a tag value part in a custom
partitioning template.
=> fix: Reject `time` as a tag value for custom partition templates

compactor/src/components/hardcoded.rs, compactor/src/components/partition_files_source/catalog.rs, compactor/src/components/partition_files_source/rate_limit.rs, compactor/src/components/partition_stream/endless.rs
While marking cold partitions hot a few thousand at a time, I'm seeing the rate limiter stray from its 5m target quite a bit (15m, 20m).  I think the cause is the variability in the rate at which it processes partitions.
This PR allows the rate limiter to have a configured burst balance, so after a period of inactivity it will allow a few queries at a higher rate.  To start, I'm allowing it to burst up to 25 queries.  That's not very many, but I'm thinking it won't take very many to smooth it out and keep the overall rate close to target.
helps: https://github.com/influxdata/idpe/issues/17902
=> chore: improve rate limiter accuracy

ingester/benches/query.rs, ingester/benches/write.rs, ingester/tests/query.rs, ingester/tests/write.rs, ingester_test_ctx/src/lib.rs
If you can't measure it, you're not optimising it.
---
* test(bench): ingester query partition pruning (32414acb0)
Adds benchmarks that exercise partition pruning during query execution
within the ingester, for varying partition counts within a table, and
varying row counts within each partition.
=> test(bench): ingester query partition pruning

clap_blocks/src/router.rs, influxdb_iox/src/commands/run/all_in_one.rs, ioxd_router/src/lib.rs, router/src/dml_handlers/rpc_write.rs, router/src/dml_handlers/rpc_write/balancer.rs, router/src/dml_handlers/rpc_write/circuit_breaker.rs, router/src/dml_handlers/rpc_write/circuit_breaking_client.rs, router/tests/common/mod.rs
This PR exposes the `ERROR_WINDOW` parameter as a way to tune router <-> ingester on-path health checking for different volumes of writes.
My thinking is that for now, extending the duration within which the error rate is assessed provides an opportunity to smooth out errors in low volume clusters over a period of time, while keeping current `#[inline]` functions in place. If we need more leniency then we can follow up and allow `MAX_ERROR_RATIO` to be configurable.
---
* feat(router): Expose circuit breaker healthcheck config (61e79374e)
Exposes the `ERROR_WINDOW` parameter that controls the router's
downstream error-gate health check behaviour as an environment
variable/command line flag. This allows tuning, per-environment, the
period over which the error rate of 80% must be exceeded …
=> feat(router): Expose circuit breaker healthcheck `ERROR_WINDOW` for config 

ingester/src/dml_payload/write/op.rs, ingester/src/init/wal_replay.rs
While this doesn't prevent a mid-write crash from potentially resulting in an empty write op appearing in the WAL, it does tolerate it during start-up and track its occurrence. The user would not have got an `OK` response for the write so skipping is consistent with this.
---
* fix(ingester): Skip empty writes with no data during WAL replay (3133f9c2e)
In very rare cases a panic mid-write can result in a partially completed
write to the WAL which contains no table data. This is now not replayed
(as there is nothing to replay) and does not panic when encountered,
but tracks the occurence into the WAL replayed ops metric and logs a
warning.
=> fix(ingester): Skip empty writes with no data during WAL replay

Cargo.lock, compactor/Cargo.toml, compactor/src/components/hardcoded.rs, compactor/src/components/partition_stream/endless.rs, compactor/src/components/partition_stream/mod.rs, compactor/src/components/partition_stream/once.rs, compactor/src/components/partitions_source/logging.rs, compactor/src/components/partitions_source/metrics.rs, compactor/src/components/partitions_source/mock.rs, compactor/src/components/partitions_source/mod.rs, compactor/src/components/partitions_source/not_empty.rs, compactor/src/components/partitions_source/randomize_order.rs, compactor/src/components/partitions_source/scheduled.rs, compactor/src/driver.rs, compactor_scheduler/src/lib.rs, compactor_scheduler/src/partitions_source.rs, compactor_scheduler/src/scheduler.rs
Part of https://github.com/influxdata/idpe/issues/17789
Move the compactor to have awareness of `CompactionJob`, not just partition id. This meant:
* ensuring that the CompactionJob was exposed to all required levels of the compactor concurrency and branching.
* this includes where the update_job_status() and end_job() messages are transmitted. 
* easiest way was to enable the source of our partitions (a.k.a. PartitionsSource and PartitionStream) to provide `CompactionJob`
The functional changes are in this PR.
All the renamings (no functional changes) are in [this followup PR](https://github.com/influxdata/influxdb_iox/pull/8326).
---
* refactor(idpe-17789): move PartitionsSource to be separate traits in scheduler vs compactor (82d55fd6b)
* chore(idpe-17789): make PartitionsSource be …
=> feat(idpe-17789): provide CompactionJob throughout compactor

ingester/src/buffer_tree/partition/buffer.rs, ingester/src/buffer_tree/partition/buffer/state_machine.rs, ingester/src/buffer_tree/partition/buffer/state_machine/buffering.rs, ingester/src/buffer_tree/partition/buffer/state_machine/persisting.rs, ingester/src/buffer_tree/partition/buffer/state_machine/snapshot.rs, ingester/src/buffer_tree/partition/buffer/traits.rs
This PR allows us to (later) re-use batch snapshot schemas, instead of regenerating them for every query.
Less is definitely more :rocket:
---
* perf(ingester): reusable FSM / RecordBatch schemas (41c9c0f39)
Cache the merged Schema of all the RecordBatch within a buffer at
snapshot generation time.
To be useful, this cached schema is made available to the PartitionData
for re-use, allowing the schema of "hot" data within a partition's
mutable buffer to be read without generating a RecordBatch first.
=> perf(ingester): reusable FSM / RecordBatch schemas

compactor/src/components/compaction_job_stream/mod.rs, compactor/src/components/compaction_jobs_source/logging.rs, compactor/src/components/compaction_jobs_source/metrics.rs, compactor/src/components/compaction_jobs_source/mock.rs, compactor/src/components/compaction_jobs_source/mod.rs, compactor/src/components/compaction_jobs_source/randomize_order.rs, compactor/src/components/partition_source/mock.rs, compactor/src/driver.rs
Follow-up to https://github.com/influxdata/influxdb_iox/pull/8326.
Rename some internal variables.
Also did some updates to the code docs. Decided to highlight (for any random future dev) that we have 1 job == 1 partition; reason being that much of the compaction job stream then gets consumed by various `partition_*` abstractions which only care about the `partition_id`. Therefore, wanted to make the (current) relationship clear.
---
* refactor(idpe-17789): rename local variables and private struct properties to jobs (versus partitions). (d7fee9fdb)
* chore(idpe-17789): update code comments to reflect both jobs and partitions (9a7ff9ecf)
=> refactor(idpe-17789): rename internal variables

Cargo.lock, ingester/src/init.rs, tracker/Cargo.toml, tracker/src/disk_metric.rs
Just a small change to return a `tokio::sync::watch::channel::Receiver` with a disk usage snapshot to any listeners from the metric tracker.
---
* refactor(tracker): Return disk usage watcher from `DiskUsageMetrics` (8e0cee8e7)
This allows the creator to pass around a handle to the latest observed
disk usage statistics, allowing other threads to act upon changes.
=> refactor(tracker): Return disk usage watcher from `DiskUsageMetrics`

ingester/src/buffer_tree/partition.rs, ingester/src/buffer_tree/partition/buffer/mutable_buffer.rs, ingester/src/buffer_tree/partition/buffer/state_machine.rs, ingester/src/buffer_tree/partition/persisting.rs, ingester/src/buffer_tree/partition/persisting_list.rs
This PR both _simplifies_ and _speeds up_ querying of persisting batches of data! :rocket:
It moves statistic computation and schema union-ing from query time (which can happen an unbounded number of times) to batch-persist time (which happens exactly once per batch), and caches the resulting data for subsequent queries.
This improves performance linear to the number of persisting batches - it's effectively an unbounded improvement.
---
* perf(ingester): persisting list & cached statistics (13d60ed01)
This commit breaks the ordered list of persisting buffers into its own
type (PersistingList) for clarity, and implements a cache within it of
the merged set of schemas across all persisting buffer FSMs, and
row/timestamp summaries.
This cleans up the code, and prevents N persisting schemas …
=> perf(ingester): persisting list & cached statistics

clap_blocks/src/router.rs, influxdb_iox/src/commands/run/all_in_one.rs, ioxd_router/src/lib.rs, router/src/dml_handlers/rpc_write.rs, router/src/dml_handlers/rpc_write/balancer.rs, router/src/dml_handlers/rpc_write/circuit_breaker.rs, router/src/dml_handlers/rpc_write/circuit_breaking_client.rs, router/tests/common/mod.rs
Follow-up to https://github.com/influxdata/idpe/issues/17928.
---
* feat(router): Expose `num_probes` request count used to health-check ingesters as config option (e4a5d2efa)
This allows routers to be configured to mark downstreams as healthy/
unhealthy with a requirement for the number of probe requests
which can/must be collected to transition the health checkers circuit
state to healthy/unhealthy.
=> feat(router): Expose `num_probes` request count used to health-check ingesters as config option

generated_types/build.rs, generated_types/protos/influxdata/iox/gossip/v1/message.proto, generated_types/src/lib.rs
The router's will gossip schema diffs to interested peers - this PR defines the format of those messages.
Note that _differentials_ are sent to peers, and not the entire schema. This cuts down on unnecessary write amplification caused by retransmitting 100 tables with 100 columns when adding a single column. Because of this, convergence is best effort, which is as strong as we need, as schema cache misses go to the source-of-truth (catalog).
---
* feat(proto): schema gossip message definitions (081dc03a3)
Define the gossip message types used to disseminate schema changes to
other peers.
Currently there are two types defined: an initial "create" operation,
intended to be followed by "update" operations where appropriate. Both
messages are trivial CRDTs in that they are effectively add-only …
=> feat(gossip): schema diff message proto

router/src/gossip/dispatcher.rs, router/src/gossip/handle.rs, router/src/gossip/mod.rs, router/src/lib.rs
This PR adds the types that'll form part of the schema gossip subsystem within the router.
---
* feat(router): schema gossip skeleton (41c9604e4)
Adds the supporting types required to integrate the generic gossip crate
into a schema-specific broadcast primitive.
This commit implements the two "halves":
* GossipMessageDispatcher: async processing of incoming gossip msgs
* Handle: the send-side handle for async sending of gossip msgs
These types are responsible for converting into/from the serialised
bytes sent over the gossip primitive into application-level / protobuf
types.
=> feat(router): schema gossip skeleton

ioxd_router/src/lib.rs, router/src/gossip/mod.rs, router/src/gossip/namespace_cache.rs, router/src/namespace_cache.rs, router/src/server.rs
Lets do it :rocket:
This PR adds more docs, more tests, and then the bits necessary to slot it into the router runtime.
After this PR is merged, clusters that are configured to use gossip will start gossiping schema changes to each other! Currently this is only an internal staging cluster, with a wider rollout soon.
---
* refactor: remove redundant NamespaceCache impl (3133318e1)
The NamespaceCache does not need to be a decorator itself - it can
operate using a reference to the cache without needing access to cache
requests.
* docs(router): gossip subsystem types / topology (16c115d5c)
Describes the router's schema gossiping types and how they fit together.
* test: schema gossip integration (00542f704)
Adds an integration test ensuring the schema gossip layer added to one
instance ("node …
=> feat(router): intra-cluster schema diff gossiping 

querier/src/table/mod.rs, querier/src/table/test_util.rs
Extracted from https://github.com/influxdata/influxdb_iox/pull/8412, which now depends on this one merging successfully first.
Connects to #8066.
This PR changes the querier to:
- Not filter out partitions if they're not in the cache (currently all partitions are in the catalog+cache because the ingester creates them on the first write for the partition, but soon the ingester won't create the partition in the catalog until the first persist
- If the partition isn't in the querier's partition cache, set partition column ranges starting from an empty column range 
- Not prune ingester chunks because the ingester is already pruning them
=> feat: Just the querier changes needed for using the bloom filter to avoid catalog requests in the ingester

ingester/src/buffer_tree/partition.rs, ingester/src/buffer_tree/partition/resolver/cache.rs, ingester/src/buffer_tree/partition/resolver/mod.rs, ingester/src/buffer_tree/partition/resolver/old_filter.rs, ingester/src/buffer_tree/partition/resolver/sort_key.rs, ingester/src/init.rs, iox_catalog/src/interface.rs, iox_catalog/src/mem.rs, iox_catalog/src/metrics.rs, iox_catalog/src/postgres.rs, iox_catalog/src/sqlite.rs, test_helpers_end_to_end/src/mini_cluster.rs, test_helpers_end_to_end/src/steps.rs
~~THIS DEPENDS ON https://github.com/influxdata/influxdb_iox/pull/8475 MERGE THAT FIRST~~ Merged!
Closes #8066 
This PR:
- Wires up the `OldPartitionBloomFilter` so that when the ingester resolves the partition, it doesn't go to the ingester's partition cache or the catalog if it's definitely a new-style partition
- When the ingester fetches the sort key from the catalog for persistence, upsert the partition at that point rather than expecting it to exist
- Have end-to-end tests asking the catalog for partitions explicitly ask the ingester to persist before making the catalog request
I *think* all this is correct. Please review commit-by-commit!
=> feat: Use the bloom filter to reduce ingester catalog queries, Luke

Cargo.lock, Cargo.toml, data_types/src/columns.rs, gossip_schema/Cargo.toml, gossip_schema/src/dispatcher.rs, gossip_schema/src/handle.rs, gossip_schema/src/lib.rs
This PR adds the (currently unused) `gossip_schema` crate, that layers the schema-specific messages / logic onto the underlying `gossip` transport crate.
This is designed to make listening for schema changes easy in IOx - initialise a `gossip` instance, initialise the `SchemaRx` and receive a callback for each incoming schema change event :rocket:
A follow-up PR will switch the router to use this crate, removing the bespoke implementation currently in use. All of the logic in this PR is copy/pasted from the current router implementation.
---
* refactor: ColumnsByName::from_iter() (55631a4f8)
Allow a ColumnsByName to be constructed by collecting a set of (name,
column_schema) tuples.
* feat: implement gossip_schema crate (2e77507f7)
Adds a new gossip_schema crate that provides a high-level …
=> feat: reusable schema notifications via gossip_schema crate

ingester/src/persist/completion_observer.rs, ingester/src/persist/context.rs, ingester/src/persist/file_metrics.rs, ingester/src/persist/queue.rs, ingester/src/persist/worker.rs, ingester/src/test_util.rs
This change propagates the full metadata of newly persisted files to persist completion observers.
No functional change in this PR - nothing needs those fields yet.
---
* refactor(ingester): full parquet file metadata (6ccf3324e)
Include the full ParquetFile metadata when invoking
PersistCompletionObserver implementations, instead of the
ParquetFileParams subset.
=> refactor(ingester): full parquet file metadata

ingester/src/persist/completion_observer.rs, ingester/src/wal/reference_tracker/handle.rs
:clean:
---
* refactor: impl observer where type defined (a5df75371)
Implement the PersistCompletionObserver for the WalReferenceHandle
alongside the WalReferenceHandle type, instead of the other way around.
=> refactor: impl observer where type defined

ioxd_common/src/rpc.rs
This forces TCP_NODELAY to be enabled for all IOx gRPC servers.
We definitely want NODEALY enabled :+1:
---
* perf: enable TCP_NODELAY on gRPC servers (652300400)
This change forces TCP_NODELAY to be set, which is the default for
tonic, and is enabled by default, but is silently discarded when using
serve_with_incoming_shutdown().
=> perf: enable TCP_NODELAY on gRPC servers

compactor/src/components/split_or_compact/start_level_files_to_split.rs
This PR helps https://github.com/influxdata/idpe/issues/17974
This PR is a followup to https://github.com/influxdata/influxdb_iox/pull/8506
I noticed a cluster with a lot of backlog with highly nonlinearly distributed data was having trouble computing suitable regions for the data distribution.  This caps the calculations at 10,000.  That doesn't mean there will be 10,000 regions, its just estimating data distribution for that many, then it consolidates similar regions before actually splitting files.  Its possible this means we'll need to split more than once, but if there's that much backlog its probably best not to try to deal with it all at once anyway.
After https://github.com/influxdata/influxdb_iox/pull/8559 goes in I want to make more changes related to very highly backlogged …
=> chore: limit compactor region count computations

router/benches/schema_validator.rs
This was broken and now it isn't.
---
* fix(bench): schema validator bench panic (932532c3e)
The benchmark code was completely broken - running the benches would
immediately panic.
=> fix(bench): schema validator bench panic

router/src/lib.rs
This was mildly annoying me :)
---
* ci: lint failures as warnings (9055bc175)
Don't fail to compile / run tests because of an unreachable pub, or
missing debug impl - just emit a compiler warning.
This lets the compilation complete, but isn't accepted in PRs as CI runs
with "deny warnings".
=> ci: lint failures as warnings

router/benches/namespace_schema_cache.rs, router/src/gossip/anti_entropy/actor.rs, router/src/gossip/anti_entropy/handle.rs, router/src/gossip/anti_entropy/merkle.rs, router/src/gossip/anti_entropy/mod.rs
This PR introduces an actor+handle responsible for maintaining the merkle search tree, moving it out of the hot write path, and ensuring callers are decoupled.
---
* test(bench): MerkleTree overhead (31c8b04d6)
Layers the MerkleTree over the NamespaceCache stack in benchmarks to
measure the overhead.
* perf(anti_entropy): add AntiEntropyActor for MST (51c018bac)
Separate the management of the Merkle Search Tree state into an actor
to manage concurrent access.
This moves hashing and tree updates off of the hot request path, and
into an asynchronous background process, practically eliminating
overhead for maintaining the MST structure.
This decoupling will allow convergence runs between peers to proceed
without causing contention on the lock in the request hot path.
=> perf: asynchronously maintain merkle search tree

Cargo.lock, gossip/Cargo.toml, gossip/src/handle.rs, gossip/src/peers.rs, gossip/src/reactor.rs, gossip/tests/smoke.rs
This lets us send frames to a subset of gossip members, instead of all of them.
This will be handy when we want to periodically perform a consistency check, but without full N^2 spamming.
---
* feat(gossip): broadcast to randomised peer subset (43db19b7d)
Provide a new broadcast_subset() method to gossip users, enabling a
message to be sent to a random subset of peers that have a registered
interest in the message being dispatched.
=> feat(gossip): broadcast to randomised peer subset

gossip/src/dispatcher.rs, gossip/src/handle.rs, gossip/src/lib.rs, gossip/src/peers.rs, gossip/src/reactor.rs, gossip/tests/smoke.rs, gossip_parquet_file/src/rx.rs, gossip_schema/src/dispatcher.rs
When a callback receives a message, provide it with the opaque peer identity of the sender.
76dafa511 allows a caller to use this identity to discover the sender's socket address, which can be used as a simple primitive for discovering service addresses.
We'll use gossip to have the routers say "hey, do we need to perform a sync round?" to converge cache state, and if the answer is "yes", we'll use this identity / socket address lookup functionality to derive the RPC address of the peer, and then use a TCP-based RPC interface to reliably perform the actual sync operation.
---
* refactor(gossip): remove Uuid from Identity (f81f6efb2)
The identity contains both a UUID, and the byte representation of this
UUID. This change retains the latter, generating the former on-demand
(which is rarely …
=> feat(gossip): expose peer identity & socket address

generated_types/protos/influxdata/iox/namespace/v1/service.proto, generated_types/protos/influxdata/iox/table/v1/service.proto, influxdb_iox/tests/end_to_end_cases/cli/helpers.rs, influxdb_iox/tests/end_to_end_cases/cli/namespace.rs, influxdb_iox/tests/end_to_end_cases/cli/table.rs, ioxd_querier/src/rpc/namespace.rs, service_grpc_namespace/src/lib.rs, service_grpc_table/src/lib.rs
Closes #8576.
Just a small one to expose partition templates for namespaces and their tables through the current set of proto interfaces. Follow up PRs for new commands and requests will continue to do so for any new methods 👍 
---
* feat(namespace): Return namespace custom partition templates to API (e6ab51a2d)
This exposes the custom partitionining scheme of a namespace (if any)
in the response to namespace create and list calls.
* feat(table): Return PartitionTemplate in table create proto response (125135399)
If tables can be created with a custom partition template (or the namespace
has a custom partition template) then this should be exposed to the user
interacting with it through the CLI too!
=> feat(cli): Queries for namespaces and tables should return their `PartitionTemplate`

data_types/src/lib.rs, service_grpc_table/src/lib.rs
Implements the new `GetTables` RPC method for the `TableService`.
Part of #8618
---
* refactor(proto): Impl `From<Table>` to proto `Table` (1007989cd)
* chore(table): Add missing assertion for None partition template (8d4731734)
* feat(table): GetTables gRPC endpoint implementation (f110aee26)
=> feat(table): `GetTables` gRPC endpoint implementation

generated_types/protos/influxdata/iox/gossip/v1/schema_sync.proto
🥔 
---
* refactor(proto): unsigned port numbers (3a2e70157)
I was trying to remember what the notation for integer types was in
proto - -1 is not a port number...
=> refactor(proto): unsigned port numbers

buf.yaml
We should catch breaking changes for the ingester->querier protobufs as well.
=> chore: apply proto lints to ingester->query gRPC

influxdb_iox/src/commands/table/create.rs, influxdb_iox/src/commands/table/list.rs, influxdb_iox/src/commands/table/mod.rs, influxdb_iox/tests/end_to_end_cases/cli/table.rs, influxdb_iox_client/src/client/table.rs
This will close #8618. This uses the `<DATABASE>` terminology in the help text, as that seems to be what the `table create` command intended. The proto types amongst other bits use `namespaceId` still though 😅 
Looks something like this:
```shell
% influxdb_iox table list bananas_database
[
{
"id": "1",
"name": "platanos",
"namespaceId": "1"
},
{
"id": "2",
"name": "ananas",
"namespaceId": "1"
},
{
"id": "3",
"name": "bananas",
"namespaceId": "1",
"partitionTemplate": {
"parts": [
{
"timeFormat": "%Y-%m"
},
{
"tagValue": "great"
}
]
}
}
]
```
---
* feat(cli): Add `table list <DATABASE>` command (2a396c1b7)
This commit hooks the influxdb_iox_client and CLI up to the new
`GetTables` gRPC endpoint on the `TableService`, allowing users to
query a list of tables within a database and …
=> feat(cli): Add `table list <DATABASE>` command

wal/src/blocking/reader.rs
🧹🧹🧹
No need for the mem shenanigans and `&mut` signature now that https://github.com/BurntSushi/rust-snappy/pull/54 has merged with `into_inner()`.
---
* refactor(wal): Consume `CrcReader` when invoking `checksum()` (b969d07bc)
=> refactor(wal): Consume `CrcReader` when invoking `checksum()`

ingester/src/persist/compact.rs, ingester/src/persist/worker.rs
Tidy up the sort key "data flow" during persist (who has what information, and where that information goes).
---
* refactor(persist): load sort key once (8853296be)
Passes the already-loaded sort key into update_catalog_sort_key()
This makes the function inputs clear, and avoids loading the same key
twice (which should be a no-op now, but not in the future!).
* refactor: remove Result from infallible return (e5e12ebb1)
The compact_persisting_batch() call is infallible, but prior to this
commit, would return a Result with a () unit type as the error type.
This is misleading - it's never going to return an error, so call sites
checking for errors are misleading.
=> refactor(persist): load sort key once

generated_types/build.rs, generated_types/protos/influxdata/iox/gossip/v1/compaction.proto
Define the gossip message schema that'll be sent when a compaction completes.
This is aiming to enable https://github.com/influxdata/idpe/issues/17854 to increase query performance.
---
* feat(gossip): define CompactionEvent protobuf (855e8bb34)
This commit adds the CompactionEvent protobuf type that'll be gossiped
between peers to provide a (compact) description of completed
compactions.
=> feat(gossip): define CompactionEvent protobuf

generated_types/protos/influxdata/iox/gossip/v1/schema_sync.proto
Names are important.
---
* refactor(proto): SyncMessage -> ConsistencyProbe (96d099a29)
Rename "SyncMessage" to "ConsistencyProbe" - it's a clearer name for the
use - the message does no syncing!
=> refactor(proto): SyncMessage -> ConsistencyProbe

Cargo.lock, Cargo.toml, generated_types/src/lib.rs, gossip_compaction/Cargo.toml, gossip_compaction/src/lib.rs, gossip_compaction/src/rx.rs, gossip_compaction/src/tx.rs
Adds the "gossip_compaction" crate that layers compaction-specific logic over the underlying gossip crate to present a simpler API to callers.
Defines the new `CompactionEvents` gossip topic to separate out the compaction events from other messages.
---
* refactor(gossip): add Topic::CompactionEvents (044d5bfdc)
This adds a separate compaction event gossip topic.
* feat(gossip): add gossip_compaction crate (c0b4a1087)
Adds a crate that layers compaction-specific gossip types and
abstractions over the underlying gossip transport for a nicer (and
decoupled!) internal API.
=> feat(gossip): compaction events crate

router/src/namespace_cache.rs
🧹 
---
* docs: remove outdated cache race warning (b200d82d0)
Concurrent writes to the cache no longer overwrite each other - entries
are now merged.
=> docs: remove outdated cache race warning

ioxd_router/src/lib.rs, router/benches/namespace_schema_cache.rs, router/benches/schema_validator.rs, router/src/dml_handlers/schema_validation.rs, router/src/gossip/anti_entropy/mst/actor.rs, router/src/gossip/schema_change_observer.rs, router/src/namespace_cache.rs, router/src/namespace_cache/memory.rs, router/src/namespace_cache/metrics.rs, router/src/namespace_cache/read_through_cache.rs, router/src/namespace_cache/sharded_cache.rs, router/src/namespace_resolver.rs, router/src/namespace_resolver/ns_autocreation.rs, router/tests/common/mod.rs
This was driving me a little crazy!
The `MemoryNamespaceCache` is often the lowest-level implementation of `NamespaceCache` in a chain of decorators, and it had an unnecessary `Arc` due to the actual impl - this kinda propagated everywhere.
This PR only removes an unnecessary `Arc` wrapper 👍 
It makes for less confusing types/code, but also removes some pointer indirection (though LLVM probably saw through that already).
---
* refactor: remove Arc from MemoryNamespaceCache (51096119b)
Prior to this commit, the NamespaceCache was only implemented for
Arc<MemoryNamespaceCache> instead of the cache type itself.
In the vast majority of cases, this Arc wrapper is completely
unnecessary - it adds both runtime overhead, and code/type complexity.
This commit impls NamespaceCache for any …
=> refactor(router): remove unnecessary Arc wrapper in NamespaceCache stack

ingester/src/buffer_tree/partition.rs, ingester/src/buffer_tree/partition/resolver/cache.rs, ingester/src/buffer_tree/partition/resolver/catalog.rs, ingester/src/buffer_tree/partition/resolver/coalesce.rs, ingester/src/buffer_tree/partition/resolver/mock.rs, ingester/src/buffer_tree/partition/resolver/old_filter.rs, ingester/src/buffer_tree/partition/resolver/trait.rs, ingester/src/buffer_tree/root.rs, ingester/src/buffer_tree/table.rs, ingester/src/buffer_tree/table/metadata.rs, ingester/src/buffer_tree/table/metadata_resolver.rs, ingester/src/persist/compact.rs, ingester/src/persist/context.rs, ingester/src/test_util.rs
🧹 
This just moves the table metadata - no functional change.
---
* refactor: move table metadata alongside resolver (9379a227c)
We already have a metadata resolver, so lets stick the metadata types
next to it.
=> refactor: move table metadata alongside resolver

ingester/src/buffer_tree/namespace.rs, ingester/src/buffer_tree/partition/resolver/cache.rs, ingester/src/buffer_tree/partition/resolver/coalesce.rs, ingester/src/buffer_tree/partition/resolver/mock.rs, ingester/src/buffer_tree/partition/resolver/trait.rs, ingester/src/buffer_tree/root.rs, ingester/src/buffer_tree/table.rs, ingester/src/persist/handle.rs, ingester/src/test_util.rs
No functional change, but allows the mocked partitions to be constructed with the instances of deferred loaders (etc) that are used by the buffer tree itself.
This makes testing a little simpler in an upcoming PR, but I think it'll be nice in general.
---
* test: accept PartitionDataBuilder in provider (429d90cde)
Use the PartitionDataBuilder in the MockPartitionProvider, allowing the
test caller to specify any necessary parameters, but still allow the
mock provider to inject the arguments it was called with.
=> test: accept PartitionDataBuilder in provider

Cargo.lock, influxdb_iox/Cargo.toml, influxdb_iox/src/commands/run/ingester.rs, workspace-hack/Cargo.toml
Have the ingesters automatically use half the CPU cores for DF, instead of always trying to use 4.
This might reduce the performance of persist when cores < 4, increasing the time taken to process N tasks, but the throughput reduction will be less than you might expect because DF wouldn't have had full use of the cores that were also serving API requests anyway.
Nothing is even close to saturating the persist queues as far as I am aware, so I believe this to be totally fine to change without needing to reconfigure prod anywhere.
---
* perf: use half of logical cores for persist exec (1bb4c0806)
Changes the default ingester configuration to assign half the logical
cores to datafusion for persist execution. Prior to this commit,
datafusion always used 4 threads by default.
In situations …
=> perf: use half of logical cores for persist exec

ingester/src/buffer_tree/namespace.rs, ingester/src/buffer_tree/partition.rs, ingester/src/buffer_tree/partition/counter.rs, ingester/src/buffer_tree/partition/resolver/cache.rs, ingester/src/buffer_tree/partition/resolver/catalog.rs, ingester/src/buffer_tree/partition/resolver/coalesce.rs, ingester/src/buffer_tree/partition/resolver/mock.rs, ingester/src/buffer_tree/partition/resolver/old_filter.rs, ingester/src/buffer_tree/partition/resolver/trait.rs, ingester/src/buffer_tree/root.rs, ingester/src/buffer_tree/table.rs, ingester/src/test_util.rs
This changes the previously-merged per-namespace partition limit to only consider _non-empty partitions_ during enforcement. It also tightens up the consistency semantics of the counter, removing any (minor) racy overshoot of the limit.
The previous limit would cause a problem: given a long enough ingester uptime, the limit would always be hit, even for a workload that touches only one partition per day! If the limit was set to 10, and a user was writing to 1 partition per day, after 10 days they'd be locked out. 
This no longer happens, as only _non-empty_ partitions are limited now, so in the example above, there'd be 9 empty partitions, and 1 non-empty that's evaluated for limiting. This correctly limits what we want to limit: the number of parittions that can end up on the persist …
=> feat(ingester): limit non-empty partitions per namespace

Cargo.lock, router/Cargo.toml
This picks up a more efficient way of constructing page range snapshots from owned values that'll be used in API requests in a follow-up PR:
https://docs.rs/merkle-search-tree/latest/merkle_search_tree/diff/struct.OwnedPageRange.html
---
* build: pick up latest merkle-search-tree version (33a441fbe)
Pick up the improvements allowing construction of PageRangeSnapshots
from owned keys / no cloning.
=> build:  latest merkle-search-tree version

querier/src/parquet/creation.rs, querier/src/parquet/mod.rs, querier/src/table/metrics.rs, querier/src/table/mod.rs
This should lower query latency, because creating many chunks just to throw them away afterwards isn't exactly cheap.
Closes #8705.
=> feat: prune partitions before creating parquet chunks

router/src/gossip/anti_entropy/mst/actor.rs, router/src/gossip/anti_entropy/mst/handle.rs, router/src/gossip/anti_entropy/mst/mod.rs
This lets holders of a handle to the MST generate a concise "snapshot" of the MST state.
This snapshot can be cheaply transmitted across the network between peers (it's orders of magnitude smaller than a fully populated MST) and is used to compute inconsistencies between peers.
This is currently unused, but needed for a follow-up PR.
---
* feat: merkle search tree snapshot generation (ec96545c3)
Allow an owned, compact content summary snapshot of the merkle search
tree state to be read from the MST actor.
This snapshot describes the structure of the MST in a compact/efficient
representation suitable for exchanging over the network between peers.
=> feat: merkle search tree snapshot generation

rust-toolchain.toml
Pick up latest rust.
---
* build: bump rust to 1.72.1 (3c9f28283)
https://github.com/rust-lang/rust/releases/tag/1.72.1
=> build: bump rust to 1.72.1

ioxd_router/src/lib.rs, router/benches/schema_validator.rs, router/src/dml_handlers/mod.rs, router/src/dml_handlers/schema_validation.rs, router/src/dml_handlers/trait.rs, router/src/lib.rs, router/src/schema_validator.rs, router/src/server/http.rs, router/tests/common/mod.rs, router/tests/grpc.rs, router/tests/http.rs
Extracted from https://github.com/influxdata/influxdb_iox/pull/8682.
The first commit is as close to just moving the existing code to a new file as I could get, then the second commit is only the type changes and computation of the arguments being moved around to make sharing this code possible, because  the upsert schema API won't have batches, just columns.
=> feat: Prepare SchemaValidator to be shared with schema upsert as well as writes

iox_catalog/src/lib.rs, router/src/schema_validator.rs
Extracted from https://github.com/influxdata/influxdb_iox/pull/8682.
Reviewing commit-by-commit should be straightforward. The usage of the extracted functions in another place isn't included in this PR, but I do have a branch locally using these successfully.
=> refactor: Extract more functionality that schema upsert will need too

Cargo.lock, data_types/src/columns.rs, router/Cargo.toml, router/src/gossip/anti_entropy/mod.rs, router/src/gossip/anti_entropy/sync/actor.rs, router/src/gossip/anti_entropy/sync/consistency_prober.rs, router/src/gossip/anti_entropy/sync/mock_consistency_prober.rs, router/src/gossip/anti_entropy/sync/mock_rpc_client.rs, router/src/gossip/anti_entropy/sync/mod.rs, router/src/gossip/anti_entropy/sync/rpc_worker.rs, router/src/gossip/anti_entropy/sync/traits.rs
This PR builds on #8780, consuming the merkle search tree content and eventually using it to drive eventual consistency of the schema cache content across gossip peers.
This PR introduces the client-side sync mechanism driving eventual consistency of the schema cache content across gossip peers, using the sync protocol described in https://github.com/influxdata/influxdb_iox/pull/8753.
A follow-up PR will introduce the server-side component this client interacts with.
---
* refactor: ColumnsByName default impl (9493ce74a)
The ColumnsByName type can/should default to an empty set.
* feat(router): schema cache anti-entropy/sync actor (ee0334dab)
Adds the foundational components of the router anti-entropy subsystem.
This subsystem compliments the existing schema gossiping mechanism to
provide …
=> feat(router): schema cache anti-entropy/sync actor

router/src/gossip/anti_entropy/sync/rpc_worker/mod.rs, router/src/gossip/anti_entropy/sync/rpc_worker/worker_task.rs
:broom:
---
* refactor: move RpcWorker into a submod (2177d3a0a)
Organise a little in preparation for more rpcworker type things.
=> refactor: move RpcWorker into a submod

data_types/src/namespace_name.rs, router/src/gossip/anti_entropy/mst/actor.rs, router/src/gossip/anti_entropy/mst/handle.rs
Teaches the AntiEntropyActor to perform a merkle tree diff when given a `MerkleSnapshot` from another peer, returning the difference between the local MST and the snapshot.
This diff isn't symmetrical, and from the perspective of the API caller providing the snapshot, the node on which the diff is computed is the peer. The returned diff response describes what pages the _caller_ needs to pull from the _differ_.
---
* perf: don't execute ops for dead callers (bc7260916)
Operations against the AntiEntropyActor that fetch data for the caller
(with ~no other side effects) can be optimised out when the caller is no
longer waiting for the answer (i.e. API call timeout, etc).
* perf: efficient NamespaceName -> String conversion (a4b1ded8e)
Allow a NamespaceName constructed from a String to be …
=> feat(router): Merkle Search Tree diff computation support

router/src/gossip/anti_entropy/sync/actor.rs, router/src/gossip/anti_entropy/sync/mock_rpc_client.rs, router/src/gossip/anti_entropy/sync/rpc_worker/mod.rs, router/src/gossip/anti_entropy/sync/rpc_worker/task_set.rs, router/src/lib.rs
This PR adds logic to throttle _outgoing_ anti-entropy sync tasks, preventing more than 3 from running at any one time, and preventing more than one task syncing against the same upstream peer.
---
* feat: sync task concurrency restrictions (9ffccd9d6)
This commit introduces a MergeTaskSet, responsible for limiting the
number of concurrent outbound sync tasks at any one time, and preventing
concurrent sync tasks running against the same peer.
The MergeTaskSet encapsulates this behaviour entirely, and any tasks
that are prevented from starting are logged for debugging purposes.
Dropping the MergeTaskSet causes the tasks it is managing to be aborted.
* refactor: abort sync tasks on drop (1ea31f77d)
Ensure sync tasks never outlive the MergeTaskSet by aborting the tasks
when the task handles …
=> feat(router): sync task concurrency restrictions

router/src/gossip/anti_entropy/mst/actor.rs, router/src/gossip/anti_entropy/mst/handle.rs
Allow a caller to ask the MST "what keys do your consistency proofs cover?"
This will allow us to extract the keys that need to be synced when we have identified a range of keys that are inconsistent. Put another way, given the range `[bananas, platanos]` we can ask the MST "what keys are between `bananas` and `platanos` that you care about?" and it'll return the set (obviously the correct answer is `bananas, donkey, platanos`).
Test in the next PR which ties together (and tests) everything MST :+1:
---
* feat(router): query merkle tree for key ranges (86608c72f)
Allow an AntiEntropyHandle holder to query the actor (and in turn, the
merkle tree) for the keys (namespaces) the tree covers within a given
lexicographic range.
=> feat(router): query merkle tree for key ranges

clap_blocks/src/catalog_dsn.rs
See https://github.com/influxdata/influxdb_iox/pull/8728
---
* docs: mark sqlite as for non-production use only (c17b61b7a)
The sqlite-based catalog is not maintained to a level which allows it to
be used for production workloads.
See https://github.com/influxdata/influxdb_iox/pull/8728
=> docs: mark sqlite as for non-production use only

router/src/gossip/anti_entropy/mod.rs, router/src/gossip/anti_entropy/mst/merkle.rs, router/src/gossip/anti_entropy/mst/mod.rs
:broom: and determinism :+1:
---
* refactor: move prop generators to gossip module (6d9a18033)
Move the arbitrary namespace / table / column generators used for
property testing to the parent "gossip" module, so they can be shared
across the sync implementation tests too.
* test: deterministic table name -> IDs generators (74b8fe0e4)
Changes the property test NamespaceSchema generators to
deterministically build consistent table name -> table ID mappings in
the generated schemas.
This prevents "table X has ID Y but gossip message maps table X to Z"
panics - an invariant upheld by IOx, but which was not respected by the
test generators.
=> refactor: move prop data generators and deterministic ID mapping

router/src/gossip/anti_entropy/mst/actor.rs, router/src/gossip/anti_entropy/mst/merkle.rs
This PR adds (or rather, uses the existing) field mask that ensures only the content the anti-entropy system is (currently!) capable of syncing forms part of the consistency checks.
---
* feat: selective NamespaceSchema field MST coverage (64e0d20a3)
Move and use the NamespaceContentHash to restrict the field coverage of
merkle tree content hashes over NamespaceSchema's.
Only the schema elements are to be part of the anti-entropy protocol (at
first!) as only these fields are CRDTs / deterministically merge-able.
Therefore the MST hashes must only consider these fields when deciding
if two nodes are consistent, as only these fields will be converged.
=> feat: selective NamespaceSchema field MST coverage

Cargo.lock, router/Cargo.toml, router/src/gossip/anti_entropy/mst/actor.rs, router/src/gossip/anti_entropy/sync/actor.rs, router/src/gossip/anti_entropy/sync/mod.rs
This PR adds a integration test of the entire anti-entropy system, asserting that it can converge two randomly populated `NamespaceCache`.
This tests all the logic of anti-entropy without spawning any actual servers - the (already well tested) gRPC transport and the gossip transport (for consistency probes) are coming up next.
---
* refactor: clearer log message for MST updates (394788602)
"applying schema" doesn't say what it is being applied to!
* refactor: delay initial sync trigger (669fe6669)
Don't immediately dispatch a consistency probe when the router starts
up, when it may be under higher initial load.
* test: anti-entropy integration sync (c7d900369)
This commit adds an integration test that covers:
* Merkle tree construction
* Schema cache observer (propagating to merkle tree) …
=> test: anti-entropy integration sync

router/src/gossip/anti_entropy/sync/consistency_prober.rs
Defines a gossip `Dispatcher` for anti-entropy consistency probes, and an adaptor that resolves the sender's socket address (used for service discovery / deriving the sync RPC address).
---
* feat(sync): gossip consistency probe rx (b8ede4c54)
Implements a gossip Dispatcher for anti-entropy consistency probes,
including an adaptor to translate the stream of probes into a stream of
probes + sender addresses (resolved from the sender's identity via the
gossip peer list).
See the service discovery section on the ConvergenceActor.
* test: gossip consistency probe integration (8cfb707fc)
Initialise the gossip transport, and use it to send a consistency probe,
asserting the receiver correctly deserialises it, and correctly resolves
the sender's socket address.
=> feat(gossip): consistency probe dispatcher

gossip_schema/src/handle.rs, gossip_schema/src/lib.rs, influxdb_iox/src/commands/run/all_in_one.rs, influxdb_iox/src/commands/run/router.rs, ioxd_router/src/lib.rs, router/src/gossip/anti_entropy/mst/handle.rs, router/src/gossip/anti_entropy/sync/rpc_server.rs, router/src/server.rs, router/src/server/grpc.rs, router/tests/common/mod.rs
This initialises the anti-entropy subsystem and enables it on nodes that are configured to partake in schema gossiping.
---
* refactor: extract gossip init into fn (a7da69c52)
No functional change - just pulls the optional gossip init into a
function of its own.
* refactor: share gossip handle (7e4418719)
Wrap the gossip handle in an Arc to share it across subsystems.
* feat(router): anti-entropy service (f5764f460)
This commit binds the anti-entropy service to the gRPC server, and
initialises the ConvergenceActor and associated plumbing to enable the
anti-entropy subsystem iff gossip is enabled on the node.
* refactor: remove dead code lints (5b84bb668)
It's no longer dead code!
=> feat(router): anti-entropy service

Cargo.lock, Cargo.toml, workspace-hack/Cargo.toml
Closes https://github.com/influxdata/project-clustered/issues/116
Closes https://github.com/influxdata/project-clustered/issues/111
This PR switches to TLS native certs. IOx will use the CA roots defined by the OS (usually by the container in which it runs).
This allows customers to inject their own custom CA certificates.
---
The `ca-certificates` apt package is installed in our Dockerfile
```console
$ grep ca-certificates **/Dockerfile
&& apt install --yes ca-certificates gettext-base libssl3 --no-install-recommends \
```
=> fix: Use native roots

ioxd_router/src/lib.rs
⚡ It's alive!
---
* feat: enable schema cache gossiping (4340749d9)
This enables the schema cache consistency probes between router gossip
peers.
=> feat: enable schema cache gossiping

ioxd_router/src/lib.rs, router/src/gossip/anti_entropy/sync/rpc_server.rs, router/src/gossip/anti_entropy/sync/rpc_worker/grpc_connector.rs
The current limit limits syncs to about 0.08% of a cache :fire:
---
* refactor: increase maximum grpc sync message size (6572a500d)
The default (4MiB) limit doesn't allow for many schemas to be
transferred, and causes sync failures when large diffs need exchanging.
=> refactor: increase maximum grpc sync message size

compactor/src/components/namespaces_source/mock.rs, data_types/src/lib.rs, data_types/src/service_limits.rs, iox_catalog/src/interface.rs, iox_catalog/src/mem.rs, iox_catalog/src/postgres.rs, iox_catalog/src/sqlite.rs, iox_tests/src/catalog.rs, ioxd_querier/src/rpc/namespace.rs, router/benches/namespace_schema_cache.rs, router/benches/partitioner.rs, router/benches/schema_validator.rs, router/src/dml_handlers/schema_validation.rs, router/src/gossip/anti_entropy/mod.rs, router/src/gossip/anti_entropy/sync/rpc_worker/worker_task.rs, router/src/gossip/namespace_cache.rs, router/src/namespace_cache/memory.rs, router/src/namespace_cache/metrics.rs, router/src/schema_validator.rs, router/src/server/http.rs, router/tests/grpc.rs, router/tests/http.rs, service_grpc_namespace/src/lib.rs
Connects to influxdata/idpe#18100. There's still a little bug and some needed tests that need to be done to close out that issue.
This changes the newtypes added in the previous commit to properly validate MaxTables and MaxColumnsPerTable values whether they're coming from protobuf, the CLI, or the database (because the database stores i32s and there's a chance of invalid values in there, and we don't want to crash if that's the case!).
=> fix: fixing validation of max tables/max columns per table
