influxdata/influxdb_iox

packers/src/packers.rs, packers/src/sorter.rs
This adds support for `String` packers backed by a `std::string::String`. This is useful when generating test data as it's cheaper to deal with `Strings` than the Parquet `ByteArray` in several situations.
=> feat: add String support to Packers

data_types/src/error.rs, data_types/src/lib.rs, src/server/rpc/storage.rs
Rationale:
I was trying to trace down a test failure that happens on https://github.com/influxdata/delorean/pull/328, but there was no mention of an error in the logs. After looking into it, it turns out that the error was being swallowed by spawned task  -- nothing checked return results and thus the error was not logged
This PR adds logging to operations in the tasks so the errors can be debugged more easily.
=> fix: Log errors if they happen on separate tokio tasks

segment_store/Cargo.toml, segment_store/benches/dictionary.rs, segment_store/src/column.rs, segment_store/src/column/dictionary.rs
This PR enables an optimisation for producing `RowID` sets on a column when providing an equality predicate. In this specific but common case I already have the logical row ids for each distinct logical value on the RLE columns. They're maintained as compressed bitmaps on the column. These bitsets will also be utilised during grouping.
I added a benchmark that exercises applying an equality predicate to an RLE column and then materialises the resulting values at the matching logical rows.
<details>
<summary>Benchmark Results</summary>
```code
Running target/release/deps/dictionary-96a531812a599449
encoding_rle_select/rows_100000/loc_Start/card_100                                                                             
time:   [3.9631 us 3.9838 us 4.0056 us]
thrpt:  [24.965 Gelem/s …
```
=> perf: enable row ID bitset optimisation for equality predicates

.circleci/config.yml
I got an email from circle ci this morning that the nightly ci image didn't build. I think it needs a branch name update
=> fix: update the branch referece in nightly ci image to main

src/commands/write_buffer_server.rs, src/main.rs
@rbetts  noted that the current message when the IOx server starts is somewhat misleading as it implies startup is still in process and it is not obvious that the server is ready.
```
$ cargo run
Starting InfluxDB IOx server
```
This PR proposes making the output look as follows (there can actually be a significant delay between the two messages if there is a lot of data in the WAL)
```
$ cargo run
InfluxDB IOx server starting
InfluxDB IOx server ready
```
=> feat: Print message to stdout when the server is ready

Cargo.lock, arrow_deps/Cargo.toml, storage/src/exec/planning.rs, storage/src/util.rs, write_buffer/src/table.rs
There was a bug in Apache Arrow DataFusion (https://issues.apache.org/jira/browse/ARROW-10547, fixed in https://github.com/apache/arrow/pull/8633) that prevented us from enabling its query Optimizer passes in IOx. The issue has been resolved upstream so we can now enable the optimizer in IOx.
This PR:
1. Upgrades to use a new version of arrow https://github.com/apache/arrow/commit/8e4d9ebef30857bab7a35003af0c663e776909aa
2. Enables the query optimizer passes
3. Note this also removes vestigial `dump_plan` code in IOx in favor of `display_indent_schema` and `display_graphviz` from DataFusion.
4. Fixes #422
=> fix: Use datafusion optimizer in IOx query plans

generated_types/predicate.proto, src/server/rpc/expr.rs, src/server/rpc/storage.rs, tests/end-to-end.rs
Rationale: Ensure IOx is in sync with the influxdb storage gRPC definitions
Part of a three PR cycle:
This PR copy/pastes the contents, as closely as possible, from https://github.com/influxdata/influxdb/blob/master/storage/reads/datatypes/predicate.proto
Changes:
1. Remove  gogoproto specific stuff such as the following:
```
[(gogoproto.enumvalue_customname) = "ComparisonGreater"]
```
2. Change `tag_ref_value` from string --> bytes (as influx can send `0xff` for a field reference which is not a valid UTF-8 String and causes an error in Rust)
3. Removed the gogoproto extension of `option = false;`
=> chore: Update predicate protobuf definitions

docker/Dockerfile.ci
The [CI docker image builder](https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/1834/workflows/bf76c1c0-146a-4268-82db-d90242382bb7/jobs/6849) job failed last night due to an outdated reference to `master` (we have since updated this repo to use `main` as the default branch)
```
---> 60fe27b4de81
Removing intermediate container 45ad9ca4c8c9
Step 19/21 : RUN cd /home/rust/project && git checkout master && git reset --hard
---> Running in eab97803f0e3
error: pathspec 'master' did not match any file(s) known to git
The command '/bin/sh -c cd /home/rust/project && git checkout master && git reset --hard' returned a non-zero code: 1
Exited with code exit status 1
CircleCI received exit code 1
```
This PR updates the Dockerfile to check out the right branch
=> fix: Update git branch ref from master --> main to reflect repository updates

generated_types/build.rs, generated_types/service.proto, generated_types/source.proto, generated_types/src/lib.rs, generated_types/storage_common.proto, generated_types/storage_common_idpe.proto, src/server/rpc/storage.rs, tests/end-to-end.rs
Rationale: Ensure IOx is in sync with the influxdb storage gRPC definitions (so it can run Flux and InfluxQL)
Part of a three PR cycle related to https://github.com/influxdata/influxdb_iox/issues/369
This PR copy/pastes the contents, as closely as possible, from 
https://github.com/influxdata/idpe/blob/master/storage/storageproto/source.proto
https://github.com/influxdata/idpe/blob/master/storage/storageproto/service.proto
as well as deltas in https://github.com/influxdata/idpe/blob/master/storage/storageproto/storage_common.proto that haven't yet made it into OSS. 
Changes:
1. Remove  gogoproto specific stuff such as the following:
```
[(gogoproto.enumvalue_customname) = "FieldTypeFloat"]
```
leaving in annotations for non nullable as comments:
```
// [(gogoproto.nullable) = false];
``` …
=> feat: Update storage protobuf definitions, add stubs for read_window_aggregate

src/commands/write_buffer_server.rs
Make sure an error is returned to the user, instead of panicking, if binding the HTTP server address fails.
=> fix: return error from binding HTTP server address instead of panicking

src/commands/write_buffer_server.rs, src/main.rs, write_buffer/src/database.rs
Inspired by https://github.com/influxdata/influxdb_iox/pull/453#issuecomment-728152365, this PR improves the error reporting for the main server loop by bringing it up to the [error standards](https://github.com/influxdata/influxdb_iox/blob/main/docs/style_guide.md#errors)
Old message (before this PR):
```
InfluxDB IOx server starting
[2020-11-16T15:50:25Z ERROR influxdb_iox] Server shutdown with error: hyper::Error(Listen, Os { code: 48, kind: AddrInUse, message: "Address already in use" })
```
New message (with this PR -- note the inclusion of the host/port (`127.0.0.1:8080`):
```
InfluxDB IOx server starting
[2020-11-16T16:38:02Z ERROR influxdb_iox] Server shutdown with error: Unable to bind to listen for HTTP requests on 127.0.0.1:8080: error creating server listener: Address already …
```
=> fix: Improve error messages in main server loop

Cargo.lock, storage/Cargo.toml, storage/src/lib.rs, storage/src/window.rs
Rationale: We need to implement the `read_window_aggregate` gRPC service (#449) to provide Flux (and maybe InfluxQL)  compatible group push down with the other storage engines (OSS and Cloud).
In order to implement `read_window_aggregate` , we need to implement `window_bounds` which is defined in terms of Duration and Window as described in the design [spec](https://docs.google.com/document/d/1yY2CcicBK32rUkS8VQtHztGCJJhnU-pO_NAwThKa6Jc/edit#) for supporting `read_window_aggregate`  
Notes:
*  This PR ports the code and selected tests for `Duration`, `Window` , and `Bounds`
* I only ported enough to implement `Window::GetEarliestBounds`
* I tried to port it as "Go transliterated to Rust" rather than "Idomatic Rust" and left pointers to the source material. 
* This logic is not yet hooked …
=> feat: Port Duration and Window logic to support window aggregates

docs/style_guide.md
I was definitely operating with these as implicit assumptions, but I figured it would be good to make them explicit and write them down in the style guide
=> docs: Add mentions of `unsafe` and platform dependent compilation in style guide

object_store/Cargo.toml
I'm not sure why this just started happening just now for me, but I was getting an error from `objectstore/src/lib.rs` that it couldn't find `dotenv` (which is used in tests). `dotenv` is also used in `objectstore`'s `build.rs`, so it needs to be listed under both `dev` and `build` dependencies.
=> fix: dotenv is both a build and a dev dependency

src/server/rpc/expr.rs, src/server/rpc/input.rs, src/server/rpc/storage.rs, storage/src/exec/seriesset.rs, storage/src/groupby.rs, storage/src/lib.rs, storage/src/predicate.rs, storage/src/test.rs, tests/end-to-end.rs, write_buffer/src/database.rs
Rationale: We need to implement the `read_window_aggregate` gRPC service (#449) to provide Flux (and maybe InfluxQL)  compatible group push down with the other storage engines (OSS and Cloud).
See the the design [spec](https://docs.google.com/document/d/1yY2CcicBK32rUkS8VQtHztGCJJhnU-pO_NAwThKa6Jc/edit#) for supporting `read_window_aggregate`
This PR implements:
* Storage interface: `storage/src/groupby.rs`
* gRPC --> storage interface translation (including input validation)
* storage --> gRPC data translation
* Capability and capability response claiming support for window aggregates (which isn't quite true yet, but will be)
After this PR, the only thing left to do is actually hooking this up into the write buffer for plan execution.
Here is how this PR fits into past and planned PRs:
=> feat: Implement gRPC and storage interface for read_group_aggregate

Cargo.lock, server/Cargo.toml, server/src/buffer.rs
Resolves #466
Added logging for dropped writes and old segments in rollover scenarios
Some notes on the PR:
1) I wasn't entirely sure what the most useful context would be for the logs. I figured the segment `id` might be relevant at least. Let me know what else you'd like to see.
2) I added a dev-dep on the `test_helpers` crate in order to use the `enable_logging` function to test my change. I cut the usage since I didn't want to spam logs during test runs, but I left the dep in since it's included in most other crates in the repo.
3) I almost like feel [this function][1] should return the whole segment-- collections like `Vec` and `HashMap` usually do this on removal. However, I was only *actually* using the ID so I couldn't justify it.
[1]: …
=> chore(server): add logs for dropped WAL segments

query/src/exec.rs, query/src/exec/planning.rs, query/src/group_by.rs, query/src/window.rs, tests/end-to-end.rs, write_buffer/src/database.rs, write_buffer/src/table.rs
This PR implements read_window_aggregate in the write_buffer and adds an end-to-end test of read_window_aggregate
Closes #449
Rationale: We need to implement the `read_window_aggregate` gRPC service to provide Flux (and maybe InfluxQL)  compatible group push down with the other storage engines (OSS and Cloud).
See the the design [spec](https://docs.google.com/document/d/1yY2CcicBK32rUkS8VQtHztGCJJhnU-pO_NAwThKa6Jc/edit#) for supporting `read_window_aggregate`
Here is how this PR fits into past and planned PRs:
=> feat: Hook up read_window_aggregate into the write_buffer, end-to-end tests

query/src/exec/planning.rs
Implement suggestion from @e-dard  in https://github.com/influxdata/influxdb_iox/pull/483#discussion_r530393992
Make the `use` statements less redundant
=> refactor: clean up `use` statements

src/commands/server.rs, src/server/rpc/storage.rs
Rather than having to specify unique ports for test server instances, have the
kernel randomly assign ports and configure the storage gRPC client to use them.
=> test: random ports for storage fixture server

src/server/rpc/storage.rs
I found this while tracking down #490 -- namely when a gRPC request results in an error, the error is reported properly to the UI
```
query error: rpc error: code = InvalidArgument desc = Error converting read_aggregate_window aggregate definition 'aggregate: [Aggregate { r#type: Sum }], window_every: 0, offset: 0, window: Some(Window { every: Some(Duration { nsecs: 10000000000, months: 0, negative: false }), offset: Some(Duration { nsecs: 0, months: 0, negative: false }) })': Error parsing window bounds duration 'window.offset': duration used as an interval cannot be zero
```
However, the  IOx logs don't' include the error message which is a bit of an oversight 🤣 . Though they do include a reference to the request being sent:
```
[2020-11-25T20:25:04Z INFO …
```
=> feat: Log error message returned to gRPC in IOx logs

query/src/util.rs, src/server/rpc/expr.rs
Closes https://github.com/influxdata/influxdb_iox/issues/479
This is the same type of change to use the datafusion expression building API rather than creating the structures directly as in https://github.com/influxdata/influxdb_iox/pull/484, applied to the remaining places in IOx that I could find it.
=> refactor: More use of datafusion expr building function

query/src/group_by.rs, src/server/rpc/expr.rs
fix: allow empty `offset` widows for read_window_aggregate offset
This is fix 1 of 2 needed to get read_window_aggregate working correctly (#490)
My input error checking was overly aggressive. It turns out that offset windows can be zero.
With this input query:
```
from(bucket: "devbucket")
|> range(start: v.timeRangeStart, stop: v.timeRangeStop)
|> filter(fn: (r) => r["_measurement"] == "cpu")
|> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)
|> yield(name: "sum")
```
This gRPC request is sent to storage (note the offset duration is zero):
```
read_window_aggregate
database 26f7e5a4b7be365b_917b97a92e883afc,
range: Some(TimestampRange { start: 1606335604437610000, end: 1606335904437610000 }),
window_every: 0,
offset: 0,
aggregate: [Aggregate { r#type: Sum }],
window: …
```
=> fix: allow empty `offset` widows for read_window_aggregate offset

README.md
Found while investigating #465 - clang is needed to build the croaring dependency.
=> docs(README): document clang requirement

query/src/exec.rs, query/src/exec/seriesset.rs, tests/end-to-end.rs, write_buffer/src/table.rs
This is fix 2 of 2 needed to get read_window_aggregate working correctly
Closes #490
Despite even writing a mini spec, I still ended up creating a plan that sent back `GroupFrame` responses for read_window_aggregate, which is not correct
This PR adds a hack / special case to not do this.
I am also working a PR with a much more significant refactoring to unify / remove the duplication between the Group / non Grouped query execution path and remove this special case but figured I would get this one up so that I had it ready and so I can demonstrate the the functionality working.
=> fix: Do not send GroupFrames in response to read_window_aggregate

server/src/server.rs
Ensure database names contain only `{alphanumeric, -, _}` characters.
Fixes #278.
=> chore: validate database names

segment_store/src/column.rs
Closes #501
This PR does some refactoring of the logical types supported in the Sement Store, restricting them to those described in #501.
It also add some convenience `From` implementations for the value and scalar types.
=> refactor: restrict logical scalar type

Cargo.lock, Cargo.toml, src/commands/input.rs, src/server/http_routes.rs
A quick set of benchmarks confirms decompression in `flate2` is indeed faster
than `libflate` by ~2x or more:
```
enwiki-latest-all-titles-in-ns0.gz/flate2/enwiki-latest-all-titles-in-ns0.gz
time:   [1.0241 s 1.0276 s 1.0313 s]
thrpt:  [308.88 MiB/s 309.98 MiB/s 311.06 MiB/s]
enwiki-latest-all-titles-in-ns0.gz/libflate/enwiki-latest-all-titles-in-ns0.gz
time:   [1.9891 s 1.9928 s 1.9968 s]
thrpt:  [159.53 MiB/s 159.85 MiB/s 160.15 MiB/s]
000000000068612-000000044.tsm.gz/flate2/000000000068612-000000044.tsm.gz
time:   [4.6415 s 4.6483 s 4.6556 s]
thrpt:  [439.93 MiB/s 440.62 MiB/s 441.27 MiB/s]
000000000068612-000000044.tsm.gz/libflate/000000000068612-000000044.tsm.gz
time:   [12.165 s 12.232 s 12.306 s]
thrpt:  [166.43 MiB/s 167.45 MiB/s 168.36 MiB/s]
```
Where:
* …
=> perf(gzip): switch to flate2

query/src/exec.rs, query/src/exec/seriesset.rs, query/src/lib.rs, query/src/test.rs, src/server/rpc/data.rs, src/server/rpc/storage.rs, write_buffer/src/database.rs, write_buffer/src/table.rs
This PR removes a bunch of the code  duplication (mostly plumbing, ~200 lines) that allowed for a distinction between "grouped series sets" and "series sets" -- as mentioned in https://github.com/influxdata/influxdb_iox/pull/497. Instead this PR generalizes SeriesSet in general. 
As backstory, `SeriesSets` represent results from running a query, along with timeseries specific metadata (aka what columns are the tags and fields) needed to convert those results into the format needed for gRPC. `GroupedSeriesSets` was a wrapper over a wrapper wrapper that also includes information about "groups" -- which I am sure is not correct anyways (I will fix it https://github.com/influxdata/influxdb_iox/issues/448)
The only difference between series and grouped series sets is a single field and ~ 20 …
=> refactor: consolidate GroupedSeriesSet and SeriesSet

Cargo.lock, Cargo.toml, influxdb_tsm/Cargo.toml, influxdb_tsm/src/mapper.rs, influxdb_tsm/src/reader.rs, ingest/Cargo.toml, ingest/src/lib.rs, src/server/http_routes.rs, tests/commands.rs
Follows #505 - switches all other usage of `libflate` to `flate2`.
=> chore: use flate2 everywhere

src/server/rpc/expr.rs, src/server/rpc/storage.rs
This PR adds a debugging tool to print out the gRPC predicates.
As part of chasing down https://github.com/influxdata/influxdb_iox/issues/491 I want to have a non-mentally taxing way of seeing what predicate was passed to the request
The `predicate` argument passed to various gRPC requests was previously not logged. Partly this was because the default `fmt::Debug` implementation for `Predicate` is pretty terrible to read.
This PR adds a reasonable display of such predicates and adds them to the logs
Here is an example predicate formatted:
```
(FieldRef:host > 5)
```
Here are some example logs  that are now generated:
```
[2020-11-30T19:21:16Z INFO  influxdb_iox::server::rpc::storage] tag_values with tag_key=[x00] for database 26f7e5a4b7be365b_917b97a92e883afc, range: Some(TimestampRange { …
```
=> feat: Log gRPC predicates  in a human readable form

query/src/lib.rs, query/src/test.rs, server/src/server.rs, src/server/http_routes.rs, src/server/rpc/storage.rs, write_buffer/benches/benchmark.rs, write_buffer/src/database.rs
This is inspired by a chat with @domodwyer  this while trying to explain the query layer design. The `Database` trait is really a timeseries focused facade, so I wanted to rename the trait to make that clearer
I also renamed `field_columns` to `field_column_names` to be clearer about what it does.
I did this while taking a break from figuring out what is going on in https://github.com/influxdata/influxdb_iox/issues/491 (updates on that ticket)
As a follow on PR, I plan to break out SQL specific query stuff into its own trait
=> refactor: rename Database --> TSDatabase to better reflect its purpose

.circleci/config.yml, .github/workflows/rust.yml
Splits the internal/community pipelines, with the community pipelines using GitHub Actions.
The main benefits of this are:
* ~~[Fast builds]~~ (~30s `cargo build`, but scheduling runs seems to take longer)
* [GitHub caching] keyed on the `Cargo.lock` file contents (recursive / workspace friendly)
* Changing the dependencies produces a cache for immediate reuse
* Builds for community forks also make use of the same caches
* Separates the internal / container-pushing bits from the public CI runs
* Clippy will [leave comments] on your PRs
* It's free!
Good to know:
* Each repo has 5GB of caching, once a new cache pushes over the limit an old cache is evicted
* The current per-build cache is ~600MB, so we have about 8 cache slots, which means 8 different `Cargo.locks` in parallel
* A cache …
=> ci: use GitHub for CI

generated_types/storage_common.proto, src/server/rpc.rs, src/server/rpc/data.rs, src/server/rpc/expr.rs, src/server/rpc/storage.rs, test_helpers/src/lib.rs, tests/end-to-end.rs
Closes https://github.com/influxdata/influxdb_iox/issues/491, a bug in the IOx gRPC protocol implementation
The bug manifests itself as the `_field` drop down in the UI is never populated.
The root cause of the issue is that the `tag_value` request is (technically) invalid as it includes a `0xff` value in a field that is defined to be a `string` which causes Rust to 🤮  when parsing the request. This is the same basic problem as on https://github.com/influxdata/influxdb_iox/issues/346 but in a different request.
Specifically, here is the `tag_values` request that is made to IOx:
```
TagValues" log_id=0Qoj7_Al000 component=read
TagValues source partition_id: 0 org_id: 26f7e5a4b7be365b bucket_id: 917b97a92e883afc
TagValues pred [none]
TagValues range {1606832791724952000 1606836391724952000} …
```
=> fix: Update gRPC definitions so tag_key=_field requests work in IOx

segment_store/src/column/cmp.rs, segment_store/src/segment.rs
Things would be a bit simpler inside a `Segment` if there wasn't a requirement to have predicates on the `time` column. Enforcing the requirement to range by time can still be achieved, it would just be done at the `table` level rather than the segment level.
For segments that are completely covered by a time-range predicate(s) the `table` can then just remove those predicates before pushing down the rest of the predicates to the relevant segment.
=> refactor: avoid requiring time predicate in Segment

segment_store/src/segment.rs, segment_store/src/table.rs
This PR encapsulates results from segments and tables into `ReadFilterResult` and `ReadFilterResults` types respectively. 
Both these types implement either the `Debug` or `Display` traits, which is useful for writing tests where you want to compare to some textual table-representation.
=> refactor: encapsulate results from segment/table into nicer types

docker/Dockerfile.ci
Stops adding the IOx source code and performing a cargo build/test/clippy each
night. Previously this build would compile the IOx source & dependencies,
populating the incremental build cache and allowing builds that used the same
dependencies to complete quicker. This build caching was moved to
per-dependency-set caching in #496, and this pre-build is no longer used.
This should reduce the build image size substantially, making the whole CI
process a bit faster.
---
I was going to disable the nightly building of the build container to stop pushing identical images to quay, but we need to produce a new image whenever the CI Dockerfile is changed so left it for now - I'm open to ideas how to automate this!
=> ci: remove IOx pre-building in rust build container

query/src/predicate.rs, src/server/rpc/service.rs, write_buffer/src/column.rs, write_buffer/src/database.rs, write_buffer/src/partition.rs, write_buffer/src/table.rs
Closes  https://github.com/influxdata/influxdb_iox/issues/518 (by removing the `assert!`, 😆 ).
When I first wrote this code, my mind wasn't prepared to comprehend what a metadata query (e.g. `tag_keys` or `tag_values`) with a field list meant, so I left an `assert!` rather than trying to figure it out then.
Now that I am older, wiser, and have had a chance to study the existing Go code more, I believe the field restrictions will work as intended here, and have clarified the comments in the code with my new found understanding
I also added a test and fixed a bug (that field restrictions were also being applied to tag columns) that it discovered.
=> fix: Fix gRPC panic` when multiple field selections are provided

data_types/src/database_name.rs, data_types/src/lib.rs, query/src/lib.rs, server/src/server.rs, src/server.rs, src/server/http_routes.rs, src/server/rpc/service.rs
Previously the $ORG and $BUCKET was joined as:
$ORG + "_" + $BUCKET
Which is fine unless either $ORG or $BUCKET includes a "_", such as:
$ORG = "org_a"
$BUCKET = "bucket"
and
$ORG = "org"
$BUCKET = "a_bucket"
This change continues to join $ORG and $BUCKET with an underscore, but
disallows underscores in either $ORG or $BUCKET. It appears these values
are non-zero u64s in the gRPC protocol converted to their base-10 string
representations for the DB name, so this seems safe to enforce.
In addition, this change introduces a `DatabaseName` type to avoid
passing bare strings around, and allow consuming code to ensure only
valid database names are provided at compile type. This type works with
both owned & borrowed content so doesn't force a string copy where we
can avoid it, and derefs to …
=> fix: unambigious bucket/org to DB mappings

Cargo.toml
This makes it easier to do visualise profiles when running benchmarks.
=> chore: add debug symbols to benchmarks

Cargo.lock, Cargo.toml, data_types/src/partition_metadata.rs, object_store/Cargo.toml, object_store/src/lib.rs, query/src/lib.rs, query/src/test.rs, server/Cargo.toml, server/src/lib.rs, server/src/snapshot.rs, src/commands/server.rs, src/server/http_routes.rs, write_buffer/src/database.rs, write_buffer/src/lib.rs, write_buffer/src/partition.rs, write_buffer/src/table.rs
This introduces snapshot to the server packages to manage snapshotting. It also introduces a new trait for representing a PartitionChunk. There is a very crude API wired up in http_routes for testing purposes. Follow on work will bring the server package into http_routes and rework the snapshot API.
Currently, this removes the partition being snapshotted from the write buffer database and snapshots it in the background. Obviously we'll want to instead keep an Arc of that partition in the write buffer DB so the data is queryable while its getting snapshotted. I think this work might coincide well with some re-organization to bring in the concept of `Chunks` vs. `Partitions`.
The snapshotting currently happens serially (one table after the other) but I've structured the status in a way that …
=> feat: Implement write buffer to Parquet snapshotting

Cargo.lock, packers/src/packers.rs, segment_store/Cargo.toml, segment_store/benches/segment.rs, segment_store/src/column.rs, segment_store/src/column/dictionary.rs, segment_store/src/column/dictionary/plain.rs, segment_store/src/column/dictionary/rle.rs, segment_store/src/lib.rs, segment_store/src/partition.rs, segment_store/src/segment.rs, segment_store/src/table.rs
TLDR; this PR adds a method for doing grouped by aggregates on low-cardinality columns that is ~invariant to the number of rows being aggregated across. It could be useful for queries across large numbers of rows where you only want to group on lower cardinality columns.
This PR adds some initial support for `read_group` aggregates in Segment Store.
Currently it only supports one particular type of grouped aggregates; I will continue to add support for other cases until all general cases are covered.
Expressed in SQL, the kinds of read_group aggregate support (pinching a bit of InfluxDB terminology here...) added in this PR could be expressed in SQL like:
```sql
SELECT SUM(duration), COUNT(foo), MIN(bar) ...
FROM "cpu"
GROUP BY "region", "host", .... 
```
Concretely, for the code-paths in …
=> feat: grouped aggregates for low-cardinality columns

query/src/group_by.rs, src/server/rpc/expr.rs, tests/end-to-end.rs
This is the first PR towards ensuring the proper implementation of the read_group gRPC call (https://github.com/influxdata/influxdb_iox/issues/448)
It adds tests to ensure `read_group` implements the semantics described in [the read_group mini spec](https://docs.google.com/document/d/1UoCov4_NEhJHTxQftn5-YlzfhCiP5hgqDq9ikbRRa3g/) for queries that use the `None` aggregate and adds some additional commentary
Here is the rough implementation plan:
=> test: Adds tests for read_group for None aggregates

src/main.rs
Prevent the panic handler from being uninstalled, as it is uninstalled when it is handling a panic! doh.
Fixes #548
=> fix: never uninstall panic handler

docs/env.example, object_store/src/lib.rs
Closes #140 
This PR adds the members `bucket` and `location` both of `String` type to various `object_store` applicable S3 and GCS error enum variants. Also, adds some unit tests for S3 and GCS to attempt to receive errors that we assert saved the `bucket` and `location` members saved. The unit tests only cover a subset of the error enum variants added.
Questions and Remarks:
1. Should `bucket` and `location` represent `String` objects or `&str`?   
1. I plan to add the snafu display to the modified enum variants, but would like guidance on what the format should be to indicate the `source`, `bucket`, and `location` values.
1. Any guidance on more full code coverage to trigger a `tokio::task::JoinError`.
1. I believe the `put_get_delete_list` test helper function is susceptible to race …
=> fix: Report bucket/location when relevant with object store errors

segment_store/src/column.rs, segment_store/src/segment.rs, segment_store/src/table.rs
These commits detangle and simplify the way data is borrowed around the segment store and query results. There's some more we could do here, but I did talk to @e-dard about this and we agreed this helps :)
=> fix: Correct and clarify lifetimes around the segment store

write_buffer/src/table.rs
There is an implementation of creating `OR` expressions in DataFusion; I am not sure why I wrote one myself, but I ran into it while implementing aggregates, so I figured I would remove it.
=> refactor: remove duplicated or implementation in write buffer tests

src/server/rpc/expr.rs, src/server/rpc/service.rs
This is a PR towards ensuring the proper implementation of the read_group gRPC call (https://github.com/influxdata/influxdb_iox/issues/448)
It adds validation to the input parameters of `read_group` per the semantics described in [the read_group mini spec](https://docs.google.com/document/d/1UoCov4_NEhJHTxQftn5-YlzfhCiP5hgqDq9ikbRRa3g/)
Here is the rough implementation plan:
=> fix: better read_group input validation checking: group and hints fields

Cargo.lock, Cargo.toml, docs/env.example, docs/tracing.md, ingest/Cargo.toml, src/main.rs
Adds tracing support to IOx, pushing the spans to a Jaeger collector that is optionally enabled at runtime.
I've wrote a doc ([rendered here]) that covers a lot of what I would have put in this description - I'm interested to know if there's any other topics that should be included. I've tried to keep it relatively brief, but link to more resources for further detail - there's a lot to read about if you're inclined!
[rendered here]: https://github.com/influxdata/influxdb_iox/blob/dom/opentelemetry/docs/tracing.md
----
commit 4091823c4d6b4ba4076e1d1e80006ce0b2288441 (HEAD -> dom/opentelemetry, origin/dom/opentelemetry)
Author: Dom <dom@itsallbroken.com>
Date:   Thu Dec 10 11:05:36 2020 +0000
docs(tracing): add IOx tracing usage doc
Describes the components involved in, and usage of the …
=> feat(tracing): integrate Jaeger tracing sink

object_store/src/lib.rs
So this doesn't fix the underlying problem of not compiling all targets that is detailed in #537, but it does solve the compilation errors in the AWS tests that weren't caught because we're not compiling them in CI... I was hitting them locally because I did have the env vars set.
=> fix: Compiler errors missed in aws object store tests

Cargo.lock, segment_store/Cargo.toml, segment_store/benches/segment.rs, segment_store/src/segment.rs, segment_store/src/table.rs
This PR provides an initial implementation of `read_group` aggregation in the segment store. Grouping by any column other than a dictionary encoded string column, e.g., a "tag column" is not covered in this PR.
Further, there are three subsequent PRs that will each add optimisations to this operation for specific types of query. 
The implementation in this PR is pretty simple. First we apply predicates to the appropriate columns in the segment and materialise an intermediate set of row ids held in a compressed bitset. 
We take that set of row IDs and then materialise the _encoded_ values for columns we are grouping on, i.e., we materialise vectors of `u32` integers for each grouping column. We do the same for the columns we will be aggregating on.
Next we iterate over each row for all …
=> feat: implement read_group aggregates with a hashmap

Cargo.lock, segment_store/Cargo.toml, segment_store/src/column.rs, segment_store/src/segment.rs
This PR improves the performance of `read_group` in the Segment Store by `60-70%` (in terms of numbers of groups/second that we can generate).
`read_group` runtime is dominated by hashing group keys and checking they exist in the hashmap that builds the aggregates. By default in Rust, the hash function used in `std::collections::HashMap` is cryptographically secure, which means that it's slower than necessary for use-cases where you don't need the security. This is one such case.
Performance can be significantly improved by using an alternative hashing function via the `hashbrown` crate, which is what I have added here.
Benchmarks are included in the 7a40bd5 commit message.
=> perf: Improve `read_group` performance with faster hash function

docs/env.example, server/src/server.rs, src/commands/server.rs, src/server/http_routes.rs, tests/end-to-end.rs
This updates the http_routes and main server to use the Server crate. This is the first step in a larger effort to start hooking up the initial IOx API and get things running end to end with in-memory database, WAL buffer, and object storage.
For the time being, this disables the previous disk based WAL. Or rather, it uses the WriteBufferDb without it. That means that this IOx server has no persistence until later. Because of this, the restart in the end-to-end was removed.
Later PRs will add the WAL buffer and restart logic that loads from object store. We can opt to bring the local disk based WAL back later, but it will likely require some refactoring to work with how the WAL Buffer will operate.
The next PR will bring in the Routerify routes and move the snapshot logic over to Server. …
=> chore: Connect server crate to http routes and server command

segment_store/src/segment.rs
It occurred to me whilst doing performance analysis of `read_group` that the majority of the time is spent hashing keys (group keys) and checking if they exist in the hashmap being used to build the grouped aggregates.
In #572 things are helped by using a faster hash function via `hashbrown`. 
This PR improves things further by actually changing the representation of the group keys so that less hashing has to happen in the first place.
Stepping back a moment: 
`read_group` currently works by build a hash-table that maps all possible group keys to the aggregates for those group keys. Specifically we have a structure like:
```Rust
groups: HashMap<Vec<u32>, Vec<Aggregates>>
```
For performance reasons we do not materialise the values we are grouping on but instead use their encoded …
=> perf: pack group keys into integer for `read_group` performance

README.md, docs/README.md
Re #571 
Add a link to the docs directory from the main readme and a small table of contents
=> docs: Add reference to docs directory and a table of contents

segment_store/benches/segment.rs, segment_store/src/segment.rs
This PR adds functionality to `read_group` that improves performance when grouping on a single column, such as:
```
SELECT MIN(a), SUM(b) FROM cpu
GROUP BY "host"
```
In  this case, rather than using a `Hashmap` to map group keys to aggregates we can just allocate a single vector and use the encoded group key for the column (`u32`) to _index into the vector_. This provides constant-time access to the appropriate aggregate to update as we move through the rows in the columns we're aggregating using the value in the grouping column as an index.
Encoded values for group columns are always sequential, monotonically increasing integers so the maximum length that the allocated vector needs to be is the cardinality of the column we are grouping on. Therefore, the space requirements for this …
=> perf: use vector to build aggregates for single-column grouping

Cargo.lock, arrow_deps/Cargo.toml, query/src/exec/planning.rs, query/src/func/selectors/internal.rs, write_buffer/src/database.rs
Updates to latest arrow upstream
Closes https://github.com/influxdata/influxdb_iox/issues/568 by removing custom min/max implementation for boolean (which I have ported upstream).
=> chore: Update arrow dependencies, remove custom min/max implementation

query/src/exec.rs, query/src/exec/field.rs, query/src/exec/seriesset.rs, src/server/rpc/data.rs, tests/end-to-end.rs, write_buffer/src/column.rs, write_buffer/src/database.rs, write_buffer/src/table.rs
This PR completes the implementation of `read_group` gRPC (https://github.com/influxdata/influxdb_iox/issues/448)
This PR implements the approach described in https://github.com/influxdata/influxdb_iox/issues/448#issuecomment-744601824. The actual change to the plans is fairly small (use different aggregate functions) but there is a bunch of plumbing required as the previous assumption that all aggregated field values share the same timestamp is no longer the case. 
I'll leave more comments inline
=> feat: implement read_group in the write_buffer

src/server/rpc/service.rs, tests/end-to-end.rs
This is the final PR for `read_group` support, advertising that IOx support read_group queries. Closes https://github.com/influxdata/influxdb_iox/issues/448
=> feat: report support for read_group in gRPC

Cargo.lock, Cargo.toml, server/src/server.rs, src/commands/server.rs, src/server/http_routes.rs
This moves the HTTP API over to Routerify, which has the basic route parsing logic that will enable the API design for IOx.
I had a little trouble with the error handling in Routerify so I ended up creating a macro for constructing error responses in the HTTP API. I'm not sure what I think of this pattern so I'm interested in what others think. Another option would be to have two functions for each API endpoint. One which is `x_handler` with a Routerify function signature. Then another which is just `x` that has the `Result<Response<Body>, ApplicationError>` return type, which would make using the `?` operator work in those functions. That would eliminate the need for the `return_err` macro.
I'm happy to refactor to that if people prefer it. I only updated the `write` endpoint with this …
=> chore: move http API over to Routerify

Cargo.lock, arrow_deps/Cargo.toml, mem_qe/src/bin/main.rs, server/src/server.rs
Arrow is fast moving. I want to keep up to date as much as possible and thus avoid massive merge conflicts down the line
=> chore: Upgrade arrow dependencies

Cargo.lock, data_types/Cargo.toml, data_types/benches/benchmark.rs, data_types/src/data.rs, data_types/src/database_rules.rs
This adds benchmarks to the data_types crate for ReplicatedWrite. This was part of a broader effort to see if switching to JSON for the WAL Buffer format made any sense (#606). The conclusion is that we'll continue to use Flatbuffers, but these benches might be worth keeping around.
=> chore: Benchmark ReplicatedWrite

mutable_buffer/src/chunk.rs, mutable_buffer/src/lib.rs, mutable_buffer/src/partition.rs
This PR ensures that the terminology used for open/closed chunks matches the intent. Previously for reasons I can't remember, I called chunks in the mutable buffer `mutable_chunks` and `immutable_chunks`. Talk about confusing: "Immutable chunks in the mutable buffer"
After this PR we have the consistent terminology of "Closed Chunks" and "Open Chunks" in the mutable buffer.
=> refactor: consistently name open/closed chunks in mutable_buffer

benches/mapper.rs
As the bench name ends up in file names, avoid spaces to make scraping scripts easier to write. 
The Right Thing (TM) would be to update the script (https://github.com/influxdata/influxdb_iox/pull/605) to handle spaces. But for now I just want the 'expedient' thing to get everything wired up.
=> fix: remove spaces in bench name to ease automatic scraping

benches/packers.rs
Running `cargo bench` on master currently takes ~12 hours. I left a VM running trying to collect data for the last 30 commits and it ran for almost a week (here is the CPU usage over that time -- when it is at 50% that is when the benchmarks are running) 
I did some profiling and determined that most of the time is being spent in the packers benchmarks re-creating the same input data over and over again.
Now, also if you watch the benchmarks run the behavior makes much more sense -- when the output says "warming up for 3 seconds" it actually finished on a count of three when that was not the case prior to this PR
packers: DNF (Did Not Finish -- I killed it after an hour or two)
packers: 3m27.166s
```
set -x
echo "Starting run at " `date`
date
time cargo -v bench --bench encoders
date
time …
```
=> fix: Avoid hours of time running benchmarks

mutable_buffer/src/database.rs, mutable_buffer/src/lib.rs, query/src/lib.rs, query/src/planner.rs, query/src/test.rs, server/src/db.rs, server/src/lib.rs, server/src/server.rs, src/server/rpc/service.rs
Related to #532 
This PR lays out a proposed evolution of the existing code structure for holding and managing data across the mutable buffer, read buffer, and parquet files. It shows one (very small) example pattern for the write path and I try to sketch out how it would work for the read path.
See also [Background slides / query engine design proposal](https://docs.google.com/presentation/d/1Q9WhgX2Ylxhz33o-AglJVML2n6pMLxkQYa2tDUeuCt8)
The current code, as written, has the query APIs as part of the storage -- and thus the query code is all in the mutable_buffer now. As we  expand IOx so it can store data in multiple places (chunks) we need to handle querying across multiple chunks as well as different types of chunks.
Chunks can be in one of three places:
* mutable_buffer -- and the …
=> feat: Interface for writing and querying mutable buffer, read buffer and parquet

data_types/src/database_rules.rs, server/src/server.rs, src/server/http_routes.rs, tests/end-to-end.rs
This PR is start of the IOx specific API. It puts everything under /iox/api/v1 as this is the beginning of the IOx API. Creating a database is done with a PUT and a GET request can retrieve the DatabaseRules details.
After having implemented this, I think there may be a broader discussion to be had about how to make the creation/configuration of a database easier or more straightforward. The `DatabaseRules` struct has a ton of stuff in it. So while a user could create a JSON payload to set all those rules in one go, doing so would likely be a little painful. I'll have to give it some thought, but open to ideas.
=> feat: add create and get database to API

mutable_buffer/src/chunk.rs, mutable_buffer/src/database.rs, mutable_buffer/src/partition.rs, mutable_buffer/src/table.rs, query/src/lib.rs, query/src/test.rs, server/src/db.rs, server/src/snapshot.rs, src/server/http_routes.rs
Closes #
Chunks are part of partitions but they shoudn't have to have the back pointer too. The `key` is left over from prior to the introduction of Chunks. I think this is causing confusion (e.g. https://github.com/influxdata/influxdb_iox/pull/621#discussion_r553619255) so I propose removing them.
=> refactor: Remove partition key from the Chunk trait

Cargo.lock, read_buffer/Cargo.toml, read_buffer/src/chunk.rs, read_buffer/src/column.rs, read_buffer/src/column/fixed.rs, read_buffer/src/column/fixed_null.rs, read_buffer/src/lib.rs, read_buffer/src/row_group.rs, read_buffer/src/table.rs
This PR adds a mechanism for writing individual row groups to the `ReadBuffer`. Using this API a caller can add entire chunks from, e.g., the `MutableBuffer` in a way that breaks down the potentially large amount of materialisation that would happen if all tables had to be materialised to record batches.
It also implements the `table_names` method end-to-end, meaning `table_names` is now exposed outside of the `ReadBuffer`.
The general idea is that the `ReadBuffer` store will accept new chunks, and these chunks should be submitted by providing:
- a `u32` chunk id;
- A table name;
- Table data for the table.
Table data should be represented by an Arrow `RecordBatch`. The API allows a caller (the `MutableBuffer` for example) to add individual `RowGroups` to tables and chunks. A `RowGroup` …
=> feat: add support for writing chunks to ReadBuffer

read_buffer/src/chunk.rs, read_buffer/src/lib.rs
This adds back the concept of a `partition` to the `ReadBuffer` so that we can ensure that chunk ids do not clash within a database (chunk ids are not guaranteed to be unique across partitions).
This could have been a map of a map but since I knew we will want to do bulk operations on a partition, e.g., drop all the chunks in it, I dug out some previous code and refactored it back into the `ReadBuffer`.
I took the opportunity to rename the `update_*` methods to `upsert_x` since, as @domodwyer pointed out, they both modify and create.
=> feat: add partition concept to ReadBuffer

src/server/http_routes.rs
Removes a stray unwrap() that was causing a request with invalid JSON / empty
body to panic the handler thread.
Fixes #632
=> fix: invalid API request body causes panic

read_buffer/src/chunk.rs, read_buffer/src/column.rs, read_buffer/src/lib.rs, read_buffer/src/row_group.rs, read_buffer/src/table.rs
This PR adds an API that enables a caller to lazily stream results out of the `ReadBuffer` in the form of record batches.
The external API (that other crates may use) looks like:
```rust
pub fn read_filter<'a>(
&self,
table_name: &str,
partition_key: &str,
chunk_ids: &[u32],
select_columns: ColumnSelection<'a>,
predicates: &'a [Predicate<'a>],
) -> Result<ReadFilterResults<'a, '_>> {
```
`chunk_ids` should specify all of the chunks that the caller wishes to query across. The caller could provide single chunk ids and call `read_filter` multiple times, or it can provide many chunk ids and call it once. 
`ColumnSelection` is an enum that lets you ask for "all columns" or specify some columns. 
`predicates are a set of conjunctive predicates. The `ReadBuffer` currently supports `=, !=, <, <=, …
=> feat: read filter API for lazily streaming out of Read Buffer

mutable_buffer/src/chunk.rs, mutable_buffer/src/partition.rs, query/src/lib.rs, query/src/test.rs, server/src/db/chunk.rs
Closes https://github.com/influxdata/influxdb_iox/issues/634
This uses u32 to identify chunks everywhery to harmonize across the IOx systems -- previously `mutable_buffer` used `u64` and `read_buffer` used `u32` which caused some silly friction in https://github.com/influxdata/influxdb_iox/pull/630
=> refactor: Use u32 for Chunk ids consistently

Cargo.lock, mutable_buffer/Cargo.toml, mutable_buffer/src/chunk.rs, mutable_buffer/src/column.rs, mutable_buffer/src/database.rs, mutable_buffer/src/dictionary.rs, mutable_buffer/src/partition.rs, mutable_buffer/src/table.rs
This PR implements listing available chunks (including a snapshot of the open chunk) in the mutable buffer and is part of  #532 (run queries against data in read buffer)
It has been extracted from the RFC https://github.com/influxdata/influxdb_iox/pull/630 -- now with Tests!
Specifically, this implementation `clone`s (deep copies) all the currently mutable data in the mutable buffer so that it can be queried by different threads. This is non ideal for performance reasons, as outlined by @pauldix , though it is no different performance wise than the code currently in IOx (which converts all the data to Arrow Record batches during query planning).
A proper handling of concurrent read / modification of the mutable buffer is tracked here: https://github.com/influxdata/influxdb_iox/issues/635
=> feat: implement chunk listing and snapshotting in mutable buffer

mutable_buffer/src/database.rs, mutable_buffer/src/partition.rs, query/src/frontend/sql.rs, query/src/lib.rs, query/src/test.rs, server/src/db.rs
This is another part of implementing query of the read buffer https://github.com/influxdata/influxdb_iox/issues/532 that has been extracted out of the RFC https://github.com/influxdata/influxdb_iox/pull/630
It changes the SQL frontend to implement plans in terms of Chunks rather than Databases in preparation for querying across different kinds of chunks (Mutable Buffer, Read Buffer, etc)
As it is just changes to the traits I don't think any additional testing is warranted yet (I think existing tests ensure I didn't break SQL querying) and subsequent PRs will start using these traits as we hook everything up together
=> feat: implement query planning in terms of chunks

src/server/rpc/id.rs, src/server/rpc/input.rs, src/server/rpc/service.rs
Rationale: keep names consistent and bother Edd less :)
Follow on from https://github.com/influxdata/influxdb_iox/pull/646
=> refactor: rename Id to ID in gRpc implementation

docs/README.md, query/README.md
This adds a README.md file in the query crate trying to capture the rationale and sweet sweet ASCII art. I figured that since @pauldix  said this matches what he currently has in mind  https://github.com/influxdata/influxdb_iox/pull/630#discussion_r555757382 I would get it into the repo.
=> docs: Add query README file and explain some rationale

src/commands/config.rs, src/commands/influxdb_ioxd.rs, src/commands/logging.rs, src/main.rs
I often use the -v and -vv arguments to control the logging level (so I don't have to remember the the right logging levels to set). After https://github.com/influxdata/influxdb_iox/pull/640 was merged in I noticed `-v` didn't work any longer (a classic case of me not having put tests in...), and when I was adding it back in I noticed that specifying `influxdb_iox server --log=<>`  didn't actually set the log level either. 
So this PR fixes both of those items
=> fix: (re)Implement logging configuration from the command line

read_buffer/benches/row_group.rs, read_buffer/src/chunk.rs, read_buffer/src/column.rs, read_buffer/src/column/cmp.rs, read_buffer/src/lib.rs, read_buffer/src/row_group.rs, read_buffer/src/table.rs, server/src/db.rs
This PR basically enables one to convert a Query Engine predicate into a predicate that can be interpreted by the `Read Buffer`.
Currently the `ReadBuffer` supports predicates that only contains binary expressions, which are combined conjunctively. Each binary expression at the moment must be a column name, an operator (`<, <=, >, >=, =, !=`) and a literal, which should be a logical type such as `i64, f64, u64, String, bool` etc.
The Query Engine Predicate maintains a time-range using two integers, which represent two expression with the operators `>=` and `<` respectively. The Read Buffer  supports arbitrary expressions on the time column (assuming they follow the rules above) so these time-range values on the Query Engine are handled explicitly in the predicate conversion process and …
=> feat: add helper for converting query engine predicate to read buffer format

docker/Dockerfile.ci
Adds jq to the builder image used for CI runs.
This lets us use some existing scripts provided by the deployments team for
consistency.
=> build: include jq in CI image

docker/Dockerfile.ci
Try #659 again - I accidentally put jq in the wrong build container...
=> build: add jq to the actual build image

read_buffer/benches/dictionary.rs, read_buffer/benches/fixed.rs, read_buffer/benches/plain.rs, read_buffer/benches/row_group.rs, read_buffer/src/chunk.rs, read_buffer/src/lib.rs, read_buffer/src/table.rs, server/src/db.rs
This PR is a refactoring of the Read Buffer API to provide an externally consumable API, which hopefully won't have to change much.
Currently I have got hooked up:
- `read_filter`, with predicate support;
-  `table_names`, without predicate support (this is a drop-in for `SHOW MEASUREMENTS`);
And this PR adds/refactors public stubs for:
- `read_aggregate` - just a stub at the moment;
- `read_window_aggregate` - just a stub at the moment;
- `column_names` -  just a stub at the moment (this is a drop-in for `SHOW TAG KEYS`);
- `tag_values` - just a stub at the moment (this will support `SHOW TAG VALUES`).
The only extra thing I planned to do here was to not return concrete types but return `Result<impl Iterator<Item = RecordBatch>>` but there are some lifetime things to straighten out …
=> refactor: clean up public Read Buffer API

influxdb_iox_client/Cargo.toml
The serde_json package is only actually used in tests, so doesn't need to be
part of the API client dependencies.
This also relaxes the version pin as it was conflicting with dependencies in
other projects.
=> build: move serde_json to dev deps for API client

Cargo.lock, object_store/Cargo.toml, object_store/src/disk.rs, object_store/src/path.rs
This gets the tests working for the `File` object store.
I'm still not completely happy with the structure of these types overall, but I have Jake helping me with that. So this doesn't take care of some of the `todo!`s from [the last PR](https://github.com/influxdata/influxdb_iox/pull/629), but it does make the existing structure function properly at least.
=> fix: Get file-based object store working with regards to object store paths

read_buffer/benches/row_group.rs, read_buffer/src/chunk.rs, read_buffer/src/column.rs, read_buffer/src/lib.rs, read_buffer/src/row_group.rs, read_buffer/src/schema.rs, read_buffer/src/table.rs
This PR is a refactor. There is a lot of code-shuffle here but the main thing is that I decided to help my future self by reducing the number of lifetimes on a bunch of intermediate results from two to one. I did this by creating a schema type that describes the schema of results as they're passed up the read buffer.
When constructing record batches this schema will be consulted for:
- column names;
- column logical types;
- whether the column is part of the group key or an aggregation that may need to be merged or a plain selection.
I have wired up `read_aggregate` but not exposed it in the public API because I have not yet implemented the merging of row group results for `read_aggregate`. I'm saving that for the next PR at which point we should have a `read_aggregate` we can call from …
=> refactor: refactor read buffer result schema

data_types/src/database_rules.rs, server/src/config.rs, server/src/db.rs, server/src/lib.rs
This pulls the server configuration into its own module. It updates the config so that databases can be created and saved without holding a write lock across an async call. Follow on work will add reading of these rules from object store on server initialization.
=> feat: Add persistence of database rules

Cargo.lock, mutable_buffer/src/database.rs, mutable_buffer/src/table.rs, query/src/frontend/sql.rs, query/src/lib.rs, query/src/test.rs, read_buffer/src/lib.rs, read_buffer/src/table.rs, server/Cargo.toml, server/src/config.rs, server/src/db.rs, server/src/db/chunk.rs, server/src/lib.rs
Closes #532
This is is the final part of the initial integration and demonstrates running queries against data in read buffer. It has only superficial changes to the read buffer (implements `Debug` for two structs).
This PR completes the implementation of:
1. The API (discussed more in  #621 / #630) for migrating chunks from mutable buffer to read buffer
2. The discussion / implementation on how to connect the ReadBuffer with the query system (using the API from https://github.com/influxdata/influxdb_iox/pull/662)
I recommend looking at the tests in db.rs which basically shows how the system operates. The tests are the copy/paste the same as on #630 (though the implementation of the code they call has changed)
The major outstanding item here is sorting out more fine grained locking of the …
=> feat: Chunk Migration APIs and query data in the read buffer via SQL

.circleci/get-deploy-tags.sh
Adds PublishedAt to the `get-deploy-tags.sh` script.
=> chore: add PublishedAt to get-deploy-tags.sh script

.circleci/get-deploy-tags.sh
Fixes the structure of JSON file generated in `get-deploy-tags.sh`
=> fix: add Images toplevel object to JSON in get-deploy-tags.sh

Cargo.lock, data_types/Cargo.toml, data_types/src/database_name.rs, server/src/lib.rs
Fixes #677 and allows any valid UTF-8 string that doesn't have "control" characters to be used as a database name
This PR disallows all ascii characters between 0x00 (null) and 0x1F (unit separator) as well as some more esoteric control codes in [UnicodeData.txt](https://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt). This means that characters like \t 'tab' and \n 'newline' are not allowed but space ' ', underscore '_', and minus '-' are.
=> fix: Allow more flexible database names

query/src/lib.rs, query/src/predicate.rs
The struct for `TimestampRange` was moved into a module but its tests did not go along for the ride. Put the tests in the same file as their definition
=> refactor: Put tests in same file that defines the Structure under test

.circleci/get-deploy-tags.sh
Once an image is built and ready, exec the binary defined in the env var
IMAGE_PROMOTION_COMMAND to promote it (if set).
Docs to follow elsewhere.
=> ci: trigger image promotion for deployment

src/commands/logging.rs
Rationale (from @pauldix 👍 )
> I would think info should be the default log level. Things like what configuration options it’s using on startup, individual requests, etc would be info and I’d expect those to show up in the default logging level.
Changes: Change the default IOx logging level to INFO
=> feat: change default log level to INFO

read_buffer/src/chunk.rs, read_buffer/src/column.rs, read_buffer/src/lib.rs, read_buffer/src/row_group.rs, read_buffer/src/schema.rs, read_buffer/src/table.rs
This PR adds some initial support for `read_aggregate`, including predicate support.
Currently supported aggregates:
- SUM
- COUNT
- MIN
- MAX
First/Last are not hooked up in the read buffer yet.
Further, you can only currently group on tag columns. This means you can't do time-based windowing; that will arrive with `read_windowed_aggregate`.
The Read Buffer will merge multiple results from row groups within the same table automatically, but they're collected lazily, which is cool. Each chunk is also processed lazily.
**Note**: I want to get this in so there is simply some working `read_aggregate` support to keep things moving but I'm not happy with the design and I plan to change how aggregates are built up and materialised to be more "SOA" than "AOS".
=> feat: Read Buffer read_aggregate support 

mutable_buffer/src/chunk.rs, query/src/frontend/influxrpc.rs, server/src/db.rs, server/src/db/chunk.rs
This PR lays out the pattern I plan to use to test the gRPC query planner, namely that each test is in terms of predicate and expected results, and there are several different scenarios of how that data is layed out in chunks.
This PR was meant to be a test change to prepare testing data in the read buffer, but it turns out a scenario I found also exposed a bug (table_names would panic if all chunks had been dropped).
=> test: revamp rpc query testing so it works in multiple chunk scenarios

Cargo.lock, arrow_deps/Cargo.toml
This PR fixes IOx CI  failures like this: https://github.com/influxdata/influxdb_iox/pull/697/checks?check_run_id=1765238294
```
/usr/local/cargo/bin/cargo build --workspace
Updating git repository `https://github.com/apache/arrow.git`
error: failed to get `arrow` as a dependency of package `arrow_deps v0.1.0 (/__w/influxdb_iox/influxdb_iox/arrow_deps)`
Error: failed to get `arrow` as a dependency of package `arrow_deps v0.1.0 (/__w/influxdb_iox/influxdb_iox/arrow_deps)`
Caused by:
failed to load source for dependency `arrow`
Caused by:
Unable to update https://github.com/apache/arrow.git?rev=67d0c2e38011cd883059e3a9fd0ea08088661707#67d0c2e3
Caused by:
object not found - no match for id (67d0c2e38011cd883059e3a9fd0ea08088661707); class=Odb (9); code=NotFound (-3)
Error: The process …
```
=> chore: Update Arrow deps to work after 3.0.0 Arrow master force push

read_buffer/Cargo.toml, read_buffer/benches/database.rs, read_buffer/src/chunk.rs, read_buffer/src/lib.rs, read_buffer/src/row_group.rs, read_buffer/src/table.rs
This PR adds support for pushing predicates down into the `table_names` implementation in the Read Buffer.
In terms of InfluxDB-type meta queries, this will provide the ability to answer queries like `SHOW MEASUREMENTS WHERE "region" = 'foo' AND time > 100 AND time <= 2000`. Currently, as with other Read Buffer operations only conjunctive binary expressions are supported.
The Read Buffer will answer this operation pretty quickly. Within this implementation it know how to:
- skip row groups that cannot possible satisfy all expressions on a predicate (column pruning);
- skip tables that cannot possible satisfy all expressions on a table (row group pruning);
- skip tables that have already been returned from other chunks;
- return early if a row group contains rows satisfying the predicate. …
=> feat: add predicate support to `table_names` in the Read Buffer

server/src/db.rs, server/src/db/chunk.rs
This PR adds proper support for `meausrement_names` for gRPC queries to data in the read buffer.  It is the first time gRPC requests will include data in the read buffer 🎉 
~The only slightly sketchy bit is skipping the predicate scenarios with the read buffer (as predicate's are not yet supported there). I'll add some notes inline~
(update: sketchy bit removed as https://github.com/influxdata/influxdb_iox/pull/698 merged)
=> feat: gRPC measurement_names support for read buffer

data_types/src/schema/builder.rs
I found this while implementing tests for table schema across read buffer and mutable buffer (part of #701), and figured I would pull it out into its own PR
Influx Fields can be null, but the builder code incorrectly marked them as non-nullable
=> fix: influx_fields are nullable and thus should be marked as such

mutable_buffer/src/chunk.rs, mutable_buffer/src/database.rs, mutable_buffer/src/partition.rs, mutable_buffer/src/table.rs, query/src/frontend/sql.rs, query/src/lib.rs, query/src/selection.rs, query/src/test.rs, server/src/db.rs, server/src/db/chunk.rs, server/src/db/selection.rs, server/src/snapshot.rs
Rationale: This is part of implementing the DataFusion `TableProvider` api for cross chunk queries in IOx (#701). I am trying to avoid a massive single PR.
Part of what is needed is a uniform way to describe which columns are selected in a query. This PR follows the model of the ReadBuffer to introduce a reasonable selection API (aka what columns) for the mutable buffer and the query interface.
Among other benefits, this should clear up mistakes related to confusing `[]` as "all columns" --  I have been confused about this and I think @pauldix  has as well. I will comment inline.
This is part of my planned sequence of PRs:
Basic PR checklist:
=> feat: Add selection interface to mutable buffer and query interface

data_types/src/schema.rs, data_types/src/schema/builder.rs
The ability to merge potentially different schemas across chunks is a precursor to being able to query across those chunks.
This PR adds a builder (and tests) for merging schemas by  implementing the logic for "compatibile" schemas  -- namely that columns can be added but there can not be any datatype conflicts.
Related to https://github.com/influxdata/influxdb_iox/pull/700
=> feat: Implement schema merging

read_buffer/src/chunk.rs, read_buffer/src/lib.rs, read_buffer/src/row_group.rs, read_buffer/src/table.rs
This PR makes the Read Buffer's external API safe for concurrent use 🥳  Big thanks to @carols10cents for the several discussions we had this week on this!
The PR ensures that it is safe to concurrently call any of the Read Buffer's external APIs.
The design also minimises lock contention in the read path by only holding locks on the read buffer for the initial part of query execution. The most expensive parts of query execution (actually operating on the columnar data and materialising data into record batches) is done in a lock-free manner.
Whilst the Read Buffer executes on immutable blocks of data (`Row Groups`), the Read Buffer itself is not immutable because the consumer of the Read Buffer needs to be able to do things like:
* add new partitions, chunks and tables by adding more …
=> feat: Read Buffer safe for concurrent access

read_buffer/src/lib.rs, read_buffer/src/row_group.rs, read_buffer/src/schema.rs, read_buffer/src/table.rs
This PR adds a feature that I had already built at a lower level, but forgotten to implement in the Read Buffer's table and external API. Now you can use `read_aggregate` to ask for column aggregates without grouping on any other columns. Predicates are supported. So this effectively provides Read Buffer support for things like:
```sql
SELECT COUNT(temp), SUM(foo), MAX(bar) FROM cpu WHERE time > 100;
```
As part of this work I had to teach tables to merge row group results for `read_aggregate` when there were no group keys. My bad for forgetting this previously.
=> feat: aggregates without group keys

read_buffer/src/column.rs, read_buffer/src/lib.rs, read_buffer/src/row_group.rs
Quick one here... This just wires up the existing nullable column encodings for primitive types (`i64`, `u64`, `f64`). I just needed to call into the array array in a slightly different way to get it working.
I took the opportunity to tidy up some unnecessary `From` implementations while I was in and around that code.
=> refactor: wire up nullable column encodings

read_buffer/src/column.rs, read_buffer/src/column/bool.rs, read_buffer/src/lib.rs, read_buffer/src/row_group.rs, read_buffer/src/table.rs
This PR adds support for nullable boolean column values in the Read Buffer.
The following aggregations are currently supported on them: `{Count, Sum, Min, Max}`, along with the following predicate operators: `{=, !=, <, <=, >, >=}`.
The encoding is backed by an arrow `BooleanArray`.
=> feat: add Boolean column support

data_types/src/schema.rs, data_types/src/selection.rs, mutable_buffer/src/chunk.rs, mutable_buffer/src/table.rs, query/src/lib.rs, query/src/test.rs, read_buffer/src/lib.rs, server/src/db.rs, server/src/db/chunk.rs
In order to plan queries, DataFusion (and really any query engine) needs to know what the schemas of the input tables are
1. adds functions to the `PartitionChunk` trait for if a table is present and what its schema is for a particular chunk / set of chunks
2. Implements this function for mutable buffer and read buffer
3. Tests that the same schema is reported for the same data laid out in several different ways
This is part of my planned sequence of PRs:
=> feat: Create table_schema api call and implementation

Cargo.lock, Cargo.toml, logfmt/Cargo.toml, logfmt/src/lib.rs, logfmt/tests/logging.rs, src/commands/config.rs, src/commands/logging.rs
Closes https://github.com/influxdata/influxdb_iox/issues/516
The heroku logfmt logging format is commonly used (including The InfluxDB cloud service). The Rust standard log format is less commonly used (at the time of this writing). Thus, IOx should make it easy to hook up logs to existing systems.
I *really* want structured logs to appear in our internal InfluxData testing tools clusters as we roll IOx out. logfmt seems like the shortest path to get there.
I could find nothing suitable: https://crates.io/search?q=logfmt
I did not go with the seemingly obvious choice, https://crates.io/crates/logfmt_logger (though thanks @mcountryman for creating that), because
1. Doesn't (obviously) work with `tracing_subscriber`
2. Has been downloaded 65 (not a typo) times total ever
3. Doesn't seem to …
=> feat: Implement logfmt (Heroku) formatted log output

Cargo.lock, arrow_deps/Cargo.toml, arrow_deps/src/lib.rs, arrow_deps/src/test_util.rs, server/src/db.rs, src/influxdb_ioxd.rs, src/influxdb_ioxd/flight.rs, src/influxdb_ioxd/rpc.rs, src/influxdb_ioxd/rpc/service.rs, tests/end-to-end.rs, tests/end_to_end_cases/flight_api.rs, tests/end_to_end_cases/mod.rs
This starts a Flight implementation that only has do_get. The request's `Ticket` value is bytes of JSON that looks like:
```
{
"org": "0000111100001111",
"bucket": "1111000011110000",
"sql_query": "select * from cpu_load_short"
}
```
which is very similar (read: copypasta'd) to the `ReadInfo` that the "/api/v2/read" route takes as URL params. I'm not sure the best way to share those just yet, but eventually they should be. Some of the error types having to do with running the queries can probably be shared too.
Please let us know if this wasn't what you had in mind; as I've mentioned, the Flight API is extremely flexible!
=> feat: Start of a Flight API - do_get

mutable_buffer/src/chunk.rs, mutable_buffer/src/database.rs, query/src/frontend/influxrpc.rs, query/src/frontend/sql.rs, query/src/lib.rs, query/src/provider.rs, query/src/provider/physical.rs, query/src/test.rs, server/src/db.rs, server/src/db/chunk.rs, server/src/db/streams.rs, server/src/lib.rs, server/src/snapshot.rs
Closes #701
TLDR is that this is needed to supporting streaming execution, selection and predicate pushdown into the Mutable Buffer, Read Buffer and Parquet chunks. 
This PR adds the following features itself
* Streams reads out of the ReadBuffer and MutableBuffer during (SQL) queries
* Projection pushdown (only materialize columns needed by query rather than all of them) during (SQL) queries
* Streams data during the creation of parquet snapshots
Streaming in this case means "process one record batch at time" rather than "get them all at once". This is beneficial so that data isn't buffered overly long as well as limiting wasted work if the plan shuts down early (eg. `.. LIMIT 10`) if results aren't sent
While I specifically say "SQL" above, the mechanism will work for all DataFusion …
=> feat: Implement TableProvider for Trait for `Db`

src/influxdb_ioxd/rpc/service.rs
Rationale: Error handling with Snafu is hard enough. Having multiple patterns to accomplish the same thing (Boxing an error in a way Snafu is happy with) makes it even harder.
This PR makes the error handling in the rpc service more uniform and conform to the [style guide](https://github.com/influxdata/influxdb_iox/blob/main/docs/style_guide.md#errors)
=> refactor: standardize error handling in rpc service

Cargo.lock, Cargo.toml, src/influxdb_ioxd/http_routes.rs
Uses routerify [changes](https://github.com/influxdata/routerify/pull/1) to allow stripping out the per-handler wrapper shims, thereby providing more consistent error handling and logging
=> feat: consistent global error handling and logging

mutable_buffer/src/chunk.rs, mutable_buffer/src/column.rs, mutable_buffer/src/database.rs, mutable_buffer/src/dictionary.rs, mutable_buffer/src/partition.rs, mutable_buffer/src/table.rs
This updates the mutable buffer, partitions, chunks, dictionary, tables, and individual columns to be able to return their approximate memory size used. This doesn't aim to be exact. There are spots where I'm not counting table or column pointers or the partition key. My expectation is that the data size will dominate and a few pointers here and there won't matter.
This PR is the first bit of work that will enable a user to set how much memory they want the mutable buffer to take on a database. Follow on PRs to get there will be:
1. Adding  column names to summary statistics
2. Enabling partitions to roll up summary statistics
3. Adding to database rules to let users specify partition eviction rules
4. Add per database periodic checking to enforce sizes rules and evict partitions
=> feat: add approximate memory size tracking to mutable buffer

mutable_buffer/src/database.rs, mutable_buffer/src/table.rs
This one is a bit of a yak shave in advance of adding column names to the summary statistics. I needed the column and its name (or identifier) to be together, rather than the id to index map that existed before. I think the table_id and column_id stuff should be refactored out over time since they add a ton of complexity to the code and don't add much value. Having those as Strings would be much easier and probably be a drop in the bucket for memory usage. Basically, I don't think they need to be interned. But that would be an even more massive refactor touching so many things in the MutableBuffer, I leave it as a later exercise.
Hopefully this makes the code simpler and cleaner in the interim and it gives me the column_id with the column so that I can easily look up the name when …
=> chore: refactor how columns are kept in the table in the mutable buffer

src/influxdb_ioxd/http_routes.rs
=> fix: Fix copy&pasted check_response descriptions

Cargo.toml, arrow_deps/Cargo.toml, data_types/Cargo.toml, generated_types/Cargo.toml, influxdb2_client/Cargo.toml, influxdb_iox_client/Cargo.toml, influxdb_line_protocol/Cargo.toml, influxdb_tsm/Cargo.toml, ingest/Cargo.toml, logfmt/Cargo.toml, mem_qe/Cargo.toml, mutable_buffer/Cargo.toml, object_store/Cargo.toml, packers/Cargo.toml, panic_logging/Cargo.toml, query/Cargo.toml, read_buffer/Cargo.toml, server/Cargo.toml, test_helpers/Cargo.toml, wal/Cargo.toml
Mostly alphabetization... Much like using rustfmt, I don't want to have to spend too much time thinking about where a new dependency should go in a Cargo.toml. So now everything is nice and tidy and alphabetized!
I also found some instances where test_helper was a regular dependency rather than a dev dependency, and the object_store crate no longer has a build script so the build dep can go away.
I'm happy to manage merge conflicts.
=> chore: Clean up Cargo.tomls

mutable_buffer/src/database.rs, server/src/db.rs
Make the code simpler (and likely more performant)
This follows [tokio best practice](https://tokio-rs.github.io/tokio/doc/tokio/sync/struct.Mutex.html#which-kind-of-mutex-should-you-use) as well as the pattern set in the read buffer, by using std::sync locks rather than tokio locks.
The only potential downside of this this approach is that now if a task has to wait on a lock for an extended period of time, it will block the tokio executor thread.  The only time I think this will actually happen with the current code is during chunk snapshotting -- tracked by https://github.com/influxdata/influxdb_iox/issues/635 -- which we need to fix before too long anyways
=> refactor: Reduce async in mutable buffer, use std::sync

read_buffer/src/chunk.rs, read_buffer/src/column.rs, read_buffer/src/column/bool.rs, read_buffer/src/column/dictionary/plain.rs, read_buffer/src/column/dictionary/rle.rs, read_buffer/src/column/fixed_null.rs, read_buffer/src/lib.rs, read_buffer/src/row_group.rs, read_buffer/src/table.rs
This PR implements the physical operation `column_names` on the Read Buffer. This operation can be used to retrieve a set of columns names for a single table across one or more Chunks of data. `column_names` accepts an optional predicate, which if set will ensure only column names are returned where at least one value in the column is on a row that matches the predicate.
This functionality will provide the execution  for IOx's equivalent of InfluxDB's `SHOW TAG KEYS WHERE ...` schema exploration query and Flux's `schema.tagKeys()`.
Here is an example using a pseudo query language:
```
Table: cpu
region  | env  | counter  | time
--------------------------------
west    | prod |    22    |  100
east    | prod |  NULL    |  200
west    | dev  |  NULL    |  300
SHOW COLUMN_NAMES FROM "cpu"; …
```
=> feat: add support for getting column names from Read Buffer

query/src/test.rs, src/influxdb_ioxd/rpc/service.rs
Per @carols10cents  suggestion in https://github.com/influxdata/influxdb_iox/pull/749#pullrequestreview-583690120
Same as in #749: Follow best practice and reduce the amount of async in the code
Switch to `std::sync::Mutex` instead of `tokio::sync::Mutex` and reduce async functions
=> refactor: Remove async locking from test database

Cargo.lock, Cargo.toml, data_types/Cargo.toml, data_types/src/http.rs, data_types/src/lib.rs, data_types/src/wal.rs, server/src/buffer.rs, src/influxdb_ioxd/http.rs
Partially closes #724
Will update `influxdb_iox_client` as separate PR as this one was getting fairly large. I've moved a couple of data structures from within the WAL module to data_types in order to facilitate this.
=> feat: add WAL metadata endpoint (#724)

influxdb2_client/Cargo.toml
Fixes build issues with the `influxdb2_client` example project.
- Enable `rt-multi-thread` in `tokio`
- Enable default features for `reqwest` which allows sending data to https endpoints.
=> fix: influxdb2_client example project

data_types/src/partition_metadata.rs, mutable_buffer/src/partition.rs
This is the next in the effort to be able to specify how much memory the mutable buffer can take. These summaries will be used by the partition eviction logic that will be executed to free up memory space.
=> feat: add ability to roll up summaries from multiple chunks

influxdb_iox_client/src/client.rs, influxdb_iox_client/src/errors/client_error.rs, influxdb_iox_client/src/errors/create_database.rs, influxdb_iox_client/src/errors/mod.rs
The writer ID changes appear to have broken these tests, and as they aren't currently run in CI, this has gone unnoticed.
Additionally, IOx no longer considers `bananas!` an invalid database name, only disallowing names with control characters. As url::parse silently strips such characters, it was necessary to add database name validation within the client to preserve the spirit of the test.
=> fix: Fix influxdb_iox_client integration tests

query/src/exec.rs, query/src/plan/stringset.rs, query/src/test.rs
As pointed out by @e-dard in https://github.com/influxdata/influxdb_iox/pull/759/files#r572917700,  comment, `KnownOK` and `KnownError` are  confusing and it turns out uneeded. 
Remove the `KnownError` variant and rename `KnownOk` --> `Known`
=> refactor: Remove unneeded StringSetPlan::KnownError variant

server/src/query_tests/sql.rs
I am tracking down a bug in the gRPC planner and I thought there might be a bug in the selection code, so I added a test. Turns out this is not the actual problem but since I had written the test anyways I figured this is a good one to add to the suite
=> test: add a SQL test case for selection (of columns)

data_types/src/database_rules.rs, influxdb_iox_client/src/client.rs, server/src/buffer.rs, server/src/config.rs, server/src/lib.rs, server/src/query_tests/utils.rs, server/src/snapshot.rs, src/influxdb_ioxd/http.rs, tests/end-to-end.rs
Here's what I'm thinking for the configuration options for the mutable buffer management. If this looks good, I'll follow up with a commit to remove the `store_locally` flag in `DatabaseRules`. After that I can move to actually implement these rules in the server.
=> feat: Add database rules configuration for mutable buffer

Cargo.lock, server/Cargo.toml, server/src/buffer.rs, server/src/lib.rs, server/src/tracker.rs
Closes #655
This adds the ability to associate a Future and accompanying metadata, with a TrackerContext. When this future is dropped, i.e. terminated or aborted, it will unregister with the TrackerContext. From the `TrackerContext` it is then possible to get a list of running futures, and trigger termination of them.
This solution is purposefully agnostic to how the future is actually scheduled, as we may wish to do something more sophisticated than `tokio::spawn` in future, or use this to track futures that are not spawned to an executor at all.
=> feat: add background task tracking

object_store/Cargo.toml
When building just the tests for a particular crate, the lack of this feature causes issues
=> fix: enable tokio::fs for object_store crate

tests/end-to-end.rs
Closes #745
This PR makes the e2e not use the same default default ports that a local ioxd server would use.
It choses two other constant port numbers which may or may not be free.
The perfect is the enemy of the good; postponing the random ports in #786.
Obligatory https://xkcd.com/221/
=> fix: Avoid clashing ports when running e2e tests

Cargo.lock, data_types/src/schema.rs, data_types/src/selection.rs, query/Cargo.toml, query/src/frontend/sql.rs, query/src/lib.rs, query/src/provider.rs, query/src/provider/adapter.rs, query/src/provider/make_null.rs, query/src/provider/physical.rs, query/src/util.rs, server/src/db/chunk.rs, server/src/db/streams.rs, server/src/query_tests/scenarios.rs, server/src/query_tests/sql.rs
Note: I apologize for the large PR -- I didn't realize how large a change this was going to be. 
I hit a bug while working on `tag_column_names` where my test case happened to have chunks with different schemas (some chunks didn't have all the columns). We had been punting on the problem for a while but I now needed a solution.
The root issue is that different Chunks can have different schemas. The schemas have to be "compatible" in the sense of no conflicting column definitions [link](https://github.com/influxdata/influxdb_iox/blob/a316b16960b35c639353ee4f39f9925d433ca2a6/data_types/src/schema.rs#L296-L299)
1. Handle merging chunk schemas when creating the "Table View" (`TableProvider`) of the table in DataFusion
2. Handle runtime schema mismatches (e.g. when the Table View wants a …
=> feat: Implement Cross Chunk Schema / RecordBatch merging at query time

CONTRIBUTING.md, Cargo.lock, server/src/query_tests/sql.rs, server/src/query_tests/table_schema.rs, test_helpers/Cargo.toml, test_helpers/src/lib.rs
TLDR; This PR allows runtime enabling/disable of logging in tests
I am trying to be more productive.
My debugging flow in the query engine often looks like
1. run tests
2. find those that fail
3. add `test_util::enable_logging()`
4. rerun to get logging
I am trying to avoid the recompile/rerun steps 3 and 4
Add a function to enable logging if `RUST_LOG` is set in the environment, and does nothing if `RUST_LOG` is not set
So now, you can enable logs in the tests without a recompile via:
```
RUST_LOG=debug cargo test -p query
```
```
cargo test -p server -- sql
```
Which runs the tests like you would hope, nice and quiet like
```
cd /Users/alamb/Software/influxdb_iox2 && cargo test -p server -- sql
Blocking waiting for file lock on build directory
Compiling server v0.1.0 …
```
=> feat: Enable/Disable logging in tests via RUST_LOG environment variable

object_store/src/aws.rs
Removes an `unwrap` we saw while doing other things. Also use `.context` in a few missing places.
=> fix: Report a failure to parse an AWS datetime

influxdb_iox_client/src/client.rs, influxdb_tsm/src/key.rs, influxdb_tsm/src/reader.rs, mutable_buffer/src/database.rs, read_buffer/src/column.rs, src/commands/input.rs, src/influxdb_ioxd/http.rs
I tried to build with nightly-2021-02-12 and noticed a few things causing warnings.
I'd propose switching to `nightly-2021-02-12` in a separate PR, but these fixes still apply with the current version recorded in rust-toolchain. Although the current toolchain will not report warnings of new occurrences of these constructs, it's still a good idea to cleanup the code base, since often one takes pieces of existing code as inspiration for new code (if not straight copy&paste).
Also removed a literal NUL byte in a string literal and replaced with `\x00`; some editors drop NUL bytes when saving files.
=> chore: Cleaning things in prep for rust 2021

docker/Dockerfile.ci
#799 is blocked on quay.io/influxdb/rust:ci having nightly-2021-02-12
that image is build on circleci, so we first need to land this, wait until it gets pushed and try #799 again
=> ci: Add nightly-2021-02-12 to quay.io/influxdb/rust:ci

read_buffer/src/chunk.rs, read_buffer/src/column.rs, read_buffer/src/column/encoding/bool.rs, read_buffer/src/column/encoding/dictionary/rle.rs, read_buffer/src/column/encoding/fixed_null.rs, read_buffer/src/lib.rs, read_buffer/src/row_group.rs, read_buffer/src/table.rs, read_buffer/src/value.rs
This PR wires up support for getting the size in bytes of the Read Buffer, adding an publicly exported `size` method to the `Database` type.
Size is calculated on a best-case effort as it's not always easy to determine the on-heap size of various types, especially containers that might over-allocate or things like Bitmaps, which are in C and don't have full API access to everything we would need to count.
=> feat: implement `size` on Read Buffer

influxdb_iox_client/src/client.rs, src/influxdb_ioxd/http.rs
Adds an API endpoint to retrieve the currently set server writer ID:
GET /iox/api/v1/id
Returning:
{"id":42}
Also adds a `get_writer_id()` method to the IOx API client.
=> feat: get writer ID endpoint

influxdb_iox_client/src/client.rs
In what has to be the least controversial change of the week, this PR derives `Clone` for the API client.
=> refactor: derive Clone for API client

mutable_buffer/src/database.rs, mutable_buffer/src/table.rs, query/src/exec.rs, query/src/frontend/influxrpc.rs, query/src/lib.rs, query/src/plan.rs, query/src/plan/fieldlist.rs, query/src/test.rs, server/src/db.rs, server/src/query_tests/influxrpc.rs, server/src/query_tests/influxrpc/field_columns.rs, server/src/query_tests/influxrpc/table_names.rs, server/src/query_tests/influxrpc/tag_column_names.rs, server/src/query_tests/scenarios.rs, server/src/query_tests/sql.rs, server/src/query_tests/table_schema.rs, src/influxdb_ioxd/rpc/storage/service.rs
Closes https://github.com/influxdata/influxdb_iox/issues/810 (includes rationale)
This PR ports the `field_columns` planning logic to the `InfluxRPC` frontend, along with tests, so that it now works across mutable buffer and read buffer.
* it was straightforward to port the code and tests
* The actual new logic is very small and the gRPC planner has almost all the right logic already
* requires no changes to the read buffer (or mutable buffer, other than removing code)
The performance of the implementation of `field_columns` is likely from ideal. The only difference between the tag_names and field_columns is that field_columns returns type information as well as a name and a timestamp.
However, the  logic in the mutable buffer (and hence now in the gRPC planner) basically runs  `SELECT …
=> feat: implement field_columns plan

src/influxdb_ioxd.rs
Rationale:
We should only write to stdout/stderr if requested like a good 12 factor app https://12factor.net/ . 
Also I would like to be able to find log messages easily showing when the server has started
This `println!` is left over from an earlier age
=> fix: do not use `println!` on server startup

build.rs, src/influxdb_ioxd.rs
Built on https://github.com/influxdata/influxdb_iox/pull/828
I wonder of @carols10cents  or @shepmaster  could comment on how reasonable an approach this is?
I would rather like to know what version of the code is running on the IOx server in tools. So while I was waiting for a new image to be deployed I figured I would propose adding this information to the log message
* include the git SHA from which the server was built.
```
cd /Users/alamb/Software/influxdb_iox && cargo  run -- server
Finished dev [unoptimized + debuginfo] target(s) in 0.40s
Running `target/debug/influxdb_iox server`
Feb 17 15:03:33.815  WARN influxdb_iox::influxdb_ioxd: NO PERSISTENCE: using memory for object storage
Feb 17 15:03:33.817  INFO influxdb_iox::influxdb_ioxd: gRPC server listening …
```
=> feat: Include GIT_HASH in startup log message

Cargo.lock, object_store/Cargo.toml, object_store/src/aws.rs, object_store/src/azure.rs, object_store/src/buffer.rs, object_store/src/disk.rs, object_store/src/gcp.rs, object_store/src/lib.rs, object_store/src/memory.rs, server/src/buffer.rs, server/src/lib.rs, server/src/snapshot.rs
Addresses the API aspect of #818
This PR contains a utility module that helps computing the length of a stream while buffering it
for later replay (in-memory or spilling it in a temporary file). This is intended to be used as a stop-gap measure until
we implement proper streaming support in the various ObjectStore implementations. Hopefully we will be able to get rid of this buffering stage since all the support object stores support "streaming" uploads (of one kind or another).
We'll add streaming functionality to the relevant ObjectStore implementations in subsequent PRs.
Most current ObjectStore implementations already slurp the input stream into memory before proceeding,
or otherwise don't need the length parameter for anything other than ensuring it matches the actual
stream length …
=> feat: Allow to put streams of unknown length to objectstore

Cargo.lock, docs/env.example, object_store/Cargo.toml, object_store/src/azure.rs
Fixes https://github.com/influxdata/influxdb_iox/issues/765.
This did require a few patches to upstream, and they've been incorporated, but the Azure crates are not being published yet so pointing to GitHub is the best we can do for the foreseeable future. In other words, this is ready for review and merging IMO.
@alamb I noticed you removed the `docs/env.sample` file in https://github.com/influxdata/influxdb_iox/pull/608, and that @domodwyer went back to `.env` over `.influxdb_iox/config` in https://github.com/influxdata/influxdb_iox/pull/640... 
The `.env` file still works (and is still relevant for tests that aren't running the `influxdb_iox` command). I think the sample file with documentation is still valuable if only for developer setup? I also tried running `influxdb_iox server …
=> feat: Implement list_with_delimiter for Azure

mutable_buffer/src/database.rs, query/src/frontend/influxrpc.rs, query/src/frontend/sql.rs, query/src/lib.rs, query/src/test.rs, server/src/db.rs, server/src/query_tests/scenarios.rs, server/src/query_tests/table_schema.rs, server/src/snapshot.rs, src/influxdb_ioxd/http.rs
A couple of methods on the `Database` trait (there could be others I guess?) don't have any `await` points in their implementations (there are two implementations: one for the mutable buffer and one for the `server::Db`).
To simplify the code it seemed reasonable to make these methods on the trait not async. This means that other methods that build on them may themselves not need to be async in some cases.
I ran into this because I was working on a feature to migrate chunks from the mutable buffer to the read buffer that will be entirely cpu-bound and therefore doesn't need to have await points in it, yet it needs to use the two methods `partition_keys` and `chunks` I've changed in this PR.
Since I'm not sure if there could every be an implementation that _does_ need to have these …
=> refactor: make certain Database method sync

read_buffer/src/row_group.rs
It seems a left over from a previous naming.
=> docs: Rename read group to row group

server/src/query_tests/scenarios.rs
Remove left over workaround code obseleted by https://github.com/influxdata/influxdb_iox/pull/822
=> fix: remove workaround query code

Cargo.lock, google_types/Cargo.toml, google_types/src/lib.rs
gRPC responses contain a response code and a string message, and originally this was the only way they could return errors. To fix this gRPC has since added the ability to return an opaque error details byte array, but, as gRPC is codec agnostic, it doesn't constrain what this payload is.
However, the convention is for it to contain a serialized `google.rpc.Status` protobuf message, which duplicates the status code and message, and includes a repeated field of `google.protobuf.Any`. Again these can be anything, but the [convention](https://cloud.google.com/apis/design/errors#error_payloads) is for one of them to be the standard error payload for the status code. These are just conventions, but many clients either assume them, or make APIs following the convention easier to interface with. …
=> feat: encoding of standard gRPC error details payloads

README.md, docs/env.example
This is a minor documentation clarification follow on from https://github.com/influxdata/influxdb_iox/pull/834 to point users at he example config file and clarify the content of that file
=> docs: Refer to the example env file and clarify comments

docs/env.example, object_store/src/aws.rs, src/commands/config.rs, src/influxdb_ioxd.rs
Rename bucket env var to `INFLUXDB_IOX_S3_BUCKET` for consistency with other storage location related env vars.
(`AWS_S3_BUCKET_NAME` was not a standard env var anyway).
Now S3 can be used to persist snapshots.
Tracking issue #808
=> feat: Add S3 plumbing to iodx config

mutable_buffer/src/table.rs, query/src/frontend/influxrpc.rs, server/src/query_tests/influxrpc.rs, server/src/query_tests/influxrpc/tag_keys.rs, src/influxdb_ioxd/rpc/storage/service.rs
The incoming gRPC function call is `tag_keys` [proto link](https://github.com/influxdata/influxdb_iox/blob/main/generated_types/service.proto#L26),  and having the implementation be named something different is confusing
Change the name of the `tag_keys` implementation to `tag_keys`
=> refactor: rename tag_column_names --> tag_keys in InfluxRPCPlanner

.gitignore
Closes #
This PR adds DS_Store into .gitignore to avoid unnecessary noises on Mac
=> chore: add DS_Store into .gitignore to avoid unecessary noises

src/commands/config.rs
Some recursive DNS servers by design return an IP record for every single request they get, even if there is no real DNS record for that name. My mobile ISP (TIM italy) is one of them; I didn't notice because I override the DHCP settings on my laptop to force 8.8.8.8.
I don't know how to write a portable test that ensures we fail with validation error in case of a DNS name that doesn't return any records. Hence I think we should drop this test that causes more problems that what it solves.
=> fix: Remove test for non-existing DNS record

Cargo.lock, Cargo.toml, README.md, buf.yaml, generated_types/build.rs, generated_types/protos/grpc/health/v1/service.proto, generated_types/src/lib.rs, influxdb_iox_client/Cargo.toml, influxdb_iox_client/src/client.rs, influxdb_iox_client/src/client/health.rs, src/influxdb_ioxd/http.rs, src/influxdb_ioxd/rpc.rs, tests/end-to-end.rs
Implements the standard gRPC health service using [tonic-health](https://github.com/hyperium/tonic/tree/master/tonic-health) (part of tonic).
The implementation is extremely basic at the moment, but it should provide a starting point.
To test install grpc-health-probe from [here](https://github.com/grpc-ecosystem/grpc-health-probe/releases/tag/v0.3.6) and then run
```
$ grpc_health_probe-linux-amd64 -addr 127.0.0.1:8082 -service influxdata.platform.storage.Storage
status: SERVING
```
=> feat: add basic gRPC health service

Cargo.lock, arrow_deps/Cargo.toml
Keeps us up with the latest and greatest stuff in Arrow (and minimizes potential changes necessitated by API changes)
I updated the arrow sha and then ran `cargo update`
=> chore: Update arrow/datafusion deps again

.circleci/config.yml, .dockerignore, docker/Dockerfile.iox
Makes the IOx deploy image smaller by not bringing in 600MB of Rust build dependencies. Also sets entrypoint intead of command, which allows using the container as if it were the binary `e.g. podman run iox:VERSION --help`.
Creating as draft as I can't easily test this locally as my local GCC is newer than is bundled in debian buster. This will also serve the dual purpose of building an image I can deploy to get the new `/health` endpoint.
=> feat: smaller IOx build images

docs/README.md, docs/env.example, docs/testing.md, object_store/src/aws.rs, object_store/src/azure.rs, object_store/src/gcp.rs, src/commands/config.rs, src/influxdb_ioxd.rs
Fixes #869.
I chose to unify the object store bucket variables first because it should save a bit of work when bringing all of the object store configuration into the config system (https://github.com/influxdata/influxdb_iox/issues/610).
I also added a document in docs/testing.md for info that's only relevant for running tests. For example, the `TEST_INTEGRATION` environment variable is not at all relevant for people using `influxdb_iox server`, so documenting that in `influxdb_iox server --help` doesn't seem appropriate. If the docs dir isn't a good spot I'm happy to move what I've put there to wherever people would rather have it :)
=> feat: Consolidate all bucket config into one option/env var

mutable_buffer/src/database.rs, mutable_buffer/src/table.rs, query/src/exec.rs, query/src/lib.rs, query/src/plan.rs, query/src/plan/seriesset.rs, query/src/test.rs, server/src/db.rs, src/influxdb_ioxd/rpc/storage/service.rs
This is related to #811 where I am moving `read_filter` into the gRPC planner but was easily separable.
=> refactor: move SeriesSetPlans into its own module

data_types/src/database_rules.rs, data_types/src/field_validation.rs, data_types/src/lib.rs
Builds on #847 and adds the ability to convert between the Protobuf types and the data_types types.
The below is copied largely verbatim from the original PR #838 this PR was split out from:
---
The possibility of using the generated types throughout IOx was raised previously, but I decided against this for a couple of reasons:
- There is an expectation that the data_types have constraints beyond just their implementing types, e.g. a Subscription has a non-empty String name, the mutable buffer has a non-zero buffer size, etc... Whilst the enforcement of these constraints is currently pretty inconsistent, we will likely want to get to a point where it isn't possible to construct malformed instances of these types, and this is incompatible with using these same types to represent what the …
=> feat: conversion to/from data_types and generated_types

Cargo.toml, src/influxdb_ioxd/http.rs, src/influxdb_ioxd/http/format.rs, tests/end-to-end.rs, tests/end_to_end_cases/read_api.rs
Resolves #726, builds on https://github.com/influxdata/influxdb_iox/pull/866 from @mkmik 
1. Adds the ability to get the results of a query in CSV and JSON as well as pretty print (defaults to pretty)
2. Remove old (org/bucket based) query api
1. Contemplate supporting jsonl -- tracked by https://github.com/influxdata/influxdb_iox/issues/872
2. Support query streaming -- https://github.com/influxdata/influxdb_iox/issues/873
3. Contribute Arrow JSON writer upstream: https://issues.apache.org/jira/browse/ARROW-11773
=> feat: implement format parameter on sql query endpoint

data_types/src/schema.rs
This is related to #811 where I am moving `read_filter` into the gRPC planner, and is easily separable. I need to be able to iterate over tags / fields / timestamps easily so I can create selections in the plan in some straightforward way. 
This may also come in handy for some of the work that @NGA-TRAN  is doing on https://github.com/influxdata/influxdb_iox/pull/875
=> feat: Add iterators over different types of columns in Schema

Cargo.lock, arrow_deps/Cargo.toml, src/influxdb_ioxd/http/format.rs
Use library standard json writing rather than IOx specific code. 
* Update to latest version of Arrow
* Run `cargo update` to get updates of other libraries
* Remove `JsonArrayWriter` and switch to using the `arrow::json::JsonWriter` I contributed back upstream to arrow in  https://issues.apache.org/jira/browse/ARROW-11773 / https://github.com/apache/arrow/pull/9575
=> chore: Update arrow deps, remove custom JsonArrayWriter

read_buffer/src/chunk.rs, read_buffer/src/column.rs, read_buffer/src/column/encoding/dictionary.rs, read_buffer/src/column/encoding/dictionary/plain.rs, read_buffer/src/column/encoding/dictionary/rle.rs, read_buffer/src/column/string.rs, read_buffer/src/lib.rs, read_buffer/src/row_group.rs, read_buffer/src/table.rs
Closes #868.
This PR implements `column_values` in the Read Buffer.
`column_values` returns the distinct set of non-null values for a pushed-down set of columns. Currently, these columns must have the semantic type of InfluxDB tags. The reasoning for this is: (1) this operation is only currently going to be used to support execution of a `SHOW TAG KEYS` type call via the gRPC API (used by InfluxQL and Flux); and (2) the operation only supports returning `String` values at the moment.
`column_values` will return an error is `Selection::All` is used as the column push-down. It will also return an error if one of the provided columns does not conform to the semantic type laid out above.
`column_values` is smart about how it executes the operation. It passes a buffer of previously calculated …
=> feat: implement column_values in Read Buffer

arrow_deps/src/util.rs, data_types/src/schema.rs, mutable_buffer/src/database.rs, mutable_buffer/src/table.rs, query/src/frontend/influxrpc.rs, query/src/lib.rs, query/src/plan/seriesset.rs, query/src/test.rs, server/src/db.rs, server/src/db/chunk.rs, server/src/query_tests/influxrpc.rs, server/src/query_tests/influxrpc/read_filter.rs, server/src/query_tests/scenarios.rs, src/influxdb_ioxd/rpc/storage/service.rs
Build https://github.com/influxdata/influxdb_iox/pull/879
Users want to query data via flux / influxql when it lives in any type of IOx chunk. Flux / InfuxQL use the gRPC storage API.
This PR ports the `read_filter` query into the `InfluxRPCPlanner` from the `MutableBuffer` so that it works across all types of Chunks.
* https://github.com/influxdata/influxdb_iox/issues/883 for possibly incorrect results with 'OR' predicate
Note I really want to write some tests with more complicated predicates in general, but I I plan to make something like https://github.com/influxdata/influxdb_iox/issues/843 before spending time adding more complex scenarios
=> feat: Make read_filter work for mutable buffer and read buffer

docker/Dockerfile.ci
This reverts commit c1856d2946f99d09b5d4133ef3ca27d1603196e6.
https://github.com/influxdata/influxdb_iox/pull/799#issuecomment-779371477:
> Lets drop the changes from #800 then - the build image has to be pulled for each CI run so we try to keep it small
We decided to aim for stable (see #809)
=> ci: Remove nightly-2021-02-12

server/src/query_tests/influxrpc/read_filter.rs, server/src/query_tests/scenarios.rs
This really is a yak shave, but I want the tests to match in style between https://github.com/influxdata/influxdb_iox/pull/905 and the rest of the query tests
=> refactor: Use `vec![]` instead of inlined strings, for legibility, in tests

Cargo.lock, arrow_deps/Cargo.toml, query/src/frontend/influxrpc.rs
Closes #
This is the work of [#913](https://github.com/influxdata/influxdb_iox/issues/913)  to use Arrow's Expr::is_not_null newly added in [ARROW-11742](https://issues.apache.org/jira/browse/ARROW-11742)
=> chore: use newly added Arrow's Expr::is_not_null function

docs/env.example, object_store/src/aws.rs, object_store/src/azure.rs, object_store/src/gcp.rs, src/commands/server.rs, src/influxdb_ioxd.rs, src/main.rs
Fixes #610.
This makes CLI args for all the various object store configuration, as well as hooks up Azure (which wasn't fully plumbed through before).
=> feat: Integrate the object store configuration into the config system

mutable_buffer/src/database.rs, query/src/frontend/influxrpc.rs, query/src/lib.rs, query/src/plan/seriesset.rs, query/src/predicate.rs, query/src/test.rs, server/src/db.rs, server/src/query_tests/influxrpc.rs, server/src/query_tests/influxrpc/read_filter.rs, server/src/query_tests/influxrpc/read_group.rs, server/src/query_tests/influxrpc/read_window_aggregate.rs, server/src/query_tests/influxrpc/util.rs, server/src/query_tests/scenarios.rs, src/influxdb_ioxd/rpc/storage/service.rs
Closes https://github.com/influxdata/influxdb_iox/issues/812
Note: I have taken a slightly different approach with this PR than in previous porting exercises -- I have simply brought the code from the mutable buffer over without removing the old version yet. I plan to remove the old implementations with several follow on PRs and thus spare you, dear reviewer, an even larger PR
Users want to query data via flux / influxql when it lives in any type of IOx chunk. Flux / InfuxQL use the gRPC storage API.
This PR ports the `read_group` and `read_window_aggregate`(which is very similar plan) into the `InfluxRPCPlanner` from the `MutableBuffer` so that it works across all types of Chunks.
This removal of the vesigal query code from the mutable buffer is tracked in …
=> feat: make read_group and read_window_aggregate work across chunks

README.md
Fixes #909
Turns out that BuildKit is "required", not "strongly suggested".
=> fix(README): make docker instructions clearer

mutable_buffer/src/database.rs, server/src/lib.rs
Part of #815; Working  to ensure there is no query logic in the `mutable_buffer`
Order of PRs (dependent):
Adminstrivia
=> refactor: Remove impl of `query::Database` in mutable_buffer

Cargo.lock, arrow_deps/Cargo.toml
Brings in the latest arrow version, and disables default `features`. This actually slims down dependency stack (by 4 crates I believe). 
In particular, this skips some crypto libraries as dependencies by not enabling `hmac` and related functions.
(👋  thanks @seddonm1  who added this upstream in https://github.com/apache/arrow/pull/9567)
=> chore: Update arrow deps, turn off optional datafusion features

mutable_buffer/src/chunk.rs, mutable_buffer/src/lib.rs, mutable_buffer/src/pred.rs, mutable_buffer/src/table.rs, server/src/db/chunk.rs, server/src/db/pred.rs
Part of #815; Working  to ensure there is no query logic in the `mutable_buffer`
Order of PRs (dependent):
Adminstrivia
=> refactor: Move chunk predicate creation from query::Predicate into server crate

mutable_buffer/src/chunk.rs, server/src/db.rs, server/src/snapshot.rs
Part of #815; Working  to ensure there is no query logic in the `mutable_buffer`
Order of PRs (dependent):
Adminstrivia
=> refactor: Remove impl of `query::PartititionChunk` in mutable_buffer

Cargo.lock, arrow_deps/src/util.rs, data_types/src/lib.rs, data_types/src/timestamp.rs, mutable_buffer/Cargo.toml, mutable_buffer/src/pred.rs, mutable_buffer/src/table.rs, query/src/frontend/influxrpc.rs, query/src/group_by.rs, query/src/predicate.rs, query/src/util.rs, src/influxdb_ioxd/rpc/storage/expr.rs, src/influxdb_ioxd/rpc/storage/service.rs
🎉 
This involves moving `TimestampRange` into data_types, and some basic Expr stuff into data_types.
Closes #815 and completes removing query logic from the `mutable_buffer`
Order of PRs (dependent):
Adminstrivia
=> refactor: Remove mutable_buffer crate dependency on query

packers/Cargo.toml
I'm currently trying to [update the version of `rand` in the data generator crate](https://github.com/influxdata/iox_data_generator/issues/2), and I'm trying to make sure that there's the fewest number of different `rand` and `rand-*` sub crates in the dependency tree as possible.
`data_generator` depends on `packers`, which pulls in `rand` as a dependency even though as far as I can tell, `packers` only uses `rand` in tests.
So this PR moves `rand` to a dev dependency of `packers`.
=> fix: Move rand to a dev-dependency of packers

generated_types/build.rs, generated_types/protos/influxdata/iox/write/v1/service.proto, generated_types/src/lib.rs, google_types/src/lib.rs, influxdb_iox_client/src/client.rs, influxdb_iox_client/src/client/write.rs, influxdb_iox_client/src/lib.rs, src/commands/database.rs, src/influxdb_ioxd/rpc.rs, src/influxdb_ioxd/rpc/error.rs, src/influxdb_ioxd/rpc/management.rs, src/influxdb_ioxd/rpc/write.rs, tests/end-to-end.rs, tests/end_to_end_cases/management_api.rs, tests/end_to_end_cases/mod.rs, tests/end_to_end_cases/util.rs, tests/end_to_end_cases/write_api.rs, tests/end_to_end_cases/write_cli.rs
Re https://github.com/influxdata/influxdb_iox/issues/942
I want to be able to do the basic administration stuff from the IOx client directly (not a mix of curl and the CLI)
```
./influxdb_iox database write --data=/path/to/line_protocol.lp
```
Example use:
```
cargo run -- writer set 43
Ok
cargo run -- database create foo
Ok
cargo run -- database write foo tests/fixtures/lineproto/metrics.lp
1000 Lines OK
```
* Define and implement a Write gRPC service in IOx
* Define and implement a Write service client in `influxdb_iox_client`
* Implement the write CLI using those pieces
* tests for same
After discussions with @tustvold, I propose adding a new gRPC write endpoint rather than using the existing http `/api/v2/write` endpoint) for the following reason:
1. The CLI currently only has the …
=> feat: Add Service + CLI command to write line protocol to IOx

data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/management/v1/base_types.proto, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, server/src/config.rs, server/src/lib.rs, tests/end_to_end_cases/management_api.rs
The replication, query, and subscription concepts here are going to be significantly different. Thought it would be best to just remove this cruft for now to avoid confusion.
=> chore: remove cruft from config/database rules

Cargo.lock, Cargo.toml, tests/common/mod.rs, tests/common/server_fixture.rs, tests/end-to-end.rs, tests/end_to_end_cases/read_api.rs, tests/end_to_end_cases/write_api.rs
Re: https://github.com/influxdata/influxdb_iox/issues/890
This is the first in what I hope to be a series of refactors to better manage the end to end tests. Specifically I want to be able to control and report on the tests individually as a normal rust test (each be a `#[tokio::test]`) as well as run them in parallel
If we like the pattern established in this PR, I will port the rest of the tests so they run as their own individual tests and make the harness more sophisticated (e.g. so setting writer_id doesn't trample on each other) but I didn't want to do so until I had some agreement this was what was an improvement.
1. Pulls the creation / setup of the server under test into a global lazily initialized fixture so that multiple tests can use it but only one server is started
2. Moves …
=> refactor: Move end-to-end test server fixture into its own module

tests/common/server_fixture.rs, tests/end-to-end.rs, tests/end_to_end_cases/flight_api.rs, tests/end_to_end_cases/management_cli.rs, tests/end_to_end_cases/write_api.rs, tests/end_to_end_cases/write_cli.rs
Re: https://github.com/influxdata/influxdb_iox/issues/890, built on https://github.com/influxdata/influxdb_iox/pull/945
I plan to be able to run some of these tests against different servers on different ports, so I want them to rely on the ServerFixture not a constant.
This moves tests that change database wide stuff (like writer id) to use their own server process so they don't potentially clobber other tests that are running in parallel
Other:
=> refactor: rework all end-to-end.rs tests to use the server fixture rather than const connection strings

data_types/src/data.rs, influxdb_line_protocol/src/lib.rs, ingest/src/lib.rs, mutable_buffer/src/column.rs, mutable_buffer/src/table.rs, packers/src/packers.rs
Fixes #904
The line protocol parser was lacking the unsigned integer type, which
suffixes values with `u`. This adds unsigned integer support to the line
protocol parser, and fills a few corresponding gaps in the mutable
buffer.
=> fix(line-protocol): add unsigned integer field type

tests/common/server_fixture.rs, tests/end-to-end.rs, tests/end_to_end_cases/management_api.rs, tests/end_to_end_cases/management_cli.rs, tests/end_to_end_cases/read_cli.rs, tests/end_to_end_cases/write_api.rs, tests/end_to_end_cases/write_cli.rs
Re: https://github.com/influxdata/influxdb_iox/issues/890
Some of these tests were changing writer id (which is shared across tests) and thus shouldn't be run in parallel.
Add a way to start up independent servers (on their own ports) and make such non-shared servers for tests that manipulate the writer id
The end-to-end.rs test is starting to look legit:
```
cargo test --test end-to-end
...
test test_http_error_messages ... ok
test end_to_end_cases::write_api::test_write ... ok
test end_to_end_cases::management_api::test ... ok
test end_to_end_cases::write_cli::test ... ok
test end_to_end_cases::management_cli::test ... ok
test read_and_write_data ... ok
```
=> refactor: Port end-to-end tests that modify global state to their own fixture

Cargo.lock, Cargo.toml, tests/common/server_fixture.rs
Closes https://github.com/influxdata/influxdb_iox/issues/951, built on https://github.com/influxdata/influxdb_iox/pull/949
In https://github.com/influxdata/influxdb_iox/pull/945 I introduced a (global static) fixture that ran the `influxdb_iox` binary as a process. In the process I introduced a bug where that child process is never terminated: https://github.com/influxdata/influxdb_iox/issues/951
The fix is to hold a "weak" reference to the shared fixtured rather than a "strong" one. This means that once a test has started using the shared fixture, and other test that is started at the same time will share it. However, when the last test is done, the descructor will be torn down.
Prior to this PR a child process is left:
```
alamb@ip-10-0-0-124 influxdb_iox2 % cargo test --test end-to-end …
```
=> fix: Do not leave child processes around after the end-to-end tes

Dockerfile, README.md, docker/Dockerfile.iox, src/commands/server.rs, src/main.rs, tests/common/server_fixture.rs
The iox binary is both a client and a server. The user can use iox binary for all sorts of configuration tasks.
By making the iox binary itself clearly show it's such a multipurpose tool, the user can figure that out without having
to remember to read the docs (and without accidentally starting another server)
=> feat: Make server no longer the default command

Dockerfile, docker/Dockerfile.iox, src/commands/logging.rs, src/commands/server.rs, src/influxdb_ioxd.rs, src/main.rs, tests/common/server_fixture.rs
Part of #917; the goal there is to add a bunch of commands like:
```console
$ influxdb_iox server remote set 23 http://10.1.1.23:8080
```
To that end, I turned the `server` into a "subcommand group" layer, and added a `run` command that actually runs the server:
```console
$ influxdb_iox server run
```
The rest of the PR contains some simplifications and cleanups.
=> feat: Add subcommands to server

data_types/src/chunk.rs, data_types/src/lib.rs, generated_types/build.rs, generated_types/protos/influxdata/iox/management/v1/chunk.proto, generated_types/protos/influxdata/iox/management/v1/service.proto, generated_types/protos/influxdata/iox/write/v1/service.proto, influxdb_iox_client/src/client/management.rs, influxdb_iox_client/src/client/write.rs, mutable_buffer/src/database.rs, mutable_buffer/src/partition.rs, query/src/lib.rs, query/src/test.rs, read_buffer/src/lib.rs, server/src/db.rs, server/src/db/chunk.rs, server/src/snapshot.rs, src/commands/chunk.rs, src/commands/database.rs, src/commands/database/chunk.rs, src/influxdb_ioxd/rpc/error.rs, src/influxdb_ioxd/rpc/management.rs, src/influxdb_ioxd/rpc/write.rs, src/main.rs, tests/end_to_end_cases/management_api.rs, tests/end_to_end_cases/management_cli.rs, tests/end_to_end_cases/util.rs, tests/end_to_end_cases/write_api.rs
Re https://github.com/influxdata/influxdb_iox/issues/942
As I add commands to move partitions around, I also need to be able to observe the changes they are making
* Add gRPC definition and implementation for listing chunks
* Add list_chunks to management api
* implement `ChunkSummary` and `Db::chunk_summaries` in Server
* tests for same
Given a database loaded thusly:
```
./target/debug/influxdb_iox database write my_db tests/fixtures/lineproto/metrics.lp
1000 Lines OK
```
List the chunks (note the partition key is "" due to https://github.com/influxdata/influxdb_iox/issues/966):
```
./target/debug/influxdb_iox database chunk list my_db
[
{
"partition_key": "",
"id": 0,
"storage": "OpenMutableBuffer",
"estimated_bytes": 564520
}
```
* This API does not include the tables in each chunk -- …
=> feat: Add management API and CLI to list chunks

generated_types/src/google.rs, src/commands/database/chunk.rs
`FieldViolation` doesn't implement Error so I couldn't wrap it the way I expected in snafu / thiserror (it doesn't implement `Display` for example).
Add the implementation, as suggested by @tustvold on https://github.com/influxdata/influxdb_iox/pull/968#discussion_r593157399
=> refactor: impl Error for FieldViolation

src/commands/database.rs, tests/end_to_end_cases/management_cli.rs
To list databases
```
influxdb_iox database get
```
(aka no args)
To list remotes:
```
influxdb_iox remote list
```
To list chunks
```
influxdb_iox database chunk list
```
List databases via
```
influxdb_iox db list
```
Making it consistent with the other commands
=> feat: make CLI to listing database consistent with other commands

Cargo.lock, data_types/src/job.rs, data_types/src/lib.rs, generated_types/build.rs, generated_types/protos/influxdata/iox/management/v1/jobs.proto, generated_types/protos/influxdata/iox/management/v1/service.proto, server/Cargo.toml, server/src/buffer.rs, server/src/lib.rs, server/src/tracker.rs, server/src/tracker/future.rs, server/src/tracker/registry.rs, src/influxdb_ioxd.rs, src/influxdb_ioxd/rpc.rs, src/influxdb_ioxd/rpc/management.rs, src/influxdb_ioxd/rpc/operations.rs
Needs more tests, currently the gRPC API has no tests :grimacing:, and I will probably split into smaller PRs for detailed review, but wanted to create a draft for feedback on the high-level design.
Examples:
```
./scripts/grpcurl -plaintext -d '{"nanos": [10000000000, 100, 10000]}' 127.0.0.1:8082 influxdata.iox.management.v1.ManagementService.CreateDummyJob
{
"name": "2",
"metadata": {
"@type": "type.googleapis.com/influxdata.iox.management.v1.OperationMetadata",
"dummy": {
"nanos": [
"10000000000",
"100",
"10000"
]
},
"pendingCount": "3",
"taskCount": "3"
}
}
```
```
./scripts/grpcurl -plaintext -d '{"name": "2"}' 127.0.0.1:8082 google.longrunning.Operations.GetOperation
{
"name": "2",
"metadata": {
"@type": "type.googleapis.com/influxdata.iox.management.v1.OperationMetadata", …
```
=> feat: add fanout task tracking

docs/README.md
Add links to tech talks as a way to document architecture more
=> docs: Add links to tech talks

generated_types/build.rs, generated_types/protos/influxdata/iox/management/v1/partition.proto, generated_types/protos/influxdata/iox/management/v1/service.proto, influxdb_iox_client/src/client/management.rs, src/commands/database.rs, src/commands/database/chunk.rs, src/commands/database/partition.rs, src/influxdb_ioxd/rpc/management.rs, tests/end_to_end_cases/management_api.rs, tests/end_to_end_cases/management_cli.rs, tests/end_to_end_cases/util.rs
Re https://github.com/influxdata/influxdb_iox/issues/942 and https://github.com/influxdata/influxdb_iox/issues/979
I need a place to hang the CLI commands to move chunks in a partition (https://github.com/influxdata/influxdb_iox/issues/979)
* Add RPC definition + implementations for listing partitions
* Add new cli command `influxdb_iox database partition list db_name` to get a list of partition keys
There is a bunch of information about a partition that should probably be included in the output of `database partition get` but I don't need it for my demo.
Thus, I figured I would get what I did need (`list`) up alongside the basic plumbing for `get` and we can fill in the details later
List all partition keys;
```
./influxdb_iox database partition list my_db
[
"2020-06-11 16:00:00", …
```
=> feat: Add management API and CLI for listing partitions

data_types/src/database_rules.rs, src/commands/database.rs, tests/end_to_end_cases/management_cli.rs
Closes https://github.com/influxdata/influxdb_iox/issues/966.  
Currently  running the `influxdb_iox database create foo` command creates a database that is not very usable:
1. It has no mutable buffer so it can't accept writes
2. It has no partitioning rules (so all data goes into a single partition)
Changes the default database configuration to:
1. Have a 100MB mutable buffer (configurable via command line)
2. Have a default hourly partitioning rule
```
./target/debug/influxdb_iox database create my_db
Ok
./target/debug/influxdb_iox database write my_db tests/fixtures/lineproto/metrics.lp
1000 Lines OK
./target/debug/influxdb_iox database chunk list my_db 
[
{
"partition_key": "2020-06-11 16:00:00",
"id": 0,
"storage": "OpenMutableBuffer",
"estimated_bytes": 189868
}
```
Note the …
=> feat: configure databases created with CLI with reasonable defaults

object_store/src/aws.rs, src/influxdb_ioxd.rs
so that if not present, the aws client library can use builtin auth providers,
such as the InstanceMetadataProvider, which is commonly used to get the credentials
granted to the AWS VM via cloud native mechanism.
CC: @jacobmarble
=> feat: Make S3 auth parameters optional

object_store/src/aws.rs
Rusoto's ChainProvider swallows the error message produced by the underlying InstanceMetadataProvider
(see https://github.com/rusoto/rusoto/blob/d59d716f097f64a713b3bbcd5fc7b84e210647e4/rusoto/credential/src/lib.rs#L397) making it hard for us to know why it's not working in our staging cluster.
=> fix: Use InstanceMetadataProvider directly

Dockerfile, docker/Dockerfile.iox
we cannot talk to S3 otherwise
=> fix: Add ca-certificates to iox docker image

README.md, src/main.rs
Adds a pointer in the README.md to the command line tool, and documents the common pattern of command structure we hope to follow (re https://github.com/influxdata/influxdb_iox/issues/979)
=> docs: Update README.md to refer to the command and CLI help

influxdb2_client/examples/ready.rs, influxdb2_client/src/lib.rs, influxdb2_client/src/ready.rs
Get the readiness of an instance at startup
Signed-off-by: Aakash Hemadri <aakashhemadri123@gmail.com>
Messed up #988
Could require possible edits if #998 is accepted. (placement of ready.rs and import in lib.rs)
=> feat: Add support for ready API to influxdb_client

generated_types/protos/influxdata/iox/management/v1/service.proto, influxdb_iox_client/src/client/management.rs, server/src/db.rs, src/commands/database/partition.rs, src/influxdb_ioxd/rpc/management.rs, tests/end_to_end_cases/management_api.rs, tests/end_to_end_cases/management_cli.rs
Part of https://github.com/influxdata/influxdb_iox/issues/979
The commands to manipulate a chunk are in the context of a partition. The current CLI / management API to see chunks is database wide (across all partitions). Until there is a more general purpose way to restrict what comes back, add a ad hoc command to list just the chunks in a partition.
* Adds management API and CLI for listing chunks in a partition
* CLI looks like `./influxdb_iox database partition list-chunks <db_name> <partition_key>`
```
./influxdb_iox database partition list-chunks 26f7e5a4b7be365b_917b97a92e883afc '2021-03-15 12:00:00'`
[
{
"partition_key": "2021-03-15 12:00:00",
"id": 0,
"storage": "OpenMutableBuffer",
"estimated_bytes": 0
}
]
```
=> feat: Management API + CLI command to list chunks in a partition

Cargo.lock, arrow_deps/Cargo.toml, arrow_deps/src/test_util.rs, ingest/src/parquet/writer.rs, query/src/provider.rs, server/src/db/chunk.rs
Its that time (to keep our dependencies up to date and minimize conflicts)
* Update deps to point at https://github.com/apache/arrow/commit/6208a79739d0228ecc566fa8436ee61068452212
* run `cargo update` and check in the resulting `Cargo.lock` file
* The only head-scratching thing was that `LogicalType` was renamed to `ConvertedType` but then a new type called `LogicalType` was added in https://github.com/apache/arrow/pull/9592. I think I am going to propose a PR upstream in arrow to at least document this a bit better
=> chore: update deps (including arrow)

server/src/lib.rs, server/src/tracker.rs, server/src/tracker/registry.rs
We want to be able to reclaim from the TrackerRegistry and enqueue the removed data in an archive as one atomic operation. This means doing the reclaim and re-enqueue under a single lock, otherwise an external observer could potentially see missing or duplicated jobs, depending on how reads to the archive and registry are sequenced.
Nothing about the TrackerRegistry having an internal mutex prevents this, but getting rid of it removes what would then be a largely redundant mutex, and also allows a more efficient "streaming" reclaim without having to buffer via a Vec.
=> refactor: remove interior mutability from TrackerRegistry

server/src/tracker.rs, server/src/tracker/future.rs, src/influxdb_ioxd/rpc/operations.rs
As was correctly pointed out by @domodwyer the current API allows observing an inconsistent "snapshot" of the state of a tracker.
This PR alters the tracker to return a TrackerStatus that prevents observing "inconsistent" states, in particular a larger pending_count than total_count, and makes it clear what is guaranteed to be "converged" at what point.
=> fix: prevent observing inconsistent tracker states

data_types/src/job.rs, generated_types/protos/influxdata/iox/management/v1/jobs.proto, generated_types/protos/influxdata/iox/management/v1/service.proto, influxdb_iox_client/src/client/management.rs, server/src/db.rs, server/src/lib.rs, src/commands/database/partition.rs, src/influxdb_ioxd/rpc/error.rs, src/influxdb_ioxd/rpc/management.rs, tests/end_to_end_cases/management_api.rs, tests/end_to_end_cases/management_cli.rs, tests/end_to_end_cases/operations_api.rs
Part of https://github.com/influxdata/influxdb_iox/issues/979
Note us built on  https://github.com/influxdata/influxdb_iox/pull/995 and https://github.com/influxdata/influxdb_iox/pull/1000 so those need to be merged first.
Need a way to manually control the chunks on an IOx cluster
* Adds management API and CLI for closing a chunk in the mutable buffer and moving to read buffer
* CLI looks like `./influxdb_iox database partition close-chunk <db_name> <partition_key> <chunk_id>`
List chunks
```
./influxdb_iox database partition list-chunks 26f7e5a4b7be365b_917b97a92e883afc  "2021-03-16 20:00:00"
[
{
"partition_key": "2021-03-16 20:00:00",
"id": 1,
"storage": "OpenMutableBuffer",
"estimated_bytes": 132086
},
{
"partition_key": "2021-03-16 20:00:00",
"id": 0,
"storage": "ReadBuffer", …
```
=> feat: Management API + CLI command to close a  chunk and move to read buffer

src/influxdb_ioxd/rpc/storage/service.rs
While recording a demo of IOx running in tools, it would have been helpful to have slightly less messy messages and more structured logging
Use fields in the `info!` macro rather than concatenated strings for logging in service.rs
Here is an example output line showing the output after this change:
```shell
[2mMar 17 18:04:03.807[0m [32m INFO[0m influxdb_iox::influxdb_ioxd::rpc::storage::service: tag_keys db_name=4331282345624666_3694002793276983 range=Some(TimestampRange { start: 1616018643791609000, end: 1616018643791609010 }) predicate=(TagRef:host == "server01")
```
=> chore: Improve use of logging macros in storage service

.github/workflows/rust.yml
Possibly this will make CI jobs faster
(the theory is that no one will be using the interactive debugger on builds created on CI so don't spend CPU cycles creating them)
=> chore: Add debuginfo=0 to CI builds

.github/workflows/rust.yml
I assumes that debuginfo=0 would still preserve traceback line numbers but I tried it out and it doesn't.
debuginfo=1 is almost as fast as debuginfo=1 (on my mac at least)
=> fix(ci): Pass debuginfo=1 to have line numbers in tracebacks

read_buffer/benches/row_group.rs, read_buffer/src/column.rs, read_buffer/src/row_group.rs, read_buffer/src/schema.rs, read_buffer/src/table.rs, read_buffer/src/value.rs
This PR changes how aggregates and grouped aggregates are build in the Read Buffer.
The reason for this change is twofold:
1) Primarily it will simplify adding support for `FIRST` and `LAST` to the Read Buffer as supported aggregations. Possibly also `MEAN` if we decide to push that down too.
2) It improves the memory footprint and query performance of `read_aggregate` operations (any query that does an aggregate or has a group by in it).
Previously the Read Buffer took a simple approach of building grouped aggregates in a row-wise way. Effectively the read buffer would materialise all of the columns that were being aggregated and also materialise compressed versions of any columns being grouped on.
Then it would iterate the grouping columns, building group keys in a hashmap. As it did …
=> refactor: build aggregates in a column-oriented fashion 

server/src/db.rs
I'm not sure why this was implemented, it doesn't appear to be used, and I don't think it is correct - it uses the defaults for the skipped members which may be at odds with what is defined in DatabaseRules.
Removing as I need to be able to a TrackerRegistry to the Db struct which doesn't have a default
=> refactor: don't implement serialize for Db

server/src/config.rs, server/src/db.rs, server/src/lib.rs, server/src/query_tests/utils.rs, server/src/snapshot.rs
I'm not sure I particularly like this, but in order to be able to register jobs within Db it either needs to be passed a reference to a job registry at call time or construction time, the latter seemed like the least annoying.
=> feat: share job registry with Db struct

src/influxdb_ioxd.rs
Sequence frontend shutdown before shutting down internal services. We don't want to be shutting down the background workers before the API which depends on them
=> feat: sequence server shutdown

server/src/db.rs, server/src/query_tests/scenarios.rs, server/src/query_tests/utils.rs
Builds on https://github.com/influxdata/influxdb_iox/pull/1043
Reduce direct dependencies on how `Db` is structured in the rest of the code base (so we can more plausibly consolidate partitions)
Make `Db::mutable_buffer_chunks` and `Db::read_buffer_chunks` private
=> refactor: Make `Db::mutable_buffer_chunks` and `Db::read_buffer_chunks` private

Cargo.lock, arrow_deps/Cargo.toml, query/src/frontend/influxrpc.rs, query/src/frontend/sql.rs, query/src/func/selectors.rs, read_buffer/src/column/encoding/bool.rs, read_buffer/src/column/encoding/fixed_null.rs, read_buffer/src/row_group.rs
Keep on top of the changes in the underlying library
Also, bring in SQL support for common table expressions (CTE) and UNION ALL and schemas.
1. Update to https://github.com/apache/arrow/commit/9262a5d83b6037d0c39668310b1875e32f1b7e83
2. Run `cargo update` (updates summarized below)
3. Changed code to compile
Here are the other library updates:
```
Updating anyhow v1.0.38 -> v1.0.39
Updating h2 v0.3.1 -> v0.3.2
Updating http-body v0.4.0 -> v0.4.1
Updating js-sys v0.3.48 -> v0.3.49
Updating libc v0.2.89 -> v0.2.91
Updating mio v0.7.10 -> v0.7.11
Updating miow v0.3.6 -> v0.3.7
Updating serde v1.0.124 -> v1.0.125
Updating serde_derive v1.0.124 -> v1.0.125
Updating standback v0.2.15 -> v0.2.17
Updating tokio v1.3.0 -> v1.4.0
Updating tokio-stream v0.1.4 -> v0.1.5
Updating tokio-util v0.6.4 -> …
```
=> chore: Upgrade arrow deps

data_types/src/database_rules.rs, server/src/config.rs, server/src/lib.rs
Note: no effort has been made to migrate from the JSON persistence format to the protobuf persistence format
=> refactor: unify serialization of database rules (#973)

server/src/tracker.rs
fixes #1051 
It would appear some systems may not wake from sleep in a timely manner - I suspect this is probably correlated with system load.
This bumps the threshold, and removes the epsilon lower bound as `std::thread::sleep` is guaranteed to sleep for at least as long as requested
=> fix: increase timing tolerance for tracker timing test (#1051)

influxdb_line_protocol/src/lib.rs
Closes #1040
Add support upper case "E" for scientific notation
=> fix: support upper case for scientific notation

docs/README.md, docs/protobuf.md, scripts/prototxt
This PR adds a prototxt script and accompanying documentation.
Rationale: help developers deal with binary protobuf files.
=> feat: Add prototxt script

query/src/frontend/influxrpc.rs, query/src/frontend/sql.rs, query/src/lib.rs, query/src/test.rs, server/src/db/chunk.rs, server/src/query_tests/table_schema.rs
Here is an attempt to help https://github.com/influxdata/influxdb_iox/pull/1058
Rationale: `async` is no longer needed now we are using sync mutexes
Changes: remove some `async` and `await` calls.
=> refactor: Remove async from `PartitionChunk::table_schema`

query/src/exec.rs, query/src/exec/context.rs, query/src/frontend/sql.rs, query/src/lib.rs, server/src/db.rs, server/src/db/catalog/partition.rs, server/src/lib.rs, server/src/query_tests/sql.rs, src/influxdb_ioxd/http.rs, src/influxdb_ioxd/rpc/flight.rs, tests/end_to_end_cases/read_cli.rs
This is a really hacky implementation of getting CatalogProvider and SchemaProvider plumbed into IOx.
Being able to do this properly is largely dependent on the work in #1042 and #1057 as it needs an infallible, non-async way to access chunks and their associated metadata
This will also allow #1013 to put the system tables in their own schema.
Finally it will likely fix #1054
=> feat: use CatalogProvider and SchemaProvider

mutable_buffer/src/database.rs, query/src/lib.rs, query/src/test.rs, server/src/db.rs, server/src/lib.rs, server/src/query_tests/influxrpc/read_window_aggregate.rs, server/src/query_tests/scenarios.rs, server/src/snapshot.rs
Similar to https://github.com/influxdata/influxdb_iox/pull/1062
These functions needed to be `async` when the underlying implementations used the async versions of `Mutex` and `RwLock`. Now that we are using the `sync` versions of those locking primitives, there is no need for `Database` to be async either
=> refactor: Remove async from Database trait

query/src/frontend/influxrpc.rs, query/src/lib.rs, query/src/provider/physical.rs, query/src/test.rs, server/src/db/chunk.rs, server/src/snapshot.rs
These functions needed to be `async` when the underlying implementations used the async versions of `Mutex` and `RwLock`. Now that we are using the `sync` versions of those locking primitives, there is no need for `PartitionChunk` to be async either
=> refactor: Remove async from PartitionChunk

README.md, data_types/Cargo.toml, data_types/src/chunk.rs, data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, mutable_buffer/src/database.rs, server/src/config.rs, server/src/db.rs, src/commands/database.rs, tests/end_to_end_cases/management_api.rs, tests/end_to_end_cases/management_cli.rs, tests/end_to_end_cases/read_cli.rs, tests/end_to_end_cases/scenario.rs
A draft PR to get feedback - this will not compile.
This is my, potentially incorrect, interpretation of the feedback on #1041.
Specifically, as well articulated by @alamb, it seeks to provide a way to configure automatic:
* Movement of a chunk from mutable buffer -> read buffer
* Persisting of a chunk to parquet
* Dropping of chunks
As such it does the following:
* It renames MutableBufferConfig to LifecycleRules
* Renames PartitionDropOrder to SortOrder
* Adds additional new settings for configuring automated chunk movement
* Renames partition_drop_order to sort_order and generalises it to cover all chunk motion <sup>1</sup> <sup>2</sup> 
<sup>1</sup> _this implicitly encodes an assumption that people would prefer to drop data later in the lifecycle than earlier and only matters if …
=> feat: lifecycle rules (RFC)

mutable_buffer/src/chunk.rs, query/src/lib.rs, query/src/test.rs, read_buffer/src/lib.rs, server/src/config.rs, server/src/db.rs, server/src/db/catalog.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/partition.rs, server/src/db/chunk.rs, server/src/lib.rs, server/src/query_tests/utils.rs, server/src/snapshot.rs, src/influxdb_ioxd/rpc/error.rs, tests/end_to_end_cases/management_api.rs
This PR is the core change proposed for https://github.com/influxdata/influxdb_iox/issues/1042 -- it collapses the `MutableBufferDb` into the `Db` itself, by storing the mutable buffer Chunks in the Catalog
This PR ensures that the Chunks and the state in the catalog remain in sync (by storing them together)
Store the actual chunk implementation (mutable buffer chunk) in the the `catalog::Chunk` state. This leverages Rust's type system.
Note there is some logic still in the mutable buffer that isn't connected to anything yet, but that I would port over if we like this PR, such as 'last write time' for chunks and partitions.
One small change in behavior is that chunks in the mutable buffer are now created only when data is actually written to them. Previously, they were eagerly created on …
=> refactor: Manage storage directly in the Catalog

Cargo.lock, arrow_deps/Cargo.toml, query/src/exec/context.rs, server/src/query_tests/sql.rs
So we can see what tables are in each database (tada!)
Implements part of https://github.com/influxdata/influxdb_iox/issues/1013 (system tables) and adds  a test for https://github.com/influxdata/influxdb_iox/issues/1054
1. Update datafusion deps (to get https://github.com/apache/arrow/pull/9818) and run `cargo update`
2. Add tests demonstrating the use of `information_schema`
I plan to add "SHOW TABLES" support as well, but I am not sure yet if that should be baked into DataFusion or special cased in IOx. I will propose adding in DataFusion and see how far I get
```
alamb@ip-10-0-0-124 influxdb_iox % ./target/debug/influxdb_iox database query 26f7e5a4b7be365b_917b97a92e883afc 'select * from information_schema.tables'
+---------------+--------------------+------------+------------+
| …
```
=> feat: Add support for listing tables via information_schema.tables

mutable_buffer/src/chunk.rs, mutable_buffer/src/table.rs, query/src/lib.rs, query/src/test.rs, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/chunk.rs, server/src/snapshot.rs
We want to expose catalog column level details via the management API (and system tables) - https://github.com/influxdata/influxdb_iox/issues/1085
This PR
1. Adds a way to get a `PartitionSummary` for partitions in a `Db`
2. Makes some methods unfallable (as they only way for them to fail is if the mutable buffer got into a state where the dictionary was corrupted, from which there is no reasonable recovery)
=>  feat: Add ability to get `PartitionSummary` statistics from a Db

Cargo.lock, data_types/src/partition_metadata.rs, read_buffer/Cargo.toml, read_buffer/src/chunk.rs, read_buffer/src/lib.rs, read_buffer/src/table.rs, server/src/db.rs, server/src/db/chunk.rs
Builds on https://github.com/influxdata/influxdb_iox/pull/1090
We want to expose catalog column level details via the management API (and system tables) - https://github.com/influxdata/influxdb_iox/issues/1085
1. Adds calculation of `TableSummary` from ReadBufferDb
2. Hooks up to Partition chunk
This PR proposes adding a dependence from the `read_buffer` crate on the`data_types` crate
(which has many other transitive dependencies). An alternative design
is to make `MetaData` public and move the conversion code to
`TableSummary` into the `server` crate. I don't have a strong
preference, and will be happy to make a change to this PR if others do.
=> feat: Add TableSummary calculation to ReadBuffer

Cargo.lock, Cargo.toml, generated_types/Cargo.toml, google_types/Cargo.toml
After #1069 building some crates directly fails:
```console
$ cd internal_types
$ cargo build
....
#[prost(bytes="bytes", tag="1")]
744 | |     pub value: ::prost::bytes::Bytes,
| |____________________________________^ the trait `Deserialize<'_>` is not implemented for `prost::bytes::Bytes`
```
The `build.rs` file of the `generated_types` and `google_types` configures prost code generation so that it adds `#[derive(serde)]` to to all types; some types contain `Bytes` fields, which requires the `bytes` crate to have the `serde` feature flag turned on. Thus, it makes sense to declare the `bytes/serde` feature flag dependency in the crates that trigger that dependency proper.
In #1069 that feature flag was enabled in the top-level `Cargo.toml` file, which made CI happy because the CI build …
=> chore: Add the serde feature to bytes dep

server/src/db.rs, server/src/lib.rs
This takes the non-controversial parts of #1066 that are highly likely to cause conflicts with other concurrent PRs
We need to be able to mutate the database rules. This PR only a RwLock around the database rules in the `Db` struct.
A secondary aspect of this PR is that `persist_database_rules` is split out of `create_database`, in preparation for an `update_db_rules` method that can use the same code to keep database rules config file persisted on objectstore.
The actual `update_db_rules` is being worked on in a separate PR (split out from #1066)
=> refactor: Add rwlock around db rules

server/src/db.rs, server/src/lib.rs
This started as an exercise to avoid acquiring a mutex on DatabaseRules twice in rapid succession, and then morphed into removing a very confusingly named member function. However, it does highlight that Db has two member functions with very similar names that do similar but subtly different things:
* `Database::store_replicated_write` - stores data to the mutable buffer
* `Db::handle_replicated_write` - stores data into the WAL and potentially the mutable buffer via calling store_replicated_write
I've preserved the existing behavior but I wonder if there isn't something a little bit off here?
=> refactor: remove Db::writeable

Cargo.lock, arrow_deps/Cargo.toml, server/src/query_tests/sql.rs
Update Arrow/DataFusion dependencies to get access to the `SHOW TABLES` and `information_schema.columns` table
Note `SHOW COLUMNS` is coming, but the upstream Arrow PR https://github.com/apache/arrow/pull/9866 is not yet merged
```
./target/debug/influxdb_iox database query 26f7e5a4b7be365b_917b97a92e883afc "SHOW TABLES"
+---------------+--------------------+------------+------------+
| table_catalog | table_schema       | table_name | table_type |
+---------------+--------------------+------------+------------+
| public        | iox                | cpu        | BASE TABLE |
| public        | iox                | disk       | BASE TABLE |
| public        | iox                | diskio     | BASE TABLE |
| public        | iox                | mem        | BASE TABLE |
| public        | iox …
```
=> feat: add SHOW TABLES and `select * from information_schema.columns`

server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/chunk.rs
Closes #
Add 2 more ChunkState to support writing chunks to object stores. Second PR for #1081
=> feat: add 2 more chunk states for writing chunks to object store

Cargo.lock, Cargo.toml, src/commands/metrics.rs, src/influxdb_ioxd.rs, src/influxdb_ioxd/http.rs, src/main.rs, tracing_deps/Cargo.toml, tracing_deps/src/lib.rs
This change adds HTTP endpoint /metrics. Now, I need to add a metric.
=> feat: add Prometheus metrics endpoint

influxdb_iox_client/src/client.rs
I have been reading the rustdoc output and wanted to clarify what the various client APIs are for
=> docs: Improve influxdb_iox_client module descriptions

docs/style_guide.md
As discussed in standup today. I'll be picking away at fixing existing nonconforming tests soon.
=> docs: Codify our preference for no return type in test functions

data_types/src/database_rules.rs, internal_types/benches/benchmark.rs, query/src/test.rs, server/src/buffer.rs, server/src/config.rs, server/src/db.rs, server/src/lib.rs, server/src/query_tests/utils.rs, server/src/snapshot.rs, src/influxdb_ioxd/http.rs, src/influxdb_ioxd/rpc/management.rs
This turned into a bit of a yak shave as various tests were relying on being able to construct invalid DatabaseRules structures, but I think this is probably a good thing to fix
=> refactor: use DatabaseName in DatabaseRules

src/commands/database.rs
As writes are currently not ever directed to a closing chunk, there currently isn't a reason to delay moving a chunk once the linger time has passed. This will occur when the partition is no longer hot for writes, or when the chunk has been moved to closing due to exceeding the mutable_size_threshold.
=> fix: disable minimum age by default

server/src/db/lifecycle.rs
If you look at the logs from tools [https://logs.aws.influxdata.io/search?q=kubernetes_container_name%3Aiox+AND+log_processed_level%3Aerror&rangetype=relative&relative=7200](link)
There are many log messages about not being able to evict a chunk, but I don't think that is an error
=> fix: avoid spamming the logs with errors that are not errors

internal_types/src/lib.rs, internal_types/src/once.rs, server/src/lib.rs
Extract the underlying primitive used by #1131 to avoid accidental misuse
=> refactor: extract OnceNonZeroU32

data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/write/v1/entry.fbs, generated_types/src/entry_generated.rs, internal_types/src/entry.rs, internal_types/src/lib.rs
This implements a builder for converting line protocol to the Entry flatbuffers. It also contains wrapper structs to make working with the flatbuffers a little easier.
The flatbuffer needed an addition to keep track of how many bits in the null mask should be used.
I still need to implement the wrapper and builder for SequencedEntry, but I wanted to get this up for comment and cleanup first.
=> feat: implement line protocol to flatbuffers

read_buffer/benches/row_group.rs, read_buffer/src/chunk.rs, read_buffer/src/lib.rs, read_buffer/src/row_group.rs, read_buffer/src/table.rs, server/src/db.rs
This PR refactors the Read Buffer so that a public API is exposed at the `Chunk` level. It does not break any existing behaviour (I kept the existing top-level DB/Partition for now).
The plan is to update the Catalog and Chunk representation in a follow on PR to use this new `Chunk` API and then I will start to cull code from the Read Buffer that's not longer needed.
I have exposed the following API:
- Chunk size: `size()`
- Chunk id: `id() -> u64`
- Table Names `table_names` and also `all_table_names`
- The schema for a `read_filter` execution `read_filter_table_schema` in 42c10e0 
- Whether there is a table in the chunk `has_table` in 6b7a5cf
- `read_filter` in 84ad3ac
- Whether a specified table could possible have rows for a predicate: `could_pass_predicate` in 82a5b78
- …
=> refactor: expose ReadBuffer public API at Chunk level

README.md
This PR fixes the IOx tech talk links in the README.
=> chore: update tech talk links in README

read_buffer/src/chunk.rs, read_buffer/src/column.rs, read_buffer/src/column/boolean.rs, read_buffer/src/column/encoding/bool.rs, read_buffer/src/column/encoding/dictionary.rs, read_buffer/src/column/encoding/dictionary/plain.rs, read_buffer/src/column/encoding/dictionary/rle.rs, read_buffer/src/column/encoding/fixed.rs, read_buffer/src/column/encoding/fixed_null.rs, read_buffer/src/column/float.rs, read_buffer/src/column/integer.rs, read_buffer/src/column/string.rs, read_buffer/src/lib.rs, read_buffer/src/row_group.rs, read_buffer/src/table.rs
@tustvold suggested it would be more consistent with the std library if the `size` method returned a `usize` rather than a `u64`. This PR makes those changes.
The changes to the `Database` and `Partition` are just hacked in with casting because those APIs are going away soon.
=> refactor: update size method to return usize

src/commands/database.rs
Rationale: it's easier to work with a newline separated list of names, rather than a comma separated one.
You can `head`, or `tail` or `| while read i; do ...`, or just copy paste it and manipulate it around more easily.
=> feat: Return newline delimited database names in database list

Cargo.lock, mutable_buffer/Cargo.toml, mutable_buffer/src/chunk.rs, mutable_buffer/src/table.rs, parquet_file/Cargo.toml, parquet_file/src/chunk.rs, server/src/buffer.rs, server/src/db.rs, server/src/db/catalog.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/partition.rs, server/src/db/lifecycle.rs, server/src/lib.rs, server/src/snapshot.rs, src/influxdb_ioxd/rpc/operations.rs, tracker/src/lib.rs, tracker/src/mem.rs, tracker/src/task.rs, tracker/src/task/future.rs, tracker/src/task/history.rs, tracker/src/task/registry.rs
Builds on top of #1124 and adds an extremely basic memory tracker.
Creating as a draft to get feedback on the general approach before improving the end-to-end test coverage.
The basic idea is to allow instrumenting objects with memory tracking handles that can easily be updated from said object, and will record the memory as "freed" on drop. Initially this is useful for providing memory instrumentation within the catalog, but I'd imagine this pattern could be useful for tracking memory usage for queries, and/or data structures within the read buffer, etc... 
The advantage of this approach over a global count coordinated in Db or similar, is it is guaranteed to live as long as the objects themselves live, which due to the use of Arcs may after they've been removed from the owning data …
=> feat: add basic memory tracking

data_types/src/database_rules.rs, influxdb2_client/src/api/ready.rs, influxdb2_client/src/api/setup.rs, influxdb2_client/src/data_point.rs, influxdb2_client/src/lib.rs, influxdb_line_protocol/src/lib.rs, influxdb_tsm/src/mapper.rs, ingest/src/lib.rs, mutable_buffer/src/column.rs, object_store/src/aws.rs, object_store/src/azure.rs, object_store/src/buffer.rs, object_store/src/disk.rs, object_store/src/gcp.rs, object_store/src/memory.rs, query/src/exec.rs, query/src/exec/schema_pivot.rs, query/src/exec/seriesset.rs, server/src/lib.rs, src/commands/run.rs, src/influxdb_ioxd/http.rs, src/influxdb_ioxd/rpc/storage/service.rs, wal/src/lib.rs, wal/tests/no_concurrency.rs
This brings the whole codebase in line with [this guideline in the style guide](https://github.com/influxdata/influxdb_iox/blob/main/docs/style_guide.md#dont-return-result-from-test-functions).
I found these by doing `grep test] -A 1 | grep Result`. Let me know if you can think of something that would miss.
=> fix: Don't return Result from test functions

Cargo.toml, src/commands/metrics.rs, src/influxdb_ioxd/http.rs
closes https://github.com/influxdata/influxdb_iox/issues/1118
As we roll out IOx to production, we need to understand the data that is flowing through it and the traffic it is handling. The first important metric is "how much line protocol are we handling"
Record metrics for:
1. Number of bytes of line protocol that were parsed and stored successfully
2. Number of lines of line protocol that were rejected
3. Number of lines of line protocol formatted data that were parsed and stored successfully
Are there standard names for these metrics from influxdb and if so what are they (so IOx can use the same names)?
=> feat: add line protocol ingest metrics

Cargo.lock, arrow_deps/Cargo.toml
* To get a fix for incorrect LIMIT results from https://github.com/apache/arrow/pull/9924
* Update arrow ref and then run `cargo update`
=> chore: Update datafusion / arrow deps again

Cargo.lock, Cargo.toml, src/main.rs
jemalloc is a good allocator, which IIUC was the default in rust, but since it's not available on all the supported rust targets it is no longer default. Rust not supports choosing an allocator and thus users can choose whether to use jemalloc.
See https://internals.rust-lang.org/t/jemalloc-was-just-removed-from-the-standard-library/8759
=> feat: Switch to jemalloc

.circleci/config.yml, generated_types/check-flatbuffers.sh, generated_types/regenerate-flatbuffers.sh
Fixes #1019.
[Here's an example of the job failing when I intentionally changed the fbs without updating the generated code](https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/4425/workflows/c19aa192-f7f8-4411-9d39-828b86a2ca3a/jobs/9287).
=> chore: CI check that generated flatbuffers code has been updated if needed

generated_types/protos/influxdata/iox/write/v1/entry.fbs, generated_types/src/entry_generated.rs, internal_types/benches/benchmark.rs, internal_types/src/entry.rs
This PR adds a builder and wrapper type for SequencedEntry. I've broken it out into 4 commits to do a little testing along the way and it might be useful to look at this in that order.
First, I implemented the builder as the flatbuffer was constructed: 0c4baa49d04c48b68b829f683c09d3a1022e0f54
That looked ugly to me and I was worried about rebuilding the flatbuffer being wasteful so I decided I'd try it out with the Entry in SequencedEntry just being a raw byte array of the previously built Entry flatbuffer. So I created a benchmark to see how long a SequencedEntry would take to construct: a5be1470eedcedb30bd3c01ed2ff0ffc5ed678b4
And then I added a new SequencedEntryRaw type and updated the flatbuffer so I could have the raw entry bytes: 0ecb379c4e0483573e1d234f5a937d8abae10fa9.
And …
=> feat: add sequenced entry builder

Cargo.lock, read_buffer/Cargo.toml, read_buffer/src/chunk.rs, server/src/db.rs, server/src/db/lifecycle.rs
Closes #1141 
Closes #1100
This PR plumbs @tustvold's memory tracker through the Read Buffer at the `Chunk` level.
Right now it uses the `size` method to effectively reset the size as new tables are pushed into a `Chunk`.
=> feat: add memory tracking to Read Buffer

Cargo.lock, Cargo.toml, buf.yaml, data_types/src/field_validation.rs, data_types/src/lib.rs, generated_types/protos/influxdata/iox/management/v1/service.proto, influxdb_iox_client/src/client/management.rs, server/src/config.rs, server/src/lib.rs, src/influxdb_ioxd/rpc/management.rs, tests/end_to_end_cases/management_api.rs
Part of #919
https://google.aip.dev/134 describes a pattern for gRPC CRUD.  We don't implement field_masks, which are optional.
This PR implements the Update API for database rules resources.
We deviate a little bit from https://google.aip.dev/134 in that we didn't reach consensus on whether to adopt the resource style of https://google.aip.dev/134 w.r.t return message of the CRUD methods, so we'll keep following the good old non-aip protobuf rules (every method should have their own request and response types).
In another PR I'll implement e-tags, so we can safely perform read-update-write cycles using this API.
---
This PR used to have a field_mask implementation which was pulled out and will be proposed again in another PR in the future, once it has better ergonomic and we gain more …
=> feat: Implement Update API for Database (rules)

scripts/edit_db_rules
There are a few yaks to be shaven before we have a good CLI for editing database rules.
This is a simple shell script that uses the grpc API to edit the database rules on a remote
IOx server. It fetches the rules, spawns your default text editor, waits until your editor quits,
and then calls the update API with the results of your local edit.
(if you use emacs, there is a thing called emacsclient which knows how to block until you closed
the buffer in your main persistent emacs)
=> feat: Add edit_db_rules script

query/src/lib.rs, query/src/test.rs, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/chunk.rs, server/src/snapshot.rs, src/influxdb_ioxd/http.rs
This lifts the table and chunk summarisation out of DBChunk (and by extension PartitionChunk) and into the catalog.
In the short term this removes the need to snapshot column statistics from the mutable buffer, and avoids some potential confusion as to whether methods like size() are the size of the snapshot or the snapshotted chunk.
Longer term, I think we will want to be lifting table statistics into the catalog anyway for immutable data in the read buffer, object storage, etc... so I think this change also makes sense in light of that
=> refactor: lift chunk and table summaries out of DBChunk

.circleci/config.yml, docker/Dockerfile.ci, generated_types/check-flatbuffers.sh
Ok, there were a number of problems that surfaced when the flatbuffers checking got merged into main that I'm fixing now:
- If the script found changes that weren't checked in, it wouldn't show you what the changes were. Now, if there are changes, the script will run `git diff` without `--quiet` to show what it thinks changed.
- I was trying to only run the checks if the current PR changed the flatbuffers schemas. However, there isn't actually a way to do that-- Circle CI gives you the commit that was last run for that branch and the current commit for that branch. So if you push a commit that changes the flatbuffers but doesn't check in the changes, that'll fail, but if you push another commit to the same branch that *doesn't* change the flatbuffers schema, the checks won't run and that …
=> fix: Don't be as clever in the flatbuffer checking

Cargo.lock, data_types/src/chunk.rs, generated_types/protos/influxdata/iox/management/v1/chunk.proto, parquet_file/src/chunk.rs, parquet_file/src/table.rs, server/Cargo.toml, server/src/db.rs, server/src/db/chunk.rs, server/src/query_tests/utils.rs
Closes #
This is kind of e2e test for the function [load_chunk_to_object_store](https://github.com/influxdata/influxdb_iox/blob/d84f05b2f5eca6a3f95fb7a21f7fe48046231d88/server/src/db.rs#L424) implemented for #1081 to write data to Object Store (OS). In order to test this, a new DB I created then data is loaded in MB, then moved to RB, then loaded to OS.
=> feat: Add tests for writing RB chunks to Object Store

src/influxdb_ioxd/http.rs
Part of #1188
Tried with
```shell
cargo run -- run -vv
```
=> fix: Use debug level to log requests

mutable_buffer/src/chunk.rs, mutable_buffer/src/lib.rs, mutable_buffer/src/table.rs, server/src/db/pred.rs, server/src/db/streams.rs
#1179 removed the query handling logic to instead point at ChunkSnapshots instead of MBChunks, effectively orphaning all this code. 
We may in future push more predicates into the ChunkSnapshot, but the current formulation of MUB predicates is tightly coupled with the MUB data representation. As the ChunkSnapshots are formulated instead in terms of arrow record batches, I'm not sure there is much reason to keep this code around. It will, of course, be preserved in the git history should we wish to refer to it in future
=> refactor: remove mutable buffer predicate logic

generated_types/protos/influxdata/iox/write/v1/service.proto, server/src/db.rs, server/src/lib.rs, src/influxdb_ioxd/rpc/error.rs, src/influxdb_ioxd/rpc/write.rs
Part of #916 
This PR adds a WriteBuffer gRPC API endpoint and an implementation that sends the entry to the Server.
The Server currently only implements the "local" short-circuit, which sends entries to the mutable buffer if the "write buffer" (aka WAL) is not configured for this node+database.
This PR is a prerequisite integration point for further work in the query later and in the write buffer layer.
=> feat: Implement WriteBuffer gRPC

read_buffer/src/chunk.rs, read_buffer/src/table.rs, server/src/db.rs
Follows on from #1201
This PR refactors the `read_time_range` method recently added in #1201 to use the semantic type of the columns in the table schema to determine which is the timestamp column, and then return the range for that column.
I changed it to do this as the `time_range` `i64` methods/fields in the Read Buffer are vestiges of a time when I was thinking about timestamps as being particularly special. They're not, and I'm going to remove those references.
=> refactor: use read_buffer column range for time range

arrow_deps/src/test_util.rs, query/src/exec.rs, query/src/exec/context.rs, query/src/exec/task.rs, query/src/frontend/sql.rs, server/benches/tag_values.rs, server/src/config.rs, server/src/db.rs, server/src/lib.rs, server/src/query_tests/influxrpc/field_columns.rs, server/src/query_tests/influxrpc/read_filter.rs, server/src/query_tests/influxrpc/read_group.rs, server/src/query_tests/influxrpc/read_window_aggregate.rs, server/src/query_tests/influxrpc/table_names.rs, server/src/query_tests/influxrpc/tag_keys.rs, server/src/query_tests/influxrpc/tag_values.rs, server/src/query_tests/influxrpc/util.rs, server/src/query_tests/sql.rs, server/src/query_tests/utils.rs, server/src/snapshot.rs, src/influxdb_ioxd/http.rs, src/influxdb_ioxd/rpc/flight.rs, src/influxdb_ioxd/rpc/management.rs
Follow on to https://github.com/influxdata/influxdb_iox/pull/1191, and related to https://github.com/influxdata/conductor/issues/244 where running CPU heavy queries can cause IOx to stop responding to health check queries.
Ensure that all queries are executed on the dedicated worker pool rather than the main tokio pool
1. Plumb a single `Arc<Executor>` through the Server and down into each Db
2. Ensure that all invocations of planning / plans happen via the `Executor`'s thread pool and not the (implicit) tokio one
I plan this for the (next) PR:
=> feat: Use single db-wide executor for running queries

data_types/src/timestamp.rs, parquet_file/src/chunk.rs, parquet_file/src/table.rs, server/src/db.rs, server/src/db/chunk.rs
Closes #
Second PR for #1082
I think left over:
=> feat: implement a few more functions as part of supporting query from parquet file

query/src/exec.rs, query/src/exec/seriesset.rs, query/src/frontend/influxrpc.rs, src/influxdb_ioxd.rs, src/influxdb_ioxd/http.rs, src/influxdb_ioxd/planner.rs, src/influxdb_ioxd/rpc/flight.rs, src/influxdb_ioxd/rpc/storage/service.rs
Follow on to https://github.com/influxdata/influxdb_iox/pull/1198 and closes https://github.com/influxdata/conductor/issues/244 where running CPU heavy queries can cause IOx to stop responding to health check queries.
Some queries can take a long time to plan (e.g. some of the "metadata" queries that touch actual data"), and we would liek these queries not to prevent other API requests from being serviced.
While the `Planner` structure is somewhat repetitive, wrapping the underlying `query::frontend` planners, this design has the benefit of keeping all the async / threading out of the core planning logic and isolated to the `influxdb_ioxd` module, where it is needed.
This structure should also make switching to a dedicated thread pool just for planning, if we ever want to, relatively …
=> feat: Run query plans on the database wide executor as well

src/influxdb_ioxd.rs
Closes #1206
__Rationale__
The IOx server can be started with an writer id flag/env variable, or the writer id
can be set with an RPC call from conductor.
If the writer ID is passed from a flag, it immediately loads the database configuration
at startup time.
If the pod networking system is not yet ready during early startup (e.g. when the main
container wins the race against the istio envoy sidecar), network requests to S3 (and to the
local cloud metadata server anycast address used to retrieve the IAM auth token) will fail.
In these cases, generally the simplest thing to do is to crash early; k8s will restart the
container and eventually envoy will be ready.
If the crash is caused by a config error, the crashlooping effect will effectively
inform the deployment controller that the …
=> fix: Crash early when writer id is passed on cmdline and cannot loaddb from objectstore

src/influxdb_ioxd/rpc/flight.rs, tests/end_to_end_cases/flight_api.rs
Closes #1226
It is perfectly legitimate for a query to return 0 rows, so there is no reason to make an error in this case
(I was seeing this error when scraping remote system tables in https://github.com/influxdata/influxdb_iox/pull/1117 for databases that had no data yet)
Remove error, add test
=> fix: Flight Query API Internal error "There were no results from ticket"

docker/Dockerfile.ci
I *think* I have everything I'll need installed correctly. Tomorrow I'll be pushing code that uses these changes and adds scripts to regenerate the flatbuffers and run the InfluxDB 2.0 OSS integration tests in docker containers by default, but these changes will need to be merged first so submitting them separately.
I hackily ran the `ci_image` job to make sure it'll pass - [it did](https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/4762/workflows/0dd451c4-6a2b-4acc-84c1-6e9de1eeebf3/jobs/11627), and the image is tagged ci-test in quay if you want to take a look at it. 
Figured pushing a different tag to quay would be a way I can use these changes in CI before this is merged and the `ci_image` job is run for real.
=> chore: Changes to the CI docker image to enable flatbuffer regeneration and InfluxDB 2.0 integration tests

scripts/edit_db_rules
- enable quitting on error by fixing `read` (read with heredoc always exits with non-0 causing the script to bail out)
- enable quitting on unbound variables by pulling cleanup outside of main
- accept hosts with `http://` prefix or without (improve compat with iox client)
Now the script cleanly reports errors when you have a typo in the db name or hostname
=> fix: Fix edit_db_rules script

data_types/src/consistent_hasher.rs, data_types/src/database_rules.rs, data_types/src/lib.rs, generated_types/protos/influxdata/iox/management/v1/shard.proto
Part #916 
This PR adds implements the `Sharder` trait for the `ShardConfig` struct.
It implements the `table_name_regexp` predicate for `specific_targets` matcher. 
It uses a simple `ConsistentHasher` impl to assign a shard id to each parsed LP line, according to the parameters specified in the `hash_ring` config.
This PR leaves the general `predicate` matcher unimplemented, since we still have to design it.
Next:
=> feat: Implement sharding logic

mutable_buffer/src/table.rs, query/src/func/window.rs
This is cleanup of some code that got introduced in https://github.com/influxdata/influxdb_iox/pull/1230
There is no reason to create copies of `Vec`s to make `TimestamNanosecondArrays`
Stop making copies of `Vec`s to make `TimestamNanosecondArrays`
=> fix: don't clone arrays to make TimestampNanosecondArrays

Cargo.lock, mutable_buffer/src/table.rs, object_store/src/path.rs, parquet_file/Cargo.toml, parquet_file/src/chunk.rs, parquet_file/src/storage.rs, parquet_file/src/table.rs, query/src/func/window.rs, server/src/db/chunk.rs
Closes #
The third PR for #1082 which implements the most tricky function read_filter for parquet.
@alamb: I follow what have been done in DataFusion but need some changes to work for us. At this stage, I am seeking for feedback whether this is an acceptable approach for us.
=> feat: full implementation of parquet's read_filter

Cargo.lock, read_buffer/Cargo.toml, read_buffer/src/chunk.rs, read_buffer/src/column.rs, read_buffer/src/column/boolean.rs, read_buffer/src/column/encoding/dictionary/rle.rs, read_buffer/src/column/encoding/fixed.rs, read_buffer/src/column/encoding/fixed_null.rs, read_buffer/src/column/float.rs, read_buffer/src/column/integer.rs, read_buffer/src/row_group.rs, read_buffer/src/schema.rs, read_buffer/src/value.rs
Closes https://github.com/influxdata/conductor/issues/253
This PR adds some logging to the Read Buffer to give me an idea of what the current situation is within our internal monitoring cluster.
I am emitting a fair bit of noise at `info` at the moment, which I will quieten down in due course and turn into alternative telemetry.
=> refactor: log new row groups added to read buffer

data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, src/commands/database.rs
This should prevent writer deaths for default configs.
Closes #1225.
=> fix: set defaults for `persist` and `drop_non_persisted` to `true`

read_buffer/src/chunk.rs, server/src/db.rs
Now I have some good data on what's currently happening with chunk migration into the Read Buffer we can quieten down the logs. 
I have decided to continue to emit details at the `info` level on a single line for when we move a row group into the Read Buffer so as to provide some high level observability in the logs around this.
=> refactor: quieten down logs

docker/Dockerfile.ci
This updates our CI builder to use `stable` Rust. This will allow me to regenerate the CI build to close out #1261
=> chore: update circle job

Cargo.lock
https://github.com/hyperium/tonic/pull/591 introduced a change to tonic codegen was then released in 0.4.2.
Arrow-flight is checking in the generated code from tonic, which has been updated to use 0.4.2. The result is that trying to compile arrow-flight with an older version of tonic e.g. 0.4.1 results in errors about `futures_core` not existing.
I personally feel that a breaking API change probably shouldn't have been a patch version bump in tonic, which cargo views as semver compatible, but the quick fix is to update the lockfile to use the new versions
=> chore: update tonic to 0.4.2

mutable_buffer/src/table.rs
Otherwise we see a horrible message such as the following in the log
```
level=error msg="Error while handling request" error="WritingPoints { org: \"844910ece80be8bc\", bucket_name: \"05d2e1304a88c000\", source: UnknownDatabaseError { source: WriteEntry { partition_key: \"2021-04-13 17:00:00\", chunk_id: 0, source: TableWrite { table_name: \"query_log\", source: InternalColumnTypeMismatch { column_id: 7, expected_column_type: \"i64\", actual_column_type: \"f64\" } } } } }" error_message="Internal error writing points into org 844910ece80be8bc, bucket 05d2e1304a88c000:  database error: Can not write entry 2021-04-13 17:00:00 0: Error writing table \'query_log\': Internal error: Expected column 7 to be type i64 but was f64" 
```
=> refactor: update schema conflicts to display column name

.circleci/config.yml, docs/regenerating_flatbuffers.md, docs/testing.md, generated_types/check-flatbuffers.sh, generated_types/regenerate-flatbuffers.sh, influxdb2_client/tests/common/server_fixture.rs
Fixes #1176.
Fixes #1166.
If you want to opt out of using Docker for either regenerating the flatbuffers or running the InfluxDB 2.0 integration tests, you can set the environment variable `LOCAL=1`.
=> chore: Run flatbuffers regeneration and InfluxDB 2.0 integration tests in docker by default

src/influxdb_ioxd.rs
Currently we log the git_hash version the binary has been compiled at only when the server actually starts,
which means that we don't easily see the version of the binary when it crashes before starting.
=> feat: Log git_hash when starting

docs/testing.md, influxdb2_client/tests/common/server_fixture.rs, object_store/src/aws.rs, object_store/src/azure.rs, object_store/src/gcp.rs
By popular vote, this changes the default test running behavior to not even try to run the `influxdb2_client` or `object_store` integration tests unless the `TEST_INTEGRATION` environment variable is set.
=> test: Don't run any integration tests unless TEST_INTEGRATION is set

mutable_buffer/src/chunk/snapshot.rs, read_buffer/src/chunk.rs
Rust 1.50 made stable [`bool::then`](https://blog.rust-lang.org/2021/02/11/Rust-1.50.0.html#library-changes), which lets you transform `true` into `Some(x)` and `false` into `None`. There were a coupleof places in IOx where this  could be used so I've updated them.
=> refactor: use then method on bool

data_types/src/chunk.rs, data_types/src/job.rs, generated_types/protos/influxdata/iox/management/v1/chunk.proto, generated_types/protos/influxdata/iox/management/v1/jobs.proto, generated_types/protos/influxdata/iox/management/v1/service.proto, influxdb_iox_client/src/client/management.rs, server/src/db.rs, server/src/db/catalog.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/partition.rs, server/src/db/lifecycle.rs, server/src/db/system_tables.rs, server/src/lib.rs, server/src/query_tests/influxrpc/read_window_aggregate.rs, server/src/query_tests/scenarios.rs, server/src/query_tests/sql.rs, server/src/snapshot.rs, src/commands/database/partition.rs, src/influxdb_ioxd/http.rs, src/influxdb_ioxd/rpc/error.rs, src/influxdb_ioxd/rpc/management.rs, tests/end_to_end_cases/management_api.rs, tests/end_to_end_cases/management_cli.rs
This changes the hierarchy from
```
database -> partition -> chunk -> table
```
to
```
database -> partition -> table -> chunk
```
Only the high-level APIs are changed for now. The chunk states (like
MutableBuffer and ReadBuffer) still multiplex tables, although they will
always only get a single table assigned (or no table if no data was
presented yet).
Closes #1256.
=> refactor: make chunks per-table

read_buffer/src/row_group.rs, read_buffer/src/table.rs, server/src/db.rs
The Read Buffer treats time as just another column, and the `time_range` fields I had on the meta data of tables and row groups is just  cruft from a previous design iteration.
As mentioned in https://github.com/influxdata/influxdb_iox/pull/1212 we can just use column ranges for the time column.
This PR removes the explicit `time_range` field.
=> refactor: remove explicit time_range field from read buffer

Cargo.lock, arrow_deps/Cargo.toml
This moves to using arrow and Datafusion sourced from their new git repositories.
Unfortunately the split between the repositories whilst retaining git version pins requires replicating the exact version pins from DataFusion here, which isn't ideal. I've created https://github.com/apache/arrow-datafusion/issues/80 to maybe kickstart a discussion on doing this differently. We're fortunate Datafusion is the only library in our dependency tree that depends on arrow and isn't versioned in the same git repository as arrow itself - otherwise we'd be in a bit of a pickle.
=> chore: update arrow versions

read_buffer/Cargo.toml
The observability_deps crate name was erroneously wrapped in double
quotes.
=> chore: fix observability dependency key

.circleci/config.yml, docker/Dockerfile.iox
This PR adds some debug output to the CI build process to print out the SHA of the release binary built, and then the SHA of the binary added to the container image built in the "perf" build job, so we have some useful information to look at when debugging the issue we're seeing where two builds are producing an image with the same digest, despite coming from different commits with apparently meaningful code changes.
=> chore: logging to debug CI

data_types/src/job.rs, server/src/db.rs, server/src/db/system_tables.rs, server/src/lib.rs, server/src/query_tests/scenarios.rs, server/src/query_tests/sql.rs, tracker/src/task.rs
Closes https://github.com/influxdata/influxdb_iox/issues/1214
As someone administering an IOx cluster
I want to be able to slice and dice the list of operations that an IOx server is doing using SQL
So that I can easily narrow in on what the server is doing
```
alamb@ip-10-0-0-124 influxdb_iox % ./target/debug/influxdb_iox database query my_db "select * from system.operations"
+----+----------+--------------------+---------+---------------------+----------+-----------------------------+
| id | status   | cpu_time_used      | db_name | partition_key       | chunk_id | description                 |
+----+----------+--------------------+---------+---------------------+----------+-----------------------------+
| 0  | Complete | 00:00:00.023225348 | my_db   | 2020-06-11 16:00:00 | 0        | …
```
=> feat: List background operations as system.operations table

src/influxdb_ioxd/http.rs
__Rationale__
1. It's useful to know how much data we're throwing on the floor due to errors.
Common ingestion errors are "no such database" or "max hard size reached".
In both cases it's useful to be quickly able to gauge how much data would
be ingested once the limiting factor for ingestion is lifted (e.g. the database is created via
the management interface).
2. The name of the metric is `ingest_points_bytes_total` and the documentation states: `The number of bytes written`
It's confusing to only count successes while not mentioning this neither in the metric name,
nor in the metric description.
3. The sister metric `ingest_points_total` already records both successes and failures.
__Changes__
This PR adds a `status` tag to the `ingest_points_bytes_total`, mirroring what
we already do …
=> feat: ingest_points_bytes_total records both success and errors

src/influxdb_ioxd/http.rs
__Rationale__
Debug logs in the middle ware (and potentially elsewhere) can cause authorization headers
(containing authentication tokens) to be accidentally leaked in the logs.
It's easy to just remove those headers early in our HTTP middleware.
=> fix: Remove authorization header in middleware

.circleci/config.yml
Works around https://github.com/influxdata/k8s-idpe/issues/3038
=> fix: Disable docker layer caching in CI

metrics/src/lib.rs
the 0.5 and 0.9 and 0.99 buckets suspiciously look like percentiles; they should be bounds instead.
Histogram bucket bounds are in the same domain as the values being measured. In our case that's often event durations.
I took this particular list of default buckets from the prometheus Go client's default; which is generally a good default for things like http request durations
NOTE: I need to fix an imperial ton of unit tests
=> fix: Histogram boundaries are durations not percentiles

Cargo.lock, query/src/frontend/influxrpc.rs, query/src/lib.rs, query/src/test.rs, server/Cargo.toml, server/src/db.rs, server/src/db/catalog.rs, server/src/db/catalog/partition.rs, server/src/db/chunk.rs, server/src/query_tests/table_schema.rs, server/src/snapshot.rs
Relates to #736 and https://github.com/influxdata/influxdb_iox/issues/735 #734
This plumbs predicate pushdown into the catalog, and provides implementations for pruning based on partition key and table name.  Pruning based on chunk data is left for a future PR. The major benefit of pushing predicates through to the catalog is it allows pruning to occur before snapshotting any chunks.
It should be noted that the way the SQL frontend is currently wired up means that no predicates are passed down, this is tracked by #734
=> feat: pushdown table and partition key predicates to catalog (#736)

data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, server/src/db/lifecycle.rs
Having chunks linger in a closing state seems to be a repeated source of confusion, and currently serves no purpose as the requisite logic is not hooked up in the write path anyway.
This PR changes the mutable_linger_seconds and mutable_minimum_age_seconds to only impact whether a chunk in the open state is considered a move candidate, any closing chunks will immediately be considered candidates, with the order determined by the sort order.
This effectively redefines the closing state to be the window of time between when a chunk exceeds the mutable size threshold and when it starts to be moved to the read buffer based on available resource (currently the heuristic for this is very basic, it just moves them one at a time)
=> feat: move closing chunks as soon as possible

.circleci/config.yml
This way we always have an image ready to run the tests on our staging environment
=> feat: Build a perf_image image for every commit in main

influxdb_tsm/src/encoders/simple8b.rs
This fixes an overflow error when `usize` is 32 bits. Not sure if this will actually run on a 32-bit Raspberry Pi.
```
pi@pi2:~/projects/influxdb_iox $ cargo build -j 1
Compiling croaring-sys v0.4.6
Compiling influxdb_tsm v0.1.0 (/home/pi/projects/influxdb_iox/influxdb_tsm)
error: this arithmetic operation will overflow
--> influxdb_tsm/src/encoders/simple8b.rs:62:27
|
62 |             let mut val = ((idx + 2) << S8B_BIT_SIZE) as u64;
|                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^ attempt to shift left by `60_usize`, which would overflow
|
= note: `#[deny(arithmetic_overflow)]` on by default
error: aborting due to previous error
error: could not compile `influxdb_tsm`
To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish... …
```
=> chore: fix usize 32-bit overflow

read_buffer/src/chunk.rs
This PR fixes the log key/value for the number of rows emitted by a log line from read buffer chunk creation.
It also changes the compression ratio so it's using the "space saving" compression definition, which would be:
- before in MUB: 50MB;
- after in RB: 34MB;
- compression = `(1 - 34 / 50) * 100.0 = 32%`
The row group has been compressed by 32% and is now 68% of the size it was before. If row groups grow when compressed in the Read Buffer the compression will be negative.
Finally, the PR adds some timing information to the row group creation, which can be useful to know.
=> fix: emit correct number of rows in log line

data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, server/src/db.rs, src/commands/database.rs
__Rationale__
We want to be able to explore the effects of the background worker loop period before prioritizing work on more clever loop adaptive control.
=> feat: Make background task period configurable

internal_types/benches/benchmark.rs, internal_types/src/entry.rs, mutable_buffer/benches/snapshot.rs, mutable_buffer/benches/write.rs, mutable_buffer/src/chunk.rs, mutable_buffer/src/table.rs, server/src/db.rs, server/src/db/catalog.rs, server/src/db/lifecycle.rs
Which is effectively the same thing as always the same in the flatbuffers, as the flatbuffers generated code will return a value of 0 if the clock value isn't present.
=> fix: Validate that ClockValue is never 0

tracker/src/task.rs, tracker/src/task/future.rs
The tracker system has two counters, pending_registrations and pending_futures. When they both hit 0 the tracker is considered 
complete. The purpose behind pending_registrations is that futures could complete in another thread before registration in the current thread has finished. 
Currently this can't occur in IOx as the fanout capability is currently not being used, but the system is designed to handle it correctly.
Unfortunately #1266 has a bug in that it will signal when the last future has been dropped, irrespective of if there are pending registrations. This means if you call join on a tracker before it has finished being registered with all its futures, join might return when is_complete would evaluate to false. This is an exceedingly strange scenario, but is at least …
=> fix: tracker join shouldn't return if pending registrations

Cargo.lock, arrow_deps/Cargo.toml
Bring in latest and greatest datafusion (and arrow) dependences to IOx
We have big plans in arrow/datafusion land to turn this into proper released versions, but we are not done with that yet and thus in the intervening time we'll keep doing it manually.
=> chore: update deps

data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, server/src/db.rs, server/src/db/lifecycle.rs, src/commands/database.rs, tracker/src/task.rs, tracker/src/task/registry.rs
This reformulates the lifecycle manager to instead backoff when there is nothing to do, and to immediately start looking for work when work it spawned completes. Previously it would just look at a regular poll frequency.
Formulating in terms of a backoff instead of a poll frequency should make it much less likely to need tweaking for high-throughput databases, but I've translated the configuration knob instead of removing it just in case I'm wrong about this.
=> feat: change background worker to use backoff instead of poll (#1339)

scripts/git-log-prs
1. by default use the repo where the `git-log-pr` script is located in, allowing it to be called
from other scripts in other repos (e.g. k8s-idpe) without too much cerimony
2. allow the git repo to be overriden with the `-C` flag (like the `git` command itself)
3. add a `--commits` flag which prints also commit shas in addition to PR numbers
4. GH merge commits contain the PR title as the body; if present use that instead of using the `gh` cli (which is slow and requires this tool to be installed).
=> feat: Improve git-log-pr

docs/README.md, docs/sql.md, src/commands/sql.rs, src/commands/sql/observer.rs, src/commands/sql/repl.rs, src/commands/sql/repl_command.rs, tests/end_to_end_cases/sql_cli.rs
While trying to understand the state of an IOx server, I want to be able to run queries on system tables across databases (so I can have a consolidated view of the system)
Follow on to https://github.com/influxdata/influxdb_iox/pull/1332, and based on code from https://github.com/influxdata/influxdb_iox/pull/1117
1. Add the observer mode to SQL repl, with tests
2. Add a quickie "Common queries" document to the admin guide with a cheatsheet of common queries
```
OBSERVER> observer;
Preparing local views of remote system tables
Loading system tables from 49 databases
...................................................................................................................................................
Completed in 3.654190485s
You are now in Observer mode.
SQL commands in this …
```
=> feat: Add `OBSERVER` mode to SQL repl along with SQL primer / cookbook

Cargo.lock, metrics/src/tests.rs, query/Cargo.toml, query/src/test.rs, src/influxdb_ioxd/rpc.rs, src/influxdb_ioxd/rpc/storage.rs, src/influxdb_ioxd/rpc/storage/service.rs
Contributes to #1370
This PR instruments the gRPC server with `RED` (requests, errors, duration) style metrics so we can observe the performance of the API.
It segments metrics by:
- operation: e.g., `read_filter`, `read_group`, `tag_values`.
- database: the database the request was for.
- status: the outcome of the request. Ok, client error (e.g., bad arguments), error (internal error).
We capture both requests and their outcome and also distributions of the latency of each request.
=> feat: add instrumentation via RED metrics in gRPC API

data_types/src/chunk.rs, generated_types/protos/influxdata/iox/management/v1/chunk.proto, mutable_buffer/src/chunk.rs, read_buffer/src/chunk.rs, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/system_tables.rs, server/src/query_tests/sql.rs, tests/end_to_end_cases/management_api.rs
I want to compute the storage consumption of data in IOx (bytes per row). While the row count exists in `system.columns` the DataFusion JOIN functionality is not good enough yet for me to calculate storage statistics directly (I can’t join in the table to get row counts).
Here is the join error for the morbidly curious:
```
select *
FROM
chunks JOIN columns using (database_name, partition)
limit 10;
Error running observer query: Error running observer query: Error during planning: Schema contains duplicate unqualified field name 'partition_key'
```
=> feat: add row_count to chunks system table

metrics/src/lib.rs, server/src/db.rs, server/src/query_tests/utils.rs
Contributes to #1370
This PR adds a new histogram metric to track the size of newly created chunks (that is, chunks that have moved to a new _stage_). It purposely only focusses on immutable chunks:
- MUB chunks just as they begin their movement into RB chunks;
- RB chunks;
- Parquet chunks.
These metrics would probably be nicely completemented by gauges that track the current size of all chunks in each stage.
=> feat: add chunk size histogram

server/src/db/system_tables.rs
Fixes bug introduced in https://github.com/influxdata/influxdb_iox/pull/1374 and https://github.com/influxdata/influxdb_iox/pull/1373
I used an API that set column nullability based on the actual contents of the record batch for creating system tables. However some of these RecordBatches don't have nulls in their columns, resulting in schemas that can differ in their nullability.
Ensure that all system tables have the same schema nullability, regardless of the data
A better fix would be to merge the schemas more diligently in observer (so it doesn't error about a mismatch in schema) but for now ensuring the system tables all have the same schema )
I now get the following error trying to created aggregated system table views: 
```
alamb@ip-10-0-0-124:~/Software/influxdb_iox$ …
```
=> fix: set nullability correctly for system tables

object_store/src/disk.rs, parquet_file/src/chunk.rs, parquet_file/src/storage.rs, parquet_file/src/table.rs, server/Cargo.toml, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/chunk.rs, server/src/query_tests/influxrpc/field_columns.rs, server/src/query_tests/influxrpc/read_window_aggregate.rs, server/src/query_tests/scenarios.rs, server/src/query_tests/utils.rs
Closes #1333 
These are tests and related bug fixes for cases when data is in both RUB and OS. This PR will serve both #1333 and a part of #1082.
. Added more scenarios in which data is in both RUB and OS that are automatically included in almost all tests under server/query_tests
. Fixed a bug that always snapshot a RUB chunk if they are both in RUB and OS
. Fixed a few other related bugs that return correct results if we read data in OS. Note that since we always read from RUB in this PR,  we do not expose read data from parquet files which will be done next.
=> feat: tests for cases when data are in both RUB and OS

arrow_deps/src/util.rs, query/src/exec.rs, query/src/provider/adapter.rs, read_buffer/benches/database.rs, src/commands/sql/repl.rs, src/influxdb_ioxd/rpc/flight.rs, src/influxdb_ioxd/rpc/storage/data.rs, tests/end_to_end_cases/scenario.rs
Similar to https://github.com/influxdata/influxdb_iox/pull/1374
This has been bugging me for a long time (the redundancy in creating `RecordBatch`es -- hopefully this PR will make it is people in IOx follow the nicer pattern.
=> refactor: remove additional uses of RecordBatch::try_new

arrow_deps/src/test_util.rs, internal_types/src/arrow/sort.rs, mutable_buffer/src/chunk.rs, query/src/provider/adapter.rs, server/src/db.rs, server/src/db/system_tables.rs, server/src/lib.rs, server/src/query_tests/influxrpc/field_columns.rs, src/influxdb_ioxd/http.rs, tests/end_to_end_cases/flight_api.rs, tests/end_to_end_cases/system_tables.rs
Keep these macro names consistent with DataFusion as well as consistent with `assert_batches_sorted_eq`
I wrote `assert_table_eq` originally for IOx, and then contributed a version to DataFusion called `assert_batches_eq` and `assert_batches_eq` which left a potpourii of names I would like to be consistent.
Ran `find . -name '*.rs' -or -name '*.toml' | grep -v target | xargs sed -i '' -e 's|assert_table_eq|assert_batches_eq|g'` and checked in the result
=> refactor: rename assert_table_eq to assert_batches_eq

Cargo.lock, metrics/Cargo.toml, metrics/src/lib.rs, metrics/src/metrics.rs, metrics/src/tests.rs
This PR implements a Gauge metric + all the testing helpers that will allow us to test the code that uses gauges.
It's correct to think of this gauge implementation as a hack.
It's possible to spend more time and figure out how to do this "the right" way,
but I really think we need gauges right now.
On the upside, I think that the API is going to be stable even once we figure out the "right way" to plumb this into opentelemetry.
=> feat: Add gauge metric

metrics/src/lib.rs, metrics/src/metrics.rs
Contributes to #1391 
This PR adds `add` and `sub` methods on a gauge, allowing gauges to be increased or decreased. I also changed the type of gauges from `u64` to `f64` to support this.
=> feat: allow gauges to be increased or decreased

generated_types/src/google.rs, tests/end_to_end_cases/management_api.rs, tests/end_to_end_cases/sql_cli.rs, tests/end_to_end_cases/system_tables.rs
It is awkward to use the operation client and wait for it to be done. Initially, the challenge is that the `id` passed to `wait_operation` is an integer, but to get it the user needs to parse a String from the response.
It is also annoying to have to instantiate a new client type to wait on an operation created by `management::Client` but perhaps I'll fix that some other time.
Here is an example of having to interpret `name` as an `id`:
```
let mut management_client = fixture.management_client();
let operation = management_client
.close_partition_chunk(&db_name, partition_key, table_name, 0)
.await
.expect("new partition chunk");
let operation_id = operation.name.parse().expect("not an integer");
// wait for the job to be done
fixture.operations_client()
.wait_operation(operation_id, …
```
=> feat: add a id() method to `management::Operations` 

server/src/db/lifecycle.rs
Print a warning if dropping chunks from a partition containing an open chunk - this indicates that the buffer size limit has been set too low as IOx is evicting hot data to stay below it.
=> feat: warn on dropping from open partition

data_types/src/chunk.rs, data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/management/v1/chunk.proto, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/chunk.rs, server/src/db/lifecycle.rs, server/src/db/system_tables.rs, src/commands/database.rs, tests/end_to_end_cases/management_api.rs
IOx does not actually have a closing state that receives writes to its keyspace. Instead it has a state called Closing that behaves like what Closed would be, and is sometimes printed as Closed e.g. in the system tables.
This is needlessly confusing. This PR therefore renames the closing state to closed, and when we add support for "closing" semantics we can add a new state for it
=> refactor: rename closing to closed

server/src/db.rs
Contributes to #1370
This PR adds a new metric `chunk_size_bytes`, which is segmented by:
- `server ID`
- `database`
- `chunk location`.
The metric tracks the current total size in bytes of all chunks in the various stages within IOx. Effectively all chunks in the catalog.
With this metric we can get a headline view of where data currently is for each database in IOx, plus of course how that the distribution of that data in IOx changes over time.
=> feat: metrics for total size of chunks across stages

internal_types/src/entry.rs, server/src/buffer.rs, server/src/db.rs, server/src/lib.rs, server/src/query_tests/utils.rs, server/src/snapshot.rs
Connects to #1157.
This doesn't finish 1157, as the logical clock isn't implemented yet. If you'd rather the logical clock be implemented before merging this, I'm fine with waiting and I'll work on the logical clock next in any case!
The write buffer will still only be used if configured in the database rules.
=> feat: Actually route SequencedEntry to the Write Buffer, if present

server/src/db.rs
We can then run this with `LOG_FILTER=info,server::db=debug` and troubleshoot why the 
`catalog_chunk_size_bytes` is not touched in our staging env.
=> feat: Add debug to update_chunk_state metrics

Cargo.lock, mutable_buffer/Cargo.toml, read_buffer/Cargo.toml, tracker/Cargo.toml
Update to hashbrown 0.11. Arrow has already updated to use this version.
Unfortunately this doesn't eliminate the duplicate dependency as indexmap hasn't [yet updated](https://github.com/bluss/indexmap/pull/181) but we might as well update the crates that we can and get the free performance :smile:
=> chore: update hashbrown

Cargo.lock, Cargo.toml, mem_qe/Cargo.toml, mem_qe/src/bin/main.rs, metrics/Cargo.toml, metrics/src/lib.rs, metrics/src/tests.rs, observability_deps/Cargo.toml, observability_deps/src/lib.rs, src/commands/tracing.rs
An initial pass at reducing the number of dependencies brought in by the observability_deps crate.
=> refactor: initial split of observability_deps

Cargo.lock, tracker/Cargo.toml, tracker/src/lib.rs, tracker/src/lock.rs
The way mutexes work in Rust is there is a lock_api crate that defines the possible traits for given raw lock implementations, it then defines the standard RAII machinery for locks implementing these traits. Crates such as parking_lot can then provide implementations of these raw lock traits.
This PR provides a raw lock implementation that wraps another and adds instrumentation on top.
Note there are LOT of other traits for raw locks, to support upgrades, fairness, timeouts, etc... we will need to wrap these traits also if we want to use them. But the below should be good enough for the catalog.
An alternative would be to instead wrap the RAII types, but this is a lot more code, with a lot of strange lifetime shenanigans so I opted not to. The tradeoff is that the raw lock traits are …
=> feat: instrumentable RwLocks (#1355)

Cargo.lock, influxdb_line_protocol/Cargo.toml
This isn't used as far as I can tell, if anything the dependency should be the other way around...
=> chore: remove unused dependency from influxdb_line_protocol

data_types/src/chunk.rs, datafusion_util/src/lib.rs, generated_types/src/chunk.rs, query/src/exec/field.rs, query/src/exec/seriesset.rs, query/src/frontend/influxrpc.rs, query/src/plan/seriesset.rs, query/src/provider.rs, query/src/provider/physical.rs, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/chunk.rs, server/src/db/system_tables.rs, server/src/query_tests/influxrpc/util.rs, src/influxdb_ioxd/rpc/storage/data.rs, test_helpers/src/lib.rs
Using `Arc<str>` instead of `Arc<String>` eliminates a pointer indirection, and as an added benefit the code to construct from a string literal is more concise.
=> refactor: use Arc<str> instead of Arc<String>

generated_types/protos/influxdata/iox/catalog/v1/catalog.proto, object_store/src/path.rs, object_store/src/path/parsed.rs, object_store/src/path/parts.rs, parquet_file/src/catalog.rs, parquet_file/src/metadata.rs, parquet_file/src/utils.rs
Closes #1380.
**NOTE: I did NOT yet preserve any hashes within the catalog. Will do that as part of #1434 since I need a bit of prep within the `object_store` crate to figure out if cloud-provided MD5es "just work".**
=> feat: preserve parquet metadata + proper path in catalog

data_types/src/chunk.rs, data_types/src/partition_metadata.rs, mutable_buffer/src/chunk.rs, mutable_buffer/src/column.rs, mutable_buffer/src/table.rs, read_buffer/src/chunk.rs, read_buffer/src/row_group.rs, read_buffer/src/table.rs, server/src/db/catalog.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/partition.rs, server/src/db/system_tables.rs, server/src/query_tests/scenarios.rs, server/src/query_tests/sql.rs
Closes https://github.com/influxdata/influxdb_iox/issues/1340
I want to understand:
1. how many bytes are used to store each column in the physical containers (aka MUB Column or RUB column)
2. the actual compression (such as "bytes per row") obtained by the MUB vs RB vs Parquet per column for a particular table so we can contemplate different merging strategies
3. the "shape" of the data in the IOx tools cluster so we can then use the data generator to automatically drive IOx with similarly "shaped" data
Add `system.chunk_columns` system table with one row for each column in each table in each chunk, and exposes low level statistics information 
Here is an example output (from the test);
```
+---------------+----------+------------+--------------+-------------------+-------+-----------+--- …
```
=> feat: Expose the storage usage for each column in system.chunk_columns

Cargo.lock, query/Cargo.toml, query/src/frontend/influxrpc.rs, query/src/func.rs, query/src/func/regex.rs, query/src/func/selectors.rs, query/src/predicate.rs, server/src/query_tests/influxrpc/read_filter.rs, src/influxdb_ioxd/rpc/storage/expr.rs, tests/end_to_end_cases/storage_api.rs
Closes https://github.com/influxdata/conductor/issues/281
This PR adds support for regex matching via the gRPC API. Effectively, this teaches IOx (and Data Fusion really) how to filter results via a predicate expression that is a match (or not a match) to a regular expression.
In Flux we would express this as:
```
from(bucket: "edd")
|> range(....)
|> filter(fn: (r) => r["_measurement"] == "cpu")
...
|> filter(fn: (r) => r["city"] =~ /^new.*/)
```
This PR adds support for both regex matching (`=~`) and also negated matching (`!~`)`. Negated matching effectively means "filter away any rows with values that match the regular expression".
I have tested this PR locally using IOx and Flux. 
This PR may be easier to review commit-by-commit:
- bf8d70b: adds a new user defined function to …
=> feat: Add Regex matching support to IOx's gRPC API

src/commands/sql/observer.rs
I want to look at column statistics from the snapshot rather than each individual database (where the data changes over time)
=> feat: Include `system.chunk_columns` in the tables that are scraped by observer mode

server/src/db/system_tables.rs
Fixes https://github.com/influxdata/influxdb_iox/issues/1436
See explanation on https://github.com/influxdata/influxdb_iox/pull/1446. TLDR is that the contents of the system table are computed many many times when they are not actually being read.
Port `system.chunk_columns`, `system.columns` and `system.operations` so it computes data only when actually needed and only `Arc::clone`s stuff on common operations
=> feat: Calculate all system tables "on demand"

Cargo.lock, Cargo.toml, src/influxdb_ioxd.rs
There is some discussion on https://github.com/influxdata/influxdb_iox/issues/1362#issuecomment-839737377 about if IOx sees the number of CPUs assigned to its kubernetes container or on the host machine. Let's stop guessing and get IOx to just tell us
Log the `num_cpus` as seen by IOx in the "InfluxDB IOx Server Starting" message
```
Running `target/debug/influxdb_iox run -vv`
May 12 09:13:16.547  INFO influxdb_iox::influxdb_ioxd: InfluxDB IOx server starting git_hash="0b1ef524817d0c72b42d84196aebbf0a3edc806e" num_cpus=16
```
cc @tustvold  @crepererum
=> feat: Report num_cpus seen by IOx on startup

read_buffer/src/chunk.rs, read_buffer/src/column.rs, read_buffer/src/column/boolean.rs, read_buffer/src/column/encoding/bool.rs, read_buffer/src/column/encoding/scalar/fixed_null.rs, read_buffer/src/column/encoding/string/dictionary.rs, read_buffer/src/column/encoding/string/rle.rs, read_buffer/src/column/float.rs, read_buffer/src/column/integer.rs, read_buffer/src/column/string.rs, read_buffer/src/row_group.rs, read_buffer/src/table.rs
This PR contributes to the observability of IOx by adding a new metric to the Read Buffer that lets us track an estimated uncompressed size. Specifically, this PR adds a metric `read_buffer_column_raw_bytes` that keeps track of the size of data in the read buffer were it to be held in `Vec<T>` for each column.
The metric can be segmented by "nullness", meaning it tracks sizes for NULL values separately from non-null values. Excluding NULL values is probably closer to line-protocol size, and including it is closer to an uncompressed record batch or basic table structure in memory.
The metric will be useful for getting an idea about overall compression rates in the Read Buffer.
=> feat: add uncompressed read buffer size metric

read_buffer/src/column.rs, read_buffer/src/column/cmp.rs, read_buffer/src/column/encoding/scalar.rs, read_buffer/src/column/encoding/scalar/rle.rs, read_buffer/src/column/float.rs
This PR introduces a new encoding to the Read Buffer: run-length encoding of scalar values.
As the primary in-memory execution engine within IOx the Read Buffer needs to aggresively compress data to maximise the total number of rows that can be held. However, this must be done whilst balancing read performance; compressions schemes that result in significant expense to access values harm query execution performance.
This PR adds a new RLE encoding scheme for compressing columns of scalar values (integers and floats). It allows us to significantly reduce the footprint of columns of these values for time-series data where it is often the case that there are many runs of repeated values.
Further, the encoding scheme compliments the existing design of the Read Buffer, which uses compressed …
=> feat: implement Read Buffer run-length encoding for scalars

server/src/db.rs, server/src/db/process_clock.rs
This connects to #1157. I *think* it might finish it, except the ticket mentions the logical clock having the ability to be "updated to a new value (if passed value is > the current one)", but that ability wouldn't be used anywhere just yet, so I'd rather add it when it's needed. If I should do it now instead, let me know!
I tried having the `process_clock` field be an `AtomicU64`, but I don't think it works because there's not a way to read the value, compare it + 1 to another value, and possibly set the value with a guarantee that the value hasn't been modified between the read + set. Let me know if I'm missing some trick with atomics, this is a lower level than I usually work at 😬
=> feat: Add a process clock to Db and use it for Sequenced Entries

mutable_buffer/src/chunk.rs
When running cargo test with the nocache feature enabled, don't run a test that asserts that caching is taking place.
Identified by @domodwyer and @carols10cents in #1496
=> fix: don't test snapshotting when disabled (#1496)

server/src/lib.rs, src/influxdb_ioxd/http.rs
This was a slight oddity I noticed whilst plumbing in kinesis, half the ingest metrics are in server and half are in the rpc interface. This moves them to be in one location.
I'm aware there is a gRPC endpoint that is now not instrumented, instead of partly instrumented, but I'm not sure how long that endpoint is for this world and I don't think it is in use...
=> refactor: track ingest metrics in one place

object_store/src/lib.rs, parquet_file/src/catalog.rs, parquet_file/src/metadata.rs, parquet_file/src/storage.rs, parquet_file/src/utils.rs, server/src/db.rs, server/src/db/catalog.rs, server/src/db/lifecycle.rs
Required a bit of refactoring:
- Extract some observability tools from db into its own file.
- Move some observability helpers into catalog.
- Add an extra layer between DB an catalog which is the "preserved
catalog" wrapper. This is required to make the ownership model
somewhat sane, because during the read operations the "preserved
catalog" is going to act on the in-mem catalog.
- Move "parquet file written" logic into catalog, so we have a single
place where new parquet files are announced. For now this only works
for chunks that are already known (i.e. the writing->written
transation when coming from read buffer), however in the next PR this
will be extended to also handle totally new parquet files during
transaction playback.
**NOTE: This does NOT include the read path yet! Also …
=> feat: wire up catalog preservation write path

read_buffer/benches/plain.rs, read_buffer/benches/sum_fixed.rs, read_buffer/src/column/encoding/scalar/fixed.rs, read_buffer/src/column/encoding/scalar/fixed_null.rs, read_buffer/src/column/integer.rs
This PR extends previous Byte Trimming support to nullable integer encodings. Prior to this change only integer columns that contained no NULL values were able to be stored in a smaller phsical type.
With this PR, any integer column that contains NULL values will be stored as a smaller physical data-type, currently backed by Arrow arrays. 
Byte trimming works by determining the range of values within an input array and storing it using the smallest physical type that all of the values will fit in. The supported conversion (in order of preference) are:
```
i64 -> u8, i8, u16, i16, u32, i32, i64
u64 -> u8, u16, u32, u64
```
**Please note** -  a lot of the code in here can and will be reduced with macros. I just wanted to get something up that's a bit easier to review, and then shrink it all …
=> feat: extend Byte trimming to all nullable integer encodings

query/src/exec/context.rs, query/src/provider/physical.rs
Have better debug for visibility into what plans are being run, so I can quickly answer questions like "are we sure projection pushdown is happening"
Use `debug!` logging to log both the
1. original plan (produced by the IOx planners)
2. The optimized *physical* plan (what is about to be executed) -- and now has a reasonable format after https://github.com/apache/arrow-datafusion/pull/337
Here is a log  snippet from my local IOx server when running a gRPC query
```
cargo run -- run --server-id=1 --object-store=file --data-dir=$HOME/.influxdb_iox -vv
```
```
cat /Users/alamb/Documents/lp_query_plans/read_request.json | grep -v _COMMENT | ./scripts/grpcurl  -d @ -plaintext localhost:8082 influxdata.platform.storage.Storage.ReadFilter
```
(using this file: …
=> chore: Improve DataFusion plan logging

parquet_file/src/catalog.rs, server/src/config.rs, server/src/db.rs, server/src/db/process_clock.rs, server/src/lib.rs, server/src/query_tests/influxrpc/read_window_aggregate.rs, server/src/query_tests/scenarios.rs, server/src/query_tests/utils.rs, server/src/snapshot.rs
That involves some refactoring which we are going to need anyway for
hooking up the "read" path of the catalog into the DB startup, namely:
- make `Db::new` async and failable
- as a consequence, make the handling in `server::config` async as well
(since the old lock wasn't `Send`)
This prepares for #1382.
**The PR was actually meant to contain more stuff (namely a bit safer handling of the preserved catalog so you don't overwrite existing ones), but that goes into the next PR because this one is really merge-conflict-prone.**
=> refactor: empty transaction during catalog creation

Cargo.lock, Cargo.toml, src/influxdb_ioxd/http.rs
Implements embedded pprof exporter
1. Compatible with: https://golang.org/pkg/net/http/pprof/
```console 
; go tool pprof 'http://localhost:8080/debug/pprof/profile?seconds=5'
Fetching profile over HTTP from http://localhost:8080/debug/pprof/profile?seconds=5
Saved profile in /Users/mkm/pprof/pprof.cpu.006.pb.gz
Type: cpu
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 93, 100% of 93 total
Showing top 10 nodes out of 185
flat  flat%   sum%        cum   cum%
93   100%   100%         93   100%  backtrace::backtrace::libunwind::trace
0     0%   100%          1  1.08%  <&str as nom::traits::InputTakeAtPosition>::split_at_position1_complete
0     0%   100%          1  1.08%  <(FnA,FnB) as …
```
=> feat: Add /debug/pprof/profile

query/src/predicate.rs, query/src/provider/physical.rs
Closes https://github.com/influxdata/influxdb_iox/issues/1516
The ability to see what the predicates actually are will help implement and debug various predicate pushdown and pruning fetures.
1. `impl Display for Predicate`
2. Use this display in plan debug code (rather than `predicate=TODO`). See https://github.com/influxdata/influxdb_iox/pull/1508#discussion_r634118915
prior to this PR, the output showed `predicate=TODO`. Now it shows `predicate=Predicate` which I think is an improvement (it shows that no predicates were pushed down) :) and :(
```
May 19 07:09:17.593 DEBUG query::exec::context: optimized physical plan text=ProjectionExec: expr=[cpu, host, usage_user, time]
RepartitionExec: partitioning=RoundRobinBatch(16)
SortExec: [cpu ASC,host ASC,time ASC]
MergeExec …
```
=> feat: Implement Display for query::predicate to improve debug printing of plans

Cargo.lock, server/Cargo.toml, server/src/lib.rs
Closes https://github.com/influxdata/k8s-idpe/issues/3339
TL;DR I didn't want to do premature optimization (i.e. I was lazy) but istio had different opinions
CC: @primeroz
=> fix: Cache outbound gRPC connections

server/src/config.rs, server/src/lib.rs, src/commands/run.rs, src/influxdb_ioxd.rs, src/influxdb_ioxd/http.rs
__Rationale__
Currently the only way to configure writes to remotes is to call the gRPC API that sets the ephemeral name mapping between ServerId and remote URL.
This is suboptimal because in our load testing environment we don't yet have conductor orchestrating that configuration change and instead we have a sidecar with a shell script simply calling `influxdb_iox server remote set 3000 http://....` every 5 seconds, which works but it sucks because 
1. every time we restart with have a bunch of unnecessary errors.
2. we need this hackish sidecar pushing very regular configuration (we have DNS mapped in such a way that node N is reachable as `iox-query-<N>`)
I believe that delegating name resolution to external systems (such as k8s; with or without stateful sets) is a rather common …
=> feat: Add remote_template for simpler remote configuration

read_buffer/src/column/encoding/scalar.rs, read_buffer/src/column/encoding/scalar/fixed.rs, read_buffer/src/column/encoding/scalar/fixed_null.rs, read_buffer/src/column/encoding/scalar/rle.rs
No behaviour change in this PR, just code shuffle.
This PR is part one of some work I have been doing to try and re-organise the scalar encodings in the Read Buffer, as I have begun focussing on various scalar encoding strategies.
Whilst this PR adds a bunch of code, the benefit will be realised in the subsequent PRs (hopefully) where I will be able to remove a lot of code so that it can be shared.
Effectively the idea is that `ScalarEncoding` is responsible for deciding _how_ to encode a column of data, which currently means either by not compressing it or by run-length encoding it. 
It will then be the job of higher level types to determine what the logical type of the column values are and how they should/shouldn't be down-casted (byte trimmed) when stored as a `ScalarEncoding`.
This …
=> refactor: consolidate Read Buffer scalar encodings

server/src/db.rs, server/src/db/catalog.rs, server/src/db/catalog/chunk.rs, server/src/db/chunk.rs, server/src/db/lifecycle.rs
This splits the states that exist to track in-progress tasks into a separate field on the chunk and adds one for compaction. This is to allow compaction to be tracked independently from the primary catalog states as seems to be the consensus on #1361. It is still necessary for the state to be tracked on the catalog chunk as the lifecycle manager is not the only thing that can trigger these actions, they can also be triggered by an API call.
=> refactor: split lifecycle tracking from chunk state (#1361) (#1099)

read_buffer/src/column/cmp.rs, read_buffer/src/row_group.rs
This PR contributes to #734.
Currently the Read Buffer knows how to build predicates from expressions like:
```
"a" > 22
"b" = "hello"
```
Now it can reorder certain expressions, so it can handle:
```
11 < "a" (rewrites as "a" > 11)
```
Also it can not handle specific timestamp nanosecond precision data fusion scalars, which are really just wrappers around `i64`.
=> fix: support converse binary expressions

parquet_file/src/chunk.rs, parquet_file/src/metadata.rs, parquet_file/src/table.rs, parquet_file/src/utils.rs, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/chunk.rs, server/src/db/lifecycle.rs
re: https://github.com/influxdata/influxdb_iox/issues/1295
closes https://github.com/influxdata/influxdb_iox/issues/1311
Chunks can have only one table, so code that implies something different is confusing
1. Remove more vestigial code from the *before* time when Chunks could contain multiple tables.
2. Fix parquet chunk size reporting (as I was messing with the code anyways)
=> refactor: Remove multiple table support from Parquet Chunk

data_types/src/database_rules.rs, entry/benches/benchmark.rs, entry/src/entry.rs, server/src/lib.rs, src/influxdb_ioxd/http.rs, src/influxdb_ioxd/rpc/write.rs, tests/end_to_end_cases/write_api.rs
I found this problem while thinking about where to hook in Kafka. I'm not sure that I understand how that all will work yet, but I think this problem is relevant in any case.
I think there's a subtle problem with the timestamp assigned to points that don't have one and partitions based on timestamps that has the potential to cause unexpected results.
I was looking at this code from the lens of saving writes before much processing has been done and restoring them later, and the assignment of the default timestamp was happening later than I expected to find it in the course of processing line protocol, and I found [2 calls to `Utc::now`](https://github.com/influxdata/influxdb_iox/blob/76ee9793dd7d4e6f99fd4a402a06d2f1c5bb8de7/entry/src/entry.rs#L71-L94) where I only expected one.
The bug I …
=> fix: Set default line timestamp and default partition time to same value

Cargo.toml
There may be many reasons for the discrepancy in jemalloc reported allocations total sizes and RSS.
One of them is that our binary doesn't use jmalloc for all the allocations.
Turns out that jemallocator only sets the global rust allocator. Any call to `malloc` will still
go throught the system allocator. Presumably those calls come from linked C code,
but it's also not impossible that not all rust code honours the global allocator (I have no idea, but let's see)
=> feat: Use jemalloc everywhere instead of malloc

Cargo.lock, query/Cargo.toml, query/src/exec/task.rs, tracker/src/task.rs
The `executor_shutdown_while_task_running` was previously racy as there was nothing to ensure that tasks on DedicatedExecutor actually completed - the tokio runtime blocks on drop waiting for tasks to yield, not to complete.
Fortunately we already have a task tracking system, so the simple fix is just to wire that in :smile: Longer-term we could do something a bit more sophisticated here, e.g. track tasks individually, but this works for now
=> feat: wait for task shutdown on DedicatedExecutor

generated_types/protos/influxdata/iox/management/v1/service.proto, influxdb_iox_client/src/client/management.rs, src/commands/run.rs, src/influxdb_ioxd.rs, src/influxdb_ioxd/rpc.rs, src/influxdb_ioxd/rpc/flight.rs, src/influxdb_ioxd/rpc/management.rs, src/influxdb_ioxd/rpc/storage.rs, src/influxdb_ioxd/rpc/storage/service.rs, src/influxdb_ioxd/rpc/write.rs, src/influxdb_ioxd/serving_readiness.rs, tests/end_to_end_cases/management_api.rs
__Rationale__
When IOx is orchestrated by a controller such as Conductor, we want to avoid serving traffic before the controller has had a chance to finalize the configuration of the IOx node. 
The controller must be able able to set server id, push configuration for all the databases and other server settings and only once that is done the node can accept incoming traffic.
__This change__
This PR implements a "serving_readiness" flag, that can be set and cleared via a Management API call.
The flag controls a gRPC interceptor which gets installed into all the data plane gRPC services, causing
any calls to them to fail with the gRPC "[UNAVAILABLE](https://grpc.github.io/grpc/core/md_doc_statuscodes.html)" status code.
__Next steps__
1. Connect the serving state to the HealthReporter.
2. …
=> feat: Implement service readiness API

data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, generated_types/src/database_rules.rs, generated_types/src/database_rules/shard.rs, server/src/lib.rs, tests/end_to_end_cases/management_api.rs, tests/end_to_end_cases/write_api.rs
__Rationale__
Currently IOx lacks a distributed query engine. That doesn't prevent us from spreading the load on multiple nodes, provided that queries never join across tables residing on different nodes.
The easiest way to guarantee that is to assign a whole DB to a node. We can do this with current "ShardConfig"s:
```json
{
"shardConfig": {
"shards": {
"42": {
"iox": {
"nodes": [
{
"id": 3002
}
]
}
}
},
"specificTargets": [
{
"matcher": {
"tableNameRegex": ".*"
},
"shard": 42
}
]
}
}
```
But there are two problems with that:
1. It's a very complicated config snippet to basically just say "send all to node 3002"
2. It's not trivial to implement a simple query router that just routes all queries for a db to one node. 
__Proposal__
We don't way to get rid of the Sharding code yet since …
=> feat: Add simpler RoutingConfig

Cargo.lock, datafusion/Cargo.toml
Update to latest DataFusion to get at least:
*  to_timestamp folding https://github.com/apache/arrow-datafusion/pull/387 (👋  @msathis)
* @e-dard 's fix for duplicate predicates: https://github.com/apache/arrow-datafusion/pull/409
1. Update git sha
2. run` cargo update` and check in results
Packages updated:
```
alamb@ip-10-0-0-124 influxdb_iox % cargo update
cargo update
...
Updating ahash v0.7.3 -> v0.7.4
Updating cc v1.0.67 -> v1.0.68
Removing datafusion v4.0.0-SNAPSHOT (https://github.com/apache/arrow-datafusion.git?rev=7359e4b4df0836b8de970d551c6eeae22d1cc810#7359e4b4)
Adding datafusion v4.0.0-SNAPSHOT (https://github.com/apache/arrow-datafusion.git?rev=d9b044787ce465e2597f9ab37f601ae8515921ee#d9b04478)
Updating httpdate v1.0.0 -> v1.0.1
Updating hyper v0.14.7 -> v0.14.8
Updating libc …
```
=> chore: Update datafusion + other deps

Cargo.toml, arrow_util/Cargo.toml, ingest/Cargo.toml, internal_types/Cargo.toml, mem_qe/Cargo.toml, mutable_buffer/Cargo.toml, packers/Cargo.toml, parquet_file/Cargo.toml, query/Cargo.toml, read_buffer/Cargo.toml, server/Cargo.toml
When building a crate that also brings in DataFusion, the `prettyprint` feature flag is enabled, as DataFusion depends on it, but when building crates that don't bring in DataFusion (e.g. mutable_buffer) the test fail to compile as the feature isn't enabled.
As the feature is almost always enabled anyway, it made sense, at least to me, to just enable it everywhere. The alternative would be to give the crates that need it an additional dev-dependency on arrow that enables the feature just for their tests.
=> chore: enable arrow prettyprint

docs/env.example, object_store/src/aws.rs, src/commands/run.rs, src/influxdb_ioxd.rs
That's what accumulated so far in #1461 and is helpful even if we won't use emulators. At least you can now test+run:
- against an emulator
- against AWS using a session token
=> feat: extend AWS configs for prod and test

query/src/exec/task.rs, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/lifecycle.rs, server/src/query_tests/scenarios.rs, tracker/src/task.rs
Currently whilst performing a lifeycle action if an error is encountered, or the task is aborted via the longrunning operations API, the chunk effectively gets orphaned in this state. This came up again when plumbing in error handling for compaction, where the abort logic for multiple chunks ends up pretty painful, and so I thought it pertinent to get proper handling for it in.
This PR proposes storing a `TaskTracker` inside the catalog for the lifecycle action.  A future PR would then extend the lifecycle manager to find chunks with lifecycle actions that have finished, and reset them, as this implies the operation failed as it never cleared the lifecycle action and is no longer running. This could potentially only reset the action a certain number of seconds from when the task was …
=> feat: associate tracker with lifecycle action (#1099)

server/src/db.rs, server/src/db/chunk.rs
Ran into this while preparing to cache schema
Make it clear chunk can have at most 1 path in object store
=> refactor: Chunks can have at most one object store path

server/src/db/catalog/chunk.rs, server/src/db/chunk.rs
This seems to only exist to fight the borrow checker and we can actually
live without it.
=> refactor: remove `ChunkState::Invalid`

Cargo.lock, Cargo.toml, arrow_util/Cargo.toml, data_types/Cargo.toml, generated_types/Cargo.toml, google_types/Cargo.toml, mutable_buffer/Cargo.toml, parquet_file/Cargo.toml, read_buffer/Cargo.toml
Removes some unused dependencies (found with https://github.com/est31/cargo-udeps) in a hail-mary attempt to reduce compile times
(though it looks like `serde_regex` is the only one that is no longer needed in the project as a whole)
=> chore: remove (moar!) unused dependencies

Cargo.lock, query/Cargo.toml, query/src/frontend/sql.rs
While waiting for `server` to compile, I am trying to reduce compile times...
The `sqlparser` dependency is no longer used directly in IOx (it is used indirectly via datafusion). Furthermore IOx used a different version than pinned in `datafusion` so this reduces (by one) the number of things to compile
=> chore: remove unused sqlparser dependency

query/src/frontend/influxrpc.rs, query/src/lib.rs, query/src/provider/physical.rs, query/src/test.rs, server/src/db.rs, server/src/db/catalog.rs, server/src/db/catalog/chunk.rs, server/src/db/chunk.rs, server/src/query_tests/table_schema.rs, src/influxdb_ioxd/rpc/storage/service.rs
Re https://github.com/influxdata/influxdb_iox/issues/1295
Once upon a time, when the world was green and fresh, chunks could have multiple tables. Now that a chunk has a single table, the API for PartitionChunk is akward
1. Remove `table_name` from several PartitionChunk methods and clean up uses.
Note: the `has_table`, `all_table_names` and `table_names` methods are also overly complicated (they can probably be replaced with a `table_name()` and a `could_pass_predicate` type methods, which I plan to do as a follow on PR
=> refactor: Remove `table_name` from PartitionChunk API

Cargo.lock, server/Cargo.toml
Removes unused dependency. 
Sadly, this still gets included as part of `influxdb_iox_client` so this change doesn't really affect compile time
=> chore: remove unused dependency in server

server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/partition.rs, server/src/db/chunk.rs, server/src/db/lifecycle.rs
This is the first step towards #1513. However it leaves all consumers
bascially unchanged and also does NOT touch state transitions. These
changes will follow in upcoming PRs.
=> refactor: change state structure for chunks

mutable_buffer/src/chunk/snapshot.rs, parquet_file/src/chunk.rs, parquet_file/src/table.rs, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/chunk.rs, server/src/db/lifecycle.rs
In order to prune chunks in https://github.com/influxdata/influxdb_iox/pull/1567 I need access to the `TableSummary` (statistics) and `Schema` for `DbChunk`. I don't want to re-compute these structures once per chunk considered for query and 
My longer term plan / vision is to answer all "metadata" queries (that don't have predicates) in DbChunk using the metadata in `ChunkMetadata`.
1. Cache `ChunkMetadata` on each `catalog::Chunk` and copy it to `DbChunk`
2. Use   `ChunkMetadata` in DBChunk for schema queries
=> feat: Cache TableSummary, Schema in chunks

read_buffer/src/column.rs, read_buffer/src/column/boolean.rs, read_buffer/src/column/float.rs, read_buffer/src/column/integer.rs, read_buffer/src/column/string.rs
I already had this on a branch from when I tried out the idea in the PR review.
---
* refactor: avoid copying encoding name for stats (aca00a50)
Swaps the encoding name String type for a Cow in the column Statistics, 
avoiding having to copy the encoding name where it is a static string already.
=> refactor: avoid copying encoding name for stats

Cargo.lock, parquet_file/Cargo.toml, parquet_file/src/storage.rs, query/src/exec/context.rs, server/src/query_tests/influxrpc/read_group.rs
Closes https://github.com/influxdata/influxdb_iox/issues/1487
To read a parquet file , IOx currently uses a modified version of the DataFusion `ParquetExec`. The code then:
1. Reads the parquet data from object store entirely into memory (`Vec<u8>` style)
2. Does so in a way that blocks an executor thread
3. Decodes the parquet data into a buffer of `RecordBatch`es and returns them as a "stream"
This is non ideal for the code duplication, inefficiency, and the  direct use of the low level pruning API which I recently changed in https://github.com/apache/arrow-datafusion/pull/426
1. I have to change this code anyways in order to upgrade datafusion (https://github.com/influxdata/influxdb_iox/pull/1578)
2. The current code both uses blocking IO as well as buffers the data twice (the encoded …
=> refactor: Use ParquetExec from DataFusion to read parquet files

Cargo.lock, datafusion/Cargo.toml
Get sort preserving merge operator from @tustvold  https://github.com/apache/arrow-datafusion/pull/379 and partition pruning code from https://github.com/apache/arrow-datafusion/pull/426
Updates to datafusion: https://github.com/apache/arrow-datafusion/commit/c794f2df539a10524566cb02b6158ee46cb1459a
=> chore: update datafusion

mutable_buffer/src/chunk.rs, mutable_buffer/src/chunk/snapshot.rs, parquet_file/src/chunk.rs, parquet_file/src/table.rs, query/src/frontend/influxrpc.rs, query/src/lib.rs, query/src/plan/stringset.rs, query/src/predicate.rs, query/src/test.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/partition.rs, server/src/db/chunk.rs, server/src/query_tests/table_schema.rs, src/influxdb_ioxd/rpc/storage/service.rs
Re https://github.com/influxdata/influxdb_iox/issues/1295 and a follow on to https://github.com/influxdata/influxdb_iox/pull/1584
Once upon a time, when the world was green and fresh, chunks could have multiple tables. Now that a chunk has a single table, the API for PartitionChunk is awkward.
I also realize while doing this taht `PartitionChunk::apply_predicate` may also be the perfect place to apply chunk pruning logic (e.g. https://github.com/influxdata/influxdb_iox/pull/1567)
1. Consolidate `has_table`, `all_table_names` and `table_names` methods into a single `table_name()` and a `apply_predicate` method
2. Add a `PredicateMatch` enum to clearly explain what the return value of `apply_predicate` means
2. No functional changes intended
=> refactor: Remove last vestiges of multi-table chunks from PartitionChunk API

Cargo.lock, datafusion/Cargo.toml
Get @NGA-TRAN 's fix for https://github.com/apache/arrow-datafusion/pull/434 into IOx
Update DataFusion Pin
=> chore: update deps for datafusion

server/src/db.rs, server/src/db/catalog.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/partition.rs, server/src/db/chunk.rs, server/src/db/lifecycle.rs
Some things that came up in #1585. Another idea came from @alamb who proposed to inline the extra structs into the enum.
Note that there is still a bit of work to do (like addressing [this comment](https://github.com/influxdata/influxdb_iox/pull/1585/files#r642476096)) however I think this change is sufficiently large for now.
=> refactor: clean-up chunk structure + add tests

Cargo.lock, generated_types/protos/influxdata/iox/catalog/v1/catalog.proto, parquet_file/Cargo.toml, parquet_file/src/catalog.rs
During #1572 we concluded that having some kind of declarative way to wipe catalogs would be helpful. I think that "a catalog last touched/written before X" would be a helpful way to implement that. So this PR implements the underlying tracking to achieve that:
1. store transaction timestamps
2. a way to get the last known transaction timestamp from a potentially broken catalog
CC @mkmik
=> feat: preserve and read timestamps to/from preserved catalog

read_buffer/src/column/encoding/scalar/rle.rs, read_buffer/src/column/float.rs, read_buffer/src/column/integer.rs
Often time-series data can include metrics that do not change very often, perhaps because they track some active value (e.g., in a gauge) rather than some accumulating value (in a counter). For these data there can be signifcant compression benefits to run-length encoding them.
This PR uses the already generic `RLE` for scalar types implementation in the Read Buffer, so all I had to do was teach `IntegerEncoding` when to use an `RLE` encoder or not. As with the implementation for floats I kept the heuristic simple: if we can get a 10% or greater reduction in memory usage when using RLE for an integer column then we choose that.
Note, the Read Buffer will both do byte trimming where possible on integer columns, and then apply RLE to the already compressed representation (if it's valuable …
=> feat: add RLE support for integer columns

query/src/lib.rs, query/src/pruning.rs
Related to chunk pruning https://github.com/influxdata/influxdb_iox/issues/736
The overall PR https://github.com/influxdata/influxdb_iox/pull/1567 that also hooks this code up is getting rediculously large, but the interface is looking good so I wanted to get this reviewed / merged separately
1. Add a `pruning` module in query that runs on `TableSummary`
2. Adds a bunch of tests for the same
=> feat: Add pruning module to query crate

Cargo.lock, data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, generated_types/src/database_rules.rs, parquet_file/src/cleanup.rs, server/Cargo.toml, server/src/db.rs, server/src/lib.rs, server/src/query_tests/utils.rs, tests/end_to_end_cases/management_api.rs
It turned out that eagerly starting the clean-up job on DB startup might be a bit too aggressive, especially since a single IOx node can restore many DBs on start-up.
=> feat: jitter background clean-up job + wait on first job

object_store/src/disk.rs, object_store/src/lib.rs
Disk-driven object stores were reporting `UnableToProcessEntry` when
calling `list_with_delimiter` and a non-existing prefix.
To prevent regressions add a test to the test suite shared by all
store implementations.
=> fix: do not error on `list_with_delimiter` w/ non-existing prefix

server/src/db.rs, server/src/db/catalog.rs, server/src/db/catalog/partition.rs
re https://github.com/influxdata/influxdb_iox/issues/735
As part of and https://github.com/influxdata/influxdb_iox/pull/1567 I am making predicate based pruning happen in a new layer like the following
```
┌────────────────────────────┐
│             Db             │
└────────────────────────────┘
▲
│
│
┌────────────────────────────┐
│       CatalogAccess        │     Predicate based
│           (new)            │   pruning happens at
└────────────────────────────┘       this layer
▲
│
│
┌────────────────────────────┐      Only table name
│          Catalog           │   filtering happens at
└────────────────────────────┘        this level
```
Right now, the `Predicate` structure is pushed all the way down
into the Catalog, but only `partition_key` and `table_name` filtering is applied. …
=> refactor: Make it clear only partition_key and table name pruning happens in catalog

logfmt/src/lib.rs, logfmt/tests/logging.rs
Closes #1252
I defer to #1252 for the wider context; the "why" this escaping rule is the likely the right one (the "official" logfmt is particularly light on the spec side)
This PR, implements the following interpretation of the escaping rules:
1. To put a double quote in a double quoted string, you need to escape the double quote with a backslash: `"` -> `"\""`.
2. To put a backslash in a double quoted string, you need to escape the backslash with another backslash: `\` -> `"\\"`.
3. To put a character sequence `\"` inside a double quoted string, you need to combine the previous two rules: `\"` -> `"\\\""`
These rules are quite reasonable and follow the escape rules of most languages.
The test strings are correctly parsed by https://github.com/brandur/hutils
=> fix: Fix logfmt escaping

parquet_file/src/cleanup.rs, server/src/db.rs
Since the number of parquet files can potentially be unbound (aka very
very large) and we do not want to hold the transaction lock for too
long and also want to limit memory consumption of the cleanup routine,
let's limit the number of files that we collect for cleanup.
=> feat: limit number of files during storage cleanup

scripts/logfmts
```console
$ kubectl logs deploy/iox-router-1000 -c iox -f | TZ=UTC ./scripts/logfmts
2021-06-04 10:25:46 level=debug msg="Successfully processed request" response="Response { status: 204, version: HTTP/1.1, headers: {\"x-powered-by\": \"Routerify v2.0.0-beta-2\"}, body: Body(Empty) }" target="influxdb_iox::influxdb_ioxd::http" location="src/influxdb_ioxd/http.rs:359"
```
=> feat: Add logfmts script to humanize timestamps

data_types/src/partition_metadata.rs, query/src/frontend/influxrpc.rs, query/src/lib.rs, query/src/predicate.rs, query/src/provider.rs, query/src/provider/physical.rs, query/src/test.rs, server/src/db.rs, server/src/db/access.rs, server/src/db/catalog.rs, server/src/db/chunk.rs, server/src/db/lifecycle.rs, server/src/query_tests.rs, server/src/query_tests/pruning.rs
Closes #735, Closes #736
Query performance is critical to IOx's use case and quickly skipping chunks and partitions that can not have data that passes predicates is a key part of this.
This PR implements "Pruning" of chunks from query plans. It does so by introducing a `CatalogAccess` layer in the `server` module that handles the interface plumbing between the query layer and the Db / Catalog and teaches this layer how to prune chunks based on Predicates. 
```
┌────────────────────────────┐
│             Db             │
└────────────────────────────┘
▲
│
│
┌────────────────────────────┐
│       CatalogAccess        │     Predicate based
│           (new)            │   pruning happens at
└────────────────────────────┘       this layer
▲
│
│
┌────────────────────────────┐      Only table …
```
=> feat: Implement Chunk Pruning

src/influxdb_ioxd/http.rs
This reverts commit 293433a73ea5e637980ecd3b22a283326b5f18d4.
We have some of that now as debug logs and we'll soon have other info in trace logs.
The error message in itself is the wrong place to put this info; it has been added here
just as a hack and hacks must be cleaned up.
=> fix: Revert Add more details to WritePoints error log

src/commands/tracing.rs
CC: @jacobmarble 
Closes #1615
w.r.t testing: lazy cause ETOOMANYYAKS: this is not easy to test as it involves non determinism to reproduce the issue.
I tested it manually by comparing,,
before:
```console
$ LOG_FORMAT=logfmt LOG_FILTER=debug ./target/debug/influxdb_iox run \
| awk -F 'level=' '{print (NF?NF-1:0)}' \
| sort | uniq -c
11543 0
12193 1
1116 2
150 3
25 4
8 5
3 6
1 7
```
after:
```console
$ LOG_FORMAT=logfmt LOG_FILTER=debug ./target/debug/influxdb_iox run \
| awk -F 'level=' '{print (NF?NF-1:0)}' \
| sort | uniq -c
14029 1
```
Closes #
=> fix: Fix garbled log lines

src/commands/tracing.rs
Rationale: https://github.com/influxdata/influxdb_iox/pull/1637/files is the result of hard won knowledge from @mkmik 's experience and could be casually removed by accident as there is no test coverage (which is reasonable given how hard this would be to test)
Changes: Add a comment explaining the rationale
=> docs: add a comment w/ rationale for LineWriter

.circleci/config.yml
the `perf_build` job on circle ci fails very often, e.g. https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/6586/workflows/2ad23ddb-0344-4cbd-a4bc-76eca4eced88/jobs/26677
we use the `xlarge` resource type for all other build jobs on circle ci; we probably forgot to use it for the `perf_image` too
=> fix: give xlarge image to perf_image build step

internal_types/src/schema.rs, internal_types/src/schema/builder.rs, mutable_buffer/src/table.rs, parquet_file/src/test_utils.rs, read_buffer/src/schema.rs
As part of #1357 I want to add a new piece of per-column metadata. Additionally I would like this metadata to transparently continue to work through projections, column re-orderings, etc... The simplest option would be to store the sort information for each column in the schema metadata with the column name plus some prefix as the key. This feels a bit rubbish though, so moving to use field metadata for all field-specific information seems like a better solution.
NB: THIS WILL BREAK ALL CURRENTLY PERSISTED PARQUET. This is possibly a further reason to get this change in now before we need to maintain backwards-compatibility for persisted data
This PR also makes SchemaBuilder non-consuming so it is a bit easier to work with
=> refactor: use field metadata to store influx types

query/src/frontend/influxrpc.rs, query_tests/src/influxrpc/read_filter.rs
Closes #1655 closes https://github.com/influxdata/influxdb_iox/issues/554
This PR implements the required functionality to enable `!=` operations on tags for the InfluxRPC frontend.
=> feat: enable not equal operator for the influxrpc frontend

data_types/src/partition_metadata.rs, internal_types/src/schema/builder.rs, query/src/duplicate.rs, query/src/lib.rs
Re https://github.com/influxdata/influxdb_iox/issues/1645 
As part of #600 we need to combine chunks which *may* contain "duplicate" primary keys in the InfluxDB Data Model. Duplicate primary key in this case means where data with the same combination of `tag` and `timestamp` columns   have been written in via multiple line protocol writes.
You can read more background in the [design document](https://docs.google.com/document/d/1iD_Q2kpC2Kopo4DEq_Oym4jEvaz-SfUUVmr_dpMcikc/edit#)
1. Introduce a new module, `duplicates.rs` 
2. Implement a `group_potential_duplicates` function in terms of min/max statistics (can feed in `PartitionChunks` directly)
3. Add code in `Statistics` and `StatValues` to compute min/max overlaps
1. As written, the chunk grouping code relies on the InfluxDB data model …
=> feat: Group chunks by potential overlap

query/src/lib.rs, query/src/provider.rs, query/src/pruning.rs, query/src/test.rs, server/src/db/chunk.rs
Closes https://github.com/influxdata/influxdb_iox/issues/1645
As part of #600 we need to combine chunks which may contain "duplicate" primary keys. You can read more background in the [design document](https://docs.google.com/document/d/1iD_Q2kpC2Kopo4DEq_Oym4jEvaz-SfUUVmr_dpMcikc/edit#)
Kudos to @NGA-TRAN for making it so clear what was needed.c
1. Add a `may_contain_pk_duplicates` function in PartitionChunk to signify if the chunk has potential duplicates *within* itself
2. Implement `split_overlapped_chunks` in terms of group_duplicates and may_contain_duplicates
3. tests for same
=> feat: Hook up chunk grouping into provider

query/src/duplicate.rs
Resolves https://github.com/influxdata/influxdb_iox/issues/1661 by fixing the overlap calculation introduced in https://github.com/influxdata/influxdb_iox/pull/1654#discussion_r647548153
I found this super tricky (natch, as it relates to NULLs). I tried to explain what is going on in comments (so it lives with the code rather than in the PR description)
Changes:
1. Fix algorithm + tests
2. Add documentation that tries to explain this
=> fix: Fix bug in chunk overlap calculation due to nulls

object_store/src/buffer.rs, object_store/src/lib.rs, parquet_file/src/catalog.rs, parquet_file/src/cleanup.rs, parquet_file/src/lib.rs, parquet_file/src/rebuild.rs, server/src/db.rs
See https://rust-lang.github.io/rust-clippy/stable/index.html#future_not_send . It's super annoying when you write a lib function and later during integration figure out that it doesn't work in all cases because of tokios `Send` requirement. This only addresses two crates for now, will clippify more later.
=> chore: enforce `clippy::future_not_send` for `parquet_file,object_store`

influxdb2_client/src/api/write.rs, influxdb2_client/src/lib.rs, influxdb_iox_client/src/client/flight.rs, influxdb_iox_client/src/client/health.rs, influxdb_iox_client/src/client/management.rs, influxdb_iox_client/src/client/write.rs, influxdb_iox_client/src/connection.rs, influxdb_iox_client/src/lib.rs, query/src/lib.rs, tracker/src/lib.rs, tracker/src/task.rs, tracker/src/task/history.rs, tracker/src/task/registry.rs
Same as #1671 for a few more crates. Notable future work are `server` and the top-level `src` which I'll do after this PR.
=> chore: enforce `clippy::future_not_send` for `influxdb_iox_client,influxdb2_client,query,tracker`

Cargo.lock, datafusion/Cargo.toml
Keep dependencies up to date
1. Update datafusion to latest master
2. Run `cargo update` to pick up the following changes:
```
Updating hyper v0.14.8 -> v0.14.9
Updating itertools v0.10.0 -> v0.10.1
Updating libc v0.2.95 -> v0.2.96
Updating security-framework v2.2.0 -> v2.3.1
Updating security-framework-sys v2.2.0 -> v2.3.0
```
=> chore: update dependencies

Cargo.lock, data_types/src/partition_metadata.rs, influxdb_iox_client/src/client/management.rs, query_tests/src/influxrpc/read_window_aggregate.rs, query_tests/src/pruning.rs, query_tests/src/scenarios.rs, server/Cargo.toml, server/src/db.rs, server/src/db/access.rs, server/src/db/catalog.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/metrics.rs, server/src/db/catalog/partition.rs, server/src/db/catalog/table.rs, server/src/db/lifecycle.rs, server/src/db/system_tables.rs, server/src/lib.rs, src/commands/database/partition.rs, src/influxdb_ioxd/rpc/error.rs, src/influxdb_ioxd/rpc/management.rs, tests/end_to_end_cases/management_api.rs, tests/end_to_end_cases/preservation.rs, tests/end_to_end_cases/sql_cli.rs, tests/end_to_end_cases/system_tables.rs, tracker/src/lock.rs
This PR swaps the order of partitions and tables within the in-memory catalog. This will be the first in a number of PRs to simplify the in-memory catalog and bring it closer to @pauldix 's vision (which i share) of a less concurrent but simpler catalog and accompanying lifecycle.
This PR looks a lot longer than it is, because it swaps the order of partition key and table name in a number of methods
=> refactor: swap order of partition and table in in-memory catalog

query/src/pruning.rs
As noted by @e-dard, the message produced for pruning looks like :
```
level=debug msg="Pruned chunks" num_chunks=17 num_pruned_chunks=14 target="query::pruning" location="query/src/pruning.rs:80" time=1623347902889392098
```
A reasonable person might conclude that `num_chunks=17 num_pruned_chunks=14` means 14 chunks were pruned, and 3 remain after pruning. It actually means 14 chunks remain *after* pruning.
Make the message explicit for the three numbers: `num_chunks`, `num_pruned_chunks`, and `num_remaining_chunks`
=> fix: make pruning debug log less confusing

server/src/db/lifecycle.rs, tests/end_to_end_cases/mod.rs, tests/end_to_end_cases/persistence.rs, tests/end_to_end_cases/scenario.rs
Closes https://github.com/influxdata/influxdb_iox/issues/1686
Fixes order of arguments so that `partition_key` and `table_name` are correct.
I think this was just a small part that was forgotten in https://github.com/influxdata/influxdb_iox/pull/1678
=> fix: persistence to parquet by swapping order of arguments

src/commands/run.rs, src/commands/tracing.rs
`--traces-exporter-jaeger-max-packet-size` is important also when you run the jaeger collector
on "localhost" by running `docker run jaegertracing/all-in-one ....` which on mac doesn't really
work on the real localhost but has a few hops between tunneling interfaces, so you'd get mysteriously
dropped packets that can easily drive you to doubt your own sanity on an otherwise calm Thursday evening.
=> fix: Expose jaeger knobs and default max-packet-size to something that works everywhere

read_buffer/benches/database.rs, read_buffer/benches/read_filter.rs, read_buffer/src/lib.rs, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/chunk.rs, server/src/db/lifecycle.rs
Helps with #1699
It makes sense for a chunk in the Read Buffer crate to be `Chunk` (as it does in parquet of MUB) but outside of the crates, where they intermingle, it's helpful if the exported symbol is something distinguishable. This PR exports a Read Buffer chunk as `RBChunk`.
=> refactor: export Read Buffer Chunk as RBChunk

Cargo.lock, data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, generated_types/src/database_rules/lifecycle.rs, parquet_file/src/catalog.rs, parquet_file/src/chunk.rs, parquet_file/src/test_utils.rs, server/Cargo.toml, server/src/db.rs, server/src/db/lifecycle.rs, server/src/lib.rs, server/src/utils.rs, server_benchmarks/benches/catalog_persistence.rs, src/commands/database.rs, tests/end_to_end_cases/management_api.rs
Closes #1381.
To quote the last commit message that illustrates the effect using a benchmark:
> test: enable checkpointing in catalog benchmark
> 
> This now creates a checkpoint every 10 transactions. To make it a bit
> more fair increase the chunk count to 109, so we have some transactions
> after the last checkpoint. With that we improve performance from 10.5s
> to 1.2s (or even 0.3s if we would keep the chunk count at 100).
=> feat: wire up catalog checkpointing 

mutable_buffer/src/chunk.rs, mutable_buffer/src/chunk/snapshot.rs, server/src/db.rs, server/src/db/catalog.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/partition.rs, server/src/db/lifecycle.rs, server_benchmarks/benches/snapshot.rs, server_benchmarks/benches/write.rs
re https://github.com/influxdata/influxdb_iox/issues/1699
1. We have too many things named Chunk which is confusing for people new to the code base as well as when doing code reviews.
While this change results in more typing, we feel making the code easier to read rather than write is a better metric to optimize. 
Code is read many more times than written).
=> refactor: rename mutable_buffer::Chunk --> mutable_buffer::MBChunk

server/src/db.rs
- rename `name` to `db_name`
- add `table_name` to error-detection logs
- use `Display` instead of `Debug` fmt for errors, which results in
nicer outputs and follows the rest of the stack
This is for #1725.
=> refactor: improve server background task logging

parquet_file/src/catalog.rs, parquet_file/src/metadata.rs
This should have been done in #1714. Also add a note so that future devs
might hopefully not forget. In any case though the code also works w/o
this bump, it's just that the error message is a bit less nice ("cannot
parse IOxMetadata" instead of "unsupported catalog version").
=> fix: bump catalog version

server/src/init.rs
Add a info log when the server ID is set. Because this is done where the
server ID is also stored, this automatically affects all ways to set it
(via CLI, via environment variable, via gRPC call).
Closes #1595.
=> feat: info-log server ID during init

parquet_file/src/chunk.rs, parquet_file/src/test_utils.rs, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/partition.rs, server/src/db/chunk.rs, server/src/db/lifecycle.rs
re https://github.com/influxdata/influxdb_iox/issues/1699, follow on PR to https://github.com/influxdata/influxdb_iox/pull/1702 (rename MB chunk)
1. We have too many things named Chunk which is confusing for people new to the code base as well as when doing code reviews.
While more typing (if your editor doesn't autocomplete for you) making the code easier to read (rather than write) is a better metric to optimize (as the code is read many more times than written).
@pauldix  notes calling it `XChunk` may be still be misleading as it might not be correct to call this a "Chunk" at all...
=> refactor: Rename parquet_file::Chunk --> ParquetChunk

server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/lifecycle.rs, tracker/src/task.rs, tracker/src/task/registry.rs
Currently the lifecycle logic, both policy and otherwise, is contained within server. This is unfortunate for a couple of reasons:
* The server crate takes a long time to compile
* There isn't a clear API boundary between the lifecycle policy, lifecycle actions, catalog and the Db 
* `db.rs` is turning into a bit of a monster
All of these complicate making changes to the lifecycle logic, without ending up with a change-the-world PR.
This PR takes the first step to trait-ify the lifecycle policy to not directly depend on any of the catalog, RUB, MUB, parquet, Db, etc... Later PRs can then start to pull parts of it out into a separate crate.
=> refactor: traitify lifecycle policy

src/commands/run.rs, src/commands/tracing.rs, trogging/src/cli.rs
Client CLI utils only need LoggingConfig. Servers need also the TracingConfig
Closes #influxdata/conductor#346
=> chore: Split LoggingConfig out of TracingConfig

Cargo.lock, mutable_buffer/Cargo.toml, mutable_buffer/src/lib.rs, mutable_buffer/src/persistence_windows.rs
This adds a new module, persistence_windows, to the mutable buffer crate. Later PRs will add this into the mutable buffer chunk where it can be used to track when the lifecycle for persistence should be triggered.
=> feat: Add persistence windows ingestion tracking

parquet_file/src/catalog.rs, parquet_file/src/cleanup.rs, parquet_file/src/rebuild.rs, server/src/db.rs, server/src/db/catalog/chunk.rs
This allows us to handle transaction aborts (e.g. when the write IO for the transaction file fails) correctly. Before this change aborts would lead to an inconsistent in-memory VS persisted state (in-memory says it's persisted while in fact the transaction wasn't written).
The reason this problem existed was some design mistake and laziness. When I designed the persisted catalog I somewhat assumed that we could just copy the whole managed in-memory state at transaction start, modify it during the transaction and commit it in the end. However this doesn't work for the real DB, so during the integration I made the "copy" step optional. Turns out that breaks the abort semantic :sweat_smile: 
So the fix comes basically in 3 steps:
1. Add a generic test for `CatalogState` implementations that …
=> feat: make DB catalog work w/ transaction aborts

query/src/exec/schema_pivot.rs
The physical plan with one of our extensions printed out by DataFusion looks like this:
```
ExecutionPlan(PlaceHolder)
ProjectionExec: expr=[borough, city, state]
RepartitionExec: partitioning=RoundRobinBatch(16)
IOxReadFilterNode: table_name=o2, chunks=2 predicate=Predicate
```
`ExecutionPlan(PlaceHolder)` is where the `SchemaPivotExec` is but we haven't provided a nice display for it
1. Add custom formatting for `SchemaPivotExec` so that it looks more like:
```
SchemaPivotExec
ProjectionExec: expr=[borough, city, state]
RepartitionExec: partitioning=RoundRobinBatch(16)
IOxReadFilterNode: table_name=o2, chunks=2 predicate=Predicate
```
=> chore: Add proper format for SchemaPivotNode

data_types/src/chunk_metadata.rs, parquet_file/src/catalog.rs, parquet_file/src/cleanup.rs, parquet_file/src/metadata.rs, parquet_file/src/storage_testing.rs, parquet_file/src/test_utils.rs, server/src/db.rs, server/src/db/catalog.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/partition.rs, server/src/db/catalog/table.rs
I started this PR to push the database name into the catalog, but I ended up splitting out the information that identifies the location of a chunk into a separate struct called `ChunkPath` (flexible on naming).
This was for a number of reasons:
* Propagating all 4 items at every function call, log statement, error construction, etc... is cumbersome
* Different callsites would print different subsets of the information, sometimes in different orders
* Eliminates a load of unnecessary string conversions
This is currently only plumbed in a couple of places, but other obvious candidates would be the Task metadata and the other chunk metadata structures. Most of the churn is in the persisted catalog tests
=> refactor: add ChunkAddr to describe location of chunk in catalog

query_tests/src/influxrpc/tag_keys.rs
Ignoring a bunch of flaky (and potentially flaky) tests until #1735 gets resolved.
I noticed in #1735 that it's not always the same test that fails. I disabled a bunch of tests that looked like doing similar things; that may be excessive but I assume that #1735 will be resolved relatively soon.
=> chore: Ignore flaky test

Cargo.lock, Cargo.toml, internal_types/Cargo.toml, object_store/Cargo.toml, read_buffer/Cargo.toml, server/Cargo.toml
My goal of reducing dependency bloat starts with keeping up to date on dependencies
Update dependencies via
```
cargo update
```
As well as manually. I found dependencies by running
```
cargo outdated -wR
```
I will make some more PRs over time as I have some slack time
=> chore: Update itertools + deps

query/src/frontend/influxrpc.rs, query/src/lib.rs, query/src/provider.rs, query/src/provider/physical.rs, query/src/test.rs, query_tests/src/pruning.rs, query_tests/src/scenarios.rs, query_tests/src/table_schema.rs, server/src/db.rs, server/src/db/access.rs, server/src/db/chunk.rs, server/src/lib.rs, server/src/utils.rs, src/influxdb_ioxd/http.rs, src/influxdb_ioxd/planner.rs, src/influxdb_ioxd/rpc/management.rs
Closes https://github.com/influxdata/influxdb_iox/issues/1699, follow on PR to https://github.com/influxdata/influxdb_iox/pull/1702 (rename MB chunk) and https://github.com/influxdata/influxdb_iox/pull/1722 (rename parquet chunk)
We had too many things named `Chunk` which is confusing for people new to the code base as well as when doing code reviews.
Each subsystem has its own view/ trait of what a Chunk is (query, catalog, etc) so making sure those names are clear is valuable.
While more typing (if your editor doesn't autocomplete for you) making the code easier to read (rather than write) is a better metric to optimize (as the code is read many more times than written).
1. Rename `query::PartitionChunk` --> `query::QueryChunk`
1. Rename `query::Database` --> `query::QueryDatabase`
=> refactor: Rename query::PartitionChunk --> query::QueryChunk

query/src/duplicate.rs, query/src/lib.rs, query/src/pruning.rs, query/src/test.rs, server/src/db/access.rs, server/src/db/chunk.rs
This is a step of https://github.com/influxdata/influxdb_iox/issues/1683, I need to merge Schemas / subsets of schemas (and partition keys). Right now there are two different ways to get a Schema from a PartitionChunk:
1. table_schema(selection) --> Schema
2. schema() (via `Prunable`) --> ArrowSchema
This is confusing, and it means code that uses `schema()` doesn't have access to the IOx specific functionality (like merging)
Changes:
1. Rename `Prunable` to `QueryChunkMeta` and move it to the main query crate to make it easier to find
2. Update QueryChunkMeta::schema() to return a `Arc<Schema>`
3. Update pruning logic to work on `Schema` rather than `ArrowSchemaRef`
2. Remove `PartitionChunk::table_schema` (as it is redundant with ChunkMeta)
Then I will move on to getting the InfluxDB …
=> refactor: Unify schema handling in query crate

internal_types/src/schema.rs, mutable_buffer/src/chunk/snapshot.rs, parquet_file/src/chunk.rs, query/src/frontend/influxrpc.rs, query/src/lib.rs, query/src/provider.rs, query/src/provider/physical.rs, query/src/test.rs, query_tests/src/table_schema.rs, server/src/db/access.rs, server/src/db/chunk.rs
Follow on from  https://github.com/influxdata/influxdb_iox/pull/1755
This is another step towards  https://github.com/influxdata/influxdb_iox/issues/1683 where I need to merge Schemas / subsets of schemas (and partition keys). As there are two redundant ways to get schema from chunks now (and I want one so it is always consistent)
1. Remove PartitionChunk::table_schema
2. Implement Schema::selection() in terms of `Selection`
This also removes a bunch of mess where getting a chunk's schema is infallible (but getting a selection is not)
See full checklist / plan here: https://github.com/influxdata/influxdb_iox/issues/1683#issuecomment-863367715
=> refactor: Remove PartitionChunk::table_schema

Cargo.lock, server/Cargo.toml, server/src/lib.rs, src/influxdb_ioxd.rs, src/influxdb_ioxd/http.rs
Another attempt at trimming our deps, like #1747 but this crate supports TTLs too (not used here).
This crate also doesn't suffer from the thundering herd issue, and it waits until the first thread that misses a key loads the element (asynchronously).
=> chore: Switch to smaller cache dep

Cargo.lock, datafusion/Cargo.toml, query_tests/src/influxrpc/tag_keys.rs
Closes https://github.com/influxdata/influxdb_iox/issues/1735, which was an intermittent test failure due to a race condition in datafusion
1. Update datafusion dependency to https://github.com/apache/arrow-datafusion/commit/4a55364448c81182731f4fa4c3e65aef5b31fa0f
2. Re-enable tests by reverting c63ad0e
=> fix: fix flaky test by updating datafusion dep

data_types/src/partition_metadata.rs, internal_types/src/schema.rs, query/src/duplicate.rs, query/src/provider.rs, query/src/util.rs
Based on  https://github.com/influxdata/influxdb_iox/pull/1756 (so draft until that is merged)
This is another step towards  https://github.com/influxdata/influxdb_iox/issues/1683 where I need to merge Schemas / subsets of schemas (and partition keys). What I need is the ability to know the primary keys from a merged schema, so in this PR primary keys are computed from Schemas.
1. Move `primary_key` to be in `Schema` rather than `TableSummary`
2. Update `Provider` to use  `Schema` rather than `TableSummary`
3. Update deduplicate detection code to use  `Schema` rather than `TableSummary`
After this PR I will be able to implement deduplicating for chunks with different schemas (yay!)
See full checklist / plan here: https://github.com/influxdata/influxdb_iox/issues/1683#issuecomment-863367715 …
=> refactor: use Schema to compute InfluxDB primary keys

data_types/src/job.rs, docs/README.md, docs/server_startup.md, generated_types/protos/influxdata/iox/management/v1/jobs.proto, generated_types/protos/influxdata/iox/management/v1/service.proto, generated_types/src/job.rs, influxdb_iox_client/src/client/management.rs, parquet_file/src/catalog.rs, parquet_file/src/rebuild.rs, server/src/config.rs, server/src/db.rs, server/src/init.rs, server/src/lib.rs, server/src/utils.rs, src/commands/database.rs, src/commands/database/catalog.rs, src/influxdb_ioxd/rpc/management.rs, tests/end_to_end_cases/management_api.rs, tests/end_to_end_cases/management_cli.rs
TBH I am not entirely happy with restricting the wipe to DBs that do not exist, however I don't know what we should do otherwise. Doing it "online" would require that we basically wipe all parquet files from the in-mem catalog as well and pause all object store IOs during the wipe. Since I expect a wipe to be require only if the DB cannot start up because of a broken catalog, I think even with this restriction this CLI command is still very useful.
Note that I have implemented that on the server side because:
- the client (or human operator) might not have storage credentials
- human operators might act over messy connections which can really bottleneck deleting thousands of files from object store quickly to get a DB back up and running
- the client might have not permissions to interact …
=> feat: wire catalog wiping all the way to the CLI

lifecycle/src/guard.rs, lifecycle/src/lib.rs, lifecycle/src/policy.rs, query_tests/src/pruning.rs, query_tests/src/scenarios.rs, server/src/db.rs, server/src/db/lifecycle.rs, server/src/lib.rs, server_benchmarks/benches/catalog_persistence.rs
As described in #1732 we wish to be able to plan and execute lifecycle actions under the same lock, however, this isn't possible with the current functionality exposed by `Db` - there is no way to plan an action and then start it executing under the same lock.
As this is a critical piece of making the lifecycle function correctly in the presence of multiple components initiating lifecycle actions, e.g. `LifecycleManager`, the write path, etc... I wanted to get something working with the current chunk-based lifecycle, to prove out the concepts. The same approach can then be adapted as we move to a partition-based lifecycle.
Unfortunately this turns into a bit of a pain when it comes to the lifecycle traits, see the docs at the top of `lifecycle/src/gaurd.rs`, because of the lack of support …
=> feat: transactional lifecycle API

read_buffer/benches/database.rs, read_buffer/benches/read_filter.rs, read_buffer/src/chunk.rs, read_buffer/src/lib.rs, read_buffer/src/table.rs, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/chunk.rs
Contributes to #1613 #1295 
It has been decided that a `Chunk` should be thought of as a horizontal partition of data for a single table. Therefore chunks should only have data for one table and not many tables.
This PR makes a minimal amount of changes outside of the Read Buffer, and of focusses on remove the data structures that supported holding multiple tables of data in a single chunk. 
Rather than break the API, which would cause lots of changes to the rest of IOx I have left the API as it is. Follow on PRs will make the breaking changes and fix any broken code as a result.
I have the following tickets to track this work:
- #1716
- #1717
- #1718
=> refactor: remove multiple tables from Read Buffer Chunk

datafusion_util/src/lib.rs, internal_types/src/schema.rs, mutable_buffer/src/chunk/snapshot.rs, query/src/provider.rs, query/src/provider/physical.rs, query/src/util.rs
feat: Support deduplicating from chunks that have different schemas
This is (hopefully) the last code step needed for https://github.com/influxdata/influxdb_iox/issues/1683. All that remains after this PR is to hook up the logic and update the query tests.
1. Ensure the primary key columns are fetched if needed for deduplication
2. Hook up the output schemas correctly
3. Tests for same
1. Turn on the deduplication logic outside of the tests / update sql tests in query_tests
=> feat: Handle merging chunks that have different schemas

scripts/git-log-prs
When a user runs the `git-log-prs --titles` script without the `gh` utility, the script exited swallowing the error message.
=> fix: Report error to stderr in git-log-prs

parquet_file/src/catalog.rs, parquet_file/src/cleanup.rs, parquet_file/src/rebuild.rs, server/src/config.rs, server/src/db.rs, server/src/init.rs, server/src/lib.rs
For #1740.
- move type parameters around / API clean-up (this PR)
- move in-mem catalog out of the transaction, this will be a HUGE simplification (next PR)
- cleanups (e.g. remove some `Arc`s that are no longer needed) (the PR after)
=> refactor: decouple preserved and in-mem catalog (part 2)

server/src/init.rs
Auto-wipe broken catalogs should be enabled until #1522 is closed.
=> fix: auto-wipe should still be enabled

.circleci/config.yml
it's quite slow:
but with `--exclude datafusion` it's not *that* much slower than the kafka integration tests:
It's possible that once we add some more tests to the kafka integration tests, this circleci job will no longer be in the critical path
=> chore: Store generated rustdoc as circleci artifacts

parquet_file/src/catalog.rs, parquet_file/src/cleanup.rs, parquet_file/src/rebuild.rs, server/src/db.rs
For #1740.
- move in-mem catalog out of the transaction, this will be a HUGE simplification (this PR)
- cleanups (e.g. remove some `Arc`s that are no longer needed) (next after)
=> refactor: decouple preserved and in-mem catalog (part 3)

server/src/lib.rs, src/influxdb_ioxd/rpc/error.rs
We've reported "databases not loaded" which is a bit confusing for
router nodes, so change the description to "server not initialized".
=> fix: improve "server not initialized" error

query/src/frontend.rs, query/src/frontend/reorg.rs, query/src/provider.rs, query/src/test.rs
re https://github.com/influxdata/conductor/issues/359
This is the "productionization" (meaning tests written) of https://github.com/influxdata/influxdb_iox/pull/1777, which adds a physical planner for merging chunks together
The hope is it can be used to wire up #1776  (such a patriotic PR number 🇺🇸)  and then we can have actual merge plans
=> feat: Reorg Planner for merge plans

parquet_file/src/chunk.rs, parquet_file/src/metadata.rs, server/src/db/catalog/chunk.rs, tests/end_to_end_cases/persistence.rs
Previously IOx would report the non-null count of the first column as the row count for the chunk, this is incorrect.
=> fix: correct row count for object store chunks

parquet_file/src/catalog.rs, parquet_file/src/rebuild.rs, server/src/config.rs, server/src/db.rs
Last part of the patch series, just some clean-ups.
Closes #1740.
=> refactor: decouple preserved and in-mem catalog (part 4)

Cargo.lock, Cargo.toml, grpc-router/Cargo.toml, grpc-router/grpc-router-test-gen/Cargo.toml, grpc-router/grpc-router-test-gen/build.rs, grpc-router/grpc-router-test-gen/protos/test.proto, grpc-router/grpc-router-test-gen/src/lib.rs, grpc-router/src/connection_manager.rs, grpc-router/src/lib.rs, grpc-router/src/router.rs
Dear reviewer, this PR contains only new code in a new crate.
You may find it easier to navigate through the large change by reading through [rustdoc](https://32400-223485832-gh.circle-artifacts.com/0/rustdoc/grpc_router/index.html) generated on circleci for this branch.
---
This PR implements the main building block for implementing the The Storage gRPC API router.
__Context__
The Storage gRPC API (`src/influxdb_ioxd/rpc/storage.rs`) is one of the IOx query endpoints. It allows us to plug an IOx cluster into the influxdb cloud2 system, as if it were a storage node.
The API consists of many (11) methods, most of which use the streaming gRPC feature.
Each node routing layer must parse the request, figure out the database to which the query is targeted, and perform a gRPC downstream …
=> feat: Implement grpc-router crate

parquet_file/src/storage.rs, query/src/exec.rs, query/src/exec/stream.rs, query/src/provider/deduplicate.rs
re https://github.com/influxdata/conductor/issues/360
1. There was already one copy paste version of this code
2. I need it for the "split" operator / plan I am working on for persist plans
1. Extract `AdapterStream` into its own module
2. Add additional documentation
2. Remove duplications
=> refactor: pull Channel --> Stream adapater into its own module

Cargo.lock, query_tests/src/influxrpc/read_window_aggregate.rs, query_tests/src/pruning.rs, query_tests/src/scenarios.rs, server/Cargo.toml, server/src/config.rs, server/src/db.rs, server/src/init.rs, server/src/lib.rs, server/src/utils.rs, server/src/write_buffer.rs, server_benchmarks/benches/catalog_persistence.rs, tests/end_to_end_cases/write_buffer.rs
This PR lets you configure a write buffer for a database to write to, and when you've done that, the entry will be written to the write buffer and the sequence sent to the mutable buffer.
This does not handle consuming data from Kafka as it's written or restoring from Kafka.
=> feat: Write entries to Kafka

query/src/exec.rs, query/src/exec/context.rs, query/src/exec/schema_pivot.rs, query/src/exec/split.rs, query/src/frontend/reorg.rs, query/src/provider.rs, server/src/db/lifecycle/compact.rs
re https://github.com/influxdata/conductor/issues/360
Needed for the persist operation where a chunk needs to be split on time.
For example, if the input looks like:
```text
X | time
---+-----
a | 1000
b | 2000
c | 4000
d | 2000
e | 3000
```
A split plan with `split_time=2000` will produce the following two output streams
```text
X | time
---+-----
a | 1000
b | 2000
d | 2000
```
```text
X | time
---+-----
c | 4000
e | 3000
```
1. Implement `SplitStream` operator and tests
2. Connect to split_plan
3. tests for same
It agree it seems like a lot of ceremony / plumbing to do the actual work... :shrug:
=> feat: Implement split_plans

query/src/exec/context.rs, query/src/exec/seriesset.rs, query/src/exec/split.rs, query/src/frontend/influxrpc.rs, query/src/provider.rs, query/src/provider/deduplicate/algo.rs, query/src/pruning.rs
We recently had a log-aplosion when `debug` logging was enabled due to the high volume of spew. We have reduced the logging level so debug is not generated anymore but @e-dard notes it is useful to maintain the ability to have some debug information.
Reduce several `debug!` calls to `trace!` to reduce said spew
=> chore: Reduce debug logging in query crate

read_buffer/src/chunk.rs
We're seeing some abnormally large RecordBatch being upserted into the RUB, and it is unclear why they are so monstrous. This adds some temporary logging to help diagnose what is going on. I'll likely downgrade this to debug once it has served its purpose
=> feat: temporary log information on record batch data

data_types/src/database_rules.rs, entry/src/entry.rs, mutable_buffer/src/lib.rs, mutable_buffer/src/persistence_windows.rs, server/src/db.rs, server/src/db/catalog/partition.rs
This brings the persistence windows into the catalog partition. It adds a helper method on TableBatch to get the min and max times for a given write. Finally, it adds this logic to the db to update persistence windows on every write while the partition write lock is being held.
=> feat: add persistence windows to partition and update on write

src/main.rs, trogging/src/layered_tracing.rs, trogging/src/lib.rs
The main issue that was preventing us to use open telemetry / jaeger tracing in IOx (and to close #1012) was the "per layer filtering" issue (see https://github.com/influxdata/influxdb_iox/issues/1012#issuecomment-821291660), whose summary is roughly:
> If we enable both logging and OT tracing, then both the logs and the trace output will be filtered with the intersection of the log and trace filters. We don't want our logs to be accidentally miss events because they are excluded from the tracing filter and we usually want the OT/jaeger tracing system to capture events at a higher verbosity (albeit at lower sample rate) than the logs.
This issue has been worked around in #1681 but it hasn't been plumbed in the IOx tracing configuration (which has been in the meantime factored out in the …
=> fix: Use layered tracing

query/src/frontend/influxrpc.rs, query/src/lib.rs, query/src/test.rs, server/src/db/chunk.rs
I was working on catching up on some refactor issues I have for the Read Buffer. One of those was to replace `table_names` in the Read Buffer with something more suitable to a Read Buffer chunk with only one table in it.
As part of that I was reviewing the code that calls `table_names` and got confused by the expected semantics of `apply predicate`. After a bit it became appararent that this was intended to only analyse meta-data.
This PR renames the method on the trait just to make it a bit clearer with the expectation that it might make sense to add a future method like `chunk_satisfies_predicate` or similar that will actually determine if there exists at least one row satisfying the predicate. This would then be useful for the `table_names` implementation.
=> refactor: clarify intent of applying predicate to Chunk

parquet_file/src/rebuild.rs
Stop relying on in-parquet transaction information during catalog
rebuilds. This has some downsides (no fork detection, only a single
transaction hence no time travel) but will allow that we remove
transaction information from parquet files, so that we can finally move
the actual parquet file storage out of the transaction lock.
This will help with #1821.
=> refactor: only rebuild a single txn for pres. catalogs

entry/src/entry.rs, mutable_buffer/src/chunk.rs, mutable_buffer/src/persistence_windows.rs, server/src/db.rs, server/src/db/catalog.rs, server/src/db/catalog/chunk.rs, server/src/db/process_clock.rs, server/src/write_buffer.rs, server_benchmarks/benches/snapshot.rs, server_benchmarks/benches/write.rs
Proposed fix for https://github.com/influxdata/influxdb_iox/issues/1817
Aka `panic!` ala
```
level=error msg="thread \'tokio-runtime-worker\' panicked at \'assertion failed: sequence.number > n.max\', mutable_buffer/src/persistence_windows.rs:234:17" target="panic_logging" location="panic_logging/src/lib.rs:110" time=1624875128145767206
```
The problem is the code on master has nothing to ensure writes from the `write` endpoint are written in the same order as they are given sequence nubers. Since the persistence windows assume each write is performed in increasing order it asserts when they get out of order under load.
This is likely a temporary solution to get IOx on tools back to healthy.  When we implement a local write buffer (aka not kafka) we'll have to implement some sort of code …
=> fix: Do not sequence local writes (avoid panic under load)

parquet_file/src/cleanup.rs, server/src/db.rs
Instead of (ab)using the transaction lock to prevent the cleanup job
from removing just-written parquet files, use a dedicated lock. This
will later allow us to write parquet files before starting a transaction
(i.e. w/o holding the transaction lock).
This will help with #1821.
=> refactor: improve locking around the parquet file cleanup

tests/end_to_end_cases/persistence.rs
To help with debugging #1809, which I can't reproduce locally, it would be beneficial to dump the state of any in-progress lifecycle actions on failure
=> feat: print operations on wait_for_chunk failure (#1809)

influxdb_iox_client/src/client/operations.rs, tests/end_to_end_cases/persistence.rs
Improves the logging added by #1833 to render the internal protobuf and print the operations in order. Serves me right for not testing this properly :facepalm:
=> chore: improve wait_for_chunk failure output

parquet_file/src/catalog.rs, parquet_file/src/metadata.rs, parquet_file/src/rebuild.rs, parquet_file/src/storage.rs, parquet_file/src/test_utils.rs, server/src/db.rs
=> refactor: write parquet files w/o holding the transaction lock

CONTRIBUTING.md, tests/common/server_fixture.rs
This makes a couple of changes to the end-to-end logging setup to help with debugging #1809 in particular
1. Each new server is given its own named temporary log file
2. On server shutdown it prints the output of the server
3. The default log level is `info` but it will respect `LOG_FILTER` in the environment
Together these should make it easier to debug end-to-end test failures in general, but in particular in CI - where currently there is no easy way to get at the server output.
Regarding the new temporary files, on Linux system-tmpfiles will clean them up periodically (normally a day). I'm not sure about OS X, but given we weren't truncating the logs before this should be no worse than before in terms of total file footprint.
Example output might be
```
****************
Server …
```
=> chore: print end-to-end output

mutable_buffer/src/checkpoint.rs, mutable_buffer/src/lib.rs
Implements logic for checkpoint persistence and replay handling as described in the lifecycle 3.0 doc. Docs for easier review can be found [here](https://33606-223485832-gh.circle-artifacts.com/0/rustdoc/mutable_buffer/checkpoint/index.html).
=>  feat: implement persistence window checkpointing 

read_buffer/src/chunk.rs, server/src/db.rs, server/src/db/chunk.rs
Closes #1717
Changes Read Buffer crate API to not include table names
=> refactor: remove table name from Read Buffer API.

CONTRIBUTING.md, tests/common/server_fixture.rs
Turn off so much logging
After https://github.com/influxdata/influxdb_iox/pull/1838 was merged, when I run `cargo test --all` logs of INFO logging is spewed to my screen during the end to end tests even when there is no failure:
```
****************
Start TestServer Output
****************
Jun 29 15:58:23.605  INFO influxdb_iox::influxdb_ioxd: InfluxDB IOx server starting git_hash="f04835eaea3fd0c9892b1c39a47d415186537636" num_cpus=16 build_malloc_conf="\u{0}"
Jun 29 15:58:23.606  INFO influxdb_iox::influxdb_ioxd: Using File for object storage
Jun 29 15:58:23.608  WARN influxdb_iox::influxdb_ioxd: server ID not set. ID must be set via the INFLUXDB_IOX_ID config or API before writing or querying data.
Jun 29 15:58:23.609  INFO influxdb_iox::influxdb_ioxd: gRPC server listening …
```
=> fix: do not print test output to logs except on failure

README.md
Revises the "Quick start" section of the main README, which I've renamed to "Get started". I've tried to make these instructions easier to follow and more concise.
=> docs: Edit Quick Start

scripts/git-log-prs
Previously this script would print
```
'1825 fix: remove shared dictionary concept from ChunkSnapshot (#1570) (#1820)'
```
This would then get bundled into changelogs in other repositories, where these issues would refer to different things. I wasn't sure whether to fix this here or in the other repo, the sed expression can be applied in either.
The output would now be
```
1825 fix: remove shared dictionary concept from ChunkSnapshot (influxdata/influxdb_iox#1570) (influxdata/influxdb_iox#1820)
```
=> feat: namespace issues in git-log-prs

query_tests/src/pruning.rs, query_tests/src/scenarios.rs, server/src/db.rs, server/src/db/lifecycle.rs, server_benchmarks/benches/catalog_persistence.rs
Re: #1855 
Using consistent terminology for moving data to the read buffer will make it easier to understand
=> refactor: rename load_chunk_to_read_buffer to move_chunk_to_read_buffer

server/src/db.rs, server/src/db/lifecycle.rs, server/src/db/lifecycle/error.rs, server/src/db/lifecycle/move_chunk.rs, server/src/db/lifecycle/unload.rs, server/src/db/lifecycle/write.rs
1. Having one place to see what lifecycle actions are available will make it easier to ensure they stay in sync (e.g. hoping to avoid stuff like https://github.com/influxdata/influxdb_iox/issues/1855)
2. It contributes to the 'make db.rs less of a mess' project
There are no intended functional changes -- this just shuffles code around
1. Put the `move_to_read_buffer` code into `lifecycle/move.rs`
2. Per the `write_to_object_store` code into lifecycle/write.rs`
3. Put the `unload_read_buffer` code into lifecycle/unload.rs
4. Make a lifecycle error enum
=> refactor: move lifecycle implementations out of db.rs and into their own modules

lifecycle/src/lib.rs, lifecycle/src/policy.rs, server/src/db.rs, server/src/db/lifecycle.rs, server/src/db/lifecycle/compact.rs, server/src/db/lifecycle/error.rs, server/src/db/lifecycle/move_chunk.rs, server/src/db/lifecycle/unload.rs, server/src/db/lifecycle/write.rs
This PR follows on from #1858 and brings compact_chunks into alignment with the error handling for the other lifecycle actions.
It also tweaks the db::lifecycle module to not expose its internal module topology, to avoid redundancy
=> refactor: single lifecycle error enumeration

src/influxdb_ioxd/rpc/storage/service.rs, tests/common/server_fixture.rs
Closes #
Make intervals and timeout longer for all the tests pass on my laptop
=> fix: change timeout to have all tests passed on slow laptop

query_tests/src/influxrpc/tag_values.rs, query_tests/src/scenarios.rs, server/src/db.rs, server/src/db/lifecycle.rs, server/src/db/lifecycle/compact.rs
Re https://github.com/influxdata/influxdb_iox/pull/1855
The query_tests scenarios do not currently include chunks created via "compaction" (they only test chunks created by load, rollover, etc); As I work to disable over eager deduplication for chunks created in the read buffer in  https://github.com/influxdata/influxdb_iox/pull/1855 and https://github.com/influxdata/influxdb_iox/issues/1763 I want to ensure sufficient coverage.
1. Add a function `Db::compact_partition` to trigger a compaction
2. Adds a 7th scenario to two chunk secnarios where the data is compacted into a single large RUB chunk
This test has also uncovered a bug in `column_values` implementation of the read buffer, which I have filed as https://github.com/influxdata/influxdb_iox/issues/1860
=> chore: Add query tests for compacted chunks

Cargo.lock, generated_types/build.rs, generated_types/protos/influxdata/iox/catalog/v1/parquet_metadata.proto, parquet_file/Cargo.toml, parquet_file/src/catalog.rs, parquet_file/src/metadata.rs, parquet_file/src/storage.rs
In preparation for more complex types (e.g. replay checkpoints).
=> refactor: use protobuf for in-parquet metadata

lifecycle/src/lib.rs, lifecycle/src/policy.rs, query_tests/src/influxrpc/field_columns.rs, query_tests/src/influxrpc/read_filter.rs, query_tests/src/influxrpc/read_group.rs, query_tests/src/influxrpc/read_window_aggregate.rs, query_tests/src/influxrpc/table_names.rs, query_tests/src/influxrpc/tag_keys.rs, query_tests/src/influxrpc/tag_values.rs, query_tests/src/pruning.rs, query_tests/src/runner.rs, query_tests/src/scenarios.rs, query_tests/src/sql.rs, server/src/db.rs, server/src/db/lifecycle.rs, server/src/db/lifecycle/compact.rs, server/src/db/lifecycle/move_chunk.rs, server/src/db/lifecycle/unload.rs, server/src/db/lifecycle/write.rs, server/src/utils.rs
Currently we somewhat cheat by borrowing `&Db` from the `Arc<Db>` bundled into the background worker loop, and then `Arc::clone` relevant fields from this for the background lifecycle actions. 
This works, however, it means you can't spawn a lifecycle action from another lifecycle action (as you no longer have access to Db).
Various solutions were proposed:
1. Bundle Arc<Db>  into the lifecycle actions. This is the most consistent with what we currently do, the downside is the member functions on Db now take self: Arc<Self> resulting in a lot of churn in query_tests and a bit of a sad API imo
2. Move the members from Db onto a DbShared and store Arc<DbShared>  on Db
3. Create a custom payload type for the lifecycle actions with just the relevant members
Of these, the consensus was for …
=> refactor: use Arc<Db> in lifecycle actions

read_buffer/benches/database.rs, read_buffer/src/chunk.rs, server/src/db/lifecycle/compact.rs, server/src/db/lifecycle/move_chunk.rs
Drive by refactor to remove redundant table name from read buffer API
=> refactor: remove table name from upsert_table (#1295)

internal_types/src/guard.rs, internal_types/src/lib.rs, mutable_buffer/src/persistence_windows.rs
We have two requirements for persistence:
1. Don't stall ingest whilst persisting a partition
2. Don't flush data from PersistenceWindow till it is actually persisted
Criteria 1 means that we must drop the partition lock whilst persisting, but this means that the persistable window may be mutated whilst this is taking place. When we then flush the persistable window after having persisted, currently we may end up flushing more data than we actually persisted!
The simplest way around this is to stick a lock around the persistable window that is held whilst the persistence operation is running. Once persistence has completed, we re-acquire a write lock on the partition, drop the flush guard and then flush the persistable window. We are guaranteed that what is flushed hasn't changed since …
=> feat: add flush guard to PersistenceWindows

Cargo.lock, Cargo.toml, mutable_buffer/src/lib.rs, parquet_file/Cargo.toml, parquet_file/src/metadata.rs, parquet_file/src/test_utils.rs, persistence_windows/Cargo.toml, persistence_windows/src/checkpoint.rs, persistence_windows/src/lib.rs, persistence_windows/src/min_max_sequence.rs, persistence_windows/src/persistence_windows.rs, server/Cargo.toml, server/src/db.rs, server/src/db/catalog/partition.rs, server/src/db/lifecycle/write.rs
The entire persistence windows data structures (including the
checkpoints) have nothing to do with the mutable buffer per se. So lets
move them into their own crate. This also makes `parquet_file` not
longer depend on `mutable_buffer`.
=> chore: move persistence windows related code into own crate

lifecycle/src/policy.rs
`persist_row_threshold` should limit the rows of the post-compaction
output chunk (and hence the sum of rows over the input chunks), not
the number of rows of each individual input chunk.
Fixes #1874.
=> fix: `persist_row_threshold` limits the out chunk row count

internal_types/src/schema/merge.rs, query/src/frontend/influxrpc.rs, query/src/frontend/reorg.rs, query/src/provider.rs, query/src/test.rs, server/src/db/access.rs
I'm probably going to need the `SchemaMerger` for #1897 , so here is a little fix/cleanup:
The error handling in `merge` was incomplete, aka it could leave the
merger in a half-modified state in case of an error. That's generally a
bad idea and can lead to ugly bugs. Also the "builder" pattern that is
used here usually consumes itself (and provides a clone impl), so it is
easier to reason about modifications. So this commit just changes it to
self-consuming builder.
A nice side effect of the new pattern is also that it is build-time
checked and does not contain a runtime assert any longer.
=> refactor: rework builder pattern

lifecycle/src/policy.rs
This can possibly help us better understand #1899.
The practical reason for increasing the log level for those
events is that we cannot currently ingest debug logs in our log aggregation system,
but it currently takes 7h to reproduce #1899 which means we don't have access to debug logs
from `kubectl logs` to help us troubleshoot.
That said, I do think that these logs are not debug logs but legit lifecycle information.
In particular if a log says "unexpected ..." I think it may be better regarded as an error/warning.
(If it becomes too verbose, it means its either a bug or not that unexpected).
=> fix: Increase log level for important lifecycle events

server/src/db.rs
re https://github.com/influxdata/influxdb_iox/issues/1906 suggested by @mkmik  
This function is not invoked automatically by the lifecycle manager, which may not be obvious to a casual reader. 
Add a comment to try and help future readers save some time
=> docs: Note that rollover_partition is not automatically called

data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, generated_types/src/database_rules/lifecycle.rs, src/commands/database.rs, tests/end_to_end_cases/scenario.rs
Re https://github.com/influxdata/influxdb_iox/issues/1878 and re https://github.com/influxdata/influxdb_iox/issues/1906
The `mutable_size_threshold` is not connected to any code or policy, and having it in the lifecycle rules is confusing. The PR that removed it was https://github.com/influxdata/influxdb_iox/pull/1875
1. Remove the unused setting
=> refactor: remove unused `mutable_size_threshold` in lifecycle setting

data_types/src/database_rules.rs, generated_types/src/database_rules/lifecycle.rs, lifecycle/src/policy.rs, tests/end_to_end_cases/management_api.rs
This is a cleanup follow up to #1915
=> refactor: Turn mutable_linger_seconds into a non-optional

entry/src/entry.rs, parquet_file/src/catalog.rs, server/src/db.rs, server/src/db/catalog.rs, server/src/db/catalog/metrics.rs, server/src/db/catalog/table.rs, server/src/db/load.rs, server/src/utils.rs, server_benchmarks/benches/snapshot.rs, server_benchmarks/benches/write.rs
This way we can:
- check for schema matches even for writes going into different
partitions
- solve #1768 and #1884 in some future PR
I have put some special care into the locking, so we don't serialize on table-wide schema.
Closes #1897.
Closes https://github.com/influxdata/influxdb_iox/issues/636
=> feat: store schemas per table, enforce schema on write

data_types/src/database_rules.rs, generated_types/src/database_rules/lifecycle.rs, lifecycle/src/policy.rs, tests/end_to_end_cases/management_api.rs
Follow up cleanup PR: https://github.com/influxdata/influxdb_iox/pull/1917 (no longer make mutable_linger_seconds an option and move the defaulting to the configuration layer)
Closes #1899
Closes https://github.com/influxdata/influxdb_iox/issues/1914
=> fix: Ensure mutable_linger_seconds can not be None

Cargo.lock, datafusion/Cargo.toml, datafusion_util/src/lib.rs, query/src/exec.rs, query/src/exec/context.rs, query/src/exec/schema_pivot.rs, query/src/exec/split.rs, query/src/frontend/influxrpc.rs, query/src/frontend/reorg.rs, query/src/predicate.rs, query/src/provider.rs, query/src/provider/deduplicate.rs, query/src/provider/deduplicate/algo.rs, query/src/pruning.rs, query/src/util.rs, query_tests/cases/in/duplicates.expected, query_tests/cases/in/pushdown.expected, read_buffer/src/row_group.rs, server/src/db/pred.rs, server_benchmarks/benches/read_filter.rs, server_benchmarks/benches/read_group.rs, server_benchmarks/benches/tag_values.rs
https://github.com/apache/arrow-datafusion/pull/55 was a non trivial change to DataFusion (basically to have proper `relation`.`column` identifiers) and it needs to be integrated into IOx (so that we can keep the features flowing)
1. Update to https://github.com/apache/arrow-datafusion/commit/f2c01de7d620081eb370966d928673c8d38ac798, to get https://github.com/apache/arrow-datafusion/pull/681 among other things like improved join support. 
2. run `cargo update`
3. Update IOx to use new API
Here are some other items that were needed to be added to DataFusion to get this PR to pass the tests:
Also, TIL "Star Roving" -- https://www.youtube.com/watch?v=ogCih4OavoY -- it's pretty good 👍
=> chore: Update datafusion deps

query_tests/src/runner.rs
(this is definitely an itch I have wanted to scratch)
Today, when you run `cargo test -p query_tests` you get the spew shown in the "example output before change" section below. 
This is due to the fact that whatever redirection mechanism used in the Rust test runner seems to only work on `println!` rather than things that are sent to `stdout` directly
1. Use println rather than `std::io::stdout()` to write log output
```
running 112 tests
test influxrpc::field_columns::test_field_columns_empty_database ... ok
test influxrpc::read_filter::test_read_filter_data_pred_refers_to_non_existent_column ... ok
test influxrpc::read_filter::test_read_filter_data_pred_refers_to_good_and_non_existent_columns ... ok
test influxrpc::read_filter::test_read_filter_no_data_no_pred ... ok
test …
```
=> chore: Reduce output spew during query tests

data_types/src/job.rs, entry/src/entry.rs, generated_types/protos/influxdata/iox/management/v1/jobs.proto, generated_types/src/job.rs, persistence_windows/src/persistence_windows.rs, query/src/exec/context.rs, query/src/frontend/reorg.rs, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/partition.rs, server/src/db/lifecycle.rs, server/src/db/lifecycle/compact.rs, server/src/db/lifecycle/error.rs, server/src/db/lifecycle/move_chunk.rs, server/src/db/lifecycle/write.rs
feat: Infrastructure for persistence
re https://github.com/influxdata/conductor/issues/360
This is part of the persist lifecycle action PR https://github.com/influxdata/influxdb_iox/pull/1888 which I am splitting into multiple PRs for easier review. It is therefore somewhat of a potpourri of various refactorings
There are no functional changes intended in this PR (it is setup for the next one where there are functional changes)
This code was largely written by @tustvold 
1. Add in Job and Job related proto bugs (could be its own PR)
2. Twiddle with persist window API
3. Add in `Display` formatting for various `LockablePartitions` (which I was using to get understandable logs)
3. Refactor the server's lifecycle crates to reduce code duplication creating rub chunks
=> refactor: Infrastructure for persistence

data_types/src/partition_metadata.rs, internal_types/src/schema/sort.rs, read_buffer/src/chunk.rs, server/src/db/lifecycle/compact.rs
I have rebased on https://github.com/influxdata/influxdb_iox/pull/1925 otherwise this would trample all over @alamb's PR. I will rebase again when https://github.com/influxdata/influxdb_iox/pull/1925 is merged in.
We want more observabilty around the compaction process.
This PR adds some observability around a single compaction operation. I considered adding explicit metrics for this but I think this log line will get us useful information sooner. 
We should add some metrics around compaction soon.
The log line looks like this:
```
Jul 08 11:24:31.303  INFO server::db::lifecycle::compact: chunk(s) compacted input_chunks=1 rub_row_groups=1 input_rows=100000 output_rows=100000 sort_key="tag2, tag3, tag1, tag0, time," compaction_took=3.637288958s rows_per_sec=27493
``` 
It includes:
- …
=> refactor: log information for compaction results

parquet_file/src/chunk.rs, parquet_file/src/metadata.rs, parquet_file/src/rebuild.rs, parquet_file/src/storage.rs, parquet_file/src/test_utils.rs, persistence_windows/src/checkpoint.rs, server/src/db.rs, server/src/db/lifecycle/write.rs
This has the (somewhat nice) side effect that it shrinks the in-mem
catalog a bit as well because now `ParquetChunk` is a bit smaller making
the chunk stage enum smaller as well.
=> refactor: convert some table name and part. key String to Arcs

data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, generated_types/src/database_rules.rs, server/src/config.rs, server/src/db.rs, server/src/init.rs, server/src/lib.rs, server/src/utils.rs, server/src/write_buffer.rs, src/influxdb_ioxd/rpc/error.rs, tests/end_to_end_cases/management_api.rs, tests/end_to_end_cases/write_buffer.rs
This adds the reading side of the Kafka write buffer, that streams entries from a Kafka topic into a database's mutable buffer.
This PR is missing:
- Metrics counting the number of failed imports, see the TODO comments
- End-to-end integration tests
I will be adding these in future PRs.
=> feat: reading entries from Kafka

Cargo.lock, datafusion/Cargo.toml
Pick up @e-dard 's performance improvement for https://github.com/apache/arrow-datafusion/pull/691
1. Update to https://github.com/apache/arrow-datafusion/commit/024bd89603dea13e63b70c92274116edbe36c4f9
2. Run `cargo update`
3. Check in results
=> chore: Update DataFusion again

data_types/src/chunk_metadata.rs, lifecycle/src/lib.rs, lifecycle/src/policy.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/partition.rs, server/src/db/lifecycle.rs, server/src/db/lifecycle/write.rs, server/src/db/system_tables.rs
refactor: Move ChunkLifecycleAction to the data_types crate
Re: https://github.com/influxdata/influxdb_iox/issues/1912, we want to add external (API and system table) visibility about any lifecycle actions that might be happening
To add to both the API and system tables, I plan to add the the outstanding lifecycle action to `ChunkSummary`.
1. Move `ChunkLifecycleAction` to `data_types` crate so that in a follow on PR I can add it to `ChunkSummary` which is also in that crate.
=> refactor: Move ChunkLifecycleAction to the data_types crate

mutable_buffer/src/chunk.rs, server/src/db.rs, server/src/db/catalog.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/partition.rs, server_benchmarks/benches/snapshot.rs, server_benchmarks/benches/write.rs
Connects to #1927, this is just one part of completing that but it seemed pretty separate and a good reviewable chunk (pun intended).
This also makes it so that you can't have an empty `mutable_buffer::chunk::MBChunk` because the only constructor takes a `TableBatch`.
=> feat: Record first and last write times on MUB chunks

query/src/frontend/influxrpc.rs, query/src/frontend/reorg.rs, query/src/lib.rs, query/src/provider.rs, query/src/test.rs, query_tests/cases/in/all_chunks_dropped.expected, query_tests/cases/in/all_chunks_dropped.sql, query_tests/src/cases.rs, query_tests/src/runner.rs, query_tests/src/scenarios.rs, server/src/db.rs, server/src/db/access.rs, server/src/db/catalog.rs, server/src/db/catalog/chunk.rs, server/src/db/catalog/partition.rs, server/src/db/catalog/table.rs, server/src/db/lifecycle/compact.rs, server/src/db/lifecycle/move_chunk.rs
Do no longer scan chunks during query planning to determine the schema
(except for the lifetime jobs where we have a good reason to do so).
Instead pass the schema down to from whoever is triggering the query.
For real SQL queries, we then just use the the table-wide schemas
introduced in #1913.
Apart from avoiding schema merges we now also don't crash any longer
when no chunks are left in the table (aka columns are present but all
rows are gone).
Fixes #1768.
Fixes #1884.
=> refactor: pass schema arcs from catalog to query engine (instead of creating them on-demand)

.circleci/config.yml, Cargo.toml, object_store/Cargo.toml, object_store/src/aws.rs, object_store/src/buffer.rs, object_store/src/dummy.rs, object_store/src/lib.rs, server/src/lib.rs, src/influxdb_ioxd.rs
Builds on https://github.com/influxdata/influxdb_iox/pull/1932
This may be a controversial change, but I wanted to get it up for discussion
It only reduces the best case link/re-compile time by 5% but it helps more when everything isn't already in cache as there are 100 fewer dependencies during normal development
Between them, the S3, Azure, and GCP crates bring in over 100 dependent crates which are not used for normal development / testing workflow. I plan to make these dependencies optional to speed up my normal development workflow
1. Make  aws, gcp and azure optional features of the object_store crate
2. Only compile them in for the final release binary
```
touch server/src/db.rs && cargo test -p server --no-run
```
main, compiles 474 dependencies
```
Finished test [unoptimized + …
```
=> refactor: Make aws/azure/gcs optional features and stop compiling 100 dependencies during dev

lifecycle/src/guard.rs, lifecycle/src/lib.rs, lifecycle/src/policy.rs, server/src/db/lifecycle.rs, server/src/db/lifecycle/compact.rs, server/src/db/lifecycle/move_chunk.rs, server/src/db/lifecycle/persist.rs, server/src/db/lifecycle/write.rs, tests/end_to_end_cases/persistence.rs, tests/end_to_end_cases/scenario.rs
Closes https://github.com/influxdata/conductor/issues/360 closes https://github.com/influxdata/influxdb_iox/issues/1943
Adds the policy and implementation to split and persist chunks based on the persistence windows.
@tustvold  notes that he doesn't like the interface with the persistence windows. Since I (@alamb) don't have anything better to offer, I have picked this PR up and gotten it ready for review.
=> feat: Persist lifecycle action

data_types/src/chunk_metadata.rs, generated_types/protos/influxdata/iox/management/v1/chunk.proto, generated_types/src/chunk.rs, server/src/db.rs, server/src/db/catalog/chunk.rs, server/src/db/system_tables.rs, tests/end_to_end_cases/management_api.rs
Make ongoing chunk lifecycle actions observable by operators
Closes #1912
1. Add a new `lifecycle_action` field to `ChunkSummary`
1. Add a new `lifecycle_action` field to the management API GRPC
2. Add a new `lifecycle_action` field to system.chunks table
There are sufficient unit tests, but I don't really have a great way to "end to end" test this PR because it involves catching a chunk while a background lifecycle action is underway. 
So I manually tested it: 
```shell
cargo run -- run  --num-worker-threads=1 --object-store=file --data-dir=$HOME/.influxdb_iox --server-id=42
```
``shell
./target/debug/influxdb_iox database create my_db
./scripts/edit_db_rules localhost:8082 my_db
```
Setup lifecycle rules to compact aggressively:
```
{
"rules": {
"name": "my_db",
"partitionTemplate": { …
=> feat: Add any lifecycle_action to system.chunks and API

data_types/src/database_rules.rs, generated_types/protos/influxdata/iox/management/v1/database_rules.proto, generated_types/src/database_rules/lifecycle.rs, lifecycle/src/policy.rs, src/commands/database.rs, tests/end_to_end_cases/management_api.rs, tests/end_to_end_cases/scenario.rs
The interplay between mutable_linger_seconds, late_arrive_window and persist_age_threshold_seconds can be tricky to reason about. I realized that the lifecycle rules can be simplified by removing mutable_linger_seconds and instead using late_arrive_window_seconds for the same purpose. Semantically, they basically mean the same thing. We want to give data around this amount of time to arrive before the system persists it, which gives it more of an opportunity to persist non-overlapping data.
When a partition goes cold for writes, after we've waiting past this window, we should compact and persist that partition. This removes one unnecessary knob from the lifecycle configuration and also removes the potential for conflicting configuration options.
=> refactor: remove mutable_linger_seconds from lifecycle

object_store/src/disk.rs, object_store/src/lib.rs, object_store/src/memory.rs, object_store/src/throttle.rs, parquet_file/src/test_utils.rs, server/src/config.rs, server/src/db.rs, server/src/db/load.rs, server/src/init.rs, server/src/lib.rs, server/src/utils.rs, server_benchmarks/benches/catalog_persistence.rs, src/influxdb_ioxd.rs, src/influxdb_ioxd/http.rs
1. Keeping the object store construction interface consistent is a good thing
2. Keeping the implementation details of object_store encapsulated is also a good thing
1. Make `memory`, `disk` and `throttle` modules object store private
2. Update the object store constructor interface for disk, memory, and throttled the same as for AWS, S3 and GCP (which were changed in https://github.com/influxdata/influxdb_iox/pull/1932
=> refactor: make object_store construction interface consistent

data_types/src/partition_metadata.rs, query/src/frontend/reorg.rs, query/src/provider.rs, query/src/provider/overlap.rs, query/src/pruning.rs, query/src/test.rs, src/influxdb_ioxd/rpc/storage/service.rs
While working towards #1927, in the query crate, I found 2 `TestChunk`s and 1 `TestChunkMeta` that looked like they were doing similar things, so I unified them into one `query::test::TestChunk`. The diff stats aren't quite as dramatic as I was hoping for, but it's still a net negative :)
=> refactor: Go from 3 mock chunks to 1

src/influxdb_ioxd/http.rs
I noticed this on https://github.com/influxdata/influxdb_iox/pull/1968 and refactored it while writing a version of the test for #1968 that did not make it into the final PR, but it seemed useful anyways to reduce some copy/pasta
=> refactor: reduce some repetition in http tests

server/src/init.rs, server/src/lib.rs
When a node starts, it initializes the existing databases when it reads the persisted rules file.
If a database rules file is later updated, it doesn't (currently) apply the write buffer config.
We'll address that in another commit, but let's just log this now because it's important to know the effective
personality configuration of a database (i.e. whether it acts as an in-memory database or as a router!)
=> chore: Log whether the write buffer is enabled

server/src/lib.rs, server/src/write_buffer.rs
And log message size on kafka write error.
Turns out the kafka partition message size limit default is 1MB, but also the
client side "max request size" default is also 1MB.
The error message we get from our kafka client is misleading: it says
```
KafkaError (Message production error: MessageSizeTooLarge (Broker: Message size too large)) }
```
which to my mind it seemed like if ("Broker:") the broker said "Message size too large".
That was a lie; I killed the broker and the client kept saying the same error message which means
it didn't even try to send the message out.
TODO: make this a proper parameter. (but let's unblock)
=> fix: Raise kafka max request size to 10M

write_buffer/src/kafka.rs
I think that this will set an appropriate configuration setting to increase the maximum size of a message we can produce onto Kafka.
=> refactor: set kafka max message size

query/src/provider.rs
This increases the record batch size used in the `SortPreservingMergeExec` operator to 25600 rows. I am experimenting with the impact that this has on compaction performance, with the theory that it should improve it.
Longer term we need to do this ticket here and then we should have something more configurable.
https://github.com/influxdata/influxdb_iox/issues/2001
=> refactor: increase compaction batch size

read_buffer/src/chunk.rs, server/src/db/catalog/chunk.rs
Because chunks now have only one table.
Connects to #1718, #1613, #1295. Might fix the first one? Not sure, because that one talks about removing `table_summaries` entirely. @e-dard what do you think? I saw you just closed the other two...
=> fix: Change RUB chunk table_summaries to table_summary

Cargo.lock, Cargo.toml, docker/Dockerfile.ci.integration, docker/integration_test.sh, entry/src/entry.rs, server/src/db.rs, tests/end_to_end_cases/write_buffer.rs, write_buffer/Cargo.toml, write_buffer/src/core.rs, write_buffer/src/kafka.rs, write_buffer/src/mock.rs
This refactors the write buffer a bit for:
- **Testing:** Add generic tests for the Kafka and the mocking
implementation. The same interface can be used easily add new
implementations (e.g. via Redis, filesystem, ...).
- **Partition on Write:** The caller of the writer operation must now
specify the partition/sequencer ID. The implicit partitioning of the
Kafka writer would have lead to broken data since we must never spill
entries w/ the same primary key over multiple partitions. At the
moment we will only use partition 0 but we can easily implement
better logic in the future.
- **Improved Mocking:** The mocked implementation now simulates a system
that feels more real. Especially the handling around multiple streams
and "write while read" has been improved. This will be helpful for …
=> refactor: write buffer testing + better mocking
