ingest/src/lib.rs
ingest/src/parquet/writer.rs
ingest/tests/read_write.rs
packers/src/packers.rs
packers/src/sorter.rs

refactor: change String variant to Bytes

---

Cargo.toml
src/cpu_feature_check/main.rs

This was something I whipped up while trying to see if my home machine had features that were being tested by conditional compilation `avx2` specifically.
I am not sure if this is something we want to put into the iox repo, but I figured I would at least throw the code out there for consideration

feat: add cpu_feature_check

---

storage/src/lib.rs

I was writing this as part of another PR, but figured it would be just as good to get it into its own PR

docs: Clarify the intent of the `Database` trait

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

This PR adds some documenation to the project `README` that provides guidance on:
* Submitting issues and feature requests to the project;
* Submitting issues to discover big code changes;
* The process of submitting community PRs.
I have added Github templates that provide further information for these specific things. I also placated some markdown lints.
Closes https://github.com/influxdata/influxdb_iox/issues/471

chore: improve community contribution documentation

---

src/server/rpc/expr.rs

As suggested by @domodwyer  on https://github.com/influxdata/influxdb_iox/pull/474#discussion_r529807966

refactor: Remove uneeded unwrap

---

write_buffer/src/database.rs
write_buffer/src/partition.rs
write_buffer/src/table.rs

Related to https://github.com/influxdata/influxdb_iox/issues/479
This was just a pure 'scratch the itch' kind of PR -- DataFusion has a bunch of nice to use functions for creating expressions programmatically (this sort of thing is a non trivial part of why we are using data fusion in the first place) but I didn't use them in earlier versions of the IOx query engine.
So go back and use those functions rather than our own homegrown versions

refactor: use datafusion expression building functions in write_buffer

---

segment_store/src/column.rs
segment_store/src/lib.rs
segment_store/src/partition.rs
segment_store/src/segment.rs
segment_store/src/table.rs

This PR ports over some code I have in a WIP development branch I've been using for some experiments. No new features here, just a refactor that makes things easier w.r.t lifetimes.

refactor: remove some lifetimes

---

.circleci/config.yml

Adds some extra quick-glance docs for the CI flow.
Not sure who is best to add to this PR - add whoever!

docs(ci): extra CI documentation

---

data_types/src/data.rs
object_store/src/lib.rs
src/commands/server.rs

comments and rename function paramenter.

chore: some minor comments and rename

---

mem_qe/README.md

chore: deprecate mem_qe

---

tests/end-to-end.rs
write_buffer/src/database.rs
write_buffer/src/table.rs

This is a PR towards ensuring the proper implementation of the read_group gRPC call (https://github.com/influxdata/influxdb_iox/issues/448)
It adds *actual* aggregation support for Sum, Count, and Mean
Here is the rough implementation plan:

feat: implement read_group for Sum, Count and Mean aggregates

---

server/src/server.rs

Moves the server ID value outside of the mutex-wrapped `Config` type and
into the `Server` struct, synchronising threads using an atomic instead.
This prevents any calls to `require_id()` from having to contend for a
read lock on the config mutex while maintaining lineraisaion of ID
values - all threads see the change as soon as it is set.
On x86 this synchronisation is actually completely "free" - memory
accesses are totally ordered, so this turns into a compile fence to
prevent LLVM changing program order at compile time with no runtime
overhead at all.
Previously the ID value was wrote as part of the config, but this is no
longer the case. It should be easy to add back in, but it appears to be
redundant as the ID is required to construct the path to the config when
loading in the first …

perf: avoid locking to load server ID

---

src/commands/server.rs
src/server/http_routes.rs

Improves some logging messages that I noticed while recording a demo

chore: tweak logging messages

---

src/server/rpc/expr.rs

Closes https://github.com/influxdata/influxdb_iox/issues/588
Closes https://github.com/influxdata/influxdb_iox/issues/589
This PR removes some overzealous error checking. I made some initial assumptions / theories of what types of inputs would be sent by flux and when I tested with Flux, it turns out that flux can send requests with properties I theorized it could not.
So update the code to be more lenient

fix: Less zealous error checking for gRPC group requests

---

object_store/src/path.rs

This adds more tests and a bit more functionality to the `ObjectStorePath` as a follow on to https://github.com/influxdata/influxdb_iox/pull/611

feat: More work on the ObjectStorePath

---

server/src/lib.rs

Do not overwrite an existing database when attempting to create a DB with an
existing name.
This should probably update the existing database config, but for the time being
this prevents the existing database from being silently dropped.
Fixes #643

fix: do not overwrite databases

---

mutable_buffer/src/database.rs
query/src/exec.rs
src/server/rpc/service.rs

Closes #
fix typo and rename variable/function

chore: rename

---

tests/end-to-end.rs

I am debugging a failure in the end to end test and I couldn't do so effectively with the error messages that are printed at the moment. 
Prior to this change the error looks like this (no line number) and obscure message
```
thread 'read_and_write_data' panicked at 'assertion failed: `(left == right)`
left: `1`,
right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /Users/alamb/.rustup/toolchains/nightly-2020-11-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/test/src/lib.rs:192:5
```
After this change, the error looks like the following which gives me an line number to work with
```
Successfully got a response from HTTP: Response { url: Url { scheme: "http", host: Some(Domain("localhost")), port: Some(8080), path: "/ping", …
```

fix: Update end-to-end.rs to have more specific error messages

---

data_types/src/database_rules.rs
influxdb_tsm/src/lib.rs
object_store/src/lib.rs
query/src/exec/seriesset.rs
server/src/buffer.rs

As Daniel Tiger sings, 🎶 clean up, pick up, put away, clean up everyday 🎶
Just some tiny things I noticed today.

refactor: Some tiny cleanups

---

data_types/src/names.rs

Left over code from https://github.com/influxdata/influxdb_iox/pull/678 that can be removed

refactor: Remove unused error

---

mutable_buffer/src/database.rs
query/src/lib.rs
query/src/test.rs
server/src/db.rs

I found this code is not used nor tested. So I propose deleting it. I found it while working to refactor out the gRPC query code into a gRPC planner

refactor: Delete remove dead code

---

Cargo.lock
arrow_deps/Cargo.toml

Pull in latest arrow to keep us up to date

chore: Bump arrow deps

---

Cargo.lock
Cargo.toml
arrow_deps/Cargo.toml
generated_types/Cargo.toml
influxdb2_client/Cargo.toml
influxdb2_client/src/lib.rs
influxdb_iox_client/Cargo.toml
mutable_buffer/Cargo.toml
object_store/Cargo.toml
object_store/src/azure.rs
object_store/src/gcp.rs
object_store/src/lib.rs
panic_logging/src/lib.rs
query/Cargo.toml
query/src/exec.rs
query/src/exec/schema_pivot.rs
query/src/exec/seriesset.rs
server/Cargo.toml
server/src/lib.rs
src/influxdb_ioxd.rs
src/influxdb_ioxd/http_routes.rs
src/influxdb_ioxd/rpc/service.rs
src/main.rs
wal/Cargo.toml

chore: update deps (tokio 1.0 and ecosystem)

---

Cargo.lock
arrow_deps/Cargo.toml
data_types/src/schema.rs
query/src/exec/schema_pivot.rs
query/src/func/selectors.rs

This time to pick up the latest and greatest DataFusion / Arrow (and the HAVING clause recently contributed by @drusso) https://github.com/apache/arrow/pull/9364 🎉 
Also doing this  frequently means updating our code based on the underlying DataFusion API changes are less painful

chore: Update deps again

---

query/src/lib.rs
query/src/test.rs
server/src/config.rs
server/src/lib.rs
src/influxdb_ioxd/http_routes.rs

Part of #722
TODO in another PR
> Also add this to the influxdb_iox_client crate
rust noob here, please be ruthless so I can learn

feat: Implement list databases API

---

query/src/frontend/sql.rs
query/src/lib.rs
query/src/provider.rs

Implement PR suggestions from @carols10cents on: https://github.com/influxdata/influxdb_iox/pull/730#pullrequestreview-582657061

fix: Improve code, comments and error messages for consistency

---

object_store/src/aws.rs
object_store/src/azure.rs
object_store/src/disk.rs
object_store/src/gcp.rs
object_store/src/lib.rs
object_store/src/memory.rs
object_store/src/path/file.rs
object_store/src/path/parsed.rs

Fixes #688 and does a bit of refactoring because the error enum was getting out of hand.

feat: list_with_delimiter for file-based object storage

---

data_types/src/lib.rs
data_types/src/schema.rs
mutable_buffer/src/chunk.rs
mutable_buffer/src/database.rs
query/src/exec.rs
query/src/frontend/influxrpc.rs
query/src/lib.rs
query/src/plan.rs
query/src/plan/stringset.rs
query/src/test.rs
read_buffer/benches/database.rs
read_buffer/src/lib.rs
server/src/db.rs
server/src/db/chunk.rs

This is a new version of https://github.com/influxdata/influxdb_iox/pull/759 (same code, but github lost the connection to the branch somehow -- I may have screwed it up). This is the same PR content https://github.com/influxdata/influxdb_iox/pull/759

feat: Change table_names to return either Some(set) or None, rather than a plan (try 2)

---

object_store/src/path/file.rs

Found this `todo`, was faster to make a fix than an issue ;)

feat: Implement display on FilePath

---

data_types/src/http.rs
influxdb_iox_client/src/client.rs
src/influxdb_ioxd/http.rs

Closes #767
This will likely be undone as part of https://github.com/influxdata/influxdb_iox/issues/725#issuecomment-776095439
but I was still curious to see how it would look like.

feat: Implement database list API in the client.

---

.kodiak.toml

Enabling kodiak (see biased comparison table at https://kodiakhq.com/docs/prior-art-and-alternatives).
It's a light-weight merge bot, with seamless integration with common merge workflows people like us use natively GitHub.
Once enabled, it waits until somebody adds the `automerge` label. Once set, it will wait until all other checks are green (honouring every knob that GitHub offers, from CI statuses to reviewer configs, etc) and then add it to the merge queue (in FIFO order). Before merging it will sync to main. After merging or failing to merge it will move to the next PR in the queue.
Notable differences from bors (and its descendants, such as alchemy): It doesn't batch commits into a "staging" branch and you don't chat with it via PR comments.
There are a few [configuration …

chore: Add kodiak config

---

src/commands/config.rs

fix: Make --api-bind et.al. support localhost

---

Cargo.lock
Cargo.toml
influxdb_iox_client/Cargo.toml
influxdb_iox_client/README.md
influxdb_iox_client/src/builder.rs
influxdb_iox_client/src/client.rs
influxdb_iox_client/src/client/flight.rs
influxdb_iox_client/src/errors/grpc_error.rs
influxdb_iox_client/src/errors/grpc_query_error.rs
influxdb_iox_client/src/errors/http_error.rs
influxdb_iox_client/src/errors/mod.rs
influxdb_iox_client/src/lib.rs
tests/end_to_end_cases/flight_api.rs

feat: Add an optional Flight client to the IOx client library

---

read_buffer/src/lib.rs

This is part of the "making tag_column_names work in gRPC"  https://github.com/influxdata/influxdb_iox/issues/791
Follows the model set in https://github.com/influxdata/influxdb_iox/pull/776 where the `ReadBuffer` responds to metadata queries with the native Rust types and the conversion to `RecordBatch` is done higher up (in the planner).
This rationale for that design is to allow efficient merging known good results across chunks without running an entire plan
Change ReadBuffer `column_names` to return `Option<BTreeSet>` and update tests.

refactor: Change ReadBuffer column_names to return Option<BTreeSet>

---

server/src/buffer.rs
server/src/config.rs
server/src/db.rs
server/src/db/chunk.rs
server/src/db/streams.rs
server/src/lib.rs
server/src/snapshot.rs
server/src/tracker.rs

I missed the `server` crate in #807.

refactor: apply clippy clone lint

---

.circleci/get-deploy-tags.sh

Change the `get-deploy-tags.sh` to use `docker image inspect` with specific image name and tag specified to simplify the script.

chore: use docker image inspect in get-deploy-tags.sh

---

Cargo.lock
arrow_deps/Cargo.toml
query/src/frontend/sql.rs
query/src/func/selectors.rs

Closes #
This is my first PR and may miss many steps. I will sit down and talk with Edd today about this

chore: update Arrow dependencies

---

read_buffer/src/lib.rs
read_buffer/src/row_group.rs
server/src/query_tests/scenarios.rs

Closes #820.
Needs #819 to merge first.

refactor: enable string fields in read buffer

---

object_store/src/buffer.rs

Address post-merge review comment https://github.com/influxdata/influxdb_iox/pull/830#pullrequestreview-594746695

docs: Fix typo

---

Cargo.lock
Cargo.toml
ingest/Cargo.toml
ingest/src/lib.rs
logfmt/Cargo.toml
logfmt/tests/logging.rs
query/Cargo.toml
query/src/test.rs
server/Cargo.toml
server/src/buffer.rs
server/src/db.rs
server/src/lib.rs
server/src/snapshot.rs
server/src/tracker.rs
src/commands/config.rs
src/influxdb_ioxd/http.rs
test_helpers/Cargo.toml
test_helpers/src/tracing.rs
wal/Cargo.toml

refactor: Use parking_lot::Mutex instead of std::sync::Mutex

---

Cargo.lock
object_store/Cargo.toml
object_store/src/gcp.rs

Closes #764.
The cloud-storage-rs crate needed to be changed to support this; I have a PR open with them and am using a forked version for now pending feedback/merge. 
I've opened https://github.com/influxdata/influxdb_iox/issues/801 to track updating to a released version.

feat: Implements list_with_delimiter for Google Cloud 

---

docs/env.example
object_store/src/lib.rs

And fix env.example. Now GCS can be used to persist snapshots.
Tracking issue #808

feat: Plug GCS list_with_delimiter impl

---

src/influxdb_ioxd/http.rs

Partially implements #726
TODO in another PR: `format` parameter. This PR implements the pretty print format.

feat: Implement /iox/api/v1/databases/:name/query?q=

---

docs/env.example

docs: Include INFLUXDB_IOX_OBJECT_STORE in env.example

---

Cargo.lock
Cargo.toml
src/commands/database.rs
src/commands/writer.rs
src/influxdb_ioxd.rs
src/main.rs
tests/commands.rs
tests/end-to-end.rs
tests/end_to_end_cases/management_cli.rs
tests/end_to_end_cases/mod.rs

An MVP CLI implementation for the management API. I fully anticipate this will need further extension to accommodate the requirements for initial IOx deployments, but it is a start.
Related to #889

feat: MVP Management CLI

---

influxdb_iox_client/src/lib.rs

fix: build of influxdb_iox_client with flight disabled

---

README.md
scripts/grpcurl

docs: Document how to use grpcurl to play with API

---

README.md

minor doc rendering improvement

docs: Use console type for interactive shell snippets

---

tests/common/server_fixture.rs

A pragmatic fix for #952: since we already set the server id in `wait_until_ready`,
let's start a test server without an ID (by not passing `INFLUXDB_IOX_ID`)
and use the property of already having an ID as an indication that we're talking
to a server instance that we didn't just start.
It doesn't necessarily mean we're talking to the right server, but the main point
of #952 was to avoid confusing error messages like "DatabaseAlreadyExists";
with this PR, the only way for that error to confuse developers is if we "unset" the
writer ID of a server fixture and leave it there hanging, with in-memory side effects
but no ID. Possible but unlikely, I think.
Closes #952

test: Detect if talking to the wrong test server

---

query/src/lib.rs
query/src/test.rs
server/src/lib.rs
src/influxdb_ioxd/http.rs
src/influxdb_ioxd/rpc/flight.rs
src/influxdb_ioxd/rpc/management.rs
src/influxdb_ioxd/rpc/storage/service.rs

Following on from #837 - remove async from some further methods

refactor: remove unnecessary async from DatabaseStore trait

---

Cargo.lock
Cargo.toml
src/commands/server.rs
src/commands/server_remote.rs
src/main.rs
tests/end_to_end_cases/management_cli.rs

Closes #917; spilling minor leftover in #969 (implementing --verify flag)

feat: Add server remote [set|remove|list] commands

---

influxdb2_client/README.md

In order to encourage more contributions (like the great one from @aakashhemadri https://github.com/influxdata/influxdb_iox/pull/988) we should be clearer about the goals and expectations for the influxdb_iox client. 
Add a README that explains what `influxdb_iox` client is and our goals

docs: Add README for influxdb_client

---

Cargo.lock
Cargo.toml
data_types/Cargo.toml
data_types/src/job.rs
generated_types/src/lib.rs
influxdb_iox_client/Cargo.toml
influxdb_iox_client/src/client.rs
influxdb_iox_client/src/client/management.rs
influxdb_iox_client/src/client/operations.rs
influxdb_iox_client/src/lib.rs
src/commands/operations.rs
src/influxdb_ioxd/rpc/operations.rs
src/main.rs
tests/common/server_fixture.rs
tests/end_to_end_cases/mod.rs
tests/end_to_end_cases/operations_api.rs
tests/end_to_end_cases/operations_cli.rs

~Still needs tests, creating as a draft for the adventurous~
This should now be good for review

feat: add longrunning operations client

---

Cargo.lock
data_types/Cargo.toml
data_types/src/job.rs
server/src/lib.rs
server/src/tracker.rs
server/src/tracker/history.rs
server/src/tracker/registry.rs
tests/end_to_end_cases/operations_cli.rs

Builds on top of #1004 and adds a TrackerArchive that retains a limited history

feat: retain limited tracker history

---

docker/Dockerfile.ci

Install lld to allow #1022 and remove musl as it's not needed

chore: install lld in CI image and remove musl

---

data_types/src/database_rules.rs
generated_types/build.rs
generated_types/protos/influxdata/iox/management/v1/shard.proto

Part of #919
Mostly mechanical mapping between protobuf and internal rust types.

feat: Add API for ShardConfig

---

Cargo.lock
arrow_deps/Cargo.toml
influxdb_tsm/src/mapper.rs
ingest/src/lib.rs
ingest/src/parquet/writer.rs

Closes #167 (but I'm unsure if I've covered everything needed, I checked where we convert nano to micro in the code)

refactor: write nanosecond timestamps to parquet

---

server/src/db.rs
server/src/db/catalog.rs
server/src/db/catalog/chunk.rs
server/src/lib.rs
server/src/query_tests/sql.rs
src/influxdb_ioxd/http.rs
src/influxdb_ioxd/rpc/error.rs
src/influxdb_ioxd/rpc/flight.rs

This was a temporary hack, now that #1057 is merged we can remove it :grin:

refactor: remove DbCatalog newtype wrapper

---

data_types/src/database_rules.rs

A zero value for these fields implies that there is no limit, or that no automated lifecycle should be performed. Encoding them as optional non-zero types makes this explicit and avoids silly classes of bugs where 0 is not special-cased.
As Non zero types have a niche for option, they are still the same size

refactor: use optional non-zero types

---

server/src/db.rs
server/src/db/catalog.rs
server/src/db/catalog/chunk.rs
server/src/db/catalog/partition.rs
server/src/db/chunk.rs
src/influxdb_ioxd/rpc/error.rs

Adds logic to automatically close chunks. Also contains some other miscellaneous cleanup that I'm happy to submit as a separate PR if necessary

feat: automated chunk closing

---

Cargo.lock
influxdb_iox_client/Cargo.toml
influxdb_iox_client/src/client/operations.rs
src/commands/operations.rs
tests/end_to_end_cases/management_api.rs
tests/end_to_end_cases/operations_api.rs

Closes #1001
@alamb This PR address all your comments including one function list_operation. I will abort the other PR because it was messed up with some unsuccessful rebase stuff

feat: make it easy to get OperationMetadata from Operation

---

server/Cargo.toml
server/src/db.rs
server/src/db/catalog.rs

This should be the last prerequisite of automated chunk movement :grin:

feat: chunk sorting

---

server/src/db.rs
server/src/db/catalog.rs
server/src/db/catalog/partition.rs
src/influxdb_ioxd/rpc/management.rs

Pushes some of the aggregation logic from Db into catalog so that it can be used by the system tables more easily.

refactor: push chunk and partition summary into catalog

---

server/src/lib.rs
src/commands/run.rs
src/influxdb_ioxd.rs
src/influxdb_ioxd/http.rs
src/influxdb_ioxd/rpc/management.rs
tests/common/server_fixture.rs
tests/end_to_end_cases/management_cli.rs
tests/end_to_end_cases/read_cli.rs

Makes the writer id write once - to allow it to be copied into Db

feat: write once writer id

---

src/influxdb_ioxd/rpc/flight.rs

Workaround for #1133
Not sure if it's a good idea long term.
This heuristic is far too simple to be reasonable in all possible cases.
However, currently it does solve the extreme cases, for example like #1133 where an innocuous `select * from http_api_requests_total limit 1;` can take tens of seconds to execute.
The idea here is that such queries are frequent in an exploratory setting, where developers play with the system to see
how some simple queries behave; it may be useful to have a shortcut optimization for that use case until we figure out a better way.
Tested locally. Not on the real data of #1133, so I don't have a time measurement, but I did log the sizes of the flatbuffer payloads received by the client and indeed they are now proportional to the size of the limit (for small …

fix: Deep clone small results over flight

---

.circleci/config.yml
Cargo.lock
docs/testing.md
influxdb2_client/Cargo.toml
influxdb2_client/src/api/ready.rs
influxdb2_client/src/api/setup.rs
influxdb2_client/src/lib.rs
influxdb2_client/tests/common/mod.rs
influxdb2_client/tests/common/server_fixture.rs
influxdb2_client/tests/setup.rs

Ok, I think this is working now. What do you think?

chore: Add integration tests for influxdb2_client against InfluxDB 2.0 OSS

---

Cargo.lock
object_store/Cargo.toml
object_store/src/gcp.rs

This should improve but likely not fully address #551

chore: update cloud-storage to 0.9

---

docs/regenerating_flatbuffers.md
generated_types/regenerate-flatbuffers.sh

This reverts commit 0efc1d81746f49a3f89e0287b859f1605d27434e, reversing
changes made to a3e04fecc1c2e698ed0ec9c60017cb19027aeffe.
@e-dard I'll redo your doc changes and add more clarification to the docs about when this needs to be update in another PR :)

chore: Revert "Merge pull request #1159 from influxdata/er/flatbuffers"

---

server/src/db.rs

fix: check filename to have deterministic output

---

docs/regenerating_flatbuffers.md
generated_types/regenerate-flatbuffers.sh

@e-dard this reintroduces the commit to the docs you made in the PR that I reverted. I've also tried to clarify how and when to use or change this script, does this help? Do you have any other suggestions?

docs: Clarify regeneration of flatbuffers

---

Cargo.lock
mutable_buffer/Cargo.toml
mutable_buffer/src/chunk.rs

Basic caching of mutable buffer snapshots

feat: basic snapshot caching

---

data_types/src/database_rules.rs
data_types/src/job.rs
generated_types/protos/influxdata/iox/management/v1/database_rules.proto
generated_types/protos/influxdata/iox/management/v1/jobs.proto
server/src/db.rs
server/src/db/lifecycle.rs
src/commands/database.rs

feat: RB -> OS lifecycle

---

query/src/exec/task.rs

fix: Remove mutex acquisition in impl `std::fmt::Debug` for DedicatedExecutor
There is some concern on https://github.com/influxdata/influxdb_iox/pull/1191/files#r612617526 that locking during a debug impl could cause lock contention. Given the value of the information in this `Debug` impl is pretty low, this PR proposes removing the content that needs a lock entirely to avoid any question
Remove content that needs a lock entirely to avoid any possible locking contention

fix: Remove mutex acquisition in impl `std::fmt::Debug` for DedicatedExecutor

---

server/src/db/chunk.rs

Closes #857
Maximise utilisation of the Read Buffer and unlock the hawtness!
Really though, just connect the optimised Read Buffer `tag_values` implementation up to the InfluxRPC frontend 😄 
Here are the relevant improvements to the benchmarks I added to IOx in #1192. (Anything that didn't change by 5% is not shown).
```
group                                                                                master                                 read_buffer
-----                                                                                ------                                 -----------
Data in open chunk of mutable buffer, and one chunk of read buffer/tag0/no_pred      2.19    106.9±4.25ms        ? ?/sec    1.00     48.9±2.15ms        ? ?/sec
Data in open chunk of mutable buffer, and …
```

perf: use column_values in read buffer

---

Cargo.lock
read_buffer/Cargo.toml
read_buffer/src/chunk.rs
read_buffer/src/table.rs
server/src/db.rs

Not much to say, I've been meaning to do this for weeks.

refactor: use parking lot in the Read Buffer

---

Cargo.lock
data_types/src/database_rules.rs
generated_types/protos/influxdata/iox/management/v1/shard.proto
internal_types/src/entry.rs
server/Cargo.toml
server/src/lib.rs

Part of #916
Adding first-class concept of ShardId in shard config, fixes #1156
NEXT:

feat: Initial scaffolding for routing layer

---

generated_types/src/google.rs
server/src/db.rs
server/src/lib.rs
src/influxdb_ioxd/rpc/error.rs
tests/end_to_end_cases/scenario.rs
tests/end_to_end_cases/write_api.rs

feat: wire up hard buffer limit

---

.circleci/config.yml
docker/Dockerfile.ci

chore: update circle job

---

Cargo.lock
mutable_buffer/Cargo.toml
mutable_buffer/benches/snapshot.rs
mutable_buffer/benches/write.rs

Adds two very basic read/write benchmarks to the MUB

feat: MUB benchmarks (#635)

---

src/influxdb_ioxd/http.rs

feat(iox): Log write points errors at debug level

---

server/src/db.rs

I got the new chunk metric in _slightly_ the wrong place and it was over-counting whenever there was a write into an already-open chunk.

fix: don't over count new chunks

---

src/commands/tracing.rs
src/main.rs

Closes #1288
__Rationale__
`tracing::subscriber::set_default` only sets the subscriber for the current thread.
However, we're using multi-threaded tokio runtime, which means that most of the threads running
async code won't inherit the tracing subscriber, which means error/info/debug... logs won't be emitted!
To make things even more confusing, some logs do work (because they just happen to run in the same thread
that called `subscriber::set_default`.
__Change__
This PR makes us call `subscriber::set_global_default`.
This call can only be called once and is meant to be invoked by the main program (not by libraries).
It preserves the `TracingGuard` type, but now it's only used to flush the opentelemetry stuff.
----

fix: Set a global log/tracing subscriber

---

object_store/src/lib.rs
object_store/src/throttle.rs
src/commands/run.rs
src/influxdb_ioxd.rs

Useful for benchmarking (esp. compression VS transfer rates) w/o relying on / spamming external systems.

feat: throttled stores

---

internal_types/src/arrow.rs
internal_types/src/arrow/sort.rs
internal_types/src/lib.rs
server/src/db.rs

Closes #216
Builds on top of #1289 and #1262 and pre-sorts data before upserting it to the read buffer

feat: sort RUB (read buffer) chunks

---

docs/README.md
docs/catalog_persistence.md

**Note: It's just a copy of the pre-discussed google doc converted to markdown, so no surprises.**
Closes #1219.

docs: add design docs for catalog persistence

---

metrics/src/lib.rs
metrics/src/metrics.rs
metrics/src/tests.rs

This PR adds a Histogram metric type to the metrics crate, resulting in Prometheus histograms (which are not samples).
The histogram metric type is good for tracking latencies and other per-request or per-operation side-effects that are best handled as a distribution. 
*TODO* - I can't figure out how to set the per-metric bucket boundaries so I suggest that gets added in a future PR. For now I have left some code commented out and all Histogram metrics will use the default buckets, which should be OK at least for request latencies.

feat: add Histogram metrics to metrics crate

---

server/src/lib.rs

__Rationale__
Only the routing layers see LP writes. The routing layer then converts batches of `LP` into `Entry`es, which
get processed and stored locally or sent to other nodes downstream (e.g. to nodes of the Write Buffer layer).
The `ingest_entries_bytes_total` is like `ingest_points_bytes_total` but it measures the size of the Entry flatbuffers blobs, instead of the line protocol.

feat: Add ingest_entries_bytes_total counter

---

.circleci/config.yml

fix(ci): Push each image into its own tag

---

metrics/src/tests.rs

docs: Fix typo in comment

---

server/src/db.rs

Metrics can have default labels set on them, which will be used for all observations. This PR removes an explicit field that was storing them in the catalog - they can just be set on each metric at initialisation time.

refactor: include default labels

---

Cargo.lock
Cargo.toml
server/Cargo.toml
server/src/lib.rs

not sure how to define the metric. independent metrics, big metric with tags like these?
should the metric be jemalloc specific (after all, most of these facets are jemalloc specific)

feat: Add jemalloc stats

---

Cargo.lock
docs/catalog_persistence.md
generated_types/build.rs
generated_types/protos/influxdata/iox/catalog/v1/catalog.proto
generated_types/src/lib.rs
object_store/src/path.rs
object_store/src/path/parsed.rs
parquet_file/Cargo.toml
parquet_file/src/catalog.rs
parquet_file/src/lib.rs

feat: implement transaction handling for catalog

---

query/src/frontend/influxrpc.rs
read_buffer/src/chunk.rs

Adds column count to log lines. Tidies up some spelling.

refactor: spelling and log info

---

src/commands/sql/repl_command.rs

The if/ else if chain in SQL repl command matching is less than pleasant to read
As suggested by @domodwyer on https://github.com/influxdata/influxdb_iox/pull/1404#discussion_r625866599, use slice patterns to make the code easier to read.

refactor: Use slice patterns for CLI command matching 504f530

---

server/src/db.rs
server/src/db/catalog.rs
server/src/db/catalog/partition.rs
server/src/db/lifecycle.rs

Alters the catalog to instead store instrumented read-write locks. Once #1414 is merged I will hook them up :smile:

feat: instrument catalog locks (#1355)

---

parquet_file/src/storage.rs

This is the same fix I made in 54c5f98, just found a few more spots :)

fix: Use PathBuf rather than debug formatting and back to String

---

server/src/lib.rs

Closes #1450
Longer term, we should use a more sensible object store layout so we don't have to do this kind of contortions.
This hack is needed now because we need to be able to delete S3 files in our staging environment. The current tooling can't spare old rules.pb files, so it's quite possible that we'll hit #1450 soon.

fix: Load only databases for which a config exists

---

Cargo.lock
arrow/Cargo.toml
arrow_flight/Cargo.toml
datafusion/Cargo.toml
parquet/Cargo.toml

chore: upgrade arrow and datafusion

---

parquet_file/src/catalog.rs
parquet_file/src/lib.rs
parquet_file/src/metadata.rs
parquet_file/src/storage.rs
parquet_file/src/storage_testing.rs
parquet_file/src/utils.rs
server/src/db.rs
server/src/query_tests/utils.rs

Closes #1342
Due to some conflicts, @carols10cents and I decided to create a new branch and do cherry-pick instead of trying headache rebase

feat: we now can read parquet files from all kind of object stores

---

server/src/lib.rs
src/influxdb_ioxd/http.rs

The existing `ingest_lines_total` metric counts lines (which apparently are the same as points, quite confusingly).
LP lines can have multiple fields, which can be a useful metric.
No yaks harmed in the making of this PR.
(NOTE: the code around metric, especially dealing with happy and error paths is very painful;
to be done in another PR)

fix: Add ingest_fields_total

---

docs/profiling.md

Implement suggestions from @mkmik on https://github.com/influxdata/influxdb_iox/pull/1520#discussion_r635264353

docs: tweak profiling.md

---

server/src/lib.rs

Context: https://github.com/influxdata/k8s-idpe/issues/3339

feat: Log cached connections

---

src/influxdb_ioxd/rpc.rs

__Rationale__
With the current gRPC registration code it's easy to forget to register the service to the health reporter.
__This change__
The service builder build a heavily type parameterised chain of types,
and I didn't find a way to write generic "add_service" code that wasn't a macro.
Perhaps somebody has a better idea.
__Next steps__
I want to make it easier for services themselves to update their health status, but before doing that I wanted to make sure all the services we register are indeed hooked up.

fix: gRPC health reporter registration

---

mutable_buffer/src/chunk.rs

re: https://github.com/influxdata/influxdb_iox/issues/1295
Removing dead code

refactor: remove MutableChunk::has_table

---

src/influxdb_ioxd.rs

feat: log jemalloc build conf

---

Cargo.lock
parquet_file/Cargo.toml
parquet_file/src/catalog.rs
parquet_file/src/metadata.rs
parquet_file/src/storage.rs
parquet_file/src/storage_testing.rs
parquet_file/src/utils.rs
server/src/db.rs

feat: preserve transaction metadata in parquets

---

mutable_buffer/src/chunk/snapshot.rs
server/src/db/chunk.rs

re https://github.com/influxdata/influxdb_iox/issues/1295
Was having a brief play with storing just the ChunkSnapshot as the closed state and realised the ChunkSnapshot hadn't been de-tablified yet so thought I'd get that in

refactor: remove tables from ChunkSnapshot (#1295)

---

server/src/db/lifecycle.rs

This is taking up a significant amount of CPU time - see #1561 and is unnecessary.

feat: don't recompute chunk size on every iteration

---

server/src/db.rs

fix: fix confusing log message during catalog replay

---

src/influxdb_ioxd/http.rs

To help with https://github.com/influxdata/k8s-idpe/issues/3442

feat: Add more details to WritePoints error log

---

src/influxdb_ioxd/http.rs

fix: Log more details on http errors

---

query/src/exec/context.rs
query/src/provider.rs
server/src/db/chunk.rs
server/src/query_tests/sql.rs

Closes #
This are tests for #1538. This will be useful for the deduplicate work #600, too

refactor: macro and tests for explains

---

server/src/lib.rs

There are not functional changes here (except that errors look slightly
different) but it should allow for an easier move of the DB loading into
a delayed task.

refactor: isolate DB loading and streamline error handling

---

mutable_buffer/src/chunk/snapshot.rs
parquet_file/src/chunk.rs
server/src/db.rs
server/src/db/chunk.rs

re #1295
Remove more vestigial code from the time when chunks could have multiple tables
https://xkcd.com/303/

refactor: More cleanup related to multi-table chunks

---

server/src/db/chunk.rs
server/src/query_tests/scenarios.rs
server/src/query_tests/sql.rs

These are tests for the deduplicate work of #600

test: prepare tests for deduplicate work

---

docs/sql.md

Add a system table query I wanted to run but had to dig out of my archives to the docs so I can find it easily again

docs: add query for computing time ranges to cookbook

---

tests/end_to_end_cases/management_api.rs

chore: fix flaky test

---

entry/src/entry.rs
server/src/db.rs

Some small refactorings and rearranging that should be trivial to review and will make it easier to add the write buffer.

refactor: Preparations for optional Kafka write buffer

---

parquet_file/src/storage.rs

I wasn't thrilled (https://github.com/influxdata/influxdb_iox/pull/1580#discussion_r641807009)  with the extra layer of channels when I originally wrote this. I found a better pattern in https://github.com/apache/arrow-datafusion/pull/521
This is entirely a code cleaniless issue. No expected user noticable impact
1. Remove a set of channels and send the error directly to the output channel

refactor: Remove a layer of channels in parquet read stream

---

data_types/src/database_rules.rs
entry/src/entry.fbs
entry/src/entry.rs
generated_types/protos/influxdata/iox/management/v1/database_rules.proto
generated_types/src/database_rules.rs
server/src/config.rs
server/src/db.rs
server/src/lib.rs
server/src/utils.rs
server/src/write_buffer.rs
tests/end_to_end_cases/management_api.rs

This starts a trait for the functionality of the write buffer and implements it with a mock write buffer in unit tests.

feat: Mock write buffer + trait

---

data_types/src/partition_metadata.rs
query/src/duplicate.rs

As suggested by @NGA-TRAN https://github.com/influxdata/influxdb_iox/pull/1654#discussion_r647544068
re https://github.com/influxdata/influxdb_iox/issues/1645

refactor: move primary_key calculation to TableSummary

---

query/src/provider.rs

Implement suggestion from @NGA-TRAN at https://github.com/influxdata/influxdb_iox/pull/1662#discussion_r647712225
Also, my editor removes whitespace at the end of line by default so I figured I would check those changes in as well

docs: Improve comments + whitespace

---

server/src/init.rs
server/src/lib.rs
src/influxdb_ioxd/http.rs
src/influxdb_ioxd/rpc/error.rs
src/influxdb_ioxd/rpc/management.rs

This prepares for #1624, so the end results looks a bit cleaner.
This just moves code around a bit, functionality should be the same.

refactor: extract server init code

---

Cargo.lock
generated_types/protos/influxdata/iox/catalog/v1/catalog.proto
parquet_file/src/catalog.rs
parquet_file/src/cleanup.rs
parquet_file/src/rebuild.rs
server/src/db.rs
server_benchmarks/Cargo.toml
server_benchmarks/benches/catalog_persistence.rs
server_benchmarks/benches/influxrpc.rs

First step towards #1381.
**Note that this does NOT wire up the functionality into the actual DB. I leave that for an upcoming PR.**

feat: catalog checkpointing infrastructure

---

server/src/lib.rs
src/influxdb_ioxd/planner.rs
src/influxdb_ioxd/rpc/operations.rs
src/main.rs

chore: enforce `clippy::future_not_send` for `server` + top-level crate

---

server/src/config.rs
server/src/init.rs
server/src/lib.rs
src/influxdb_ioxd/rpc/management.rs
tests/common/server_fixture.rs
tests/end_to_end_cases/management_api.rs

feat: expose server and DB init errors over gRPC

---

query/src/exec.rs
src/influxdb_ioxd/rpc/storage/service.rs

Reverts influxdata/influxdb_iox#1706
Backing this out as it's very noisy (even for debug level) and not needed any longer

refactor: revert "refactor: read_filter debugging"

---

trogging/src/cli.rs
trogging/src/lib.rs

This PR moves the definition of the `log_filter` default value from the `structopt` annotation
to the `trogging::Builder`. This allows users of `trogging` to define their own default value
for the log level.

chore: Allow custom default log filter

---

parquet_file/src/chunk.rs
parquet_file/src/metadata.rs
parquet_file/src/storage_testing.rs
server/src/db/catalog/chunk.rs

I found more code that was not being used while working on schema tests (and waiting to compile) so remove that too

chore: remove more dead code

---

mutable_buffer/src/chunk/snapshot.rs

I found this code laying around unused so I figured I would delete it

refactor: delete unused code

---

lifecycle/src/guard.rs
lifecycle/src/lib.rs
lifecycle/src/policy.rs

chore: lint `lifecycle` crate

---

trogging/src/cli.rs
trogging/src/config.rs
trogging/src/lib.rs

We clearly need a linter rule that checks whether those linting rules are defined in our crates

chore: Add our linting rules to the trogging crate

---

logfmt/src/lib.rs

The is no specification logfmt, most implementations only unescape `\"` and leave
`\n` as is when parsing. Some implementations like go-logfmt do escape newlines as `\n` (and other chars
according to Go's escaping rules).
This PR just escapes non-printable characters using rust's string literal rules; they are not perfect but
they don't seem to be worse than other players.
(If this bites us some more we will probably be better of switching to json log output format and then equip ourselves with some simple shell scripts to reformat the logs on the fly while we're streaming them from k8s)
As a bonus point, this effectively simplifies the escaping code, possibly also speeding it up a bit
since it doesn't have to call replace twice (although I don't know what magic would the rust compiler …

fix: Escape non-printable characters in logfmt

---

CONTRIBUTING.md
README.md

chore: update CONTRIBUTING with instructions for running and debugging end-to-end tests

---

trogging/src/lib.rs

In #1796 @tustvold raised the concern that with the deferred filtering decision employed by `FilteredLayer` approach, all the arguments in a logging macro will be evaluated before we decide to filter it out.
This PR adds a test that ensures that PRs like #1796 don't accidentally introduce this kind of regression.
I'll fix #1796 so that it passes this test.

test: Ensure disabled logs don't eval args

---

query/src/frontend/reorg.rs

re https://github.com/influxdata/conductor/issues/360
As pointed out by @tustvold on https://github.com/influxdata/influxdb_iox/pull/1794#discussion_r658149400 the split_plan should also sort its output (the comments even say it does!)
1. Sort output of split_plan by user provided key

feat: Sort the output of split_plans as well

---

trogging/src/lib.rs

This is a horrible hack to fix #1806
We're currently corrupting a measurable fraction of our logs, and we disabled the verbose debug logs, so we're not causing immediate grief to graylog, but still.
```console
$ kubectl logs deploy/iox-router-1001 -c iox | tee /tmp/logs \
| awk -F 'level=' '{print (NF?NF-1:0)}' \
| sort | uniq -c
234 0
57422 1
230 2
2 3
```
---
The longer term plan for this is still to be defined. A new release of the `tracing-subscriber` crate would allow a better fix. We could depend on the unreleased crate, or do something else.

fix: Increase line buffer to avoid frequent interleaved logs

---

read_buffer/src/column/string.rs

Something to try and help debug an issue we are seeing in a cluster.

refactor: logging

---

.editorconfig

chore: add indent to editorconfig

---

trogging/src/lib.rs

When the log lines are very long and we truncated them, the trailing newline also gets truncated. This PR ensures that the single write syscall that writes a log line includes the trailing `'\n'`; It does so in a very barbaric way because I don't know a better way. Lines longer than 16KB should be very rare so the extra allocation shouldn't matter in practice. But even if the even is rare, the failure to handle this case properly can cause grief.
(The issue of log line truncation doesn't depend on the log format; even if we switch to json it's still be something we need to deal with)
__Context__
Docker "chunks" log message in 16KB chunks. The log driver receives log lines in such chunks but not all of the log drivers properly recombine the lines, and even those who do have their own max …

fix: Fix trailing newline emission in case of truncated log line

---

server/src/db.rs

`store_sequenced_entry` loops over each `partitioned_write` part of a `sequenced_entry` like this:
```
if let Some(partitioned_writes) = sequenced_entry.partition_writes() {
for write in partitioned_writes {
...
```
then for each table in each write, it gets or creates the partition from the catalog that the write should go in, gets a write lock to the partition, gets or creates an open chunk in the partition, gets the mutable buffer for that chunk, and writes a table batch-- which can fail and return out of the whole loop. 
So if adding a table batch into the mutable buffer fails, whatever writes *before* that batch in the `SequencedEntry` will have been written, and the ones *after* that batch won't be attempted.
In other words:
If we have a batch of writes and there is an error writing …

fix: Try all partition_writes even if one in the middle fails

---

mutable_buffer/src/chunk/snapshot.rs

As of #1570 the chunk snapshot no longer shares a dictionary between columns, however, its size calculation thought it still did. This is likely the cause of the panic in #1820

fix: remove shared dictionary concept from ChunkSnapshot (#1570) (#1820)

---

arrow_util/src/dictionary.rs
arrow_util/src/lib.rs
arrow_util/src/optimize.rs
arrow_util/src/string.rs
mutable_buffer/src/column.rs

feat: add ability to optimize record batch dictionaries (#1827)

---

read_buffer/benches/database.rs
read_buffer/src/chunk.rs
server/src/db/chunk.rs

Closes #1716
A Read Buffer chunk now only contains data for a single table. Therefore `table_names` didn't make sense any longer. `table_names` was a specialised physical operation that could be used by certain InfluxData meta-queries. 
I have renamed `table_names` to `satisfies_predicate`, which will return `true` if at least one row in the chunk satisfies the predicate.
For the moment a DB Chunk's `apply_predicate_to_metadata` will use `satisfies_predicate`, which will allow it to get a precise answer (for predicates supported by the Read Buffer), but should probably be replaced by something that interrogates meta-data only (since `satisfies_predicate` could be relatively expensive in pathological cases).
I think that when we implement …

refactor: remove table_names from Read Buffer

---

server/src/db/load.rs
server/src/lib.rs

When a DB is created AFTER the server is initialized, then we can assume
it is a new DB (because the rules file did not exist beforehand). We
shall treat it as a new DB with no data and should not try to load some
leftover / stale / whatever preserved catalog for it. How this catalog
came into existence we do not know and it was certainly not properly
managed by IOx. So we error if there is a catalog.
Furthermore the old implementation was kinda broken since it loaded the
perserved catalog "in-sync" with the gRPC call that issued the DB
creation (we only have a delayed init concept for DBs that are loaded on
instance startup). In production that would very likely provoke nasty
timeouts.
On top of that this new behavior will also be somewhat more sane when we
think about sequencer (e.g. …

feat: do NOT load preserved catalogs on late DB creation

---

lifecycle/src/policy.rs

Once persistence needs to operate on potentially multiple chunks it creates a situation where one of the criteria to persist has been met, but it is unable proceed because of in-progress compactions on one or more of the source chunks.
This PR therefore does two things:
* It pulls the partition loop out of `maybe_*` into a single loop
* Adds a boolean return that `maybe_persist_chunks` can use to indicate that compaction should be stalled
This currently isn't a problem as persistence currently only operates on a single chunk, and the decision to persist a chunk takes place before the decision to compact it

refactor: plumbing to prevent compaction starving persistence

---

src/influxdb_ioxd/rpc/flight.rs

Closes #1847
Currently _all_ gRPC errors are being logged at the `error!` level. This level is inappropriate for anything other than situations where operator-intervention is required (the server is on fire type events). 
This PR imrpoves the situation by deciding how to log gRPC errors based on the error condition. Of note, I explictly used a match on the `Error` enum to ensure the compiler will ask anyone adding new error variants to decide how they should be logged.
I tested this change locally:
```
INFLUXDB_IOX_ID=42 LOG_FILTER=debug RUST_LOG=debug ./target/debug/influxdb_iox run
Jun 30 11:04:35.774  INFO influxdb_iox::influxdb_ioxd: InfluxDB IOx server starting git_hash="62d3305923c9e7d1af4752f3e805c5fed7123667" num_cpus=8 build_malloc_conf="\u{0}"
Jun 30 11:04:35.775  WARN …
```

refactor: improve logging level for gRPC errors

---

data_types/src/database_rules.rs
generated_types/protos/influxdata/iox/management/v1/database_rules.proto
generated_types/src/database_rules/lifecycle.rs
src/commands/database.rs
tests/end_to_end_cases/management_api.rs

This will be used by the future persistence lifecycle

feat: add persist_age_threshold to LifecycleRules

---

Cargo.lock
data_types/src/partition_metadata.rs
entry/Cargo.toml
entry/src/entry.rs
generated_types/build.rs
generated_types/protos/influxdata/transfer/column/v1/write.proto
generated_types/src/lib.rs
internal_types/src/schema.rs
internal_types/src/schema/builder.rs
mutable_buffer/src/chunk.rs
mutable_buffer/src/column.rs
packers/src/packers.rs
parquet_file/src/metadata.rs
query/src/test.rs
server/src/lib.rs
src/influxdb_ioxd/rpc.rs
src/influxdb_ioxd/rpc/write_pb.rs

Creates a new write service using gRPC/protobuf.

feat: add gRPC listener for new write protocol

---

data_types/src/database_state.rs
data_types/src/lib.rs
generated_types/protos/influxdata/iox/management/v1/service.proto
generated_types/src/database_state.rs
generated_types/src/lib.rs
server/src/config.rs
server/src/init.rs
server/src/lib.rs
src/influxdb_ioxd/rpc/management.rs
tests/end_to_end_cases/management_api.rs

I know you want to have this as part of the system tables, but patience! That will follow next week.

feat: expose DB state in gRPC interface

---

Cargo.lock
generated_types/protos/influxdata/iox/catalog/v1/parquet_metadata.proto
mutable_buffer/src/checkpoint.rs
mutable_buffer/src/persistence_windows.rs
parquet_file/Cargo.toml
parquet_file/src/catalog.rs
parquet_file/src/metadata.rs
parquet_file/src/rebuild.rs
parquet_file/src/storage.rs
parquet_file/src/test_utils.rs
server/src/db/lifecycle/write.rs

This will be required for replay on server startup.

feat: persist part+db checkpoint in parquets and catalog

---

data_types/src/database_state.rs
generated_types/protos/influxdata/iox/management/v1/service.proto
generated_types/src/database_state.rs
server/src/config.rs
server/src/db.rs
server/src/init.rs
server/src/lib.rs

No actual replay yet, I'm waiting for #1752 to be merged.

feat: add `Replay` state to DB init

---

lifecycle/src/policy.rs

chore: Add some more tests for can_move

---

server/src/db.rs

chore: Log partition rollover

---

lifecycle/src/policy.rs

chore: Add debug logs to maybe_compact_chunks

---

entry/regenerate-flatbuffers.sh

Closes https://github.com/influxdata/influxdb_iox/issues/1891
Update script to point at new directory

fix: fix flatbuffers regeneration code

---

server/src/db.rs

fix: don't update last write time on failed writes

---

data_types/src/database_rules.rs
generated_types/protos/influxdata/iox/management/v1/database_rules.proto
generated_types/src/database_rules/lifecycle.rs
lifecycle/src/policy.rs
src/commands/database.rs

refactor: remove unused mutable_minimum_age_seconds lifecycle setting

---

src/main.rs

```text
$influxdb_iox --version
influxdb_iox 0.1.0, revision 34dcd991d36dbaaf820478da99119c63fc38f1b3
```

feat: add GIT hash to `--version`

---

generated_types/protos/influxdata/iox/management/v1/service.proto
influxdb_iox_client/src/client/management.rs
src/commands/database/partition.rs
src/influxdb_ioxd/rpc/error.rs
src/influxdb_ioxd/rpc/management.rs
tests/end_to_end_cases/management_api.rs
tests/end_to_end_cases/management_cli.rs
tests/end_to_end_cases/persistence.rs
tests/end_to_end_cases/scenario.rs

feat: add API+CLI to unload chunks

---

src/influxdb_ioxd/http.rs

Closes https://github.com/influxdata/influxdb_iox/issues/1965
Return a proper error rather than `panic!`
I also verified this error is logged as are any other errors

fix: do not panic on client hangup

---

server/src/db/catalog/chunk.rs

Closes #1938. Unfortunately, this contains only a unit test to ensure that open chunks are frozen when set_compacting is called. It would be better to have a more end-to-end integration test that ensurest his behavior, but I've confirmed by hand (with some sleeps and a hacked up end-to-end test) that this fixes it.

fix: freeze open chunk when compacting

---

server/src/write_buffer.rs

fix: Remove bad max.request.size config param

---

persistence_windows/src/checkpoint.rs
persistence_windows/src/lib.rs

chore: enable more aggressive linting for `persistence_windows` crate

---

Cargo.lock
Cargo.toml
server/Cargo.toml
server/src/config.rs
server/src/db.rs
server/src/init.rs
server/src/lib.rs
server/src/utils.rs
write_buffer/Cargo.toml
write_buffer/src/config.rs
write_buffer/src/core.rs
write_buffer/src/kafka.rs
write_buffer/src/lib.rs
write_buffer/src/mock.rs

No functional change, just moving the code around. Will start to add tests and docs in a subsequent PR.

chore: move write buffer into its own crate

---

Cargo.lock
server/src/db.rs
write_buffer/Cargo.toml
write_buffer/src/kafka.rs

chore: Add some debug logs to write buffer

---

internal_types/src/schema.rs
internal_types/src/schema/sort.rs
query/src/lib.rs
query/src/provider.rs
query/src/test.rs
server/src/db/chunk.rs

Address review comments for #1790 and add log info to catch resort if any

refactor: address review comments and add useful log info to catch resort

---

lifecycle/src/lib.rs
lifecycle/src/policy.rs
persistence_windows/src/min_max_sequence.rs
query_tests/Cargo.toml
query_tests/src/influxrpc/read_window_aggregate.rs
query_tests/src/scenarios.rs
query_tests/src/sql.rs
server/src/db.rs
server/src/db/catalog/partition.rs
server/src/db/lifecycle.rs
server/src/db/lifecycle/persist.rs
server/src/db/lifecycle/write.rs
server_benchmarks/benches/catalog_persistence.rs

No new integration tests, they will follow when the replay logic is in place as well.

feat: persist real (non-fake) part.+DB checkpoints

---

object_store/src/path.rs
parquet_file/src/chunk.rs
parquet_file/src/metadata.rs

Tightens up some SNAFU code that I saw while touching other things

refactor: clean up some SNAFU usage

---

query_tests/src/influxrpc/read_window_aggregate.rs
query_tests/src/scenarios.rs
server/src/db.rs
server/src/utils.rs

This is a leftover from #1972.

test: make TestDb lifecycle better for testing

---

server/src/db.rs
write_buffer/src/core.rs
write_buffer/src/kafka.rs
write_buffer/src/mock.rs

feat: write buffer ingestion metrics

---

persistence_windows/src/checkpoint.rs
query_tests/src/pruning.rs
server/src/config.rs
server/src/db.rs
server/src/db/load.rs
server/src/init.rs
server/src/lib.rs
server/src/utils.rs

feat: implement naive replay

---

Cargo.lock
data_types/Cargo.toml
data_types/src/consistent_hasher.rs
data_types/src/database_rules.rs

Allows Conductor to serialise these structures into JSON.
---
* feat: DatabaseRules (de)serialisation support (7d3b6bf8)
Derives serde::Serialise & Deserialise for the DatabaseRules struct and 
children.

feat: DatabaseRules (de)serialisation support

---

server/src/lib.rs
tests/end_to_end_cases/scenario.rs
tests/end_to_end_cases/write_buffer.rs

`RoutingRules` such as `RoutingConfig` and `ShardConfig` use a `Sink` to decide where to write
the entries.
The write path to the write buffer is currently implemented in the `Db` and is accessed by using the `write_local_entry`
code path. This PR simply invokes that legacy code path whenever a "kafka" `Sink` is selected.
This allows us immediately to benefit from the ability of the `ShardingConfig` to select or reject
tables and send some to kafka, some to devnull.
__Roadmap__
This PR does not allow us yet to split an input batch into mulitiple shards and send each
to a different kafka topic. For that, we'll need to pull out the write buffer code path out of
the `db` and do something similar to a ConnectionManager but for write buffers. 
That's left for the next PR(s) in the series.
I …

feat(iox): Quick&Dirty KafkaProducer sink implementation

---

parquet_file/src/test_utils.rs
persistence_windows/src/checkpoint.rs
persistence_windows/src/persistence_windows.rs
server/src/db/catalog/partition.rs
server/src/db/lifecycle/write.rs
server/src/db/replay.rs

fix: add more replay tests and sequence number collection for DB checkpoint

---

query/src/frontend/reorg.rs
query/src/provider.rs
query/src/util.rs

feat: add sort option while building scan plan  to avoid extra sort during compaction

---

lifecycle/src/policy.rs
server/src/config.rs
server/src/db.rs
server/src/db/lifecycle.rs
server/src/db/replay.rs
server/src/init.rs
server/src/lib.rs
server/src/utils.rs

This is an alternative approach to #2157.

fix: compaction during replay, hard buffer limits during Kafka ingest

---

persistence_windows/src/persistence_windows.rs
server/src/db.rs

1. ensure that wall-clock check indeed panics
2. make row counts non-zero
3. panic-check min-max-time relation

refactor: harden peristence windows data structure

---

.circleci/get-deploy-tags.sh

Updates the image promotion script.

chore: update image promotion script

---

read_buffer/src/row_group.rs
read_buffer/src/table.rs

I noticed  some comments while workng on the fix for https://github.com/influxdata/influxdb_iox/issues/2217 so I figured I would put it up as its own PR for review

docs: Add/update doccomments in the read_buffer

---

parquet_file/src/catalog.rs

Connects to #2193. This is an attempt to submit changes that aren't refactoring the *entire* world, just a bit of it :)

refactor: Extract a Transaction type to manage transaction paths

---

.circleci/config.yml
Cargo.lock
Cargo.toml
src/influxdb_ioxd/http.rs
src/influxdb_ioxd/http/heappy.rs
src/main.rs

Closes #
See https://github.com/influxdata/influxdb_iox/pull/2279#issuecomment-898449111

fix: Add "heappy" feature to enable heap profiling, new test

---

tests/end_to_end_cases/scenario.rs

Actually we only need a single wait primitive here, so it's easier to reason about and also removes a wrong comment. Spotted by @alamb [in this PR](https://github.com/influxdata/influxdb_iox/pull/2282#discussion_r689443937)

test: simplify `fixture_replay_broken`

---

data_types/src/job.rs
generated_types/protos/influxdata/iox/management/v1/jobs.proto
generated_types/protos/influxdata/iox/management/v1/service.proto
generated_types/src/job.rs
influxdb_iox_client/src/client/management.rs
server/src/db.rs
server/src/db/catalog/partition.rs
server/src/db/lifecycle.rs
server/src/db/lifecycle/drop.rs
server/src/db/replay.rs
src/commands/database/partition.rs
src/influxdb_ioxd/rpc/management.rs
tests/end_to_end_cases/management_api.rs
tests/end_to_end_cases/management_cli.rs

feat: drop entire partitions

---

data_types/src/database_rules.rs
generated_types/protos/influxdata/iox/management/v1/database_rules.proto
generated_types/src/database_rules/lifecycle.rs
lifecycle/src/policy.rs
src/commands/database.rs
tests/end_to_end_cases/scenario.rs
tests/end_to_end_cases/write_api.rs

refactor: remove drop_non_persisted

---

Cargo.toml

https://github.com/mkmik/heappy/commit/82a383128e484039cc2f31476e6289bed48a6701

fix(heappy): Report free as positive numbers

---

iox_object_store/src/lib.rs

Sorry about that @jacobmarble, but this should fix your problem with minio. @shepmaster's [fault for writing the bug](https://github.com/influxdata/influxdb_iox/commit/63111d9d9adf16557141a204ab218e34f212d675), my fault for not catching that he didn't write any tests 😛
And I actually think there should be more tests that I'm happy to write in the morning!

fix: The path to db rules.pb shouldn't end in a slash

---

.circleci/config.yml
Cargo.lock
Cargo.toml
src/main.rs

Closes #2288
Layered on top of #2352

fix: Make heappy and nonheappy mutually exclusive

---

docs/sql.md

- Column `count` is renamed to `row_count`  via #1937
- System tables splits into smaller ones  #2061
- This PR updates the sql to reflect those changes.

docs: Update system table schema in docs/sql.md

---

read_buffer/src/column/encoding/string/rle.rs

We were underestimating the size of a RUB string-RLE column depending on
how the data came into existence. A well-placed debug assert proved
that.

fix: shrink RUB-string-RLE keys capacity to fit

---

query/src/exec.rs
query/src/exec/task.rs
query/src/plan/stringset.rs
server/src/application.rs
src/influxdb_ioxd.rs

feat: wait for Executor shutdown

---

.circleci/config.yml

feat: Disable jemalloc/heappy and use system allocator

---

.circleci/config.yml

feat: Re-enable jemalloc

---

tests/common/server_fixture.rs

test: use random free port for end2end tests

---

generated_types/build.rs
iox_object_store/src/paths/parquet_file.rs
parquet_file/src/catalog/api.rs
parquet_file/src/catalog/cleanup.rs
parquet_file/src/catalog/rebuild.rs
parquet_file/src/catalog/test_helpers.rs
parquet_file/src/metadata.rs
parquet_file/src/storage.rs
parquet_file/src/test_utils.rs
server/src/db/catalog/chunk.rs

Preparation for the "dump catalog in text form" feature.

test: simplify testing around preserved catalog

---

data_types/src/job.rs
server/src/application.rs
server/src/job.rs
server/src/lib.rs
server/src/utils.rs
tracker/src/task/history.rs

feat: expose job metrics

---

entry/src/entry.rs
mutable_buffer/src/chunk.rs
mutable_buffer/src/column.rs
server/src/db.rs
server/src/db/catalog.rs
server/src/db/catalog/chunk.rs
server/src/db/replay.rs
server_benchmarks/benches/snapshot.rs
server_benchmarks/benches/write.rs

Only filed for very early review.

feat: row-level pruning during replay

---

data_types/src/database_rules.rs
generated_types/protos/influxdata/iox/management/v1/database_rules.proto
generated_types/src/database_rules.rs
server/src/database.rs
server/src/db.rs
server/src/db/replay.rs
src/influxdb_ioxd/rpc/error.rs
tests/end_to_end_cases/scenario.rs
tests/end_to_end_cases/write_buffer.rs
write_buffer/Cargo.toml
write_buffer/src/config.rs
write_buffer/src/core.rs
write_buffer/src/kafka.rs
write_buffer/src/mock.rs

feat: auto-creation of sequencers by write buffer

---

Cargo.lock
metric_exporters/Cargo.toml
metric_exporters/src/lib.rs
server/src/job.rs
server/src/lib.rs

Make the job metrics actually useful.
~**This PR sits on top of #2481 and needs a rebase once that one is merged.**~ (done)

fix: job metrics

---

server/src/lib.rs

fix: Return same error when querying deleted vs uncreated database

---

tests/end_to_end_cases/deletes.rs
tests/end_to_end_cases/mod.rs

test: Ensure that a deleted and recreated database returns new data

---

Cargo.lock
generated_types/build.rs
generated_types/protos/influxdata/iox/catalog/v1/predicate.proto
predicate/Cargo.toml
predicate/src/lib.rs
predicate/src/serialize.rs

feat: `Predicate` serialization

---

iox_data_generator/src/lib.rs
iox_data_generator/src/write.rs

This improves performance of the the file output mode, which should
make it easier to improve the performance of the core generation
logic.
Benchmarked via:
```
time \
./target/release/iox_data_generator \
--spec iox_data_generator/schemas/fully-supported.toml \
--output /tmp/out \
--start '1 month ago'
```
Before:
```
Submitted 271608 total points
real	10.912	10911567us
user	3.129	3129032us
sys	6.257	6257340us
cpu	86%
mem	7152 KiB
```
After:
```
Submitted 271588 total points
real	2.291	2291364us
user	1.969	1969357us
sys	0.058	58030us
cpu	88%
mem	7104 KiB
```
That's 21.0% of the previous time.

perf: Don't open the output file each time we write.

---

server/src/db/replay.rs

The old construct uses a single assert-statement for both:
- "bubble-up" scenario, were a panic should fire
- a check, were a panic should not fire
That makes it easy to add new tests. However we need two rather
questionable things to make that work:
- catch panic: to convert an assertion to a check
- a custom panic hook: to make tests not overly verbose (aka caught
panics should not show up on stdout)
Esp. the custom panic hook doesn't work too well w/ multi-threaded tests
since it might swallow error messages from unrelated tests and makes
debugging of CI failures hard.
So instead of using assertions for checks, we now implement a proper
assertion and a check for each test. That's a bit more code per check
but easier probably more stable.

test: do not (ab)use the panic hook for replay tests

---

.github/dependabot.yml
Cargo.lock
object_store/Cargo.toml
object_store/src/azure.rs

Required for #2595 to reduce a potential ignore-list.

chore: upgrade azure dependencies

---

query_tests/src/scenarios/delete.rs
server/src/db/load.rs

All known test for soft delete #2396 are now passed

test: turn all delete tests on

---

query/src/provider.rs

feat: optimize scan for chunks without delete preidcates and without the need to sort output

---

Cargo.lock
datafusion/Cargo.toml
predicate/src/predicate.rs

chore: update latest datafusion and use its lit_timestamp_nano

---

parquet_file/src/catalog/cleanup.rs
parquet_file/src/catalog/core.rs
parquet_file/src/catalog/interface.rs
parquet_file/src/catalog/test_helpers.rs
server/src/db.rs
server/src/db/lifecycle/write.rs
server/src/db/load.rs

feat: teach `Db` to preserve delete predicates

---

query_tests/src/sql.rs

Delete test for select query with selection predicates

test: query with selection predicate on deleted data

---

query_tests/src/scenarios/delete.rs
query_tests/src/sql.rs

test: more tests that includes the repro of 2546

---

client_util/src/connection.rs

This allows to implement custom transports for iox clients (such as socks5 proxies, see #2683).

feat: Allow iox clients to specify connector

---

query_tests/src/scenarios/delete.rs
query_tests/src/sql.rs

Now #2546 is fixed by #2700, let turn its tests on

test: turn on tests of delete all

---

predicate/src/predicate.rs
query_tests/src/scenarios/delete.rs

As a part of #2396 to make stop time included in the delete time range

fix: make stop time inclusive

---

data_types/src/timestamp.rs
parquet_file/src/catalog/core.rs
parquet_file/src/catalog/interface.rs
parquet_file/src/catalog/test_helpers.rs
predicate/src/delete_predicate.rs
server/src/db.rs

refactor: delete predicate clean-ups

---

query/src/lib.rs
query/src/provider/physical.rs
query_tests/cases/in/no_stats_plans.expected
query_tests/cases/in/no_stats_plans.sql
query_tests/cases/in/stats_plans.expected
query_tests/cases/in/stats_plans.sql
query_tests/src/cases.rs
query_tests/src/runner.rs
query_tests/src/scenarios.rs
query_tests/src/sql.rs
server/src/db.rs

feat: Disable using statistics to query data if there are soft deleted rows

---

server/src/db.rs
server/src/db/lifecycle/compact.rs
server/src/db/lifecycle/persist.rs
server/src/db/lifecycle/write.rs

fix: interaction of lifecycle actions and delete predicates

---

generated_types/protos/influxdata/iox/catalog/v1/parquet_metadata.proto
lifecycle/src/lib.rs
parquet_file/src/catalog/dump.rs
parquet_file/src/metadata.rs
parquet_file/src/test_utils.rs
persistence_windows/src/checkpoint.rs
persistence_windows/src/persistence_windows.rs
server/src/db/replay.rs

I've messed up the merge of #2767 (forgot to push and added the automerge label) :sweat_smile:

fix: review comments of #2767

---

lifecycle/src/policy.rs
server/src/db.rs

fix: do not break chunk ordering during persistence

---

trace/src/ctx.rs
trace_exporters/src/jaeger.rs
trace_exporters/src/jaeger/span.rs
trace_http/src/ctx.rs

This can be used when aggregating from multiple parent spans, e.g. when
we want to implement #1473.

feat: ability to link other spans in span context

---

.cargo/audit.toml

Created #2884 to track this and #2871

chore: suppress RUSTSEC-2020-0159

---

generated_types/build.rs
generated_types/protos/influxdata/iox/management/v1/service.proto
generated_types/protos/influxdata/iox/remote/v1/remote.proto
generated_types/protos/influxdata/iox/remote/v1/service.proto
generated_types/protos/influxdata/iox/router/v1/service.proto
generated_types/src/lib.rs
influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/mod.rs
influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/remote.rs
influxdb_iox/tests/common/server_fixture.rs
influxdb_iox/tests/end_to_end_cases/mod.rs
influxdb_iox/tests/end_to_end_cases/remote_api.rs
influxdb_iox_client/src/client.rs
influxdb_iox_client/src/client/remote.rs

feat: add `RemoteService`

---

data_types/src/database_rules.rs
data_types/src/lib.rs
data_types/src/write_buffer.rs
generated_types/build.rs
generated_types/protos/influxdata/iox/management/v1/database_rules.proto
generated_types/protos/influxdata/iox/router/v1/router.proto
generated_types/protos/influxdata/iox/router/v1/shard.proto
generated_types/protos/influxdata/iox/write_buffer/v1/write_buffer.proto
generated_types/src/database_rules.rs
generated_types/src/lib.rs
generated_types/src/write_buffer.rs
influxdb_iox/tests/end_to_end_cases/scenario.rs
influxdb_iox/tests/end_to_end_cases/write_buffer.rs
influxdb_iox_client/src/client/management.rs
iox_data_generator/src/bin/create_database.rs
server/src/database.rs
server/src/lib.rs
server/tests/write_buffer.rs
write_buffer/src/config.rs
write_buffer/src/file.rs
write_buffer/src/kafka.rs
write_buffer/src/mock.rs

See commits. This would allow me to implement the router server on a more stable foundation.
Ref #2980.

refactor: decouple new router server configs from old management system

---

.github/ISSUE_TEMPLATE/developer_experience.md

Add issue template for developer experience issues.
Closes #3073

chore(github): new issue template for developer experience

---

.circleci/config.yml
influxdb_iox/Cargo.toml
influxdb_iox/src/influxdb_ioxd.rs
influxdb_iox/src/main.rs
object_store/src/aws.rs
object_store/src/azure.rs

This indeed fixes some issues in our object store implementation.
Closes #537.

ci: run clippy for all features

---

influxdb_iox/src/influxdb_ioxd.rs
influxdb_iox/src/influxdb_ioxd/server_type/database/mod.rs
influxdb_iox/src/influxdb_ioxd/server_type/mod.rs
influxdb_iox/src/influxdb_ioxd/server_type/router/mod.rs

refactor: clarify `ServerType` background worker handling

---

influxdb_iox/src/influxdb_ioxd/http/dml.rs
influxdb_iox/src/influxdb_ioxd/http/mod.rs
influxdb_iox/src/influxdb_ioxd/server_type/database/http.rs
influxdb_iox/src/influxdb_ioxd/server_type/router/http.rs

~On top of #3187.~
Closes #3154.

feat: HTTP delete support for router

---

generated_types/protos/influxdata/platform/storage/service.proto
influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/service.rs

Closes https://github.com/influxdata/conductor/issues/766
(@brettbuddin this is the reason why your https://github.com/influxdata/idpe/pull/12426 failed to deploy on staging)

fix: Implement a dummy Storage.Offsets method

---

parquet_file/src/storage.rs

docs: not persist of the input stream is empty

---

iox_data_generator/src/bin/iox_data_generator.rs
iox_data_generator/src/write.rs

This removes the create database command line flag and associated code from the data generator runner. Creation of databases should live outside the generator in other tools.

refactor: remove create database from data generator

---

query/src/frontend/reorg.rs
server/src/db/lifecycle/load.rs

Closes #3321
I have no idea why Github closed #3325..
Anyway, this is a rework of the same PR.

perf: don't sort single chunk when loading from OS to RUB

---

generated_types/protos/influxdata/iox/router/v1/service.proto
influxdb_iox/src/commands/router.rs
influxdb_iox/src/influxdb_ioxd/server_type/router/rpc/router.rs
influxdb_iox/src/main.rs
influxdb_iox/tests/end_to_end_cases/mod.rs
influxdb_iox/tests/end_to_end_cases/router_api.rs
influxdb_iox/tests/end_to_end_cases/router_cli.rs
influxdb_iox_client/src/client/router.rs

feat: add router CLI, and GetRouter gRPC request

---

query_tests/src/scenarios/delete.rs
query_tests/src/scenarios/util.rs
server/src/db/chunk.rs
server/src/db/lifecycle/compact_object_store.rs

test: sql tests and checkpoint test for compact OS chunks

---

generated_types/protos/influxdata/iox/management/v1/jobs.proto
generated_types/protos/influxdata/iox/management/v1/service.proto
generated_types/src/job.rs
influxdb_iox/src/commands/database/partition.rs
influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/management.rs
influxdb_iox/tests/end_to_end_cases/management_api.rs
influxdb_iox/tests/end_to_end_cases/management_cli.rs
influxdb_iox_client/src/client/management.rs
server/src/db.rs
server/src/db/lifecycle/compact_object_store.rs

feat: compact all object store chunks of a given partition

---

server/src/db/lifecycle/compact_object_store.rs

One more important test for #3089 and #3343
Test deletes that happen before and during OS compaction

test: propogate delete tests for compact OS chunks

---

server/src/db/lifecycle/compact_object_store.rs
server/src/db/replay.rs

Closes #3343
A final test set for #3089

test: replay test for compact OS chunks

---

docs/README.md

docs: update tech talks

---

iox_data_generator/benches/point_generation.rs
iox_data_generator/src/agent.rs
iox_data_generator/src/lib.rs

On log level info, data generator will now output what the total throughput is in rows per second after every agent's successful write.

feat: add total throughput to data generator output

---

server/src/db/lifecycle/compact_object_store.rs

fix: typos

---

influxdb_iox/src/influxdb_ioxd/server_type/database/rpc/storage/service.rs

Closes #3362
This PR exposes general predicate functionality to the influxRPC frontend's `measurement_names` operation. It reduces the number of InfluxQL test failures from *111* to *106*

feat: wire up general predicates to measurement_names

---

.circleci/config.yml
Cargo.lock
workspace-hack/Cargo.toml

fix: Don't swallow exit code when hakari test fails

---

.circleci/config.yml
influxdb_iox/src/structopt_blocks/object_store.rs
object_store/Cargo.toml
object_store/src/azure.rs
object_store/src/dummy.rs
object_store/src/lib.rs

#3392 shows that we're actually testing the code now.

test: `objest_store` azure support via Azurite

---

data_types/src/names.rs

Not an earth shattering issue, but probably not the behaviour we want - if a client specifies the `org` and `bucket` as empty, there's probably a problem upstream.
---
* fix: reject empty org & bucket (5cce69b4)
Previously a request that specified an empty org & bucket value would be 
mapped to a database named "_".
This commit changes the org/bucket mapping fn to return an error if either org
or bucket is empty.

fix: reject empty org & bucket

---

.circleci/config.yml
Cargo.lock
Cargo.toml
iox_catalog/Cargo.toml
iox_catalog/README.md
iox_catalog/migrations/20211229171744_initial_schema.sql
iox_catalog/src/interface.rs
iox_catalog/src/lib.rs
iox_catalog/src/postgres.rs
workspace-hack/Cargo.toml

This isn't ready to merge because the tests won't pass without going through the setup and I haven't fixed warnings and any clippy errors. But it's here to have a look. I also need to update table and constraint names with whatever @NGA-TRAN puts together in her writeup.
Any ideas on how we should set up the tests for this? I want to keep it as simple as possible for now and actually use Postgres. I think that's fine to have everyone have it on their laptop. I'm not sure how to make that go in Circle CI. Maybe @domodwyer or @mkmik know from setting up Conductor CI?

feat: Add initial iox_catalog skeleton

---

iox_catalog/src/interface.rs
iox_catalog/src/lib.rs
iox_catalog/src/mem.rs
iox_catalog/src/postgres.rs

Review this one after #3480 gets merged in. Should just be this last commit: 834b47830aa07fc18ceb7bd0c1554873f8096163

refactor: add new type for Kafka Partition in Catalog

---

Cargo.lock
Cargo.toml
ingester/Cargo.toml
ingester/src/data.rs
ingester/src/lib.rs
ingester/src/server.rs
iox_catalog/src/interface.rs

The branch compile but nothing to run yet and a few checks would not pass. I will add more stuff before merge but maybe @pauldix, @domodwyer and @crepererum may give me some quick review to see if this initial commit makes sense

feat: add ingester crate and a few basic data structures for its data lifecycle

---

Cargo.lock
iox_catalog/Cargo.toml
iox_catalog/migrations/20211229171744_initial_schema.sql
iox_catalog/src/interface.rs
iox_catalog/src/mem.rs
iox_catalog/src/postgres.rs
workspace-hack/Cargo.toml

* Adds ParquetFile and scaffolding to IOx catalog
* Changed the file_location in parquet_file to object_store_id which is a uuid

feat: Add parquet file records to iox_catalog

---

iox_catalog/src/postgres.rs

Quick one that should have been part of #3490

fix: clear postgres schema in test wasn't deleting parquet_file

---

ingester/src/data.rs
iox_catalog/src/interface.rs
iox_catalog/src/mem.rs
iox_catalog/src/postgres.rs

Also update ingester to get sequencer record and not attempt to create

feat: add sequencer get_by_kafka_topic_id_and_partition to catalog

---

ingester/src/data.rs

refactor: add new fields and comments in ingest data buffer

---

Cargo.lock
influxdb_iox/Cargo.toml
influxdb_iox/src/commands/run/ingester.rs
influxdb_iox/src/commands/run/mod.rs
influxdb_iox/src/influxdb_ioxd/server_type/ingester.rs
influxdb_iox/src/influxdb_ioxd/server_type/mod.rs
ingester/Cargo.toml
ingester/src/data.rs
ingester/src/handler.rs
ingester/src/lib.rs
ingester/src/server.rs
ingester/src/server/grpc.rs
ingester/src/server/http.rs
iox_catalog/src/interface.rs
iox_catalog/src/lib.rs
iox_catalog/src/mem.rs
iox_catalog/src/postgres.rs

This also includes stuff from #3505 so once that gets merged in this will be a little easier to review.
* Adds a new ingester command to start an ingester server
* Moves previous ingester server over to handler
* Skeleton for gRPC and HTTP handlers

feat: Add scaffolding for ingester server

---

Cargo.lock
ingester/Cargo.toml
ingester/src/compact.rs
ingester/src/data.rs
ingester/src/lib.rs
ingester/src/query.rs

Implementation and few tests. More tests to come next

feat: ingester's compaction 

---

query/src/frontend/influxrpc.rs

Part of https://github.com/influxdata/influxdb_iox/pull/3557 that I lost during a rebase once so want to avoid doing so again
This teaches the chunk specializer to fold `IS NULL` as well

fix: handle IS NULL / IS NOT NULL during rpc rewrite

---

Cargo.lock
Cargo.toml
compactor/Cargo.toml
compactor/src/handler.rs
compactor/src/lib.rs
compactor/src/server.rs
compactor/src/server/grpc.rs
compactor/src/server/http.rs
influxdb_iox/Cargo.toml
influxdb_iox/src/commands/run/compactor.rs
influxdb_iox/src/commands/run/mod.rs
influxdb_iox/src/influxdb_ioxd/server_type/compactor.rs
influxdb_iox/src/influxdb_ioxd/server_type/mod.rs

Skeleton of CLI command and crate for compactor. Mostly copied ingester and router2 here and there. Some TODO's left to indicate where to build out the bits to make it work.
Closes: #3777

feat: adding compactor CLI command and crate

---

router2/src/dml_handlers/instrumentation.rs

Emit spans for each instrumented router stage, including the error message of any handler failures.
---
* feat: emit trace spans for router stages (b20dce80)
Configures the instrumentation decorator to emit a trace span covering the
duration of the decorated handler's execution, recording the success/error
result and and error message, if any.

feat: emit trace spans for router stages

---

ingester/src/data.rs
ingester/src/handler.rs
ingester/src/lib.rs
ingester/src/lifecycle.rs

This makes debugging more pleasant.
---
* refactor: impl Debug for ingester types (384133aac)
Derive / implement Debug for all types in the ingester crate to help with
debugging, and add a lint at "warn" level to keep everything in sync.

refactor: impl Debug for ingester types

---

query_tests/cases/in/no_stats_plans.expected
query_tests/cases/in/no_stats_plans.sql
query_tests/cases/in/sql_system_tables.expected
query_tests/cases/in/sql_system_tables.sql
query_tests/cases/in/stats_plans.expected
query_tests/cases/in/stats_plans.sql
query_tests/src/scenarios.rs
query_tests/src/scenarios/library.rs

refactor: make query tests less OG-specific

---

write_buffer/src/file.rs

This PR fixes an inifinite loop when re-using an existing dir for the file-backed write buffer. Before this PR, running this twice would get stuck in an infine loop the second time:
```console
$ cargo run -- run all-in-one \
--write-buffer=file \
--write-buffer-addr=./testwb \
--write-buffer-partition-range-start 0 \
--write-buffer-partition-range-end 0 \
--pause-ingest-size-bytes 10000000000 \
--persist-memory-threshold-bytes 1000000000
```
---
* fix: maybe_auto_create_directories infinite loop (0948a4af2)
Fixes symlinking in maybe_auto_create_directories() - previously it would
create a symlink specifying the target path relative to the working dir, and
not relative to the symlink.
If the working dir != the path in the WriteBufferCreationConfig, subsequent
calls would get stuck in an …

fix: maybe_auto_create_directories infinite loop

---

influxdb_iox/tests/end_to_end_ng_cases/ng.rs
influxdb_ioxd/src/server_type/querier/mod.rs
influxdb_ioxd/src/server_type/querier/rpc/query.rs
querier/src/database.rs
querier/src/flight.rs
querier/src/lib.rs
querier/src/namespace/mod.rs
querier/src/namespace/query_access.rs
querier/src/namespace/test_util.rs
querier/src/table/mod.rs
querier/src/table/test_util.rs
query_tests/src/db.rs
query_tests/src/scenarios/util.rs

Small clean ups before I start w/ #4123 .

refactor: clean up querier public interface

---

compactor/src/compact.rs
compactor/src/utils.rs
parquet_file/src/storage.rs

More debug logging to narrow down where compaction hangs - the main compaction loop is now covered between each major event.
---
* refactor: extra debug in compactor (6131381b8)
Continues pushing more debug through the compaction processing loop.

refactor: extra debug in compactor

---

service_grpc_flight/src/lib.rs

This removes the SERVER-side breaking change introduced in #4273 by also
accepting JSON-based tickets.
Closes #4280.

fix: accept legacy flight requests

---

Cargo.lock
test_helpers_end_to_end_ng/Cargo.toml
test_helpers_end_to_end_ng/src/mini_cluster.rs
test_helpers_end_to_end_ng/src/server_fixture.rs
workspace-hack/Cargo.toml

test: improve NG server fixture

---

clap_blocks/src/catalog_dsn.rs
test_helpers_end_to_end_ng/src/config.rs
test_helpers_end_to_end_ng/src/database.rs
test_helpers_end_to_end_ng/src/server_fixture.rs

Otherwise tests leak state to other tests or previous runs.

test: use random catalog schema name for NG end2end tests

---

logfmt/src/lib.rs

Fixes https://github.com/influxdata/influxdb_iox/issues/4352
---
* fix(logfmt): quote strings containing '=' (8ec9d0ea)
Logfmt uses '=' as a key/value separator, and prior to this commit the 
formatter did not escape strings containing '='.

fix(logfmt): quote strings containing '='

---

docs/data_organization_lifecycle.md

docs: Fix typo in  `data_organization_lifecycle.md`

---

influxdb_iox/src/commands/sql/observer.rs
influxdb_iox/src/commands/sql/repl.rs
influxdb_iox/src/commands/sql/repl_command.rs

fix: Switch `list_database_names` to `get_namespaces`

---

influxdb_iox/src/commands/query.rs

fix: Remove commented out code, fix rather than allow a clippy lint

---

ingester/src/handler.rs

This will help quantify the volume of queries hitting the ingester for debugging.
The RPC call doesn't seem to be tested, but I'll add coverage as part of #4567.
---
* feat(ingester): emit query latency metrics (3890a8986)
Adds a histogram metric "flight_query_duration_ms" that records the duration a
flight RPC query takes to complete. Broken down by query result
(success/error).

feat(ingester): emit query latency metrics

---

.circleci/config.yml
compactor/src/compact.rs
influxdb2_client/src/lib.rs
influxdb2_client/tests/common/server_fixture.rs
ingester/src/data.rs
logfmt/src/lib.rs
rust-toolchain.toml
tracker/src/lock.rs

chore: Update to Rust 1.61

---

parquet_file/src/metadata.rs

Changes the test to embed the IOx metadata when writing the parquet file.
---
* test: fix test_metadata_from_parquet_metadata (5d74ae2ac)
Changes the test_metadata_from_parquet_metadata test to embed the IOx metadata
before asserting it can be read back.

test: fix test_metadata_from_parquet_metadata

---

parquet_file/src/serialize.rs
parquet_file/tests/metadata.rs

@NGA-TRAN as discussed :+1:
---
* refactor: always panic for empty parquet files (0bfc11f4a)
Moves the panic into the child call to_parquet() so all code paths are covered
(i.e. not serialising into memory via to_parquet_bytes()).
* test: assert panic behaviour (f8b83c508)
Modifies the existing test added as part of #4695 to ensure a panic is emitted
when serialising an empty parquet file.

refactor: always panic for empty parquet files

---

influxdb_line_protocol/src/lib.rs
metric/src/gauge.rs
packers/src/packers.rs
read_buffer/src/column/encoding/string/dictionary.rs
read_buffer/src/column/encoding/string/rle.rs
read_buffer/src/row_group.rs
read_buffer/src/value.rs
rust-toolchain.toml
test_helpers/src/tracing.rs

chore: Upgrade to Rust 1.62

---

data_types/src/lib.rs
iox_query/src/exec/context.rs
iox_query/src/frontend/influxrpc.rs
iox_query/src/plan/fieldlist.rs
predicate/src/lib.rs
query_tests/src/influxrpc/field_columns.rs
query_tests/src/influxrpc/table_names.rs
query_tests/src/influxrpc/tag_keys.rs
service_grpc_influxrpc/src/service.rs

Also fix timestamp range to allow selecting points at MAX_NANO_TIME
Closes #4827 

fix: optimize field columns for all-time predicates

---

compactor/src/compact.rs
data_types/src/lib.rs

fix: Remove unused level 1 compaction; move level 2 to level 1

---

querier/src/cache/namespace.rs
querier/src/cache/parquet_file.rs
querier/src/cache/partition.rs
querier/src/chunk/mod.rs
querier/src/database.rs
querier/src/ingester/mod.rs
querier/src/table/mod.rs
querier/src/table/state_reconciler.rs
service_common/src/lib.rs
service_common/src/test_util.rs
service_grpc_flight/src/lib.rs
service_grpc_influxrpc/src/service.rs

feat: wire up cache tracing (2/2)

---

compactor/src/parquet_file_combining.rs

If compaction is called on one level 0 file, the work of compaction
doesn't really need to be done, but for simplicity's sake for now, run
it through the compaction query/write process rather than special casing
it. This will keep us from getting stuck in the unlikely event that a
partition with one level 0 file gets selected as a top candidate for
compaction.
Connects to #5121

fix: Compact one level 0 file to avoid getting stuck on it

---

compactor/src/handler.rs
influxdb_iox/src/commands/run/main.rs

fix: compactor-related freeze and shutdown  fixes

---

write_buffer/src/kafka/mod.rs

This PR is a simple change - initialise kafka clients in parallel (concurrency=10).
---
* refactor: parallelise Kafka partition client init (bd88ac614)
Changes the Kafka write buffer impl to parallelise initialisation of the 
PartitionClient instances.
Now that the PartitionClient constructor also performs leader discovery
(using cached metadata, influxdata/rskafka#164) and establishes a broker 
connection (influxdata/rskafka#166) executing them in parallel will cause a
proportional decrease in the time taken to bring IOx up.

refactor: parallelise Kafka partition client init

---

router/src/server/http.rs

Closes #5506 
Improving write line-protocol stage observability.

feat: router write line protocol duration

---

compactor/src/compact_hot_partitions.rs
iox_tests/src/util.rs

So that the test setup is hopefully clearer on which parts are different and important.

refactor: Use more iox test utils in compactor tests

---

data_types/src/lib.rs
iox_catalog/migrations/20220819154515_sequencer_to_shard.sql
iox_catalog/src/interface.rs
iox_catalog/src/postgres.rs

Depends on https://github.com/influxdata/influxdb_iox/pull/5435 and https://github.com/influxdata/influxdb_iox/pull/5470
** might cause downtime/errors!!! **

feat: database rename

---

import/src/aggregate_tsm_schema/update_catalog.rs
influxdb_iox/src/commands/remote/partition.rs
querier/src/cache/read_buffer.rs
service_grpc_catalog/src/lib.rs
service_grpc_object_store/src/lib.rs

Based on https://github.com/influxdata/influxdb_iox/pull/5421 from @gulio-python 
Closes https://github.com/influxdata/influxdb_iox/issues/5403
Closes https://github.com/influxdata/influxdb_iox/issues/5421

chore: changed `iox_shared` to `iox-shared`

---

data_types/src/lib.rs
docs/profiling.md
executor/src/lib.rs
generated_types/protos/influxdata/iox/ingester/v1/write_info.proto
influxdb_iox/src/commands/sql/observer.rs
influxdb_tsm/src/key.rs
ingester/src/compact.rs
ingester/src/data.rs
ingester/src/test_util.rs
iox_catalog/src/interface.rs
iox_catalog/src/mem.rs
iox_catalog/src/postgres.rs
iox_query/src/exec/fieldlist.rs
iox_query/src/exec/schema_pivot.rs
iox_tests/src/util.rs
ioxd_common/src/http/dml.rs
predicate/src/rewrite.rs
querier/src/ingester/mod.rs
querier/src/table/state_reconciler.rs
schema/src/lib.rs
test_helpers_end_to_end/src/udp_listener.rs

Maybe some tools could be used, e.g:  [spell-check](https://github.com/redis/redis/blob/unstable/.github/workflows/spell-check.yml)

chore: fix comment typo

---

iox_catalog/src/postgres.rs

Closes #5683
(if you want to test this locally, you may need to cherry-pick https://github.com/influxdata/influxdb_iox/pull/5682 or wait for it to be merged)

fix: Close old connection pool after swap

---

write_buffer/src/kafka/mod.rs

The `high_watermark` appears to always be -1 when performing a read of an invalid offset, making these error conditions redundant. 
Worse, the overly broad matching for the "sequence number after watermark" arm took priority over the "sequence number no longer exists" arm, preventing the ingester from taking the existing remedial action (skipping to the first existent offset).
This relates to #5754.
---
* fix: remove future offset read check (5f49c568c)
In https://github.com/influxdata/influxdb_iox/pull/5754 I added code at seek()
time to check if the offset exists, and refuse to seek if that's not the case,
effectively making this check redundant - I left it in on the assumption that
some cases previously added would work!
Unfortunately this doesn't seem to be the case - performing a …

fix: remove future offset read check

---

compactor/src/handler.rs
compactor/src/server/grpc.rs
generated_types/protos/influxdata/iox/compactor/v1/service.proto
influxdb_iox/src/commands/debug/skipped_compactions.rs
influxdb_iox_client/src/client/compactor.rs
iox_catalog/src/interface.rs
iox_catalog/src/mem.rs
iox_catalog/src/metrics.rs
iox_catalog/src/postgres.rs

Follow up to #5931; part of #5894

feat: Add gRPC and CLI APIs to delete skipped compactions 

---

ingester/src/stream_handler/handler.rs

Histogram bucketing makes messes with our ability to measure changes in TTBR, or correctly measure values that exceed the maximum bucket. We can increase the maximum bucket size, but ultimately TTBR is unbounded and can always exceed the max.
Reverts #5895.
---
* revert: use histogram to record TTBR (39f826518)
This reverts commit c63312ce125d39415e78c9322f721ea322cf2869.
This change fixed a low-priority alert when there was no traffic flowing
through the system. The loss in TTBR value fidelity due to bucketing is
a greater concern as it affects live, high-volume clusters and hinders
operational insight.

revert: use histogram to record TTBR

---

Cargo.lock
write_buffer/Cargo.toml
write_buffer/src/kafka/instrumentation.rs
write_buffer/src/kafka/mod.rs

feat: enable ZSTD compression for write buffer payload 

---

trace_http/src/tower.rs

Slack context: https://influxdata.slack.com/archives/CRK9M8L5Q/p1667315716813859
We were seeing this message a lot on production when there were no canceled requests

fix: be more conservative w/ "request canceled" messages

---

ingester/src/data/namespace.rs
ingester/src/data/shard.rs
ingester/src/stream_handler/handler.rs
router/src/server/http.rs
router/tests/http.rs

chore: delete metric duplicate character

---

service_grpc_flight/src/lib.rs

Related to https://github.com/influxdata/idpe/issues/16465.
A bunch of the names and comments in this area seemed to imply that the JSON `ReadInfo` ticket for Flight queries was no longer being used-- but it very much is, by the Go clients, and I broke queries because I didn't appreciate that 😮‍💨
So! Add a test and links to the Go clients to better document that dependency, and hopefully prevent some future breakage.
I think this should go in even if https://github.com/influxdata/influxdb_iox/pull/6134 doesn't.

fix: Improve testing and documentation to clarify Go client behavior

---

iox_query/src/exec/context.rs
iox_query/src/exec/seriesset/converter.rs

This reverts commit dad6dee924ef71b414e4fc3b79864e454f4f7fea.

refactor: revert stream-based `SeriesSetConvert::convert` interface (#6282)

---

ingester2/src/test_util.rs

A quick helper cleanup.
---
* test: track_caller for make_write_op (c3a88f105)
Changes the stack trace to point at the call site when a panic occurs
within make_write_op, and adds a unique message per panic explaining the
issue.

test: track_caller for make_write_op

---

ingester2/src/init/wal_replay.rs

The final `ingester2` PR for the week 👌 
---
* feat(ingester2): drop empty WAL files (a8f99d459)
A shutdown of an ingester that has received no writes leaves an empty
WAL file - these can be deleted at startup.

feat(ingester2): drop empty WAL files

---

ingester2/src/buffer_tree/partition.rs

The new "new parquet file" discovery protocol between the ignester & querier (implemented in #6365) allows for out-of-order persistence of data within a partition - this lack of serialisation allows for persist parallelism, and therefore improved overall performance!
This PR removes the invariant asserts that ensured only in-order persistence was allowed.
---
* feat(ingester2): out-of-order partition persist (7d7c8db33)
Previously data within a partition had to be persisted in the order in
which the data was received. This was necessary for the correctness of
the query API, as it utilised the lower-bound sequence number to
determine what data was available in the object store.
With the changes to the parquet discovery protocol / query API made in …

feat(ingester2): out-of-order partition persist

---

ingester2/src/deferred_load.rs

Allow a thread to optimistically read the value of a `DeferredLoad` immediately (without blocking) if available. 
---
* feat(deferred_load): peek() immediate values (b15aebbdd)
Adds a peek() method to the DeferredLoad construct, allowing a caller to
immediately read the resolved value, or "None" if the value is
unresolved or concurrently resolving.
This allows a caller to optimistically read the value without having to
block and wait for it to become available.

feat(deferred_load): peek() immediate values

---

ingester2/src/persist/context.rs
ingester2/src/persist/worker.rs

Correctly handle sort key conflicts. Unblocks https://github.com/influxdata/influxdb_iox/issues/6421#issuecomment-1361627546.
Fortunately I was writing tests for the persist system this afternoon... I will PR soon.
---
* fix(persist): invalidate cached sort key (23b781f27)
The sort-key conflict path invalidated the cached sort key in the
PartitionData, but not the cached sort key in the persist's Context. Now
both are invalidated.

fix(persist): invalidate cached sort key

---

router/src/dml_handlers/rpc_write/balancer.rs
router/src/dml_handlers/rpc_write/circuit_breaking_client.rs

Faster node health recovery by ensuring "probe" nodes are always probed immediately.
---
* perf(router): faster balancer node recovery (6eb1773ec)
Ensure a "probe" node is always returned as the first candidate, driving
it to recovery faster.
This also includes a fix for the balancer metrics that would report
probe candidate nodes as healthy nodes.

perf(router): faster balancer node recovery

---

router/src/dml_handlers/rpc_write/circuit_breaker.rs

I wanted to add one of these, but I had to prioritise other bits first :)
---
* test: CircuitBreaker recovery property fuzz test (f5d4171be)
Adds a multi-threaded fuzz test that ensures a circuit breaker can
always transition to the healthy state, regardless of the sequence of
events prior.

test: CircuitBreaker recovery property fuzz test

---

ingester2/src/persist/handle.rs

The queue times can range from milliseconds to minutes - we're not too fussed about the granularity of the lower-end (10ms vs 100ms doesn't make much difference) we would prefer to be aware if jobs spend a long time enqueued (beyond the 10s default bucket).
---
* refactor: appropriate queue wait histogram buckets (241090f70)
Changes the bucket values for the queue wait duration metric to be more
appropriately scaled.

refactor: appropriate queue wait histogram buckets

---

iox_catalog/src/postgres.rs

We use UTC in our infra, but other users may not - correctness relies on queries using the UTC time zone.
Default time zones also change, which is an amusing problem - I once worked with a guy who turned up from Singapore and immediately changed the tz +8 hours without mentioning it to anyone - it was a confusing day.
---
* feat(catalog): use explicit UTC time zone (c343ea60b)
We use UTC, but that doesn't mean everyone does. Queries that utilise
NOW() will return incorrect results when the server is using a non-UTC
tz, but application-provided UTC timestamps / epochs.

feat(catalog): use explicit UTC time zone

---

influxdb_iox/tests/end_to_end_cases/ingester.rs
influxdb_iox/tests/end_to_end_cases/querier.rs
influxdb_iox/tests/end_to_end_cases/querier/multi_ingester.rs
test_helpers_end_to_end/src/config.rs
test_helpers_end_to_end/src/mini_cluster.rs
test_helpers_end_to_end/src/steps.rs

Follow-on from https://github.com/influxdata/influxdb_iox/pull/6850

test: Test with multiple ingesters, like in production

---

Cargo.lock
ingester2/Cargo.toml
ingester2/src/init.rs
ingester2/src/server/grpc.rs
ingester2/tests/common/mod.rs
ingester2/tests/write.rs
ioxd_ingester2/Cargo.toml
ioxd_ingester2/src/lib.rs

test: Ingester integration tests that can have a little a internal state 

---

wal/src/blocking/writer.rs

Reduce the number of syscalls needed to write a batch of data to the WAL to reduce the latency of the write overall.
This was more of a drive-by refactor than something I set out to do...
---
* perf(wal): reduce I/O syscall count (c180d3d8a)
Each WAL entry is prepended by a two field header, followed by the
payload bytes. Previously a syscall was made for each header field, and
then another to write the payload bytes (or in reality, at least one
call is made).
This commit reduces the syscalls down to a single write call by building
the entire record in memory before calling write(). This adds 8 bytes to
the in-memory buffer size compared to prior to this commit.
This is effectively a reimplementation of a BufWriter but optimised for
our expected memory usage and (more importantly) capable …

perf(wal): reduce syscalls / allocations

---

compactor2/tests/layouts/core.rs

The simulator checks L1 / L2 file overlap invariants in two scenarios:
- for input files generated by the simulator at the start of `run_layout_scenario` (a failure here would indicate a bad test case)
- for output files from the compactor at the end of `run_layout_scenario` (a failure here would indicate a misbehaving compactor)
These checks allow L0s to overlap anything, and ensure L1s and L2s do not overlap within their level.  The same function `setup.verify_invariants` is called to verify both scenarios.  This PR adds 2 test cases that provide overlapping L1/L2 input files to the simulator and confirm the simulator will panic.
The top of the core tests seemed like a reasonable place to put these tests.  The test following these is generating overlapping L0s, which seems like a …

chore: add tests for L1/L2 invariant violations in simulator

---

compactor2/tests/layouts/many_files.rs

Reproducer of https://github.com/influxdata/idpe/issues/17221

test: reproducer for bug 17221

---

ingester2/src/wal/reference_tracker.rs

This adds metrics to the WAL reference tracker introduced in #7209.
These metrics are primarily aimed to allow us to spot any problems with WAL files/reference counting once deployed. 
While we could have way more useful metrics for the system overall, I can't think of a way to expose stuff like "per file percent referenced" or "per file references remaining" without the large metric cardinality cost of the "per file" bit.
---
* feat(wal): reference tracker metrics (5e94aee44)
Adds three metrics to expose the internal state of the WAL file
reference tracker.
These metrics are mainly useful to identify why WAL files are not being
deleted, if any.

feat(wal): reference tracker metrics

---

README.md

I ran through the readme as a new to iox person. Here are my edits and suggestions.

chore: update readme after going through it.

---

ioxd_common/src/http/utils.rs
router/src/server/http.rs

Closes https://github.com/influxdata/idpe/issues/17449
Although `content-encoding: identity` is [restricted by the http spec](https://httpwg.org/specs/rfc9110.html#field.content-encoding), we have [users with 3rd party libs](https://github.com/influxdata/idpe/issues/17449#issuecomment-1507432672) that attach this header. Therefore we must handle this use case.
---
* fix(idpe-17449): accept content-encoding identity as a valid header (b1d10671b98aac479bf16609f31fe70ee28eed7b)
* fix(idpe-17449): accept content-encoding identity for the parseBody (ca492b09d266346c7640c9326365fca2ba66ac20)
```
running without content-encoding header
204
running with content-encoding header
204
```

fix(idpe-17449): content-encoding identity

---

influxdb_influxql_parser/src/literal.rs
influxdb_iox/tests/end_to_end_cases/flightsql.rs
router/src/dml_handlers/rpc_write/balancer.rs
rust-toolchain.toml

🚀 
---
* build: bump rust version (6d2641916)
Bump to 1.69 for more fixing magic.

build: bump rust version

---

Cargo.lock
clap_blocks/Cargo.toml
workspace-hack/Cargo.toml

:broom:
---
* chore(clap_blocks): remove unused dep (ba44cde5d)
Config & logic are now decoupled!

chore(clap_blocks): remove unused dep

---

clap_blocks/src/catalog_dsn.rs
docs/testing.md
garbage_collector/src/lib.rs
influxdb_iox/src/commands/run/all_in_one.rs
influxdb_iox/tests/end_to_end_cases/compactor.rs
iox_catalog/src/sqlite.rs
test_helpers_end_to_end/src/config.rs
test_helpers_end_to_end/src/database.rs

This reverts #7708.
---
* revert: PR #7708 (c9cfe05f8)
This reverts commit 61abb589331bb3adc337d7333adefdee8df9185a.

revert: PR #7708

---

predicate/src/lib.rs

Found while working on #7470. This is a leftover of #7852.

refactor: remove dead code

---

ingester/benches/query.rs

Evaluate the ingester's query performance under concurrent read load.
---
* test(bench): concurrent partition queries (ea38e9351)
Benchmark the performance of concurrent queries against a single
partition, varying the number of concurrent queries and size of buffered
data in the partition.

test(bench): concurrent ingester partition queries

---

ingester/src/server/grpc/query.rs

It's spantastic.
---
* refactor(ingester): emit span for query handler (af56985d7)
Emit a span that covers the entire flight query handler.

refactor(ingester): emit spans for query handler

---

ingester/src/buffer_tree/partition/resolver/cache.rs
ingester/src/buffer_tree/partition/resolver/coalesce.rs
ingester/src/buffer_tree/partition/resolver/mod.rs
ingester/src/buffer_tree/partition/resolver/trait.rs
ingester/src/buffer_tree/root.rs

Found these while doing partition hash id work, but it's unrelated really, so submitting separately.

fix: Clean up some comments and unused imports that were allowed

---

ingester/src/query_adaptor.rs

This is dead code and no longer used.
---
* refactor: remove unused projection code (5c3e19742)
This code was superseded in:
https://github.com/influxdata/influxdb_iox/pull/8154
This code is now unused.

refactor: remove unused projection code

---

generated_types/build.rs
generated_types/protos/influxdata/iox/gossip/v1/schema_sync.proto
generated_types/src/lib.rs

We'll use gossip to say "hey, are we the same?" and this is the message (and topic) we'll use to do it.
---
* feat(gossip): sync message proto (8751720f1)
Defines the message one peer will send to another to solicit a
consistency check.
* feat(gossip): schema cache convergence topic (c2d50c0a9)
Adds a new topic to be used for schema cache convergence messages.

feat(gossip): schema sync proto message & topic

---

ingester/src/init/wal_replay.rs

🥔 
--- 
* fix(ingester): Correctly compute min sequence number for WAL replay debug logging (168a9e37f)

fix(ingester): Correctly compute min sequence number for WAL replay debug log

---

ingester/src/buffer_tree/partition.rs
ingester/src/buffer_tree/partition/resolver/catalog.rs
ingester/src/buffer_tree/partition/resolver/sort_key.rs
ingester/src/persist/context.rs
ingester/src/persist/handle.rs
ingester/src/persist/mod.rs
ingester/src/persist/worker.rs
ingester/src/test_util.rs
iox_catalog/src/interface.rs
iox_catalog/src/mem.rs
iox_catalog/src/metrics.rs
iox_catalog/src/postgres.rs
iox_catalog/src/sqlite.rs

Just in case this PR does not do what it is expected https://github.com/influxdata/influxdb_iox/pull/8556/files

chore: prepare for revert just in case

---

Cargo.lock
data_types/src/lib.rs
service_grpc_schema/Cargo.toml
service_grpc_schema/src/lib.rs

Split out from https://github.com/influxdata/influxdb_iox/pull/8682.
I believe the changes in this PR aren't actually relevant to schema upsert and are improvements that can be merged separately.

refactor: Improvements made during UpsertSchema work that are actually independent

---

router/src/gossip/anti_entropy/mst/mod.rs

Here's a nice property test that ties together the recent merkle tree functionality additions.
This test generates random sets of namespaces, containing semi-random (to induce collisions) sets of tables, which in turn contain semi-random sets of columns. All table names -> IDs are deterministic, and all column name -> id and column name -> column types are deterministic (like the other MST property tests). This will drive convergence of both disjoint sets of namespaces, and sets that overlap by a random degree.
Essentially this test generates two randomly populated namespace caches on two pseudo "nodes" and drives the MST subsystem to converge them, asserting that they converged within a bounded number of steps.
---
* test: schema cache convergence via merkle tree (881b37ced)
Define a …

test: schema cache convergence via merkle tree

---

router/src/gossip/anti_entropy/sync/mod.rs
router/src/gossip/anti_entropy/sync/rpc_worker/grpc_connector.rs
router/src/gossip/anti_entropy/sync/rpc_worker/mod.rs

Sync connector + client adaptor for the gRPC generated sync client.
---
* feat(sync): SyncRpcClient implementation for gRPC (d0335bb7d)
Implements a sync RPC client & connector for the gRPC service.

feat(sync): SyncRpcClient implementation for gRPC

---

router/src/gossip/anti_entropy/mst/mod.rs

This looks like a [non-deterministic flake](https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/38263/workflows/7f4c42f4-41af-4e01-a625-10deee6f1f8c/jobs/364256) because the actor hadn't fully synchronised - never happens (in thousands of tests) on my laptop but I guess CI is way slower 🤷 
---
* test: wait for convergence (2a91f3c68)
Prevent flakes by waiting for convergence instead of assuming the actor
is fully up-to-date.

test: wait for convergence
